### ISSUE TITLE
Socket not created by this factory

### ISSUE THREAD

**Issue by vreascul** [aws/aws-sdk-java#1032]
Hello,

Total noob here so here is a bucket of "i'm sorry" to use it as you see fit.

My app is downloading some files from aws and it was working fine (i have no idea what changed) but now i get this exception:
Exception in thread "main" java.lang.IllegalStateException: Socket not created by this factory
        at org.apache.http.util.Asserts.check(Asserts.java:34)
        at org.apache.http.conn.ssl.SSLSocketFactory.isSecure(SSLSocketFactory.java:435)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:186)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:837)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3750)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1101)
        at no.xms.main.content.downloader.FileDownloader.downloadRemoteFile(FileDownloader.java:118)

I'm using maven and if i run the app from intelij it is still running without issues.
I'm using aws-java-sdk 1.10.71
If you need more info please let me know but i am so lost that i have no idea what else would be needed.

And now here is a bucket of "thank you".

**Comment by vreascul** [comment]
Hello again,

I updated to 1.11.95 and it works again so i will close the issue. Thank you
