### ISSUE TITLE
SQS: NoSuchMethodError raised on defaultClient creation

### ISSUE THREAD

**Issue by tylfin** [aws/aws-sdk-java#1071]
Getting this traceback
```
Caused by: java.lang.NoSuchMethodError: com.amazonaws.SDKGlobalConfiguration.isInRegionOptimizedModeEnabled()Z
        at com.amazonaws.ClientConfigurationFactory.getConfig(ClientConfigurationFactory.java:35)
        at com.amazonaws.client.builder.AwsClientBuilder.resolveClientConfiguration(AwsClientBuilder.java:163)
        at com.amazonaws.client.builder.AwsClientBuilder.access$000(AwsClientBuilder.java:52)
        at com.amazonaws.client.builder.AwsClientBuilder$SyncBuilderParams.<init>(AwsClientBuilder.java:411)
        at com.amazonaws.client.builder.AwsClientBuilder.getSyncClientParams(AwsClientBuilder.java:354)
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
        at com.amazonaws.services.sqs.AmazonSQSClientBuilder.defaultClient(AmazonSQSClientBuilder.java:44)
```

From trying to build an SQS Client:

```
AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();
```

Any workarounds for this issue? Tried aws-java-sdk-(1.11.105 and 1.11.100)

**Comment by rdifalco** [comment]
Sounds to me like you have a mix of versions with your AWS SDK jars. Are you using Maven? Have you tried the enforcer plugin?

**Comment by tylfin** [comment]
@rdifalco Unfortunately I'm using an ETL system built on top of Java w/o Maven support. The steps I used to install the AWS SDK was:

1. Download from https://aws.amazon.com/sdk-for-java/
2. Add the aws-java-sdk-1.11.100.jar to the project directory
3. Add `<classpathentry kind="lib" path="[PATH]/aws-java-sdk-1.10.53.jar"/>` to the .classpath

**Comment by kiiadi** [comment]
@tylfin definitely sounds like a problem resolving the correct dependencies. What else do you have on your classpath? Is it possible that you're using another library that takes the SDK as a dependency? For the above no-method found issue can you try running this and see what gets printed out? That way we can try to see where the classes are being loaded from:

```java
System.out.println(SDKGlobalConfiguration.class.getProtectionDomain().getCodeSource().getLocation());
```

**Comment by tylfin** [comment]
@rdifalco @kiiadi Ah you're both totally right. Put in a logging statement and found out the ETL tool also has it's own version of the AWS SDK and they're colliding. Closing this issue, thank you for the help!
