### ISSUE TITLE
Dependencies broken in 1.11.106?

### ISSUE THREAD

**Issue by gorzell** [aws/aws-sdk-java#1077]
There seems to be a change in 106 that breaks an existing dependency.

```
:: resolving dependencies :: com.amazonaws#aws-java-sdk-cloudformation-caller;working
	confs: [default]
	found com.amazonaws#aws-java-sdk-cloudformation;1.11.106 in central
	[1.11.106] com.amazonaws#aws-java-sdk-cloudformation;1.11.+
	found com.amazonaws#aws-java-sdk-core;1.11.106 in central
	found com.amazonaws#jmespath-java;1.11.106 in central
	found com.fasterxml.jackson.core#jackson-databind;2.6.6 in central
	found com.fasterxml.jackson.core#jackson-annotations;2.6.0 in central
	found com.fasterxml.jackson.core#jackson-core;2.6.6 in central
downloading http://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-cloudformation/1.11.106/aws-java-sdk-cloudformation-1.11.106-sources.jar ...
	[SUCCESSFUL ] com.amazonaws#aws-java-sdk-cloudformation;1.11.106!aws-java-sdk-cloudformation.jar(source) (202ms)
downloading http://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-cloudformation/1.11.106/aws-java-sdk-cloudformation-1.11.106-javadoc.jar ...
	[SUCCESSFUL ] com.amazonaws#aws-java-sdk-cloudformation;1.11.106!aws-java-sdk-cloudformation.jar(javadoc) (315ms)
downloading http://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-cloudformation/1.11.106/aws-java-sdk-cloudformation-1.11.106.jar ...
	[SUCCESSFUL ] com.amazonaws#aws-java-sdk-cloudformation;1.11.106!aws-java-sdk-cloudformation.jar (138ms)
downloading http://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.11.106/aws-java-sdk-core-1.11.106.jar ...
	[SUCCESSFUL ] com.amazonaws#aws-java-sdk-core;1.11.106!aws-java-sdk-core.jar (206ms)
downloading http://repo1.maven.org/maven2/com/amazonaws/jmespath-java/1.11.106/jmespath-


#!/usr/bin/env amm
java-1.11.106.jar ...
	[SUCCESSFUL ] com.amazonaws#jmespath-java;1.11.106!jmespath-java.jar (46ms)
downloading http://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.6.6/jackson-databind-2.6.6.jar ...
	[SUCCESSFUL ] com.fasterxml.jackson.core#jackson-databind;2.6.6!jackson-databind.jar(bundle) (302ms)
downloading http://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.6.0/jackson-annotations-2.6.0.jar ...
	[SUCCESSFUL ] com.fasterxml.jackson.core#jackson-annotations;2.6.0!jackson-annotations.jar(bundle) (79ms)
downloading http://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.6.6/jackson-core-2.6.6.jar ...
	[SUCCESSFUL ] com.fasterxml.jackson.core#jackson-core;2.6.6!jackson-core.jar(bundle) (69ms)
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at ammonite.runtime.SpecialClassLoader.findClass(ClassLoaders.scala:122)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.amazonaws.AmazonWebServiceClient.<clinit>(AmazonWebServiceClient.java:71)
```

**Comment by gorzell** [comment]
105 resolves these:
```
:: resolving dependencies :: com.amazonaws#aws-java-sdk-cloudformation-caller;working
	confs: [default]
	found com.amazonaws#aws-java-sdk-cloudformation;1.11.105 in central
	found com.amazonaws#aws-java-sdk-core;1.11.105 in central
	found commons-logging#commons-logging;1.1.3 in central
	found org.apache.httpcomponents#httpclient;4.5.2 in central
	found org.apache.httpcomponents#httpcore;4.4.4 in central
	found commons-codec#commons-codec;1.9 in central
	found software.amazon.ion#ion-java;1.0.2 in central
	found com.fasterxml.jackson.core#jackson-databind;2.6.6 in central
	found com.fasterxml.jackson.core#jackson-annotations;2.6.0 in central
	found com.fasterxml.jackson.core#jackson-core;2.6.6 in central
	found com.fasterxml.jackson.dataformat#jackson-dataformat-cbor;2.6.6 in central
	found joda-time#joda-time;2.8.1 in central
	found com.amazonaws#jmespath-java;1.11.105 in central
```
106 only resolves these:
```
:: resolving dependencies :: com.amazonaws#aws-java-sdk-cloudformation-caller;working
	confs: [default]
	found com.amazonaws#aws-java-sdk-cloudformation;1.11.106 in central
	[1.11.106] com.amazonaws#aws-java-sdk-cloudformation;1.11.+
	found com.amazonaws#aws-java-sdk-core;1.11.106 in central
	found com.amazonaws#jmespath-java;1.11.106 in central
	found com.fasterxml.jackson.core#jackson-databind;2.6.6 in central
	found com.fasterxml.jackson.core#jackson-annotations;2.6.0 in central
	found com.fasterxml.jackson.core#jackson-core;2.6.6 in central
```

**Comment by juanstiza** [comment]
Using scala, with these dependencies:
```
libraryDependencies += "com.amazonaws" % "aws-lambda-java-core" % "1.1.0",
libraryDependencies += "com.amazonaws" % "aws-lambda-java-events" % "1.1.0",
```

I'm getting this (yesterday was ok):

```
[info] Resolving com.amazonaws#aws-java-sdk-core;1.11.106 ...
[warn] 	module not found: com.amazonaws#aws-java-sdk-core;1.11.106
[warn] ==== local: tried
[warn]   /Users/juanstiza/.ivy2/local/com.amazonaws/aws-java-sdk-core/1.11.106/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.11.106/aws-java-sdk-core-1.11.106.pom
[info] Resolving jline#jline;2.12.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.amazonaws#aws-java-sdk-core;1.11.106: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.amazonaws:aws-java-sdk-core:1.11.106
[warn] 		  +- com.amazonaws:aws-java-sdk-kms:1.11.106
[warn] 		  +- com.amazonaws:aws-java-sdk-s3:[1.10.5,)
[warn] 		  +- com.amazonaws:aws-java-sdk-dynamodb:[1.10.5,)
[warn] 		  +- com.amazonaws:aws-lambda-java-events:1.1.0 (/Users/juanstiza/myProject/build.sbt#L12)
[warn] 		  +- scala-tracker-lambda-function:scala-tracker-lambda-function_2.11:1.0
```

**Comment by Raniz85** [comment]
We're also seeing this. The core package has no dependencies in 106.

*105*:
```
+--- com.amazonaws:aws-java-sdk-core: -> 1.11.105
|    +--- commons-logging:commons-logging:1.1.3 -> 1.2
|    +--- org.apache.httpcomponents:httpclient:4.5.2
|    |    +--- org.apache.httpcomponents:httpcore:4.4.4 -> 4.4.5
|    |    +--- commons-logging:commons-logging:1.2
|    |    \--- commons-codec:commons-codec:1.9 -> 1.10
|    +--- software.amazon.ion:ion-java:1.0.2
|    +--- com.fasterxml.jackson.core:jackson-databind:2.6.6 -> 2.8.1
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.8.0 -> 2.8.1
|    |    \--- com.fasterxml.jackson.core:jackson-core:2.8.1
|    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.6.6 -> 2.8.1
|    |    \--- com.fasterxml.jackson.core:jackson-core:2.8.1
|    \--- joda-time:joda-time:2.8.1 -> 2.9.4
+--- com.amazonaws:aws-java-sdk-sts: -> 1.11.105
|    +--- com.amazonaws:aws-java-sdk-core:1.11.105 (*)
|    \--- com.amazonaws:jmespath-java:1.11.105
|         \--- com.fasterxml.jackson.core:jackson-databind:2.6.6 -> 2.8.1 (*)
```

*106*:
```
+--- com.amazonaws:aws-java-sdk-core: -> 1.11.106
+--- com.amazonaws:aws-java-sdk-sts: -> 1.11.106
|    +--- com.amazonaws:aws-java-sdk-core:1.11.106
|    \--- com.amazonaws:jmespath-java:1.11.106
|         \--- com.fasterxml.jackson.core:jackson-databind:2.6.6 -> 2.8.1
|              +--- com.fasterxml.jackson.core:jackson-annotations:2.8.0 -> 2.8.1
|              \--- com.fasterxml.jackson.core:jackson-core:2.8.1

```

**Comment by Raniz85** [comment]
The POM looks OK in the tag, but it can be found when browsing [Maven Central](https://search.maven.org/remotecontent?filepath=com/amazonaws/aws-java-sdk-core/1.11.106/aws-java-sdk-core-1.11.106.pom).

Maybe it's just a borked publish?

**Comment by shorea** [comment]
Thanks for reporting, I am able to reproduce. Not seeing anything in our release logs that would indicate why the core pom was not uploaded to Maven but it's definitely not there. I'm hoping this is just a transient issue. We have a release later today, I'll update this issue once it's complete.

**Comment by dagnir** [comment]
Sorry about this. Wee contacted Sonatype and they said it may be an issue with their CDN. Will update when we learn more.

https://issues.sonatype.org/browse/MVNCENTRAL-1622

**Comment by dagnir** [comment]
Sonatype has fixed their CDN issue. I did a quick test using

```xml
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk</artifactId>
      <version>1.11.106</version>
    </dependency>
```

and was able to pull down all the SDK artifacts. Resolving this issue (feel free to reopen if you're still having issues). Thanks for reporting!
