### ISSUE TITLE
[DynamoDB] SdkHttpUtils locks in NIO code under load

### ISSUE THREAD

**Issue by RaphC** [aws/aws-sdk-java#1087]
Hi,

We're facing an issue with DynamoDB client which causes thread stuck. It's due to the use of URLEncoder.encode(value, DEFAULT_ENCODING) with String charsetName (class SdkHttpUtils line 72) As related in the below discussion. It can result in a synchronized bloc of code.

A part of our thread dump :

    "qtp5293969-150" #150 prio=5 os_prio=0 tid=0x08c22400 nid=0x17db waiting for monitor entry [0xbd6cd000]
    java.lang.Thread.State: BLOCKED (on object monitor)
    at sun.nio.cs.FastCharsetProvider.charsetForName(FastCharsetProvider.java:132)
     - waiting to lock <0xcefb4d18> (a sun.nio.cs.StandardCharsets)
    at java.nio.charset.Charset.lookup2(Charset.java:475) 
    at java.nio.charset.Charset.lookup(Charset.java:464) 
    at java.nio.charset.Charset.forName(Charset.java:528) 
    at java.net.URLEncoder.encode(URLEncoder.java:212) 
    at com.amazonaws.util.SdkHttpUtils.urlEncode(SdkHttpUtils.java:72) 
    at com.amazonaws.auth.AbstractAWSSigner.getCanonicalizedResourcePath(AbstractAWSSigner.java:361)     at com.amazonaws.auth.AWS4Signer.createCanonicalRequest(AWS4Signer.java:269) 
    at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:182)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:814) 
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607) 
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376) 
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287) 
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1970) 
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.getItem(AmazonDynamoDBClient.java:1320) 
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:433) 
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:496)
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:400) 

Here is the different article which talk about SDK [limitation.]

https://bugs.mysql.com/bug.php?id=61105
(http://blog.inuus.com/vox/2008/05/the-mysteries-of-java-character-set-performance.html)
(http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6790402)
(http://halfbottle.blogspot.fr/2009/07/charset-continued-i-wrote-about.html)

A related issue https://github.com/aws/aws-sdk-java/issues/188

**Comment by RaphC** [comment]
Hello @spfink 

Any news about this issue?

Regards

**Comment by millems** [comment]
Sorry for the long delay on this one.

Unfortunately, short of writing our own encoder we're a bit stuck on this one, because there's no overload for decode that accepts a charset. It looks like they're thinking about fixing it in a future version: https://bugs.openjdk.java.net/browse/JDK-8178704, but that doesn't help us now...

**Comment by millems** [comment]
How much does this particular method bottleneck your use-case?

**Comment by millems** [comment]
Closing for now. Please feel free to reopen if this is a serious bottleneck for your case. It will be difficult to work around without writing our own encoder.
