### ISSUE TITLE
Unable to execute HTTP request: null

### ISSUE THREAD

**Issue by liron4242** [aws/aws-sdk-java#1090]
An error i'm getting recently (it didn't happen before and i didn't change the code that's doing it)
is unable to execute htttp request : null.
what can make aws return null? can anyone provide some information about this?

running on android marshmellow (java 1.7)

Error during upload: 29
                                                            com.amazonaws.AmazonClientException: Unable to execute HTTP request: null
                                                                at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:430)
                                                                at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
                                                                at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4375)
                                                                at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1704)
                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:203)
                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:85)
                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:44)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                at java.lang.Thread.run(Thread.java:818)
                                                             Caused by: java.net.SocketTimeoutException
                                                                at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
                                                                at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                at com.android.okhttp.okio.Okio$2.read(Okio.java:140)
                                                                at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                                at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
                                                                at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
                                                                at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
                                                                at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:239)
                                                                at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:104)
                                                                at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1151)
                                                                at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:982)
                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:482)
                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:536)
                                                                at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:86)
                                                                at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:80)
                                                                at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)

**Comment by kiiadi** [comment]
Just looking at the stack-trace it seems like you may be using the Android SDK - can you repost this issue to that github repository (https://github.com/aws/aws-sdk-android) instead so that it finds the right engineering team?

**Comment by kiiadi** [comment]
Closing due to lack of response, please feel free to re-open if you feel this is an issue with the Java SDK.
