### ISSUE TITLE
Deprecated Java 9 Javax Dependencies

### ISSUE THREAD

**Issue by jamespedwards42** [aws/aws-sdk-java#1092]
I'm using the S3 client and I get runtime exceptions on Java 9 regarding the deprecated usage of javax bind and activation classes.  After adding the following API and implementation dependencies everything is working, but it would be nice to know exactly what versions should be used going forward.

- [javax.xml.bind:jaxb-api:+](https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api)
- [com.sun.xml.bind:jaxb-impl:+](https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl)
- [com.sun.xml.bind:jaxb-core:+](https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-core)
- [javax.activation:activation:+](https://mvnrepository.com/artifact/javax.activation/activation)

**Comment by kiiadi** [comment]
@jamespedwards42 can you post the details of the RuntimeException you're getting? I'm not sure what you mean when you say you're adding the following implementations - I can't find any reference to [com.sun.xml.bind](https://github.com/aws/aws-sdk-java/search?utf8=%E2%9C%93&q=%22com.sun.xml.bind%22&type=) or [javax.activation](https://github.com/aws/aws-sdk-java/search?utf8=%E2%9C%93&q=%22javax.activation%22&type=) in the codebase ..

**Comment by jamespedwards42** [comment]
@kiiadi Sorry, that was pretty vague of me.  I'm adding those libraries as runtime dependencies so that those deprecated javax class files are available on the classpath.  Here is the exception I get when calling `AmazonS3#putObject`.  After adding those dependencies everything seems to be working fine.

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1730)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:3282)
	at Java9S3.main(Java9S3.java:19)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:552)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
	... 3 more
```

**Comment by jamespedwards42** [comment]
And here is the java version I ran it with:

```
▶ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+162-jigsaw-nightly-h6244-20170326)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+162-jigsaw-nightly-h6244-20170326, mixed mode)
```

**Comment by kiiadi** [comment]
@jamespedwards42 how are you resolving the dependencies? Are you using maven or something? What version of the SDK are you using?

**Comment by kiiadi** [comment]
Looks like our Base64 encoding implementation is the culprit - it uses https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java#L19

I've had a bit of a look through the java 9 docs and it doesn't appear that these are deprecated:
http://download.java.net/java/jdk9/docs/api/javax/xml/bind/JAXBException.html

However you may need to add the java.xml.bind module

**Comment by jamespedwards42** [comment]
The entire [java.xml.bind module](http://download.java.net/java/jdk9/docs/api/java.xml.bind-summary.html) is deprecated and marked as 'to be removed'.  It is weird that they don't mark the individual classes within that module as deprecated. Not sure, maybe I'm misinterpreting it.

You also have to have the javax.activation dependency, without it I get the following exception.  But it looks like the same issue with using the Base64 encoder.

For anyone wanting to get this working, they can add the dependencies I have listed above, and use the java.util.Base64.Encoder to provide the Base64 encoded MD5 checksum (`ObjectMetadata#setContentMD5`).

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/DataSource
	at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl.<clinit>(RuntimeBuiltinLeafInfoImpl.java:478)
	at com.sun.xml.bind.v2.model.impl.RuntimeTypeInfoSetImpl.<init>(RuntimeTypeInfoSetImpl.java:63)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:128)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:84)
	at com.sun.xml.bind.v2.model.impl.ModelBuilder.<init>(ModelBuilder.java:162)
	at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:92)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:455)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:303)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
	at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1156)
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:165)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:563)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:290)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:280)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:393)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:680)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:624)
	at com.amazonaws.util.Base64.<clinit>(Base64.java:44)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1730)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:3282)
	at Java9S3.main(Java9S3.java:19)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:552)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:476)
	... 24 more
``

**Comment by kiiadi** [comment]
Yeah looks like the same issue re: Base64, sounds good about using `java.util.Base64.Encoder` - and we'll definitely look to do this for our next major-version. However this only came in with Java 8 and the 1.11.x family of the SDK needs to support Java 6.

Thank you for your investigation and as I say, we'll remove the custom Base64 encoder in our next major version bump which will target Java 8 as the minimum version.

I'll close this for now.

**Comment by jamespedwards42** [comment]
@kiiadi Any possibility of using the [Apache Commons Codec Base64 encoder](https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Base64.html) so that Java 9 users don't have wait for the next major version for a proper fix?  Or is the next major version just around the corner?

**Comment by kiiadi** [comment]
@jamespedwards42 we've got a couple of blog posts explaining the reasoning behind our custom implementation of Base64. The main reason not to use the Commons Codec version is because of performance - take a look:
https://aws.amazon.com/blogs/developer/a-fast-and-correct-base-64-codec/
https://aws.amazon.com/blogs/developer/follow-up-on-base64-codec-performance/

**Comment by jamespedwards42** [comment]
@kiiadi Oh! Even better! ... I didn't realize there was already a custom implementation provided.  Is it unreasonable to simply drop the javax.xml.bind related classes and reduce [`com.amazonaws.util.Base64#encodeAsString`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64.java#L70) to only use [`com.amazonaws.util.Base64Codec`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/Base64Codec.java)?

**Comment by hrchu** [comment]
The issue still exists in the last version.

**Comment by jayeshja** [comment]
I had same issue while migrating the code from java 8 to java 9, resolve with adding the module at run time
"--add-modules=java.xml.bind".

Eg: java --add-modules=java.xml.bind XmlTestClass

**Comment by michaelahlers** [comment]
@jayeshja, thanks for saving me time tracking down a workaround for this!

**Comment by YuryYaroshevich** [comment]
Hey guys!
Could you please tell me how it can be fixed if `NoClassDefFoundError` appears due to the class which is needed by maven publish plugin? I want to publish my jar into `s3` bucket but have:
```
Exception in thread "pool-5-thread-1" java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
```
I added dependencies mentioned above into `buildscript` section but that didn't help:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath group: 'javax.xml.bind', name: 'jaxb-api', version: '2.3.0'
        classpath group: 'com.sun.xml.bind', name: 'jaxb-core', version: '2.3.0'
        classpath group: 'com.sun.xml.bind', name: 'jaxb-impl', version: '2.3.0'
        classpath group: 'javax.activation', name: 'activation', version: '1.1.1'
    }
}
```

**Comment by YuryYaroshevich** [comment]
ok, if anyone experience the issue I described above you can specify in `gradle.properties`:
```
org.gradle.jvmargs=--add-modules=java.xml.bind,java.activation
```

**Comment by praveen-kl** [comment]
even I  am facing the same problem

**Comment by kskalski** [comment]
For me the "Proper long-term solution: (All JDK versions)" from https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j worked fine, adding
```
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
        </dependency>
```
as explicit dependency in maven was enough

**Comment by ericdemo07** [comment]
simply adding 
`compile group: 'javax.activation', name: 'activation', version: '1.1.1'
`
to build script fixed this issue for me

**Comment by Shashwat121** [comment]
Adding this dependency to my project worked. Please have a look at the same.
`<dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
           <version>2.3.0</version> 
        </dependency>`

**Comment by AAverin** [comment]
Looks like this was still not resolved.
This is an issue on Travis, for example, where to support newer required python versions one has to switch to Ubuntu xenial, where Java 9 is the minimal and no jaxb libraries are present in the SDK anymore.
