### ISSUE TITLE
AWS DynamoDB not able to Unconvert Date to String

### ISSUE THREAD

**Issue by aapeshave** [aws/aws-sdk-java#1096]
I have this java annotated with DyanamoDB annotations:
`@DynamoDBTable(tableName = "AccessToken")
public class AccessToken {

    private String id;
    private String tokenString;
    private String issuer;
    private String role;
    private String createdOn;
    private Long validTill;

    public AccessToken() {
    }

    public AccessToken(String tokenString, String issuer, String role, Long validTill) {
        this();
        this.tokenString = tokenString;
        this.role = role;
        this.validTill = validTill;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAutoGeneratedTimestamp
    public String getCreatedOn() {
        return createdOn;
    }

    @DynamoDBAttribute
    public Long getValidTill() {
        return validTill;
    }

    public void setValidTill(Long validTill) {
        this.validTill = validTill;
    }   
`

However when I am fetching this object from data set I am getting following error:

`com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: could not invoke null on class com.blogit.pojo.AccessToken with value 2017-04-03T12:58:30.036Z of type class java.lang.String

	at com.amazonaws.services.dynamodbv2.datamodeling.StandardBeanProperties$MethodReflect.set(StandardBeanProperties.java:136)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.set(DynamoDBMapperFieldModel.java:111)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$ValueUpdate.apply(DynamoDBMapper.java:1445)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.execute(DynamoDBMapper.java:742)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.save(DynamoDBMapper.java:623)
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.save(AbstractDynamoDBMapper.java:123)
	at org.socialsignin.spring.data.dynamodb.core.DynamoDBTemplate.save(DynamoDBTemplate.java:136)
	at org.socialsignin.spring.data.dynamodb.repository.support.SimpleDynamoDBCrudRepository.save(SimpleDynamoDBCrudRepository.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:504)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:489)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:461)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)`

Please find link to the class and test below:

https://github.com/aapeshave/CloudBusters/blob/feature/test-refactoring/release/src/main/java/com/blogit/pojo/AccessToken.java

https://github.com/aapeshave/CloudBusters/blob/feature/test-refactoring/release/src/test/java/com/blogit/AccessTokenRepositoryTest.java

**Comment by kiiadi** [comment]
@aapeshave doesn't look like there's a setter for `createdOn` - suspect that's the issue.

**Comment by aapeshave** [comment]
looks like adding the setter for `createdOn` fixed the issue. Thank you!
