### ISSUE TITLE
Getting NoClassDefFoundError for a class that's in the jar (lambda)

### ISSUE THREAD

**Issue by efenderbosch** [aws/aws-sdk-java#1116]
We're getting a CNFE when running a lambda. From CloudWatch:

```
Error loading class com.blah.LambdaHandler: com/blah/DynamoDBInsertHandler: class java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/blah/DynamoDBInsertHandler
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
Caused by: java.lang.ClassNotFoundException: com.blah.DynamoDBInsertHandler
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 13 more
```

However, I can build the project locally and confirm that the class is in the jar:

```
jar tvf target/some-lambda-1.1-SNAPSHOT-shaded.jar | grep DynamoDBInsertHandler
3984 Wed Apr 12 17:06:30 EDT 2017 com/blah/DynamoDBInsertHandler.class
```

If we upload that jar directly via the web console, we still get the CNFE. Any ideas? What JVM is used to execute lambdas? Maybe a ClassLoader bug?

Also, the missing class seems to "change" sometimes it can't find ``DynamoDBInsertHandler`` while other instances can't find the main handler class, which is also present in the jar.

**Comment by efenderbosch** [comment]
Ok, I *think* I know what happened here. We were playing around with our serverless.yml and I think we uploaded both a non-shaded and shaded jar. Now when manually uploading a new shaded jar we get this message:

``This function contains external libraries. Uploading a new file will override these libraries.``

This is happening even after deleting the entire function and CloudFormation stack.

**Comment by efenderbosch** [comment]
Figured it out. When using serverless you can specify a single artifact, such as a shaded jar, or a includes/excludes format. The single artifact will upload just the jar, while includes/excludes zips the entire directory and uploads it to S3. This simply doesn't work for Java based lambdas. Unfortunately, that means we can't use wildcards in our serverless.yml.

Closing.
