### ISSUE TITLE
Download from s3 fails when executed from docker

### ISSUE THREAD

**Issue by yevgeni-reif-intel** [aws/aws-sdk-java#1140]
I am trying to download object from S3 bucket using java API.
Please see the code below:

```AWSCredentials credentials = new AnonymousAWSCredentials();

String http_proxy = System.getenv("http_proxy");
String https_proxy = System.getenv("https_proxy");

ClientConfiguration clientConfig = new ClientConfiguration();
boolean proxyRequired = false;
String proxyToUse = null;
Protocol protocol = Protocol.HTTPS;
if(StringUtils.isNoneEmpty(https_proxy)) {
	proxyRequired = true;
	proxyToUse = https_proxy.replaceFirst("^(https://www\\.|https://|www\\.)", "");
	proxyToUse = proxyToUse.replaceFirst("^(http://www\\.|http://|www\\.)", "");
	protocol = Protocol.HTTPS;
} else if(StringUtils.isNoneEmpty(http_proxy)) {
	proxyRequired = true;
	proxyToUse = http_proxy.replaceFirst("^(http://www\\.|http://|www\\.)", "");
	protocol = Protocol.HTTP;
}

AmazonS3ClientBuilder amazonS3ClientBuilder = AmazonS3ClientBuilder.standard().
	withCredentials(new AWSStaticCredentialsProvider(credentials))
	.withRegion(Regions.US_WEST_2);

if(proxyRequired) {
	clientConfig.setProtocol(protocol);
	clientConfig.setProxyHost(proxyToUse.split(":")[0]);
	clientConfig.setProxyPort(Integer.parseInt(proxyToUse.split(":")[1]));
	amazonS3ClientBuilder.withClientConfiguration(clientConfig);
}
amazonS3 = amazonS3ClientBuilder.build();
amazonS3.getObjectMetadata(bucketName, key);
```

when this code is being executed on Linux machine everything working just fine.
When i execute the code from within ubuntu based docker image, the call to getObjectMetadata() is not returns.

After i enable logging the following can be seen:
```
2017-04-30 07:16:05.413 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
2017-04-30 07:16:05.423 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
2017-04-30 07:16:05.424 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2017-04-30 07:16:05.441 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 1 of 50; total allocated: 1 of 50]
2017-04-30 07:16:05.443 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443
2017-04-30 07:16:05.469 [SimpleAsyncTaskExecutor-1] DEBUG `o.a.h.i.c.DefaultHttpClientConnectionOperator` - Connecting to dlsdk-caffe.s3-us-west-2.amazonaws.com/52.218.160.17:443
2017-04-30 07:16:05.542 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
2017-04-30 07:16:05.542 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.impl.execchain.MainClientExec - Connection discarded
2017-04-30 07:16:05.542 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2017-04-30 07:16:05.583 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
2017-04-30 07:16:05.583 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
2017-04-30 07:16:05.583 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2017-04-30 07:16:05.583 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 1][route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 1 of 50; total allocated: 1 of 50]
2017-04-30 07:16:05.583 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443
2017-04-30 07:16:05.583 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to dlsdk-caffe.s3-us-west-2.amazonaws.com/52.218.160.17:443
2017-04-30 07:16:05.588 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-1: Shutdown connection
2017-04-30 07:16:05.588 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.impl.execchain.MainClientExec - Connection discarded
2017-04-30 07:16:05.588 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2017-04-30 07:16:05.656 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
2017-04-30 07:16:05.656 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
2017-04-30 07:16:05.656 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2017-04-30 07:16:05.657 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 2][route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 1 of 50; total allocated: 1 of 50]
2017-04-30 07:16:05.657 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443
2017-04-30 07:16:05.657 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to dlsdk-caffe.s3-us-west-2.amazonaws.com/52.218.160.17:443
2017-04-30 07:16:05.662 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-2: Shutdown connection
2017-04-30 07:16:05.662 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.impl.execchain.MainClientExec - Connection discarded
2017-04-30 07:16:05.662 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 2][route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2017-04-30 07:16:06.061 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
2017-04-30 07:16:06.061 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
2017-04-30 07:16:06.061 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2017-04-30 07:16:06.061 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 3][route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 1 of 50; total allocated: 1 of 50]
2017-04-30 07:16:06.061 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443
2017-04-30 07:16:06.061 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to dlsdk-caffe.s3-us-west-2.amazonaws.com/52.218.160.17:443
2017-04-30 07:16:06.066 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-3: Shutdown connection
2017-04-30 07:16:06.066 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.impl.execchain.MainClientExec - Connection discarded
2017-04-30 07:16:06.066 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 3][route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
```
What might be the reason?
Proxy configuration are defined correctly inside the docker

**Comment by yevgeni-reif-intel** [comment]
Is there any ports that should be open on my local server to communicate with S3?

**Comment by dagnir** [comment]
The logs don't indicate that proxy is being used. This:

```
route: {s}->https://dlsdk-caffe.s3-us-west-2.amazonaws.com:443
```

indicates that the SDK is attempting to connect directly to S3. With proxying configured, the first hop should be the proxy, like this:

```
{tls}->http://localhost:8080->https://my-bucket.s3-us-west-2.amazonaws.com:443
```

Have you verified that the body of your

```java
if (proxyRequired) { ...
```
is actually hit?

**Comment by yevgeni-reif-intel** [comment]
it seems i paste here the output from aws ec2 machine where no proxy is required, but still the connection not working..

for the proxy issue, here is the log:
```
2017-05-04 17:48:36.292 [SimpleAsyncTaskExecutor-1] DEBUG c.a.h.conn.ssl.SdkTLSSocketFactory - Starting handshake
2017-05-04 17:48:36.397 [SimpleAsyncTaskExecutor-1] DEBUG c.a.h.c.ClientConnectionManagerFactory -
java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
        at com.amazonaws.http.conn.$Proxy74.upgrade(Unknown Source)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:415)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1190)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4187)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4134)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1257)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1233)
        at com.intel.aa.dlgenie.job.DownloadPreTrainedModelJob.execute(DownloadPreTrainedModelJob.java:69)
        at com.intel.aa.dlgenie.job.DownloadPreTrainedModelJob$$FastClassBySpringCGLIB$$53fc6a64.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:108)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:192)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.upgrade(PoolingHttpClientConnectionManager.java:369)
        ... 33 common frames omitted
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
        at sun.security.validator.Validator.getInstance(Validator.java:179)
        at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        ... 37 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
        at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
        ... 49 common frames omitted
2017-05-04 17:48:36.399 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
2017-05-04 17:48:36.399 [SimpleAsyncTaskExecutor-1] DEBUG o.a.h.impl.execchain.MainClientExec - Connection discarded
```

**Comment by dagnir** [comment]
Sorry for the silence on this one. [This answer](https://stackoverflow.com/a/6788682) from StackOverflow suggest that the problem is a problem opening the Java truststore. You man want to you check that your default keystore in the docker image is accessible by the JVM process and it contains the correct certificates.

**Comment by millems** [comment]
@yevgeni-reif-intel Did the comment above help resolve your issue?

**Comment by dagnir** [comment]
Closing this due to inactivity. Please feel free to reopen if you still need help resolving this issue.
