### ISSUE TITLE
aws-java-sdk-sns - NoSuchMethodError

### ISSUE THREAD

**Issue by wbautistaEXPEDIA** [aws/aws-sdk-java#1153]
`Caused by: java.lang.NoSuchMethodError: com.amazonaws.services.sns.AmazonSNSAsyncClient.beforeClientExecution(Lcom/amazonaws/AmazonWebServiceRequest;)Lcom/amazonaws/AmazonWebServiceRequest;
	at com.amazonaws.services.sns.AmazonSNSAsyncClient.publishAsync(AmazonSNSAsyncClient.java:1290) ~[aws-java-sdk-sns-1.11.126.jar:?]
	at com.amazonaws.services.sns.AmazonSNSAsyncClient.publishAsync(AmazonSNSAsyncClient.java:1284) ~[aws-java-sdk-sns-1.11.126.jar:?]
	at com.amazonaws.services.sns.AmazonSNSAsyncClient.publishAsync(AmazonSNSAsyncClient.java:1345) ~[aws-java-sdk-sns-1.11.126.jar:?]
	at com.expedia.www.cloudgate.sns.publish.DefaultSNSMessagePublisher.publishAsync(DefaultSNSMessagePublisher.java:38) ~[aws-utils-0.2.jar:?]
	at com.expedia.www.bono.feature.flag.service.service.impl.FeatureFlagServiceImpl.publishToSns(FeatureFlagServiceImpl.java:186) ~[classes/:?]
	at com.expedia.www.bono.feature.flag.service.service.impl.FeatureFlagServiceImpl.lambda$deleteFlags$2(FeatureFlagServiceImpl.java:128) ~[classes/:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_77]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_77]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_77]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_77]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_77]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_77]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_77]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_77]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_77]`

Getting this error using the sns sdk. Our POM is using the `aws-java-sdk-bom` at version `1.11.126`

**Comment by wbautistaEXPEDIA** [comment]
This issue appears to have been caused by version conflicts between dependencies. Closing.
