### ISSUE TITLE
After the latest AWS Eclipse SDK update cannot read the data from the local DynamoDB

### ISSUE THREAD

**Issue by voiceactivity** [aws/aws-sdk-java#1168]
Scenario:
- run the DynamoDB with the command line: 
java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -port 8000 -sharedDb
- open the Eclipse then select "Local Host"
- expand the "Amazon DynamoDB" node
- expected to see the existing tables.
- shown the error message (see below) with no tables view.

In the same time I still can view | edit the tables in the "US West (Oregon)" region.

I have the previous version of the AWS Eclipse SDK installed on my other laptop. THere is no problem there. I can switch over between Local and region based DynamoDB instances.

**Installed AWS SDK versions**:
AWS Core Management Tools 1.0.0.8J8U7UcLwGo6EknCdUjpugz0TsxW
AWS Deployment Tools 1.0.0.8D--cLwSI6F8AqRlMYbZnj7IQ
AWS Developer Tools 1.0.0.7N--cLwhY6EKVTl9JmP5OAgwp
Optional - AWS Data Management Tools 1.0.0.7L--cLwAo6EIdLh2ykJ-11QcP

**Session Data:**
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/user/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/user/.eclipse_keyring

**Message:** Error loading explorer data.

**Exception** stack trace:
com.amazonaws.SdkClientException: Unable to execute HTTP request: Unrecognized SSL message, plaintext connection?
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1069)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2074)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2044)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.listTables(AmazonDynamoDBClient.java:1455)
	at com.amazonaws.eclipse.explorer.dynamodb.DynamoDBContentProvider$2.loadData(DynamoDBContentProvider.java:123)
	at com.amazonaws.eclipse.explorer.AbstractContentProvider$DataLoaderThread.run(AbstractContentProvider.java:131)
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:961)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1363)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1391)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1375)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:132)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy21.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1190)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	... 11 more

**Comment by zhangzhx** [comment]
Hey @voiceactivity ,

This is a known issue and reported in here https://github.com/aws/aws-toolkit-eclipse/issues/69, we have fixed this issue in the new version v201705232324. Please update to the latest version and let us know if you still see the problem. Thank you.

**Comment by voiceactivity** [comment]
Hi, looks like it still does not work!

I have updated to the AWS SDK version you recommended (v201705232324).
I have my local DynamoDB running on the port 8000.
Still see the error (cannot connect to the local DynamoDB) but this time a different one:

Message: Error loading explorer data

Stack Trace:
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: null (Service: AmazonDynamoDBv2; Status Code: 503; Error Code: null; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2074)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2044)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.listTables(AmazonDynamoDBClient.java:1455)
	at com.amazonaws.eclipse.explorer.dynamodb.DynamoDBContentProvider$2.loadData(DynamoDBContentProvider.java:123)
	at com.amazonaws.eclipse.explorer.AbstractContentProvider$DataLoaderThread.run(AbstractContentProvider.java:131)

**Comment by voiceactivity** [comment]
Please try it for yourself.

**Comment by voiceactivity** [comment]
![dynamodb_ 1168](https://cloud.githubusercontent.com/assets/1977721/26429840/85352928-413d-11e7-93fb-684feb18893c.png)

Please see the attached image.

**Comment by voiceactivity** [comment]
Another error:
![dynamodb_ 1168_2](https://cloud.githubusercontent.com/assets/1977721/26430168/9ac60936-413f-11e7-8125-7760cea17995.png)

**Comment by voiceactivity** [comment]
![dynamodb_ 1168_3](https://cloud.githubusercontent.com/assets/1977721/26430246/0f06bf16-4140-11e7-9936-5b71a83585a3.png)

The DynamoDB running outside of the Eclipse. If it will make any difference.

**Comment by zhangzhx** [comment]
I've tried myself and couldn't reproduce. I'm using Mac by the way and not sure if that matters. What local dynamodb version you are using?

Running outside of the Eclipse is OK.

**Comment by voiceactivity** [comment]
2017-01-24 (1.11.86)

**Comment by voiceactivity** [comment]
I can connect to the running local instance via web shell: http://localhost:8000/shell/
There is no problem with connection there.

**Comment by voiceactivity** [comment]
Tested on both (both failed):
- BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
- BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_NZ

**Comment by voiceactivity** [comment]
This is my local .aws/credentials
[default]
aws_access_key_id=test
aws_secret_access_key=test

**Comment by voiceactivity** [comment]
Btw, what Eclipse | Java do you use?
My ones:
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_45
java.vendor=Oracle Corporation

**Comment by voiceactivity** [comment]
Just tested it out again but with the oldest version of the Eclipse:
Version: Mars Release (4.5.0)
Build id: 20150621-1200

The same error occurs.

**Comment by zhangzhx** [comment]
Thanks for the detailed reporting. From the exception message, it looks like the local dynamodb service is throwing a 503 error. At least, it is not because Eclipse cannot connect to the service. 

The 503 is a service internal error, see doc here:
http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/CommonErrors.html

I've tried using Neon, Mars and Luna on Mac and couldn't reproduce. I'll dig into the code to see if I could find anything that could possibly incur the 503 error.

**Comment by voiceactivity** [comment]
Just recently updated the AWS Eclipse SDK. Everything works great. 
Can switch between local and region based DynamoDB instances and get access to all data.

Thank you for that.
Great job!

**Comment by zhangzhx** [comment]
Thanks for the confirm. Glad to hear that. Please submit issues in the Eclipse repo https://github.com/aws/aws-toolkit-eclipse/issues if you have any further bug reporting or feature requests for the AWS Toolkit for Eclipse. :)
