### ISSUE TITLE
SQS : Unable to unmarshall response

### ISSUE THREAD

**Issue by abhishekpalavancha** [aws/aws-sdk-java#1174]
From past few days we are getting this exception because of which our queue is pilling up a lot and we dint have any release for many days i'm wondering if this is sqs error,  everything is fine once we restart our script to pull data from queue but this is 2nd time this month we got following exception 

ERROR [main]: EventWorker - ERROR PROCESSING MSG:
com.amazonaws.AmazonClientException: Unable to unmarshall response (ParseError at [row,col]:[1,16186]
Message: Read timed out). Response Code: 200, Response Text: OK
        at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:1149)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:779)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:505)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:317)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2419)
        at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1130)
        at org.apio.worker.EventWorker.run(EventWorker.java:72)
        at org.apio.worker.EventWorker.main(EventWorker.java:56)
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,16186]
Message: Read timed out
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:591)
        at com.sun.xml.internal.stream.XMLEventReaderImpl.peek(XMLEventReaderImpl.java:275)
        at com.amazonaws.transform.StaxUnmarshallerContext.readText(StaxUnmarshallerContext.java:107)
        at com.amazonaws.transform.SimpleTypeStaxUnmarshallers$StringStaxUnmarshaller.unmarshall(SimpleTypeStaxUnmarshallers.java:41)
        at com.amazonaws.services.sqs.model.transform.MessageStaxUnmarshaller.unmarshall(MessageStaxUnmarshaller.java:130)
        at com.amazonaws.services.sqs.model.transform.ReceiveMessageResultStaxUnmarshaller.unmarshall(ReceiveMessageResultStaxUnmarshaller.java:47)
        at com.amazonaws.services.sqs.model.transform.ReceiveMessageResultStaxUnmarshaller.unmarshall(ReceiveMessageResultStaxUnmarshaller.java:32)
        at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:99)
        at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:42)
        at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:1106)
        ... 7 more
Exception in thread "main" java.lang.RuntimeException: Worker interrupted
        at org.apio.worker.EventWorker.run(EventWorker.java:91)
        at org.apio.worker.EventWorker.main(EventWorker.java:56)

**Comment by varunnvs92** [comment]
1) What version of the SDK are you using? Did you try the latest version?
2) Message: Read timed out
The above message in the error log suggests that the response cannot be read within the mentioned socket timeout. Are you using custom socket timeout? If so, what value are you using?
Its also possible that there might network issues on your side.

**Comment by abhishekpalavancha** [comment]
so we are using 1.10.30 version and no we don't have any  custom socket timeout

**Comment by varunnvs92** [comment]
It looks like this issue happens when there are network issues on service side (SQS here). See first comment [here](https://github.com/aws/aws-sdk-java/issues/892). To avoid this, you might need to have larger socket timeouts or catch the exception & retry. Latest version (1.11.x) of the SDK handles this by retrying.

Let me know if you have more questions.
