### ISSUE TITLE
Wrapping non-markable streams inside ReleaseableInputStream can lead to ResetException / Resetting to invalid mark

### ISSUE THREAD

**Issue by reubenfirmin** [aws/aws-sdk-java#1181]
We're getting an issue very much like #427 where a download reset is attempted, which fails. The source of the stream is an upload through dropwizard (which is a DataHead.ReadMultiStream); it is then piped through our encryption code using PipedInputStream/PipedOutputStream, and one of our own streams. At no point do we use a BufferedInputStream, nor do we have any streams that suggest markSupported=true.

It seems that the exception is happening due to the use of SdkFilterInputStream, which ultimately extends from BufferedInputStream, which comes from wrapping it in a ReleaseableInputStream.

```
AmazonS3Client:
            // When input is a FileInputStream, this wrapping enables
            // unlimited mark-and-reset
            if (input != null)
                input = ReleasableInputStream.wrap(input);
```

```
ReleaseableInputStream:
    public static ReleasableInputStream wrap(InputStream is) {
        if (is instanceof ReleasableInputStream)
            return (ReleasableInputStream)is;   // already wrapped
        if (is instanceof FileInputStream)
            return ResettableInputStream.newResettableInputStream((FileInputStream)is);
        return new ReleasableInputStream(is);
    }
```

```
public class ReleasableInputStream extends SdkFilterInputStream implements Releasable {
```

So, I believe this bug is entirely internal to the S3 client.

```
...
Caused by: com.amazonaws.ResetException: Failed to reset the request input stream;  If the request involves an input stream, the maximum stream buffer size can be configured via request.getRequestClientOptions().setReadLimit(int)
        at com.amazonaws.http.AmazonHttpClient.resetRequestInputStream(AmazonHttpClient.java:996)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:822)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:723)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:475)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:437)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:386)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3996)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1570)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1435)
        at our.package.S3.lambda$putFileAsync$1(S3.java:85)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 common frames omitted
Caused by: java.io.IOException: Resetting to invalid mark
        at java.io.BufferedInputStream.reset(BufferedInputStream.java:448)
        at com.amazonaws.internal.SdkBufferedInputStream.reset(SdkBufferedInputStream.java:106)
        at com.amazonaws.internal.SdkFilterInputStream.reset(SdkFilterInputStream.java:102)
        at com.amazonaws.event.ProgressInputStream.reset(ProgressInputStream.java:139)
        at com.amazonaws.internal.SdkFilterInputStream.reset(SdkFilterInputStream.java:102)
        at com.amazonaws.http.AmazonHttpClient.resetRequestInputStream(AmazonHttpClient.java:994)
```

**Comment by shorea** [comment]
What's the expected behavior? From the way it's described it sounds like the SDK is behaving appropriately. I.E. your source input stream does not support mark/reset so the SDK can't reset it on a retry.

**Comment by reubenfirmin** [comment]
@shorea 

The resetRequestInputStream method is this: 

```
    private void resetRequestInputStream(final Request<?> request) throws ResetException {
        InputStream requestInputStream = request.getContent();
        if (requestInputStream != null) {
            if (requestInputStream.markSupported()) {
                try {
                    requestInputStream.reset();
                } catch (IOException ex) {
                    throw new ResetException("Failed to reset the request input stream", ex);
                }
            }
        }
    }
```

This is called from inside a while loop in executeHelper, which has this block:

```
} catch (IOException ioe) {
               ...
                if (!shouldRetry(request.getOriginalRequest(), execOneParams, ace,
                        executionContext)) {
                    throw lastReset(ace, request);
                }
```

So somehow my InputStream is getting past the check of shouldRetry rather than just exiting early.

**Comment by shorea** [comment]
I see, that's more of a limitation in the existing SDK. In the retry condition we don't have any knowledge of whether it's a streaming input or not so we can't really check whether the input stream supports mark set. I don't think we can change behavior now but I do agree it would be more sane to just not retry it per the default policy and throw the original service exception. 

There is a V2 of the retry policy in the code base that we use in another SDK based project but it is not yet exposed via the configuration interfaces. This interface has a RetryPolicyContext which contains more useful information like the marshalled request object which has the input stream within it. We've got a V2 of the Java SDK scheduled for this year and are planning to base the retry policy on these interfaces to give customers more flexibility in defining their policies. This case is still a little tricky though as we'd probably only want to check if it was mark supported in the retry policy and not actually attempt to reset it so it may fail to reset after the retry policy has been evaluated. In fact it will always be mark supported as if it's not resetable we wrap it in buffered input stream to get some ability to retry (up to the buffer limit).

So I guess short answer is we can't change existing behavior but we can correct this in V2 to at least throw the original service exception.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/retry/RetryPolicy.java#L184

**Comment by reubenfirmin** [comment]
Makes sense. After spending time on (and discussing) this the stacktrace and error message are logical; however I did find it initially confusing. Any way the exception message could throw a few more hints until V2 is ready?

**Comment by shorea** [comment]
Yeah that sounds good to me, I'll see what we can do.

**Comment by millems** [comment]
The exception message has been updated, to be released some time next week.

**Comment by danio** [comment]
@millems This sounds like a good interim solution until the fix can be done. Do you have a planned version for that, or a link to a PR you can share?
