### ISSUE TITLE
Null Error Returned from DynamoDB Streams Client

### ISSUE THREAD

**Issue by mcgodes** [aws/aws-sdk-java#1184]
I'm getting a null error returned from a dynamodb streams request and because there is no error message here, I'm having difficulty understanding what the root cause is here and how to fix it.

Here is the code snippet that causes the error:

`streamsClient.describeStream(new DescribeStreamRequest().withStreamArn(streamArn))` where streamsClient is of type `AmazonDynamoDBStreams` and streamArn is a `String` that appears to be a valid ARN. 

And here's the actual error message:

`com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: null (Service: AmazonDynamoDBStreams; Status Code: 400; Error Code: null; Request ID: null)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1579) ~[aws-java-sdk-core-1.11.93.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1249) ~[aws-java-sdk-core-1.11.93.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030) ~[aws-java-sdk-core-1.11.93.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742) ~[aws-java-sdk-core-1.11.93.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716) ~[aws-java-sdk-core-1.11.93.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.93.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.93.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.93.jar:?]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.93.jar:?]
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.doInvoke(AmazonDynamoDBStreamsClient.java:627) ~[aws-java-sdk-dynamodb-1.11.93.jar:?]
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.invoke(AmazonDynamoDBStreamsClient.java:603) ~[aws-java-sdk-dynamodb-1.11.93.jar:?]
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBStreamsClient.describeStream(AmazonDynamoDBStreamsClient.java:353) ~[aws-java-sdk-dynamodb-1.11.93.jar:?]`

**Comment by shorea** [comment]
Wasn't able to reproduce. You may see more details if you turn on wire logging, see http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html. If that doesn't have additional details your next best bet is to contact the service team to have them look in their logs (hopefully the wire log will contain a Request ID, if not the service team will have a hard time tracking this request down). Other than that I would say double check that the arn exists and the stream is in the same region the client is configured in and that the user making the calls has access to it.

**Comment by dagnir** [comment]
Going to go ahead and close this due to inactivity. Please feel free to re open if you're still experiencing problems after following @shorea's suggestions.
