### ISSUE TITLE
"Thread interrupted" while uploading files

### ISSUE THREAD

**Issue by Anchorer** [aws/aws-sdk-java#1186]
Hi, I'm using the S3 SDK in an Android Application, and when I try to upload a file to the S3 server, sometimes I get an error like this: 

```
Error initiating multipart upload: 20 due to Unable to execute HTTP request: thread interrupted
	com.amazonaws.AmazonClientException: Unable to execute HTTP request: thread interrupted
		at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
		at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4625)
		at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3455)
		at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.initiateMultipartUpload(UploadTask.java:270)
		at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:103)
		at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:83)
		at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:47)
		at java.util.concurrent.FutureTask.run(FutureTask.java:237)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
		at java.lang.Thread.run(Thread.java:761)
	Caused by: java.io.InterruptedIOException: thread interrupted
		at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
		at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
		at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
		at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
		at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.flush(HttpConnection.java:308)
		at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:223)
		at com.android.okhttp.okio.RealBufferedSink$1.flush(RealBufferedSink.java:204)
		at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:176)
		at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
		at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
		at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4625) 
		at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3455) 
		at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.initiateMultipartUpload(UploadTask.java:270) 
		at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:103) 
		at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:83) 
		at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:47) 
		at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
		at java.lang.Thread.run(Thread.java:761) 
```

This issue has a percentage of about 50% to appear while starting the upload process. And my code for creating upload task is: 

```
public TransferObserver createAndStartUploadFile(String bucket, String key, File file) {
    return sTransferUtility.upload(bucket, key, file);
}
```

I'm wondering what causes this problem? Am I using S3 SDK in the wrong way? And how to fix this problem?

**Comment by shorea** [comment]
Can you open an issue at https://github.com/aws/aws-sdk-android, Android is a separate fork from the Java SDK.
