### ISSUE TITLE
One or more of the specified parts could not be found.

### ISSUE THREAD

**Issue by Anchorer** [aws/aws-sdk-java#1187]
Hi, when I upload a file(more than 5MB with multipart-method) to S3 on Android, I got this issue:

```
Failed to complete multipart: 48 due to One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag. (Service: Amazon S3; Status Code: 400; Error Code: InvalidPart; Request ID: A4E095E1BC9317A8)
		com.amazonaws.services.s3.model.AmazonS3Exception: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag. (Service: Amazon S3; Status Code: 400; Error Code: InvalidPart; Request ID: A4E095E1BC9317A8), S3 Extended Request ID: VHyoPaULoJ+R4K8Ou6dchEfmXqJDlIjsWxelEHPDaCpax2WsbidTr7P4lZXnByGy/IK/ygltC64=
			at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:729)
			at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
			at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
			at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4625)
			at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:3358)
			at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.completeMultiPartUpload(UploadTask.java:251)
			at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:191)
			at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:83)
			at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:47)
			at java.util.concurrent.FutureTask.run(FutureTask.java:237)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
			at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
			at java.lang.Thread.run(Thread.java:761)
```

The process to reproduce this issue is simple: 

#### 1. Start an upload task

I created a S3Util class for S3 upload management, which has a method to creat upload task via S3 SDK:

```
public class S3Util {

    // We only need one instance of the clients and credentials provider
    private static AmazonS3Client sS3Client;
    private static CognitoCachingCredentialsProvider sCredProvider;
    private static TransferUtility sTransferUtility;

    private volatile static S3Util mS3Util;

    /**
     * initialize S3Util
     * @param context Context
     */
    public static void init(Context context) {
        getCredProvider(context);
        getS3Client(context);
        getTransferUtility(context);
    }

    public static S3Util getInstance() {
        if (mS3Util == null) {
            synchronized (S3Util.class) {
                if (mS3Util == null) {
                    mS3Util = new S3Util();
                }
            }
        }
        return mS3Util;
    }

    /**
     * Gets an instance of CognitoCachingCredentialsProvider which is
     * constructed using the given Context.
     *
     * @param context An Context instance.
     * @return A default credential provider.
     */
    private static CognitoCachingCredentialsProvider getCredProvider(Context context) {
        if (sCredProvider == null) {
            sCredProvider = new CognitoCachingCredentialsProvider(
                    context.getApplicationContext(),
                    S3Consts.COGNITO_POOL_ID,
                    Regions.US_WEST_2);
        }
        return sCredProvider;
    }

    /**
     * Gets an instance of a S3 client which is constructed using the given
     * Context.
     *
     * @param context An Context instance.
     * @return A default S3 client.
     */
    public static AmazonS3Client getS3Client(Context context) {
        if (sS3Client == null) {
            sS3Client = new AmazonS3Client(getCredProvider(context.getApplicationContext()));
        }
        return sS3Client;
    }

    /**
     * Gets an instance of the TransferUtility which is constructed using the
     * given Context
     *
     * @param context
     * @return a TransferUtility instance
     */
    public static TransferUtility getTransferUtility(Context context) {
        if (sTransferUtility == null) {
            sTransferUtility = new TransferUtility(getS3Client(context.getApplicationContext()),
                    context.getApplicationContext());
        }

        return sTransferUtility;
    }

    /**
     * Create an upload task and start upload
     *
     * @param bucket bucket name for the file
     * @param key    file key
     * @param file   local File object to upload
     * @return the TransferObserver created
     */
    public TransferObserver createAndStartUploadFile(String bucket, String key, File file) {
        return sTransferUtility.upload(bucket, key, file);
    }
    public TransferObserver createAndStartUploadFile(String bucket, String key, File file, TransferListener transferListener) {
        TransferObserver transferObserver = sTransferUtility.upload(bucket, key, file);
        transferObserver.setTransferListener(transferListener);
        return transferObserver;
    }
}

```

#### 2. Listener for state change

I register a TransferListener for this TransferObserver, and can see the output log during the uploading process:

```
UploadTask progress changed. id: 48, total: 23762003, uploaded: 11272192
UploadTask progress changed. id: 48, total: 23762003, uploaded: 17694720
UploadTask progress changed. id: 48, total: 23762003, uploaded: 23199744
UploadTask progress changed. id: 48, total: 23762003, uploaded: 26514515
UploadTask progress changed. id: 48, total: 23762003, uploaded: 29791315
```

As you can see, the uploadedBytes became bigger than the totalBytes during the process. ( Maybe it's because the Multipart Method uploads additional data? )

#### 3. Error occur

Then, the error occurs:

```
Failed to complete multipart: 48 due to One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag. (Service: Amazon S3; Status Code: 400; Error Code: InvalidPart; Request ID: A4E095E1BC9317A8)
		com.amazonaws.services.s3.model.AmazonS3Exception: One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag. (Service: Amazon S3; Status Code: 400; Error Code: InvalidPart; Request ID: A4E095E1BC9317A8), S3 Extended Request ID: VHyoPaULoJ+R4K8Ou6dchEfmXqJDlIjsWxelEHPDaCpax2WsbidTr7P4lZXnByGy/IK/ygltC64=
```

This error triggers the TransferListener to make a callback to tell me that the TransferObserver is failed. However, after I checked my S3 account, I found the file has actually succesfully been uploaded. 

What causes this problem? And how to fix it? Thanks.

**Comment by shorea** [comment]
Can you open an issue at https://github.com/aws/aws-sdk-android, Android is a separate fork from the Java SDK.
