### ISSUE TITLE
FileLockException on SingleFile Download with SSD or M2 discs

### ISSUE THREAD

**Issue by studioam** [aws/aws-sdk-java#1188]
I'm using the 11.142 version of the library and have the following issue when using Download:

     Download down = tx.download(getObjectRequest,new File(percorso+"\\"+ 
     file.getKey().substring(file.getKey().lastIndexOf("/") + 1)));
                     
                
                    
                     try {
                         down.waitForCompletion();
                     } catch (AmazonClientException ex) {

The problem is when I set as destination a very fast disc such an SSD or M2 disc, I have the following exception:

      run:
        com.amazonaws.services.s3.transfer.exception.FileLockException: java.io.FileNotFoundException: 
            C:\Users\Alessandro\Desktop\SILENCE_TLR-1_F_IT-XX_51_2K_O1_20161206_AM\SILENCE_TLR-1_F_IT-XX_51_2K_O1_20161206_AM_01.mxf (Impossibile accedere al file. Il file è utilizzato da un altro processo)
	  at com.amazonaws.services.s3.internal.FileLocks.lock(FileLocks.java:76)
	  at com.amazonaws.services.s3.internal.ServiceUtils.appendFile(ServiceUtils.java:449)
	 at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:46)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:29)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
                          Caused by: java.io.FileNotFoundException: C:\Users\Alessandro\Desktop\SILENCE_TLR-1_F_IT-XX_51_2K_O1_20161206_AM\SILENCE_TLR-1_F_IT-XX_51_2K_O1_20161206_AM_01.mxf (Impossibile accedere al file. Il file è utilizzato da un altro processo)
	 at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at com.amazonaws.services.s3.internal.FileLocks.lock(FileLocks.java:70)
	... 7 more

While with regular hard disk everything is fine, it seems being the disc too fast the threads collide... Has anyone had the same issue? Thanks in advance

**Comment by shorea** [comment]
Is it possible to reproduce this outside of the SDK in a sample application (just reading/writing files using Java's APIs). May be that either your disk is corrupted or the application just doesn't have permissions to those files.

**Comment by shorea** [comment]
Closing due to inactivity, feel free to reopen if the problem persists.
