### ISSUE TITLE
Odd response from AwsOrganization API

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1217]
I intermittently get this log message in an AwsOrganizations call. I'm assuming it gets re-tried and succeeds because I don't see it bubbled up in my error logs. Is that possible? I thought you might want to know this is occurring so you could work it out with the services team. 

```
2017-07-03 19:42:18,063 INFO c.a.p.j.JsonContent [AwsVerifier-29] Unable to parse HTTP response content
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@441980a2; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2689) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3850) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3799) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2420) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.protocol.json.JsonContent.parseJsonContent(JsonContent.java:72) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.protocol.json.JsonContent.<init>(JsonContent.java:64) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:54) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1570) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.services.organizations.AWSOrganizationsClient.doInvoke(AWSOrganizationsClient.java:8264) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.services.organizations.AWSOrganizationsClient.invoke(AWSOrganizationsClient.java:8240) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.services.organizations.AWSOrganizationsClient.executeListAccounts(AWSOrganizationsClient.java:5561) ~[credentials-app-4.0.20.jar:4.0.20]
	at com.amazonaws.services.organizations.AWSOrganizationsClient.listAccounts(AWSOrganizationsClient.java:5537) ~[credentials-app-4.0.20.jar:4.0.20]
```

**Comment by rdifalco** [comment]
Maybe related to this but for ORGS? https://github.com/aws/aws-sdk-java/issues/821

**Comment by millems** [comment]
You're right, it seems like the service is returning html (or xml) because of an error instead of JSON. The SDK retries automatically for transient errors without bubbling the error up, unless it persists after a few attempts.

Is there something you would prefer the SDK do to handle things more gracefully in this case?

**Comment by rdifalco** [comment]
@millems I suppose I'd like to see what the actual error is. For example, what if the retry logic was different, would it bubble up and what would it bubble up as? I guess I'd like you to look at the media type and parse correctly for it. Currently there is no way to know if this is rate limiting or something else.

**Comment by millems** [comment]
Unfortunately it's a service-side problem that they're returning XML/HTML. This can happen when the request fails at an HTTP-level load balancer. The load balancer returns a 5XX error code and an html error body because it couldn't get through to the backend service.

If the response is predictable, the SDK could monitor for it and provide a better log message. Unfortunately the error happens very rarely, so I've never personally seen the full message. We preserve the content of the message in the exception, but don't preserve the exception if the request is retried, so it's not possible to get access to the content of the response.

To answer your question regarding what would happen if you had disabled retries, it would bubble up as an [`AmazonServiceException`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/AmazonServiceException.html) from the client method invocation you made (in this case, `AWSOrganizationsClient.listAccounts`).

**Comment by rdifalco** [comment]
Just want to say that I get a prolific number of these. I think they give them out for rate limiting but without seeing the actual XML reponse it's hard to know.  The way the AWS SDK Client fails here makes it difficult to see what the status code even is. Just a vote again that if you cannot parse the response as JSON that you should return it as a plain text string in the Exception along with the status code.

**Comment by millems** [comment]
Please reopen if you catch the HTML body of this service response at any point. We aren't able to reproduce it in order to make the SDK modification.

**Comment by meowfaceman** [comment]
Might have something for you guys here. Edited to remove IDs/timestamps.

```
Unable to parse HTTP response (Invocation Id:*****, Request Id:******) content to XML document '<ErrorResponse xmlns="http://rds.amazonaws.com/doc/2014-10-31/">
  <Error>
    <Type>Sender</Type>
    <Code>DBInstanceNotFound</Code>
    <Message>DBInstance ******** not found.</Message>
  </Error>
  <RequestId>*****</RequestId>
</ErrorResponse>
' 
```
