### ISSUE TITLE
NullPointerException in TransferManager

### ISSUE THREAD

**Issue by abhigna-aws** [aws/aws-sdk-java#1240]
Is this a known issue?
```java
 NullPointerException: , Stack Trace: java.lang.NullPointerException
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:718)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4223)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4170)
at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1249)
at com.amazonaws.services.s3.transfer.TransferManager.doDownload(TransferManager.java:1050)
at com.amazonaws.services.s3.transfer.TransferManager.doDownload(TransferManager.java:1008)
at com.amazonaws.services.s3.transfer.TransferManager.download(TransferManager.java:846)
at com.amazonaws.services.s3.transfer.TransferManager.download(TransferManager.java:764)
at com.amazonaws.services.s3.transfer.TransferManager.download(TransferManager.java:718)
...
```

**Comment by kiiadi** [comment]
What version of the SDK are you using? Can you provide a code-sample that reproduces this?

**Comment by varunnvs92** [comment]
There was a recent fix made to [executeWithTimer](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L710-L719) method to avoid NPE in version 1.11.160. Please try version >= 1.11.160 and see if the issue still occurs.

**Comment by varunnvs92** [comment]
Closing due to inactivity. Feel free to reopen if you still have the issue.
