### ISSUE TITLE
java.lang.NoClassDefFoundError: com/amazonaws/services/sqs/model/transform/MessageStaxUnmarshaller

### ISSUE THREAD

**Issue by ashishraval21** [aws/aws-sdk-java#1267]
Exception in thread "pool-19-thread-160" java.lang.NoClassDefFoundError: com/amazonaws/services/sqs/model/transform/MessageStaxUnmarshaller
	at com.amazonaws.services.sqs.model.transform.ReceiveMessageResultStaxUnmarshaller.unmarshall(ReceiveMessageResultStaxUnmarshaller.java:47)
	at com.amazonaws.services.sqs.model.transform.ReceiveMessageResultStaxUnmarshaller.unmarshall(ReceiveMessageResultStaxUnmarshaller.java:28)
	at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:107)
	at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:40)
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1502)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1225)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1740)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1716)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeReceiveMessage(AmazonSQSClient.java:1380)
	at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1356)
	at com.momoe.payment.services.SqsServices$CheckUpiStatusListener.run(SqsServices.java:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Currently we are using below dependency to integrating sqs.
**<dependency>
<groupId>com.amazonaws</groupId>
<artifactId>aws-java-sdk-bom</artifactId>
<version>1.11.163</version>
<type>pom</type>
<scope>import</scope>
</dependency>**

and above error only got on production server.

**Comment by millems** [comment]
These class-def-not-found-in-production errors usually indicate a jar being out of date on your production environment. Have you been able to confirm that the class is present in the jar in production?

**Comment by dagnir** [comment]
Closing this due to inactivity. As @millems pointed out, this is likely due to a version mismatch.
