### ISSUE TITLE
BUG: S3 Connection pool shut down for S3Client

### ISSUE THREAD

**Issue by shavo007** [aws/aws-sdk-java#1282]
AWS SDK: Connection pool shut down

Deps:

compile group: 'com.amazonaws', name: 'aws-java-sdk-s3', version: '1.11.176'
Spring boot: 1.5.6.RELEASE

When I try to get object, throws this exception below.
```
amazonS3.getObject(new GetObjectRequest(archiveBucketName(), archivedFile), file);
```

My suspicions is that in another part of my microservice, i use the transfer manager to put directory on a different bucket with same s3 client (as its a spring managed bean).

```
  this.tsMgr = TransferManagerBuilder.standard().withS3Client(s3).build();


  private void putMediaFilesOnBucket(String zipFileName, String number, String key) {
        try {
            File dir = new File(raidrConfig.getRaidrProperties().getTmpdir() + File.separator + number);
            MultipleFileUpload mfUpload = tsMgr.uploadDirectory(raidrConfig.getRaidrProperties().getBucketName(), key, dir, true);
            mfUpload.waitForCompletion();
        } catch (AmazonS3Exception | InterruptedException e) {
            log.error("Failed to upload file {} to the bucket  {} {} with error message ", zipFileName, raidrConfig.getRaidrProperties().getBucketName(), e.getMessage());
            throw new RaidrException(e);
        } finally {
            tsMgr.shutdownNow();
        }
    }
```

Should i shutdown but instead say tsMgr.shutdownNow(false)? Or why is my connection pool shutdown for other calls in my application?

Stacktrace:

```
java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:189)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:257)
	at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy75.requestConnection(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1189)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4227)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4174)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1382)
	at com.amazonaws.services.s3.AmazonS3Client$3.getS3ObjectStream(AmazonS3Client.java:1459)
```

**Comment by shorea** [comment]
Could something else be shutting down your S3 client outside of the TransferManager? Can you try putting a breaking on the client shutdown method and see where and when it's being called.

**Comment by shavo007** [comment]
Hi @shorea , no i do not shutdown the s3 client. This is also a spring managed bean:


```
  @Bean
    @Profile("default")
    public AmazonS3 amazonS3DefaultClient(){
        ClientConfiguration clientConfiguration = new ClientConfiguration();
        return AmazonS3ClientBuilder.standard().withRegion(Regions.fromName(raidrProperties.getRegion()))
                .withClientConfiguration(clientConfiguration)
                .build();
    }

```

If i shutdown now with shutdownS3Client (false), I now get RejectedExecutionException with subsequent requests to my API.

```
  tsMgr.shutdownNow(false);
```

As you can see below transferManager is only initialised once in my application:
```
   @Autowired
    public UploadMediaService(AmazonS3 s3, Client client, RaidrConfig raidrConfig) {
        this.s3 = s3;
        this.tsMgr = TransferManagerBuilder.standard().withS3Client(s3).build();
        this.client = client;
        this.raidrConfig = raidrConfig;
    }
```
Do I have to initialise every time instead?

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@27c5636a rejected from java.util.concurrent.ThreadPoolExecutor@44007787[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 15]

**Comment by shorea** [comment]
> Do I have to initialise every time instead?

No we generally recommend you keep a long lived instance of clients and TransferManager for best performance. What you are doing is best practice.

It seems like something is shutting down your transfer manager before it's finished doing work. Can you put a breakpoint in the shutdown method to see what that is?

**Comment by shorea** [comment]
Closing issue due to no response. Feel free to reopen if problem persists.

**Comment by shavo007** [comment]
Apologies for late reply:

we changed it to spring managed bean with no shutdown. 


```
 @Bean
    TransferManager s3TransferManager(AmazonS3 amazonS3) {
        return TransferManagerBuilder.standard().withS3Client(amazonS3).build();
    }

```


```
  MultipleFileUpload mfUpload = s3TransferManager.uploadDirectory(raidrConfig.getRaidrProperties().getBucketName(), key, dir, true);
            mfUpload.waitForCompletion();

```

**Comment by gravindran2412** [comment]
Hi @shavo007 / @shorea,
Facing similar issue on connection pool shutdown:
Amazon client error: Unable to complete transfer: Connection pool shut down

I am using spring managed been for doing this. Below is the code snippet.
@Bean
  public TransferManager s3TransferManager(AmazonS3 amazonS3) {
      return TransferManagerBuilder.standard().withS3Client(amazonS3).build();
  }

Upload:
Upload xfer = s3TransferManager.upload(bucketName, keyPrefix+"/final_result.csv", file);

Any help will be highly appreciated.

Thanks!

**Comment by suryavas** [comment]
I too face same issue, **Connection pool shut down**, even after we set txBuilder.**setShutDownThreadPools**(false); in spring managed beans, but it fails after processing ~30k stream uploads in ~1.50hr time frame and we used aws-sdk-java:1.11.390
`S3 TransferManager: Connection pool shut down 
com.amazonaws.AmazonClientException: Unable to complete transfer: Connection pool shut down
	at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.unwrapExecutionException(AbstractTransfer.java:286)
	at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.rethrowExecutionException(AbstractTransfer.java:265)
	at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.waitForCompletion(AbstractTransfer.java:103)`

**Comment by athom** [comment]
face same issue, how can I reopen this?

**Comment by sbennettmcleish** [comment]
I was getting this same issue, I had a utility class that was being used in various places and it was retaining the s3 client rather than constructing a new one each time. Assume two parts of my code were attempting to use it at once, have changed utility to simply create a new s3 client and it's now working fine.

**Comment by izian** [comment]
We've experienced where we have a long lived (static final even!) S3 client and a long lived (but not static) SNS client, and when we put the SNS client. Both synchronous.
Both built separately with separate builders by separate libraries in separate parts of out application for separate functions.
When we put the SNS sender under some load, not too much, eventually without any other logging one of the messages just starts failing with "connection pool shutdown" and the next time the S3 client is used to check on some data, it also fails with the same.

It's almost like something else is closing both of their connection pools, since it seems that neither share a client or pool, it looks in debug to create a new client and new pooled connection manager etc.
They both get registered with some static collection for checking and clearing idle connections.
When we create new clients for the load work and destroy them then this issue goes away, so we can send the same amount of messages if we kill the SNS clients and recreate for each group of 5 we're sending. 

I can't see any reason why one client being under any load would do this...

> I too face same issue, **Connection pool shut down**, even after we set txBuilder.**setShutDownThreadPools**(false); in spring managed beans, but it fails after processing ~30k stream uploads in ~1.50hr time frame and we used aws-sdk-java:1.11.390

This seems like what we're seeing

**Comment by izian** [comment]
I found our cause, we were hitting heap space issues and `httpclient` version 4.5.7 introduced a catch on Throwable that shuts down the connection pool silently
https://github.com/apache/httpcomponents-client/commit/ca98ad69adad79de57d8b944ba524f7267a795cb

**Comment by akuzni2** [comment]
so what's the solution here? There was never any recommendation from anyone from the community or AWS. It seems like it's a common issue.

**Comment by fahad-workspace** [comment]
I experienced a similar issue where I would receive a connection pool shutdown error every hour. To address this problem, I implemented a custom AWS credentials provider that supports the automatic refresh of STS credentials when they are nearing expiration. On our servers, we use WebIdentityToken, while for local setups, we use DefaultCredentialsProvider. Both authentication methods are supported by the code provided below. Here is the reference code for your convenience.

**Implementation:**

```java
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.Duration;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import software.amazon.awssdk.auth.credentials.AwsCredentials;
import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider;
import software.amazon.awssdk.auth.credentials.AwsSessionCredentials;
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider;
import software.amazon.awssdk.services.sts.StsClient;
import software.amazon.awssdk.services.sts.model.AssumeRoleWithWebIdentityRequest;

/**
 * An AWS credentials provider that supports automatic refresh of STS credentials when they are
 * close to expiration.
 */
public class AutoRefreshingCredentialsProvider implements AwsCredentialsProvider {

  /** The constant DURATION_SECONDS. */
  public static final int DURATION_SECONDS = 3600;

  private final StsClient stsClient;
  private final AssumeRoleWithWebIdentityRequest assumeRoleWithWebIdentityRequest;
  private final Duration refreshBeforeExpiration;
  private AwsCredentials awsCredentials;
  private Instant expiration;
  private static final Logger log =
      LoggerFactory.getLogger(AutoRefreshingCredentialsProvider.class);

  /**
   * Configures the credentials provider based on the environment.
   *
   * @param roleSessionName the role session name
   * @return an instance of AwsCredentialsProvider
   */
  public static AwsCredentialsProvider configureCredentialsProvider(String roleSessionName) {
    // Check if both AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN are non-null
    if (Objects.isNull(AWS_WEB_IDENTITY_TOKEN_FILE) || Objects.isNull(AWS_ROLE_ARN)) {
      log.info("Using default credentials provider.");
      return DefaultCredentialsProvider.create();
    }
    var stsClient = StsClient.create();
    var webIdentityTokenFilePath = AWS_WEB_IDENTITY_TOKEN_FILE;
    // Read the web identity token from the file
    String webIdentityToken;
    try {
      webIdentityToken = Files.readString(Paths.get(webIdentityTokenFilePath));
      log.info(
          "Successfully read web identity token from file: %s".formatted(webIdentityTokenFilePath));
    } catch (IOException e) {
      log.info("Error reading the web identity token file: %s".formatted(webIdentityTokenFilePath));
      throw new RuntimeException(
          "Error reading the web identity token file: " + webIdentityTokenFilePath, e);
    }
    // Create an AssumeRoleWithWebIdentityRequest.Builder and set the necessary fields
    var sessionName =
        "%s-%d-%s"
            .formatted(
                roleSessionName,
                Instant.now().getEpochSecond(),
                UUID.randomUUID().toString().substring(0, 8));
    var assumeRoleWithWebIdentityRequestBuilder =
        AssumeRoleWithWebIdentityRequest.builder()
            .roleArn(AWS_ROLE_ARN)
            .roleSessionName(sessionName)
            .durationSeconds(
                DURATION_SECONDS); // Set the session duration (in seconds) - maximum is 1 hour
    // Set the web identity token if it is non-null
    if (Objects.nonNull(webIdentityToken)) {
      assumeRoleWithWebIdentityRequestBuilder.webIdentityToken(webIdentityToken);
    }
    // Create a new AutoRefreshingCredentialsProvider with the given parameters
    return new AutoRefreshingCredentialsProvider(
        stsClient, assumeRoleWithWebIdentityRequestBuilder.build(), Duration.ofMinutes(10));
  }

  /**
   * Constructs an instance of AutoRefreshingCredentialsProvider.
   *
   * @param stsClient an instance of StsClient
   * @param assumeRoleWithWebIdentityRequest an instance of AssumeRoleWithWebIdentityRequest
   * @param refreshBeforeExpiration the duration before expiration when the credentials should be
   *     refreshed
   */
  public AutoRefreshingCredentialsProvider(
      StsClient stsClient,
      AssumeRoleWithWebIdentityRequest assumeRoleWithWebIdentityRequest,
      Duration refreshBeforeExpiration) {
    Objects.requireNonNull(stsClient, "stsClient must not be null");
    Objects.requireNonNull(
        assumeRoleWithWebIdentityRequest, "assumeRoleWithWebIdentityRequest must not be null");
    Objects.requireNonNull(refreshBeforeExpiration, "refreshBeforeExpiration must not be null");
    this.stsClient = stsClient;
    this.assumeRoleWithWebIdentityRequest = assumeRoleWithWebIdentityRequest;
    this.refreshBeforeExpiration = refreshBeforeExpiration;
    refreshCredentials();
  }

  /**
   * Resolves and returns the AWS credentials. If the current credentials are close to expiration,
   * the method will refresh the credentials before returning them.
   *
   * @return the current AWS credentials
   */
  @Override
  public synchronized AwsCredentials resolveCredentials() {
    if (Instant.now().isAfter(expiration.minus(refreshBeforeExpiration))) {
      log.info("Credentials are close to expiration. Refreshing credentials.");
      refreshCredentials();
    }
    return awsCredentials;
  }

  /** Refreshes the AWS credentials by calling the STS assumeRoleWithWebIdentity API. */
  private void refreshCredentials() {
    log.info("Refreshing AWS credentials.");
    var stsCredentials =
        stsClient.assumeRoleWithWebIdentity(assumeRoleWithWebIdentityRequest).credentials();
    awsCredentials =
        AwsSessionCredentials.create(
            stsCredentials.accessKeyId(),
            stsCredentials.secretAccessKey(),
            stsCredentials.sessionToken());
    expiration = stsCredentials.expiration();
    log.info(
        "AWS credentials refreshed successfully. New expiration: %s"
            .formatted(DATE_TIME_FORMATTER.format(expiration)));
  }
}
```


**Usage:**

```java
private static S3Client createS3Client() {
    var credentialsProvider = AutoRefreshingCredentialsProvider.configureCredentialsProvider("s3");
    return S3Client.builder()
        .region(AWS_REGION)
        .httpClientBuilder(
            ApacheHttpClient.builder()
                .maxConnections(MAX_CONNECTIONS)
                .connectionTimeout(CONNECTION_TIMEOUT))
        .credentialsProvider(credentialsProvider)
        .build();
}
```

**Comment by rlconst** [comment]
Try @pwannenmacher solution
