### ISSUE TITLE
Attempting to delete more than 1000 keys from S3 gives confusing MalformedXML

### ISSUE THREAD

**Issue by ck1125** [aws/aws-sdk-java#1293]
Using S3 Java SDK 1.11.91 and get the following Client exception:

`com.amazonaws.services.s3.model.AmazonS3Exception: The XML you provided was not well-formed or did not validate against our published schema (Service: Amazon S3; Status Code: 400; Error Code: MalformedXML; Request ID: 9F5F314A9430D8F2)
...
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4141)
	at com.amazonaws.services.s3.AmazonS3Client.deleteObjects(AmazonS3Client.java:2097)
`

Should there be a more suitable error message instead?

**Comment by shorea** [comment]
Big +1, this would be a service side change so I'll pass this feedback along to them.

**Comment by shorea** [comment]
@ck1125 The S3 team has acknowledged the feature request. No word on when it might be implemented. I'll let you know when I hear more.

**Comment by shorea** [comment]
For Java Team - TT0123930555
