### ISSUE TITLE
AWS Java SDK jar issues

### ISSUE THREAD

**Issue by vikbonzai** [aws/aws-sdk-java#1302]
I am trying to invoke a Lambda function from my java application I am using AWS Java SDK version 1.11.193. There were a lot of dependancy issues which I have resolved by upgrading/removing the conflicting Jars.However, there is this one issue which I am not able to resolve. See the stack trace below: 
```
java.lang.NoSuchFieldError: ALLOW_FINAL_FIELDS_AS_MUTATORS
        at com.amazonaws.partitions.PartitionsLoader.<clinit>(PartitionsLoader.java:52)
        at com.amazonaws.regions.RegionMetadataFactory.create(RegionMetadataFactory.java:30)
        at com.amazonaws.regions.RegionUtils.initialize(RegionUtils.java:64)
        at com.amazonaws.regions.RegionUtils.getRegionMetadata(RegionUtils.java:52)
        at com.amazonaws.regions.RegionUtils.getRegion(RegionUtils.java:105)
        at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:239)
        at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:226)
```
I have updated the Jacson jars as well (using 2.6.6) which resolved most of the issues but the above one still persists.
Any lead would be highly appreciated.
Thanks.

**Comment by shorea** [comment]
Can you print out where that class is being loaded from?

```java
 System.out.println(MapperFeature.class.getProtectionDomain().getCodeSource());
```

**Comment by vikbonzai** [comment]
@shorea : Thanks for the reply. I have managed to resolve this by upgrading all the Jars (including the transitive ones). I knew this definitely had to be jackson jars version (after coming across similar issues here on Github) but had to re-look at all the dependancies  which were transitively using Jackson jars.
Thanks again. Appreciate your reply!

**Comment by shorea** [comment]
Great to hear! :)
