### ISSUE TITLE
Cannot use KMS decrypt

### ISSUE THREAD

**Issue by tolidano** [aws/aws-sdk-java#1323]
Hi,

I wrote a Python tool and now I'm trying to port it to Java. The tool, in part, uses KMS to decrypt some data at some point.

Now, for reference, in Python, the call I'm making to KMS Decrypt has the following in the CipheredBody:
```
b'\x01\x02\x03\x00x\'rv\xcbW\x08\xf10y\n\x13c"\x07x\xfaG\xee\x84)8\xa0\xac\x87S\xcdts\x0c\xdf\x8f\xef\x01Q\x13\x86\xdf\xda\x8f\xde\xc9/(\x14\x92e\xce\x06v\x00\x00\x00~0|\x06\t*\x86H\x86\xf7\r\x01\x07\x06\xa0o0m\x02\x01\x000h\x06\t*\x86H\x86\xf7\r\x01\x07\x010\x1e\x06\t`\x86H\x01e\x03\x04\x01.0\x11\x04\x0c\xae2\xbaG\xc3\xd8|\x1f\xdd\xc6\xee\xb0\x02\x01\x10\x80;\x08\xea\xcawJ!\xbd\xff\xa9DK\x11gJ\x1d!\x95\xbczG\x9d\x9aD\xe1\x8dY\x0c.\x8f\xe7\x8a_J\x89\x1a\xd7\xa0H\xf1\xa65\x15+\x82\x17ZA\xe6\xce\x16\xdc\xdf\xd4\xc1+A\xa0JM'
```

Now, in Java, here is my code:
```
public String decrypt(final byte[] ciphertextBlob, final String context) {
        final ByteBuffer buffer = ByteBuffer.wrap(ciphertextBlob);
        final byte[] backup = new byte[buffer.remaining()];
        buffer.get(backup);
        System.out.println(Arrays.toString(backup));
        buffer.rewind(); //NOTE THIS LINE
        final Map<String, String> encryptionContext = getEncryptionContext(context);
        final DecryptRequest request = new DecryptRequest()
            .withEncryptionContext(encryptionContext)
            .withCiphertextBlob(buffer);
        final DecryptResult result = kms.decrypt(request);
        return result.getPlaintext().toString();
    }
```

Anyway, this is what gets printed for that System.out in the middle:
```
[1, 2, 3, 0, 120, 39, 114, 118, -53, 87, 8, -15, 48, 121, 10, 19, 99, 34, 7, 120, -6, 71, -18, -124, 41, 56, -96, -84, -121, 83, -51, 116, 115, 12, -33, -113, -17, 1, 81, 19, -122, -33, -38, -113, -34, -55, 47, 40, 20, -110, 101, -50, 6, 118, 0, 0, 0, 126, 48, 124, 6, 9, 42, -122, 72, -122, -9, 13, 1, 7, 6, -96, 111, 48, 109, 2, 1, 0, 48, 104, 6, 9, 42, -122, 72, -122, -9, 13, 1, 7, 1, 48, 30, 6, 9, 96, -122, 72, 1, 101, 3, 4, 1, 46, 48, 17, 4, 12, -82, 50, -70, 71, -61, -40, 124, 31, -35, -58, -18, -80, 2, 1, 16, -128, 59, 8, -22, -54, 119, 74, 33, -67, -1, -87, 68, 75, 17, 103, 74, 29, 33, -107, -68, 122, 71, -99, -102, 68, -31, -115, 89, 12, 46, -113, -25, -118, 95, 74, -119, 26, -41, -96, 72, -15, -90, 53, 21, 43, -126, 23, 90, 65, -26, -50, 22, -36, -33, -44, -63, 43, 65, -96, 74, 77]
```
You can see this matches the Python exactly (starts 1, 2, 3, ends with J and M (74 and 77)).

If I include the buffer.rewind(), I get this error:
```
com.amazonaws.services.kms.model.InvalidCiphertextException: null (Service: AWSKMS; Status Code: 400; Error Code: InvalidCiphertextException; Request ID: 846b6cc5-a587-11e7-ae8d-eb5a4d826e83)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.kms.AWSKMSClient.doInvoke(AWSKMSClient.java:3036)
	at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:3012)
	at com.amazonaws.services.kms.AWSKMSClient.executeDecrypt(AWSKMSClient.java:811)
	at com.amazonaws.services.kms.AWSKMSClient.decrypt(AWSKMSClient.java:787)
```

If I comment it out, I get this:
```
com.amazonaws.services.kms.model.AWSKMSException: 1 validation error detected: Value 'java.nio.HeapByteBuffer[pos=0 lim=0 cap=0]' at 'ciphertextBlob' failed to satisfy constraint: Member must have length greater than or equal to 1 (Service: AWSKMS; Status Code: 400; Error Code: ValidationException; Request ID: 6e627135-a588-11e7-816c-a3ef27b79385)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.kms.AWSKMSClient.doInvoke(AWSKMSClient.java:3036)
	at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:3012)
	at com.amazonaws.services.kms.AWSKMSClient.executeDecrypt(AWSKMSClient.java:811)
	at com.amazonaws.services.kms.AWSKMSClient.decrypt(AWSKMSClient.java:787)
```

I'm using SDK 1.11.200 with Java 1.8 and building with Maven 3.0.4.

Any help would be appreciated, I'm not sure what to do next...

**Comment by tolidano** [comment]
Tried changing buffer to buffer.asReadOnlyBuffer(), but no change (I also removed all that backup stuff and the rewind, and it's back to the InvalidCiphertextException: null error.

**Comment by tolidano** [comment]
If anyone else ever runs into this - the issue for me was that the encryption context did not match. It would be nice if there was a specific exception that identified that instead of making me look at the cipher text for a billion hours. In my case, I had one of the keys wrong. Once I corrected it, and verified that the JSON matched (for varying values of matched between Java and Python), I was able to move past this error and into the next one! Onward!

**Comment by varunnvs92** [comment]
To summarize, when you were using invalid EncryptionContext you got InvalidCiphertextException with null message. But you are expecting a different error code or better error messaging. Correct me if I mis-understood the issue.

**Comment by tolidano** [comment]
Correct.

InvalidEncryptionContextException would be nice.

But I understand that may not be possible, so at least updating the documentation and name of the exception to better indicate the range of issues.

- Shawn (iPhone)

**Comment by varunnvs92** [comment]
Correct, changing the exception type is not possible as it will break customer who rely on catching the old exception for this case.

Docs are managed by the service (KMS) team. I will open an internal issue with them to improve docs to include a range of issues this exception covers.

**Comment by varunnvs92** [comment]
Service team has updated the docs for "InvalidCiphertextException" in decrypt operation.
http://docs.aws.amazon.com/kms/latest/APIReference/API_Decrypt.html
