### ISSUE TITLE
Multipart Upload fails with NoHttpResponse against Ceph

### ISSUE THREAD

**Issue by Gilis95** [aws/aws-sdk-java#1328]
I want to upload a file in multiple parts to CEPH, an Amazon S3 compatible storage.
 
When I try to upload a file with multiple parts to Amazon S3 Storage, it works without errors and the tile is uploaded successfully.
When I try to upload a file with multiple parts to CEPH, S3 Compatible Storage, there is an error NoHttpResponseException.
 
This is happening with the same code.
 
If there is something I let escape or there is something specific for CEPH multipart upload, please share you knowledge. 
Thanks in advance!
 
I try with the following code:
```
 public class S3MultiPartUploadLowLevel {
 
    /**
     * CEPH
     */
    private static final String ACCESS_KEY = "123"; // write access key to CEPH Storage
    private static final String SECRET_KEY = "456"; // write secret key to CEPH Storage
    private static final String BUCKET_NAME = "bucket_name"; // write real bucket name
    private static final String ENDPOINT = "10.232.2.2:7480"; // write real CEPH Endpoint - host:port
   
    /**
     * Amazon
     */
     //private static final String ACCESS_KEY = ""; // access key to Amazon S3 Storage
     //private static final String SECRET_KEY = ""; // secret key to Amazon S3 Storage
     //private static final String BUCKET_NAME = ""; // bucket name
 
    private static final String KEY = "test.zip"; // write key name
    private static final String FILE_PATH = "D:/test.zip"; // write path to existing file
   
    private static AmazonS3 mS3Client = null;
   
    public static void main(String[] args) throws IOException {
        mS3Client = new AmazonS3Client(getCredentialsProvider(), getClientConfiguration());
        /** CEPH */
        mS3Client.setEndpoint(ENDPOINT); // only for CEPH
        /** Amazon */
       //mS3Client.setRegion(Region.getRegion(Regions.US_EAST_1)); // only for AMAZON
       
        try {
            multipartUploadLowLevel();
        } catch (AmazonClientException | IOException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
 
    }
   
    private static void multipartUploadLowLevel() throws IOException {
        // Create a list of UploadPartResponse objects. You get one of these
        // for each part upload.
        List<PartETag> partETags = new ArrayList<PartETag>();
 
        // Step 1: Initialize.
        InitiateMultipartUploadRequest initRequest = new InitiateMultipartUploadRequest(BUCKET_NAME, KEY);
        InitiateMultipartUploadResult initResponse = mS3Client.initiateMultipartUpload(initRequest);
        UploadPartRequest uploadRequest = null;
        UploadPartResult result = null;
       
        long partSize = 5 * 1024 * 1024; // Set part size to 5 MB.
 
        long totalStored = 0;
        byte[] byteArray = new byte[(int) (partSize)];
        ByteBuffer buffer = ByteBuffer.wrap(byteArray);
        int len;
        boolean isLastPart = false;
 
       InputStream eventInputStream = new FileInputStream(FILE_PATH);
        try {
            // Step 2: Upload parts.
            int partNumber = 1;
            String uploadId = initResponse.getUploadId();
           
            while (true) {
 
                len = eventInputStream.read(byteArray);
 
                if (len > 0) {
                    buffer.limit(len);
                   
                    if (len < partSize) {
                        isLastPart = true;
                    }
                   
                    // make sure you read the data corresponding to the part as InputStream.read() may return with
                    // less data than asked for
                    ByteArrayInputStream bais = new ByteArrayInputStream(buffer.array());
 
                    // Create request to upload a part.
                    uploadRequest = new UploadPartRequest()
                            .withUploadId(uploadId)
                            .withBucketName(BUCKET_NAME)
                            .withKey(KEY)
                            .withPartNumber(partNumber)
                            .withPartSize(len)
                            .withLastPart(isLastPart)
                            .withInputStream(bais);
 
                    ObjectMetadata metaData = new ObjectMetadata();
                    metaData.setContentType("binary/octet-stream");
                    metaData.setContentLength(len);
 
                    uploadRequest.setObjectMetadata(metaData);
                    
                    // Upload part and add response to our list.
                    result = mS3Client.uploadPart(uploadRequest);
                    partETags.add(result.getPartETag());
 
                    totalStored += len;
                    partNumber++;
 
                    buffer.clear();
                } else {
                    break;
                }
               
                if (isLastPart) {
                    break;
                }
            }
 
            // Step 3: Complete.
            CompleteMultipartUploadRequest compRequest = new CompleteMultipartUploadRequest(BUCKET_NAME, KEY,
                    initResponse.getUploadId(), partETags);
 
            mS3Client.completeMultipartUpload(compRequest);
 
            System.out.println("Total stored: " + totalStored);
 
        } catch (Exception e) {
            System.out.println("Got error: ");
            e.getCause().printStackTrace();
           
            System.out.println("Request: ");
            if (uploadRequest != null) {
                System.out.println("Access key: " + ACCESS_KEY);
                System.out.println("Secret key: " + SECRET_KEY);
                System.out.println("UploadId: " + uploadRequest.getUploadId());
                System.out.println("Bucket name: " + uploadRequest.getBucketName());
                System.out.println("Key: " + uploadRequest.getKey());
            }
            System.out.println();
            System.out.println("Response:");
            if (result != null) {
                System.out.println("Part number: " + result.getPartNumber());
                System.out.println("Part ETag: " + result.getPartETag());
            }
           
            AbortMultipartUploadRequest abortRequest = new AbortMultipartUploadRequest(BUCKET_NAME, KEY,
                    initResponse.getUploadId());
           
            mS3Client.abortMultipartUpload(abortRequest);
 
        } finally {
            if (eventInputStream != null) {
                try {
                    eventInputStream.close();
                } catch (Exception e) {
 
                }
            }
        }
    }
   
    private static AWSStaticCredentialsProvider getCredentialsProvider() {
        BasicAWSCredentials basicCredentials = new BasicAWSCredentials(ACCESS_KEY, SECRET_KEY);
        return new AWSStaticCredentialsProvider(basicCredentials);
    }
   
    private static ClientConfiguration getClientConfiguration() {
        ClientConfiguration clientConfiguration = new ClientConfiguration();
 
        clientConfiguration.setConnectionTimeout(10_000);
        clientConfiguration.setMaxConnections(100);
        clientConfiguration.setMaxErrorRetry(3);
        clientConfiguration.setProtocol(Protocol.HTTP);
        clientConfiguration.setSocketTimeout(60_000);
        clientConfiguration.setUseTcpKeepAlive(true);
        clientConfiguration.setSocketBufferSizeHints(65536, 65536);
        //clientConfiguration.setValidateAfterInactivityMillis(2_000);
        return clientConfiguration;
    }
   
}

```

When upload part is invoked I got NoHttpResponseException error:
```

org.apache.http.NoHttpResponseException: The target server failed to respond
       at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
       at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
       at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
       at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
       at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
       at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
       at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
       at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
       at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
       at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
       at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
       at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
       at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
       at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1181)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4191)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4138)
       at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:3180)
       at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3165)
       at com.axway.securetransport.hada.filesystem.external.S3MultiPartUploadLowLevel.multipartUploadLowLevel(S3MultiPartUploadLowLevel.java:125)
       at com.axway.securetransport.hada.filesystem.external.S3MultiPartUploadLowLevel.main(S3MultiPartUploadLowLevel.java:59)
```

When I try to abort initialized multipart upload it fails with next exception: 

```
com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: tx0000000000000005d2ad3-0059d49c26-868d-us-east), S3 Extended Request ID: 868d-us-east-us
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1579)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1249)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
       at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4191)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4138)
       at com.amazonaws.services.s3.AmazonS3Client.abortMultipartUpload(AmazonS3Client.java:2896)
       at com.axway.securetransport.hada.filesystem.external.S3MultiPartUploadLowLevel.multipartUploadLowLevel(S3MultiPartUploadLowLevel.java:171)
       at com.axway.securetransport.hada.filesystem.external.S3MultiPartUploadLowLevel.main(S3MultiPartUploadLowLevel.java:59)
 ```

**Comment by Gilis95** [comment]
I've found the issues. First one was that Ceph doesn't support v4 Signer which I resolve with `       clientConfiguration.withSignerOverride("S3SignerType");
` and second one was that socket timeout was way too small. You can mark issue as a resolved.

**Comment by varunnvs92** [comment]
For non-sdk related questions, please post them on stackoverflow as you will get better support over there. Thanks for the posting your findings. Resolving.
