### ISSUE TITLE
Confusing Javadoc for userData related functions

### ISSUE THREAD

**Issue by meowfaceman** [aws/aws-sdk-java#1329]
Hi all. The Javadoc for various userData functions is very confusing. To my eye, this Javadoc implies that the provided text will be base64 encoded automatically, as I'm using the AWS Java SDK. AFAICT, this is not the case. Here's a few of the problematic functions:

```
RunInstancesRequest.setUserData(String userData)
RunInstancesRequest.withUserData(String userData)
```

The description of the userData argument passed to these functions is as follows:

> The user data to make available to the instance. For more information, see Running Commands on Your Linux Instance at Launch (Linux) and Adding User Data (Windows). If you are using an AWS SDK or command line tool, base64-encoding is performed for you, and you can load the text from a file. Otherwise, you must provide base64-encoded text.

Am I missing something, or are these functions supposed to base64 encode the provided string? One caveat: we're using 1.11.125, so I don't know if this is a bug that's been corrected since then, but I didn't see anything obvious in the changelog.

**Comment by varunnvs92** [comment]
I didn't find the encoding in the marshallers or in the client. I am not sure if the javadocs are incorrect or the code is wrong. Did you try running the operation with plain text? If so, Did you get an error and any unexpected behavior?

**Comment by meowfaceman** [comment]
I've tried it with plaintext -- it seems to behave a bit strangely, but certainly not as intended. For example, running with "A test string" as user data seems to pass as expected, though I seem to be unable to view the user data through the EC2 UI. If I base64 encode it, I'm able to view it through the EC2 UI. Adding in special characters (#$!@) seems to trigger an error.

```
Caused by: com.cloudera.director.aws.shaded.com.amazonaws.services.ec2.model.AmazonEC2Exception: Invalid BASE64 encoding of user data (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 898b5ffe-41fe-487c-9e13-1b42e16aa0b7)
	at com.cloudera.director.aws.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588)
	at com.cloudera.director.aws.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.cloudera.director.aws.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.cloudera.director.aws.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.cloudera.director.aws.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.cloudera.director.aws.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.cloudera.director.aws.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.cloudera.director.aws.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.cloudera.director.aws.shaded.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.cloudera.director.aws.shaded.com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:13611)
	at com.cloudera.director.aws.shaded.com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:13587)
	at com.cloudera.director.aws.shaded.com.amazonaws.services.ec2.AmazonEC2Client.executeRunInstances(AmazonEC2Client.java:13091)
	at com.cloudera.director.aws.shaded.com.amazonaws.services.ec2.AmazonEC2AsyncClient$221.call(AmazonEC2AsyncClient.java:8875)
	at com.cloudera.director.aws.shaded.com.amazonaws.services.ec2.AmazonEC2AsyncClient$221.call(AmazonEC2AsyncClient.java:8869)
```

Our shading could be futzing something up here, but like you, reading through the code I didn't see anything that indicating it should be actually base64 encoding things.

**Comment by varunnvs92** [comment]
I don't know what is the correct behavior of the API. I have raised an internal issue for the service team. I will update when I have more information.

**Comment by varunnvs92** [comment]
The docs have been fixed. If you are using CLI or powershell tools, base64 encoding is done for you. If you are using any SDKs, you have to provide the encoded text. Resolving.
