### ISSUE TITLE
Facing DNSResolver issue with latest-208 also seen with 180 version of java sdk core, any resolution would be help

### ISSUE THREAD

**Issue by jagadeeshraju** [aws/aws-sdk-java#1330]
2017-10-06 13:13:00.744 ERROR 4036 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.NoClassDefFoundError: org/apache/http/conn/DnsResolver
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.<init>(ApacheHttpClientFactory.java:41) ~[aws-java-sdk-core-1.11.208.jar:na]
	at com.amazonaws.http.AmazonHttpClient.<clinit>(AmazonHttpClient.java:149) ~[aws-java-sdk-core-1.11.208.jar:na]
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:162) ~[aws-java-sdk-core-1.11.208.jar:na]
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:153) ~[aws-java-sdk-core-1.11.208.jar:na]
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:138) ~[aws-java-sdk-core-1.11.208.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.<init>(AmazonSQSClient.java:236) ~[aws-java-sdk-sqs-1.11.208.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.<init>(AmazonSQSClient.java:215) ~[aws-java-sdk-sqs-1.11.208.jar:na]
	at org.apache.camel.component.aws.sqs.SqsEndpoint.createClient(SqsEndpoint.java:197) ~[camel-aws-2.10.4.jar:2.10.4]
	at org.apache.camel.component.aws.sqs.SqsEndpoint.getClient(SqsEndpoint.java:182) ~[camel-aws-2.10.4.jar:2.10.4]
	at org.apache.camel.component.aws.sqs.SqsEndpoint.doStart(SqsEndpoint.java:77) ~[camel-aws-2.10.4.jar:2.10.4]
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:75) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.RouteService.doWarmUp(RouteService.java:157) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.RouteService.warmUp(RouteService.java:145) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.DefaultCamelContext.doWarmUpRoutes(DefaultCamelContext.java:3758) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3665) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3451) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3305) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.DefaultCamelContext.access$000(DefaultCamelContext.java:202) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3089) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.DefaultCamelContext$2.call(DefaultCamelContext.java:3085) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3108) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3085) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3022) ~[camel-core-2.19.2.jar:2.19.2]
	at org.apache.camel.spring.boot.RoutesCollector.maybeStart(RoutesCollector.java:242) ~[camel-spring-boot-2.19.3.jar:2.19.3]
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:217) ~[camel-spring-boot-2.19.3.jar:2.19.3]
	at org.apache.camel.spring.boot.RoutesCollector.onApplicationEvent(RoutesCollector.java:52) ~[camel-spring-boot-2.19.3.jar:2.19.3]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144) ~[spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at com.Philips.CamelESB.CamelApplication.main(CamelApplication.java:11) [classes/:na]
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.DnsResolver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
	... 43 common frames omitted

**Comment by shorea** [comment]
Check your dependency tree. Looks like you are pulling in an older version of Apache.

**Comment by dagnir** [comment]
Closing this due to inactivity. Please feel free to reopen if you still need help resolving this issue.
