### ISSUE TITLE
TransferManager with custom executor makes upload slow and fails

### ISSUE THREAD

**Issue by mentegy** [aws/aws-sdk-java#1335]
`"com.amazonaws" % "aws-java-sdk-s3" % "1.11.208"`
I have code which uses `TransferManager` multipart upload, however there's weird issue when passing custom executor service.
For example, if I create `TransferManager` like this:

```scala
TransferManagerBuilder
      .standard()
      .withS3Client(client)
      .build()
```

For ~2.1GB files I have upload time for 1 min 30 sec average. 
But once I'm adding custom executor service:

```scala
 // It's the same as 
 // 'com.amazonaws.services.s3.transfer.internal.TransferManagerUtils:createDefaultExecutorService'
 // however number threads is not hardcoded to 10
 def createDefaultExecutorService(threads: Int): ThreadPoolExecutor = {
    val threadFactory = new ThreadFactory() {
      private var threadCount = 1
      override  def newThread(r: Runnable): Thread = {
        val thread = new Thread(r)
        thread.setName(s"s3-transfer-manager-worker-$threadCount")
        threadCount += 1
        thread
      }
    }
    Executors.newFixedThreadPool(threads, threadFactory).asInstanceOf[ThreadPoolExecutor]
  }

  class ExecutorFactory(threads: Int) extends com.amazonaws.client.builder.ExecutorFactory {
    private val executor = createDefaultExecutorService(threads)
    def newExecutor(): ExecutorService = executor
  }


TransferManagerBuilder
      .standard()
      .withS3Client(client)
      .withExecutorFactory(new ExecutorFactory(opts.uploadParallelism))
      .build()
```
In fact, my uploads increases to ~ 10 mins and exception on the completion:
```
com.amazonaws.services.s3.model.AmazonS3Exception: Your proposed upload is smaller than the minimum allowed object size. (Service: Amazon S3; Status Code: 400; Error Code: EntityTooSmall; Request ID: 3L137; S3 Extended Request ID: 3L137)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194)
	at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:2990)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartUpload.call(CompleteMultipartUpload.java:94)
```

**Comment by kiiadi** [comment]
How many threads are you configuring on your executor service?

**Comment by mentegy** [comment]
As default, 10

**Comment by kiiadi** [comment]
@mentegy can you add the code-sample for how you're doing the upload? I've been playing around with this a bit and the performance looks pretty similar to me. When I'm uploading a 2GB file using the following, it takes approximately 260 seconds:

```java
AmazonS3 s3Client = AmazonS3Client.builder().withRegion("us-west-2").build();
TransferManager tm = TransferManagerBuilder.standard()
                                           .withS3Client(s3Client)
                                           .build();

File largeFile = createFileOfSize(2 * GB);

Duration time = timeUnsafe(() -> {
    Transfer t = tm.upload(BUCKET, "test-file-" + System.currentTimeMillis(), largeFile);
    t.waitForCompletion();
    System.out.println("Complete - " + t.getState());
});

System.out.println("Upload finished, took:" + time.get(ChronoUnit.SECONDS) + "seconds");
```

When I specify the executor factory (I've just referenced the util since as you say in your example your implementation is the same), it takes about the same (225 seconds):

```java
AmazonS3 s3Client = AmazonS3Client.builder().withRegion("us-west-2").build();
TransferManager tm = TransferManagerBuilder.standard()
                                           .withS3Client(s3Client)
                                           .withExecutorFactory(TransferManagerUtils::createDefaultExecutorService)
                                           .build();

File largeFile = createFileOfSize(2 * GB);

Duration time = timeUnsafe(() -> {
    Transfer t = tm.upload(BUCKET, "test-file-" + System.currentTimeMillis(), largeFile);
    t.waitForCompletion();
    System.out.println("Complete - " + t.getState());
});

System.out.println("Upload finished, took:" + time.get(ChronoUnit.SECONDS) + "seconds");
```

**Comment by mentegy** [comment]
@kiiadi Thank you for your time, I really appreciate your help!
However it was figured out that the problem was with `.withMinimumUploadPartSize(opts.uploadPartSize)` which wasn't mentioned in the desciption :(. We were setting `5 * 1024` instead of `5*1024*1024` in some weird cases which introduced false consequences in our test cases. And that's why upload speed dramatically decreases also. 

However I'm wondering why API is not prevented users from such mistakes, e.g. to allow TransferManager consume part size param which is less than 5mb

**Comment by kiiadi** [comment]
@mentegy that makes sense. I like the idea of validation, although typically we don't do client-side validation (the 5MB limit is set by S3) because it can cause problems for customers if the server-side changes. For example if we made the limit 5MB, enforced through `TransferManager` and S3 then changed their logic to allow smaller chunks, customers would not be able to take advantage of it without upgrading their SDK version (which may introduce other changes that they don't want to take on the risk of).

**Comment by mentegy** [comment]
@kiiadi That makes sense, thank's fot the explanation!
