### ISSUE TITLE
Failed to load DynamodDB on EMR 5.9 with Spark. 

### ISSUE THREAD

**Issue by shiju80** [aws/aws-sdk-java#1356]
Connecting to Dynamodb from a Spark job on EMR 5.9 fails with the following error

Following are the Gradle dependencies 

dependencies {
    compile group: 'com.amazonaws', name: 'aws-java-sdk', version: '1.11.183'
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'org.apache.spark', name: 'spark-mllib_2.11', version: '2.2.0'
    compile group: 'org.apache.spark', name: 'spark-core_2.11', version: '2.2.0'
    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.2'
}

Spark load HTTPClient 4.3.6 into classpath, but AmazonDynamoDB expects higher versions

Failing Oozie Launcher, Main class [org.apache.oozie.action.hadoop.SparkMain], main() threw exception, org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V
java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.<init>(SdkTLSSocketFactory.java:56)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:92)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:65)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:50)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:313)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:297)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:173)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.<init>(AmazonDynamoDBClient.java:285)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder.build(AmazonDynamoDBClientBuilder.java:60)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder.build(AmazonDynamoDBClientBuilder.java:26)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)

**Comment by spfink** [comment]
You can use our bundled SDK:

https://aws.amazon.com/blogs/developer/java-sdk-bundle/

Or try and relocate the client:

https://stackoverflow.com/questions/37843400/conflict-between-httpclient-version-and-apache-spark

**Comment by shiju80** [comment]
Thanks, will relocate and use
