### ISSUE TITLE
NullPointerException in com.amazonaws.metrics.AwsSdkMetrics.getRegion()

### ISSUE THREAD

**Issue by ajfabbri** [aws/aws-sdk-java#1375]
Even though cloudwatch metrics are disabled (default setting), Apache Hadoop, which uses the AWS SDK for S3 is getting this null pointer exception repeatedly, which is showing up in the JMX servlet logs.

AWS Java SDK version 1.11.199

Caused by: java.lang.NullPointerException
	at com.amazonaws.metrics.AwsSdkMetrics.getRegion(AwsSdkMetrics.java:729)
	at com.amazonaws.metrics.MetricAdmin.getRegion(MetricAdmin.java:67)
	at sun.reflect.GeneratedMethodAccessor132.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor12.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
	at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:83)
	at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)

**Comment by millems** [comment]
Thanks for the bug report! A fix has been made and will go out with the next release.

**Comment by ajfabbri** [comment]
Wow that was fast, thank you!
