### ISSUE TITLE
ReUse QuerySpec Object..

### ISSUE THREAD

**Issue by ahm9** [aws/aws-sdk-java#1376]
I'd like to put across an issue wherein we cannot reuse the existing QuerySpec object which has been created with a HashKey,RangeKey to query a table.. 

Would like to clarify a piece of code in the AWSDynamoDBJavaModel package  , literally it is this line https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-dynamodb/src/m... . 

In the above link , if u see that method "addKeyConditionsEntry", It says, when you pass a QuerySpec object to add the HashKey condition , if it already exists it throws "duplicate keys" exception , ideally, if the key exists it should not do anything and return the QueryRequest object. For example, if u call the addKeyConditionsEntry in a loop it will break. You should always send a new QuerySpec object. 

As an example if you consider a code flow which throws exception due to a conditional write / conditional read or any other scenario and you would want to query the table with the same index, you would need to create a new QuerySpec object and instead cant reuse the same . 

Would like to know if we can be able to reuse the same QuerySpec object so that we don't need to again form the same request with exactly same parameters and create new objects. 
I believe this would need a change in the SDK/Model used to generate the SDK. 

The exception trace is as follows for a HashKey called FooHashKey : 

java.lang.IllegalArgumentException: Duplicated keys (FooHashKey) are provided. 
at com.amazonaws.services.dynamodbv2.model.QueryRequest.addKeyConditionsEntry(QueryRequest.java:1479) 
at com.amazonaws.services.dynamodbv2.document.internal.QueryImpl.doQuery(QueryImpl.java:105) 
at com.amazonaws.services.dynamodbv2.document.internal.IndexQueryImpl.doQuery(IndexQueryImpl.java:38) 
at com.amazonaws.services.dynamodbv2.document.internal.QueryImpl.query(QueryImpl.java:95) 
at com.amazonaws.services.dynamodbv2.document.Index.query(Index.java:123) 
at com.amazon.momentsinternaltrigger.utils.TestMRDDB.testRuleQuery(TestMRDDB.java:128) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by millems** [comment]
Thanks for the bug report! We've successfully tested a fix internally and are working to get it out.

**Comment by millems** [comment]
A fix has been released to maven.

**Comment by ahm9** [comment]
This fix was applied only in java and not in other languages. The documents API is a Java-only high-level library, the add* semantics are pretty much different in other languages.It's still possible that other languages might also have the same set of mistakes , but its very unlikely and improbable.
