### ISSUE TITLE
AmazonS3Encryption's KMS client doesn't set the region properly

### ISSUE THREAD

**Issue by SaltwaterC** [aws/aws-sdk-java#1386]
This piece of code shows the issue at runtime:

```java
AWSCredentialsProvider credentials = new EnvironmentVariableCredentialsProvider();
KMSEncryptionMaterialsProvider encryptionMaterials = new KMSEncryptionMaterialsProvider(kmsCmkId);
CryptoConfiguration cryptoConf = new CryptoConfiguration(CryptoMode.StrictAuthenticatedEncryption);

AmazonS3Encryption s3 = AmazonS3EncryptionClientBuilder.standard()
  .withCredentials(credentials)
  .withEncryptionMaterials(encryptionMaterials)
  .withCryptoConfiguration(cryptoConf)
  .build();

s3.putObject(bucket, key, object);
```

`s3.getRegion()` returns "eu-west-1", however, the KMS client created internally still insists on going to the default "us-east-1".

This is how the thrown exception looks like:

```bash
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.services.kms.model.NotFoundException: Key 'arn:aws:kms:us-east-1:{account_id}:key/{key_id}' does not exist (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: {request_id})
[...]
```

The workaround is straightforward, but this behaviour is definitely not ideal.

```java
AWSKMS kms = AWSKMSClientBuilder.standard()
  .withCredentials(credentials)
  .build();

AmazonS3Encryption s3 = AmazonS3EncryptionClientBuilder.standard()
  .withCredentials(credentials)
  .withEncryptionMaterials(encryptionMaterials)
  .withCryptoConfiguration(cryptoConf)
  .withKmsClient(kms)
  .build();
```

**Comment by varunnvs92** [comment]
If KmsClient is not explicitly specified, you can specify the kmsclient region using the CryptoConfiguration class.
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/CryptoConfiguration.java#L45-L50

It might make sense to use the s3 client region if the value is not provided. But we can't change this behavior now as it will break existing customers. We will take this into account in our [v2 SDK](https://github.com/aws/aws-sdk-java-v2) which is in development.
