### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by qumingxing** [aws/aws-sdk-java#1402]
`java.lang.NoSuchMethodError: com.amazonaws.services.s3.internal.S3AbortableInputStream.isAborted()Z
        at com.amazonaws.services.s3.internal.S3AbortableInputStream.close(S3AbortableInputStream.java:175)
        at com.amazonaws.internal.SdkFilterInputStream.close(SdkFilterInputStream.java:89)
        at com.amazonaws.services.s3.model.S3ObjectInputStream.close(S3ObjectInputStream.java:136)
        at com.amazonaws.internal.SdkFilterInputStream.close(SdkFilterInputStream.java:89)
        at com.amazonaws.internal.SdkFilterInputStream.close(SdkFilterInputStream.java:89)
        at com.amazonaws.event.ProgressInputStream.close(ProgressInputStream.java:211)
        at com.amazonaws.internal.SdkFilterInputStream.close(SdkFilterInputStream.java:89)
        at com.amazonaws.internal.SdkFilterInputStream.close(SdkFilterInputStream.java:89)
        at com.amazonaws.services.s3.model.S3ObjectInputStream.close(S3ObjectInputStream.java:136)`

**Comment by dagnir** [comment]
@qumingxing You likely have an incompatible version of `aws-java-sdk-core` on your classpath. Please ensure that the versions of the S3 SDK and the core module are the same as we don't support mixing different versions.

**Comment by qumingxing** [comment]
@dagnir Thanks ,I will check it.
