### ISSUE TITLE
Tests fail when trying to build from source

### ISSUE THREAD

**Issue by csimmons0** [aws/aws-sdk-java#1409]
When I run "mvn clean install -Dgpg.skip=true" at commit f3eb88a09679985eafda573a3cb0f234795c00cb, the build fails due to test failures. Here is some of the output:
```
Hi
Tests run: 10, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 100.686 sec <<< FAILURE! - in com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest
nonProxyHostsNotNull_fakeHostDoesMatch(com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest)  Time elapsed: 10.127 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.net.UnknownHostException> but was<java.lang.AssertionError>
	at com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest.mockUnsuccessfulRequest(SdkProxyRoutePlannerIntegrationTest.java:135)
	at com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest.nonProxyHostsNotNull_fakeHostDoesMatch(SdkProxyRoutePlannerIntegrationTest.java:68)

nonProxyHostsWithWildcardPrefix_fakeHostDoesMatch(com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest)  Time elapsed: 10.127 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.net.UnknownHostException> but was<java.lang.AssertionError>
	at com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest.mockUnsuccessfulRequest(SdkProxyRoutePlannerIntegrationTest.java:135)
	at com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest.nonProxyHostsWithWildcardPrefix_fakeHostDoesMatch(SdkProxyRoutePlannerIntegrationTest.java:78)

nonProxyHostsWithWildcardSuffix_fakeHostDoesMatch(com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest)  Time elapsed: 10.117 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.net.UnknownHostException> but was<java.lang.AssertionError>
	at com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest.mockUnsuccessfulRequest(SdkProxyRoutePlannerIntegrationTest.java:135)
	at com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest.nonProxyHostsWithWildcardSuffix_fakeHostDoesMatch(SdkProxyRoutePlannerIntegrationTest.java:88)

nonProxyHostsWithOrSign_fakeHostDoesMatch(com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest)  Time elapsed: 10.086 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.net.UnknownHostException> but was<java.lang.AssertionError>
	at com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest.mockUnsuccessfulRequest(SdkProxyRoutePlannerIntegrationTest.java:135)
	at com.amazonaws.internal.SdkProxyRoutePlannerIntegrationTest.nonProxyHostsWithOrSign_fakeHostDoesMatch(SdkProxyRoutePlannerIntegrationTest.java:98)

Running com.amazonaws.internal.SdkSSLMetricsSocketTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.amazonaws.internal.SdkSSLMetricsSocketTest
Running com.amazonaws.metrics.AwsSdkMetricsTest
224949 [main] WARN com.amazonaws.metrics.AwsSdkMetrics  - Failed to enable the default metrics
java.lang.ClassNotFoundException: com.amazonaws.metrics.internal.cloudwatch.DefaultMetricCollectorFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.amazonaws.metrics.AwsSdkMetrics.enableDefaultMetrics(AwsSdkMetrics.java:619)
	at com.amazonaws.metrics.AwsSdkMetricsTest.test(AwsSdkMetricsTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**Comment by dagnir** [comment]
`f3eb88a` built cleanly on Travis https://travis-ci.org/aws/aws-sdk-java/builds/310283334 with `mvn install`

Can you provide some details on the the environment you're running on? Also have you tried rerunning? The tests can be flaky at times.

**Comment by shorea** [comment]
Closing issue, feel free to reopen if problem persists.
