### ISSUE TITLE
FileLockException when repeatedly download files to same location

### ISSUE THREAD

**Issue by zmz0305** [aws/aws-sdk-java#1410]
We are trying to download files with different key that have the same file name to one temp location using getObject() method, then copy the file to the actual location, in a single thread program.

For example, in S3 we have /dir1/file, /dir2/file. We then download /dir1/file into /tmp/file, then move to /actual/path1/file, then download /dir2/file into /tmp/file, then move to /actual/path2/file.

However, we are experience random FileLockExceptions during the download process. It appears that in faster machines we experience more of such issue.

And FYI, the files we are downloading only contain a 10 digit number, e.g. the files are very small.

Here is the log:
```
*****: Caused by: com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock /path/to/file for appendData=false
*****: at com.amazonaws.services.s3.internal.ServiceUtils.downloadToFile(ServiceUtils.java:292)
*****: at com.amazonaws.services.s3.internal.ServiceUtils.downloadObjectToFile(ServiceUtils.java:272)
*****: at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:404)
*****: at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1438)
*****: at com.yahoo.tp.storage.aws.s3.S3Store.get(S3Store.java:126)
*****: ... 9 common frames omitted
*****: Dec 06, 2017 3:26:15 AM com.amazonaws.services.s3.internal.ServiceUtils downloadToFile
*****: WARNING: Unable to calculate MD5 hash to validate download: /path/to/file (No such file or directory)
*****: java.io.FileNotFoundException: /path/to/file (No such file or directory)
*****: at java.io.FileInputStream.open0(Native Method)
*****: at java.io.FileInputStream.open(Unknown Source)
*****: at java.io.FileInputStream.<init>(Unknown Source)
*****: at com.amazonaws.services.s3.internal.ServiceUtils.downloadToFile(ServiceUtils.java:328)
*****: at com.amazonaws.services.s3.internal.ServiceUtils.downloadObjectToFile(ServiceUtils.java:272)
*****: at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:404)
*****: at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1438)

```
And usually there is this log before the lock exception happens:
``` 
WARNING: Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
```

**Comment by zmz0305** [comment]
Update:
I am very sorry that we made a mistake in our code. 
We accidentally used ConcurrentHashMap.forEach(1, ()->{}) thinking that the "1" is one thread. So we are actually running it in parallel and caused the lock issue.
