### ISSUE TITLE
Getting same error while calling any method using AWS ECS client

### ISSUE THREAD

**Issue by amishra88** [aws/aws-sdk-java#1422]
I am getting the below error while calling any method like runtask ,describe task using aws ECS client.
mt S3 upoad and denamoDB clients are working fine with any operation..using same credentials and client configurations for each of the clients.

**My code:**

AmazonECSClientBuilder amazonECSclientBuilder = AmazonECSClientBuilder.standard().withRegion("us-east-1")
				                                        .withClientConfiguration(commonUtils.setcClientconfig())
				                                        .withCredentials(new AWSStaticCredentialsProvider(commonUtils.setcredentials()));
AmazonECS amazonEcsClient =  amazonECSclientBuilder.build();

Collection<String> commandCollection = new ArrayList<String>();
		commandCollection.add("xyz");
		commandCollection.add("/var/xyz.js");
		commandCollection.add("s3:/xyz/0.xml"); //TODO
		commandCollection.add("Debug"); //TODO
		commandCollection.add("xyz"); 
		
		Collection<KeyValuePair> envCollection = new ArrayList<KeyValuePair>();
		KeyValuePair keypair = new KeyValuePair();
		keypair.setName("test");
		keypair.setValue("test");
		envCollection.add(keypair);
		
		ContainerOverride containerOverrider = new ContainerOverride();
		containerOverrider.setName("vncontainer");
		containerOverrider.setCommand(commandCollection);
		containerOverrider.setEnvironment(envCollection);
                Collection<ContainerOverride> overriderCollection = new ArrayList<ContainerOverride>();
		overriderCollection.add(containerOverrider);

     RunTaskRequest request = new RunTaskRequest().withTaskDefinition(taskDef)
				                       .withOverrides(taskOverride)
			                       .withCluster(cluster);

RunTaskResult response = amazonEcsClient.runTask(request);
System.out.println("==>" + response);

**My Console Error log:**

Dec 20, 2017 11:52:28 AM com.amazonaws.protocol.json.JsonContent parseJsonContent
INFO: Unable to parse HTTP response content
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@59ca5e; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:462)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2613)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:841)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:737)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3776)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2294)
	at com.amazonaws.protocol.json.JsonContent.parseJsonContent(JsonContent.java:72)
	at com.amazonaws.protocol.json.JsonContent.<init>(JsonContent.java:64)
	at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:54)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33)
	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1570)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:2592)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:2568)
	at com.amazonaws.services.ecs.AmazonECSClient.executeDescribeTasks(AmazonECSClient.java:1139)
	at com.amazonaws.services.ecs.AmazonECSClient.describeTasks(AmazonECSClient.java:1115)
	at com.fanniemae.vnmiddleware.util.ECSUtils.runtaskECS(ECSUtils.java:113)
	at com.fanniemae.vnmiddleware.util.ECSUtils.main(ECSUtils.java:130)

Exception in thread "main" com.amazonaws.services.ecs.model.AmazonECSException: null (Service: AmazonECS; Status Code: 404; Error Code: null; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:2592)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:2568)
	at com.amazonaws.services.ecs.AmazonECSClient.executeDescribeTasks(AmazonECSClient.java:1139)
	at com.amazonaws.services.ecs.AmazonECSClient.describeTasks(AmazonECSClient.java:1115)
	at com.fanniemae.vnmiddleware.util.ECSUtils.runtaskECS(ECSUtils.java:113)
	at com.fanniemae.vnmiddleware.util.ECSUtils.main(ECSUtils.java:130)

**Comment by dagnir** [comment]
Looks like the server is responding with an error that is not JSON formatted. Can you enable [wirelogging](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) and paste the output?

**Comment by amishra88** [comment]
Thank you.I fixed it now...the protocol I was using for client config was HTTP.making it HTTPS  worked.
clientConfig.setProtocol(Protocol.HTTPS);
