### ISSUE TITLE
Many XML Parse Exceptions when calling S3 deleteObjects

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#1430]
We are calling `deleteObjects` at a high rate and often get these which can be a drag. When I retry the request in a unit test in isolation it succeeds.  I'm guessing some there is some slow down message or something else that the AWS SDK code can't parse correctly. I guess what I'd like is for these kinds of parse exceptions to include a stringified version of the `InputStream` in the `AmazonSdkClientException`.  For example, it would be fantastic if you just added the raw stringified response here:
```
XmlResponsesSaxParser#parseXmlInputStream
            throw new SdkClientException("Failed to parse XML document with handler "
                + handler.getClass(), t);
```
Here's the exception. I think all `Failed to parse` exceptions would benefit from this. 
```
com.amazonaws.SdkClientException: Failed to parse XML document with handler class com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$DeleteObjectsHandler
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseXmlInputStream(XmlResponsesSaxParser.java:156) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseDeletedObjectsResult(XmlResponsesSaxParser.java:448) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.services.s3.model.transform.Unmarshallers$DeleteObjectsResultUnmarshaller.unmarshall(Unmarshallers.java:262) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.services.s3.model.transform.Unmarshallers$DeleteObjectsResultUnmarshaller.unmarshall(Unmarshallers.java:258) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:44) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:30) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1507) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1225) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4227) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4174) ~[rest-server-2.35.259.jar:2.35.259]
	at com.amazonaws.services.s3.AmazonS3Client.deleteObjects(AmazonS3Client.java:2100) ~[rest-server-2.35.259.jar:2.35.259]
	at 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: org.xml.sax.SAXParseException: Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1438) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_91]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[?:1.8.0_91]
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseXmlInputStream(XmlResponsesSaxParser.java:142) ~[rest-server-2.35.259.jar:2.35.259]
	... 27 more
```

**Comment by steveloughran** [comment]
Actually, if this error is a symptom of a throttling problem _and it can be retried_ then I'd like it be tagged as a throttling exception and retried.

**Comment by millems** [comment]
Sorry that this issue has taken so long to get a reply. We're primarily focused on 2.x of the SDK at this time, and as such won't be making this change in 1.11.x.
