### ISSUE TITLE
AmazonEC2Exception Error Code: RequestExpired from AmazonEC2 initialised with StaticCredentialsProvider

### ISSUE THREAD

**Issue by Ruenzuo** [aws/aws-sdk-java#1443]
We're seeing a lot of this exceptions in our `aws-sdk-java` usage with the following stack trace:
```
com.amazonaws.services.ec2.model.AmazonEC2Exception: Request has expired. (Service: AmazonEC2; Status Code: 400; Error Code: RequestExpired; Request ID: 213aa903-1660-42b7-838f-176cbed53e74)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:15651)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:15627)
	at com.amazonaws.services.ec2.AmazonEC2Client.executeDescribeInstances(AmazonEC2Client.java:7621)
	at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:7597)
	at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:7633)
```

We don't use the `aws-sdk-java` directly, but through another tool which creates an instance of `AmazonEC2` with `StaticCredentialsProvider`.

According to the `RequestExpired` [error code description](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html):

> The request reached the service more than 15 minutes after the date stamp on the request or more than 15 minutes after the request expiration date (such as for presigned URLs), or the date stamp on the request is more than 15 minutes in the future. If you're using temporary security credentials, this error can also occur if the credentials have expired.

We're not using temporary security credentials, the `StaticCredentialsProvider` is initialised with an `AWSCredentials` directly (`AWSAccessKeyId` and `AWSSecretKey`).

I don't understand how this could happen. As far as I can tell, the static credentials don't need to be refresh at any point and the computer time settings are configured correctly. 

I can't really share a sample project showing this because it's hard to reproduce, we only have the Java logs. Is there something we could do different to avoid the `RequestExpired` error?

**Comment by shorea** [comment]
Are the clocks on your server correct?

**Comment by Ruenzuo** [comment]
Not sure what do you mean with server specifically. The EC2 instance running the `aws-sdk-java` code has a correct UTC date settings. If this wasn't the case, this would be a constant error right? At the moment we're seeing a lot of those exceptions but they're not constant, sometimes it works just fine.

**Comment by spfink** [comment]
Are these occurring on a single host?

RequestExpired means that the time that the request was signed with is 15 minutes off from the time that the server that received your request has. This could mean that either your host in not in sync or the host that you are hitting to contact EC2 is not in sync. 

Can you enable wire-logging to get the date from the server? You can also log out the Date from the headers returned on the HttpResponse. This will help us in identifying where the problem is occurring.

**Comment by shorea** [comment]
@Ruenzuo are you still having issues?

**Comment by Ruenzuo** [comment]
@shorea @spfink We haven't seen this for a while now, so I'll close this issue and report back if it happens again with the information requested.
