### ISSUE TITLE
Uploading from a stream from cloudfront fails non-deterministically

### ISSUE THREAD

**Issue by OndraZizka** [aws/aws-sdk-java#1448]
We are observing something similar to  https://github.com/aws/aws-sdk-java/issues/749 .

We upload a file to S3, wait until it's done. Then we open an URLConnection to this file via CloudFront, and upload it somewhere again, using it's InputStream.

In some cases, this fails with: 

    SdkClientException: More data read than expected: dataLength=457963; expectedLength=454759;

The expected is correct length of the file. I have no idea where the extra data are coming from.

Provided that S3 confirmed the upload was done, and CloudFront is supposed to cache it transparently, what else could be the cause?
What should we do to prevent this from happening?

Downloading locally and uploading will cause a major performance drawback.
Giving it "some time" is not a deterministic solution.

```
com.amazonaws.SdkClientException: More data read than expected: dataLength=457963; expectedLength=454759; includeSkipped=false; in.getClass()=class com.amazonaws.internal.ReleasableInputStream; markedSupported=false; marked=0; resetSinceLastMarked=false; markCount=0; resetCount=0
! at com.amazonaws.util.LengthCheckInputStream.checkLength(LengthCheckInputStream.java:155)
! at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:109)
! at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82)
! at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.read(MD5DigestCalculatingInputStream.java:98)
! at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
! at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
! at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
! at com.amazonaws.internal.SdkBufferedInputStream.read(SdkBufferedInputStream.java:76)
! at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82)
! at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
! at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82)
! at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:140)
! at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:160)
! at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
! at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:160)
! at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
! at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)
! at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
! at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
! at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
! at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
! at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
! at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1189)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
! at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
! at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
! at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4227)
! at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4174)
! at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1722)
! at ...repository.service.impl.S3RepositoryService.write(S3RepositoryService.java:315)
```

See also https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/LengthCheckInputStream.java

**Comment by dagnir** [comment]
Are you replacing existing objects in the S3? If so, it seems like it could be a caching issue.

**Comment by shorea** [comment]
Having trouble understanding the flow. Are you uploading from a local file? Do you perhaps have a repro case I could run?

**Comment by varunnvs92** [comment]
Feel free to reopen if you still have the issue.

**Comment by OndraZizka** [comment]
We are uploading a local file to S3, where it doesn't exist yet. What kind of caching should be involved?
