### ISSUE TITLE
Unable to Execute S3 AmazonS3ClientBuilder.standard().withCredentials

### ISSUE THREAD

**Issue by tapanbanker** [aws/aws-sdk-java#1459]
Receiving Error because of conflict with POM. The AWS S3 AmazonS3 s3Client = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(credentials)).build();
 Is Causing the Problem because of using the conflict with following jar and depencency. 
<dependency>
            <groupId>com.github.fge</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>2.2.6</version>
        </dependency>
        <dependency>
            <groupId>com.github.fge</groupId>
            <artifactId>jackson-coreutils</artifactId>
            <version>1.8</version>
        </dependency>
        <dependency>
            <groupId>com.github.fge</groupId>
            <artifactId>json-schema-core</artifactId>

            <version>1.2.5</version>
        </dependency>       

WARNING: The legacy profile format requires the 'profile ' prefix before the profile name. The latest code does not require such prefix, and will consider it as part of the profile name. Please remove the prefix if you are seeing this warning.
Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;
	at com.amazonaws.partitions.PartitionsLoader.<clinit>(PartitionsLoader.java:54)
	at com.amazonaws.regions.RegionMetadataFactory.create(RegionMetadataFactory.java:30)
	at com.amazonaws.regions.RegionUtils.initialize(RegionUtils.java:64)
	at com.amazonaws.regions.RegionUtils.getRegionMetadata(RegionUtils.java:52)
	at com.amazonaws.regions.RegionUtils.getRegion(RegionUtils.java:105)
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:369)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:337)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at io.aws.s3.utilility.AWSS3Utility.listS3Buckets(AWSS3Utility.java:47)
	at ApplicationExcel.main(ApplicationExcel.java:33)

Process finished with exit code 1

**Comment by varunnvs92** [comment]
SDK depends on [jackson version - 2.6.7](https://github.com/aws/aws-sdk-java/blob/master/pom.xml#L178-L179). You should be using a version equal or greater than this.
The version of the ObjectMapper you project is referencing doesn't have the enable(..) method. Please fix your dependencies which will resolve the issue.

**Comment by dagnir** [comment]
Definitely looks like a version issue with jackson. Any luck upgrading your Jackson dependency to 2.6.7 per @varunnvs92's comment?

Note also that we distribute a shaded version of the SDK if you are unable to fix your dependency conflict: https://aws.amazon.com/blogs/developer/java-sdk-bundle/. As noted in the Blog post, we only recommend using the Bundle if you absolutely have to because it's a sizeable JAR (~50 MB, and growing with each new service).

**Comment by tapanbanker** [comment]
I have been using the latest version of aws-sdk (java) also tried Jackson 2.6.7. Still have issues

**Comment by dagnir** [comment]
Do you have dependencies that cause a conflict for Jackson? Can you show us the output of `mvn dependency:tree`?

**Comment by dagnir** [comment]
Closing due to no response. Please feel free to reopen if you're still experiencing this issue.

**Comment by yogesh-0586** [comment]
Hi, I have same issues I run this code in aws-emr cluster as below 
`spark-shell --jars aws-java-sdk-1.11.350.jar, RedshiftJDBC42-1.2.15.1025.jar`

```
import com.amazonaws.services.redshift.AmazonRedshiftClient
import com.amazonaws.auth.{AWSSessionCredentials, InstanceProfileCredentialsProvider}
import com.amazonaws.services.redshift.model._
import com.amazonaws.services.securitytoken.AWSSecurityTokenService
import com.amazonaws.services.securitytoken.model.AssumeRoleRequest
import com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder
import com.amazonaws.auth.profile.ProfileCredentialsProvider

val roleARN = "roleARN"
val roleSessionName = "roleName"
val clientRegion = "us-east-1"

val stsClient : AWSSecurityTokenService = AWSSecurityTokenServiceClientBuilder.standard().withCredentials(new ProfileCredentialsProvider()).withRegion(clientRegion).build()
```

but it show following error 

> java.lang.NoSuchMethodError: com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.<init>(Lcom/amazonaws/client/AwsSyncClientParams;)V
  at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:60)
  at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder.build(AWSSecurityTokenServiceClientBuilder.java:26)
  at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
  ... 50 elided
