### ISSUE TITLE
Uncaught error from thread ProcessingAkkaSpringContext-akka.actor.default-dispatcher-3 shutting down JVM since 'akka.j vm-exit-on-fatal-error' is enabled for ActorSystem[ProcessingAkkaSpringContext java.lang.AbstractMethodError: com.amazonaws.services.s3.internal.S3Signer.sign

### ISSUE THREAD

**Issue by avmgan** [aws/aws-sdk-java#1475]
I'm trying to store the images in S3 using amazonaws SDK.

I used following versions.

```
>    <dependencyManagement>
>         <dependencies>
>             <dependency>
>                 <groupId>com.amazonaws</groupId>
>                 <artifactId>aws-java-sdk-bom</artifactId>
>                 <version>1.10.43</version>
>                 <type>pom</type>
>                 <scope>import</scope>
>             </dependency>
>         </dependencies>
>     </dependencyManagement>
>     <dependencies>
>         <dependency>
>             <groupId>com.amazonaws</groupId>
>             <artifactId>aws-java-sdk</artifactId>
>             <version>1.11.6</version>
>         </dependency>
>     </dependencies>
```

Following block of code execution service getting stopped:
 ```
public void SaveBinaryObject(String keyName, BinaryContent binaryContent) throws Exception
    {
        try {

            LOG.info("SaveBinaryObject: Start...");
            InputStream inputBinaryStream = new ByteArrayInputStream(binaryContent.getContent());

            ObjectMetadata objMeta = new ObjectMetadata();
            objMeta.setContentEncoding("UTF-8");
            objMeta.setContentLength(binaryContent.getContent().length);
            objMeta.setContentType("image/jpg");

            if (amazonS3 != null) {
                amazonS3.putObject(new PutObjectRequest(
                        bucketName, keyName, inputBinaryStream, objMeta)
                        .withCannedAcl(CannedAccessControlList.PublicRead));
                LOG.info("SaveBinaryObject: Upload complete");

            } else {
                LOG.info("SaveBinaryObject: Upload can't be done amazonS3 null");
            }
        }
        catch (Exception e)
        {
            LOG.error(e.getLocalizedMessage(),e);
        }
    }
```

Error:
Uncaught error from thread [ProcessingAkkaSpringContext-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.j
vm-exit-on-fatal-error' is enabled for ActorSystem[ProcessingAkkaSpringContext]
java.lang.AbstractMethodError: com.amazonaws.services.s3.internal.S3Signer.sign(Lcom/amazonaws/Request;Lcom/amazonaws/au
th/AWSCredentials;)V
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:652)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3643)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1408)
        at com.tridion.storage.aws.AwsClientRequest.SaveBinaryObject(AwsClientRequest.java:79)
        at com.tridion.storage.aws.dao.FSAWSBinaryContentDAO.update(FSAWSBinaryContentDAO.java:80)
        at com.tridion.storage.deploy.workers.BinaryWorker.doDeploy(BinaryWorker.java:101)
        at com.tridion.deployer.model.transaction.TransactionLogItemWorker.doWork(TransactionLogItemWorker.java:42)
        at com.sdl.delivery.deployer.steps.TridionPreCommitStep.process(TridionPreCommitStep.java:67)
        at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.com$sdl$delivery$deployer$engine$pipeline$actor$Ste
pActor$$execute(StepActor.scala:60)
        at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor$$anonfun$receive$1.applyOrElse(StepActor.scala:44)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
        at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.aroundReceive(StepActor.scala:27)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[ERROR] [02/17/2018 15:59:08.708] [ProcessingAkkaSpringContext-akka.actor.default-dispatcher-3] [akka.actor.ActorSystemI
mpl(ProcessingAkkaSpringContext)] Uncaught error from thread [ProcessingAkkaSpringContext-akka.actor.default-dispatcher-
3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.AbstractMethodError: com.amazonaws.services.s3.internal.S3Signer.sign(Lcom/amazonaws/Request;Lcom/amazonaws/au
th/AWSCredentials;)V
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:652)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3643)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1408)
        at com.tridion.storage.aws.AwsClientRequest.SaveBinaryObject(AwsClientRequest.java:79)
        at com.tridion.storage.aws.dao.FSAWSBinaryContentDAO.update(FSAWSBinaryContentDAO.java:80)
        at com.tridion.storage.deploy.workers.BinaryWorker.doDeploy(BinaryWorker.java:101)
        at com.tridion.deployer.model.transaction.TransactionLogItemWorker.doWork(TransactionLogItemWorker.java:42)
        at com.sdl.delivery.deployer.steps.TridionPreCommitStep.process(TridionPreCommitStep.java:67)
        at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.com$sdl$delivery$deployer$engine$pipeline$actor$Ste
pActor$$execute(StepActor.scala:60)
        at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor$$anonfun$receive$1.applyOrElse(StepActor.scala:44)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
        at com.sdl.delivery.deployer.engine.pipeline.actor.StepActor.aroundReceive(StepActor.scala:27)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Any help would be much appreciated

**Comment by shorea** [comment]
Looks like you are importing a 1.10.x BOM but using 1.11.x of the SDK. These versions are not compatible and can cause runtime errors such as these. Also we don't recommend depending on the aws-java-sdk module since it has every single service module (over 100), typically you'll want to import the BOM and then depend on just the services you need.

**Comment by avmgan** [comment]
Yes. you are right. I did use specific version and then again got different issue and logged here

Caused by: java.lang.NoSuchMethodError: com.amazonaws.SDKGlobalConfiguration.isInRegionOptimizedModeEnabled

https://github.com/aws/aws-sdk-java/issues/1476 - It's fixed its own version of the AWS SDK and they're colliding. 
Closing this issue, thank you for the help!

**Comment by avmgan** [comment]
Closing this issue, thank you for the help!
