### ISSUE TITLE
Software caused connection abort: socket write error

### ISSUE THREAD

**Issue by sunkur100** [aws/aws-sdk-java#1478]
Hi,

I am getting this error when I try to create a folder or upload a file. But I am able to get the list from the bucket successfully. Could you please suggest.
I am using aws-java-sdk-1.11.158.jar,aws-java-sdk-core-1.11.194.jar,httpclient-4.5.2.jar

Exception in thread "main" com.amazonaws.SdkClientException: Unable to execute HTTP request: Software caused connection abort: socket write error
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1063)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4229)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4176)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1720)
	at com.van.example.S3Client.createFolder(S3Client.java:36)
	at com.van.example.S3Client.main(S3Client.java:63)
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flush(SessionOutputBufferImpl.java:144)
	at org.apache.http.impl.BHttpConnectionBase.doFlush(BHttpConnectionBase.java:175)
	at org.apache.http.impl.DefaultBHttpClientConnection.flush(DefaultBHttpClientConnection.java:183)
	at org.apache.http.impl.conn.CPoolProxy.flush(CPoolProxy.java:177)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:216)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)

I appreciate your great help in advance.

Thank you
SK

**Comment by spfink** [comment]
Can you provide a code sample for how you are configuring your client?

**Comment by sunkur100** [comment]
Hi, 

Thank you very much for the response. I copied my client class here. Could you please suggest if this is correct way to connect through endpoint.


package com.cccc.s3;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.InputStream;
import java.util.List;

import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.Bucket;
import com.amazonaws.services.s3.model.ObjectListing;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.PutObjectRequest;
import com.amazonaws.services.s3.model.S3ObjectSummary;

public class S3Client {
	 
    private static void createFolder(String bucketName, String folderName, AmazonS3 client) {
 
        // Create meta-data for your folder and set content-length to 0
        ObjectMetadata metadata = new ObjectMetadata();
        metadata.setContentLength(0);
 
        // Create empty content
        InputStream emptyContent = new ByteArrayInputStream(new byte[0]);
 
        // Create a PutObjectRequest passing the folder name suffixed by /
        String SUFFIX = "/";
        PutObjectRequest putObjectRequest = new PutObjectRequest(bucketName, folderName + SUFFIX, emptyContent, metadata);
 
        // Send request to S3 to create folder
        client.putObject(putObjectRequest);
    }
 
    private static void upload(String bucketName, String tgtFile, String srcFile,
                               AmazonS3 client) {
        client.putObject(new PutObjectRequest(bucketName, tgtFile, new File(srcFile)));
    }
 
    public static void main(String[] args) {
 
        // Creating AWS Client
        AWSCredentials credentials = new BasicAWSCredentials("comp-s3-user", "yyyyy");
        // Note, you should NOT hardcode your credentials in the code when you deploy to BXP3. You should retrieve your S3 credentials using Secrets Management Service (SMS)
        // This reference application is only for displaying how to access S3 storage in your application
         
        AmazonS3 s3client = AmazonS3ClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(credentials))
                .enablePathStyleAccess()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://aaa.bbbb.net:9020", "nnnn")).build();
 
        // List all of your buckets
        for (Bucket bucket : s3client.listBuckets()) {
            System.out.println(" - " + bucket.getName());
        }
        String bucketName = "comp-s3-bucket";
 
        // Create a folder in the bucket
      //  createFolder(bucketName, "logs", s3client);
 
        // Upolad an object
        String tgtFile = "test/log.txt";
        upload(bucketName, tgtFile, "/Users/ttt/Documents/log.txt", s3client);
 
        // List all objects in your bucket
        ObjectListing ol = s3client.listObjects(bucketName);
        List<S3ObjectSummary> objects = ol.getObjectSummaries();
        for (S3ObjectSummary os : objects) {
            System.out.println("* " + os.getKey());
        }
 
        // Delete an object
      //  s3client.deleteObject(bucketName, tgtFile);
 
    }
 
}

Thank you,
SK

**Comment by spfink** [comment]
Are you attempting to use a proxy?

**Comment by sunkur100** [comment]
I think, we have proxy through our company's network. I don't gave issue while getting list from the bucket. 
I see error only during create and upload.

Thank you,
SK

**Comment by spfink** [comment]
If you are using a proxy you should be using the proxy configuration within the ClientConfiguration class.

This definitely seems like an issue with your proxy / network. The create folder operation and upload operation you are doing are longer processes as compared to just doing a list of buckets. I would check to verify your proxy is not killing the connection.

**Comment by sunkur100** [comment]
Sure. I will check.

Thank you,
SK

**Comment by dagnir** [comment]
@sunkur100 Were you able to configure the SDK with the proxy details per @spfink's recommentation? Are you still experiencing this issue?

**Comment by shorea** [comment]
Closing due to no response. Feel free to reopen if problem persists.
