### ISSUE TITLE
java.lang.NoSuchMethodError: com.amazonaws.auth.DefaultAWSCredentialsProviderChain.getInstance()Lcom/amazonaws/auth/DefaultAWSCredentialsProviderChain

### ISSUE THREAD

**Issue by gvasquez-waypoint** [aws/aws-sdk-java#1485]
We have a strange situation where a Java DynamoDB code runs smoothly when invoked from a JUnit test but, fails awfully when the same code is run within Tomcat.

Offending code:

    static AmazonDynamoDB client = AmazonDynamoDBClientBuilder
			.standard()
			.withRegion(Regions.US_EAST_1)
			.build();

Maven's pom.xml dependency:

		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-dynamodb</artifactId>
			<version>1.11.283</version>
		</dependency>

Java Version: JRE 1.8.0_144
Tomcat 8.0.47

In JUnit scenario key/secret are automatically read from the "credentials" file and, in Tomcat they are passed as Environment properties just to be sure (perhaps they are not needed though).

Stacktrace:

    SEVERE: Servlet.service() for servlet [dispatcher] in context with path [/TrackViewReport] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: com.amazonaws.auth.DefaultAWSCredentialsProviderChain.getInstance()Lcom/amazonaws/auth/DefaultAWSCredentialsProviderChain;] with root cause
    java.lang.NoSuchMethodError: com.amazonaws.auth.DefaultAWSCredentialsProviderChain.getInstance()Lcom/amazonaws/auth/DefaultAWSCredentialsProviderChain;
    	at com.amazonaws.client.builder.AwsClientBuilder.resolveCredentials(AwsClientBuilder.java:125)
    	at com.amazonaws.client.builder.AwsClientBuilder.access$100(AwsClientBuilder.java:52)
    	at com.amazonaws.client.builder.AwsClientBuilder$SyncBuilderParams.<init>(AwsClientBuilder.java:412)
    	at com.amazonaws.client.builder.AwsClientBuilder.getSyncClientParams(AwsClientBuilder.java:354)
    	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
    	at cl.waypoint.repositories.DynamoCRUD.<clinit>(DynamoCRUD.java:26)
    	at model.ReporteCumplimientoModel.getData(ReporteCumplimientoModel.java:39)
    	at model.ReporteCumplimientoModel.armaReporte(ReporteCumplimientoModel.java:43)
    	at cl.waypoint.rest.ReporteCumplimiento.getReportePorFecha(ReporteCumplimiento.java:24)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
    	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
    	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
    	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
    	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
    	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
    	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
    	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
    	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
    	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
    	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
    	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
    	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
    	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
    	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
    	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
    	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
    	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
    	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
    	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
    	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
    	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
    	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    	at java.lang.Thread.run(Thread.java:748)

**Comment by gvasquez-waypoint** [comment]
This happens on local computer: Windows 10 Pro

**Comment by spfink** [comment]
Can you provide your full pom? Sounds like you are mixing versions of the Java SDK.

**Comment by gvasquez-waypoint** [comment]
@spfink I thought that might be the problem, but according to our check it's not, this is the full pom.xml:

    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    	<modelVersion>4.0.0</modelVersion>
    	<groupId>TrackViewReport</groupId>
    	<artifactId>TrackViewReport</artifactId>
    	<version>0.3.0</version>
    	<packaging>war</packaging>
    	<properties>
    		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    	</properties>
    	<build>
    		<finalName>${project.artifactId}##${project.version}</finalName>
    		<sourceDirectory>src</sourceDirectory>
    		<plugins>
    			<plugin>
    				<artifactId>maven-compiler-plugin</artifactId>
    				<version>3.5.1</version>
    				<configuration>
    					<source>1.8</source>
    					<target>1.8</target>
    				</configuration>
    			</plugin>
    			<plugin>
    				<artifactId>maven-war-plugin</artifactId>
    				<version>3.0.0</version>
    				<configuration>
    					<warSourceDirectory>WebContent</warSourceDirectory>
    				</configuration>
    			</plugin>
    			<plugin>
    				<groupId>org.apache.maven.plugins</groupId>
    				<artifactId>maven-resources-plugin</artifactId>
    				<version>3.0.2</version>
    				<configuration>
    					<encoding>UTF-8</encoding>
    				</configuration>
    			</plugin>
    		</plugins>
    	</build>
    	<dependencies>
    		<dependency>
    			<groupId>org.springframework</groupId>
    			<artifactId>spring-webmvc</artifactId>
    			<version>4.3.4.RELEASE</version>
    		</dependency>
    		<dependency>
    			<groupId>com.fasterxml.jackson.core</groupId>
    			<artifactId>jackson-databind</artifactId>
    			<version>2.8.5</version>
    		</dependency>
    		<dependency>
    			<groupId>org.hibernate</groupId>
    			<artifactId>hibernate-validator</artifactId>
    			<version>5.2.4.Final</version>
    		</dependency>
    		<dependency>
    			<groupId>org.springframework</groupId>
    			<artifactId>spring-jdbc</artifactId>
    			<version>4.3.4.RELEASE</version>
    		</dependency>
    		<dependency>
    			<groupId>org.apache.poi</groupId>
    			<artifactId>poi-ooxml</artifactId>
    			<version>3.9</version>
    		</dependency>
    		<dependency>
    			<groupId>javax.servlet</groupId>
    			<artifactId>javax.servlet-api</artifactId>
    			<version>3.1.0</version>
    			<scope>provided</scope>
    		</dependency>
    		<dependency>
    			<groupId>net.sf.jasperreports</groupId>
    			<artifactId>jasperreports</artifactId>
    			<version>6.4.1</version>
    			<exclusions>
    				<exclusion>
    					<groupId>com.fasterxml.jackson.core</groupId>
    					<artifactId>jackson-core</artifactId>
    				</exclusion>
    			</exclusions>
    		</dependency>
    
    		<dependency>
    			<groupId>com.amazonaws</groupId>
    			<artifactId>aws-java-sdk-dynamodb</artifactId>
    			<version>1.11.283</version>
    		</dependency>
    		
    
    
    
    
    		<dependency>
    			<groupId>junit</groupId>
    			<artifactId>junit</artifactId>
    			<version>4.12</version>
    		</dependency>
    
    		<dependency>
    			<groupId>log4j</groupId>
    			<artifactId>log4j</artifactId>
    			<version>1.2.17</version>
    		</dependency>
    	</dependencies>
    </project>

We also tried to see transitive hidden dependencies via Eclipse and no other aws-sdk is referenced:

![760221_4170658ck2ow62658a5t4d_x_427x570](https://user-images.githubusercontent.com/14003078/36608847-d2a502ac-18a9-11e8-96ec-557851bbc1ca.jpg)

**Comment by spfink** [comment]
I assume the check in Eclipse is similar/the same as mvn dependency:tree?

Weird that it works in your junit tests and not in your Tomcat environment. Can you run the maven dependency tree command within your Tomcat environment?

**Comment by gvasquez-waypoint** [comment]
I also assume the check is the same, but cannot confirm it.

Tomcat is running integrated within Eclipse, so I don't really know how to actually run such maven command as there's no CLI available there.

Any other ideas?

**Comment by shorea** [comment]
You can print out where it's being loaded from 

```java
 System.out.println(DefaultAWSCredentialsProviderChain.class.getProtectionDomain().getCodeSource());
```

**Comment by gvasquez-waypoint** [comment]
Problem solved, there were actually several different AWS-SDK versions in Tomcat's classpath but, they were not actually "visible" from Eclipse, seems like the regular Maven/Eclipse problems messed this out.
