### ISSUE TITLE
S3Link Jackson Unmarshalling Issue

### ISSUE THREAD

**Issue by mayankX** [aws/aws-sdk-java#1497]
Getting following exception log while trying to unmarshal DynamoDB POJO Bean having S3Link object.

-----

Caused by: java.lang.IllegalArgumentException: Conflicting setter definitions for property "acl": com.amazonaws.services.dynamodbv2.datamodeling.S3Link#setAcl(1 params) vs com.amazonaws.services.dynamodbv2.datamodeling.S3Link#setAcl(1 params)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:497)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getPrimaryType(POJOPropertyBuilder.java:338)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getRawPrimaryType(POJOPropertyBuilder.java:358)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.filterBeanProps(BeanDeserializerFactory.java:625)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:495)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:227)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:137)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)

**Comment by shorea** [comment]
Using a newer version of Jackson databind will fix it.

**Comment by varunnvs92** [comment]
Try shorea@ suggestion and feel free to reopen if it doesn't solve the issue.

**Comment by vishalbhushan** [comment]
@varunnvs92 How did we fixed the issue. I am facing the similar issue. I tried with latest version of jackson but still not working for me
