### ISSUE TITLE
No such method error in ses java SDK

### ISSUE THREAD

**Issue by nitinvavdiya** [aws/aws-sdk-java#1524]
Hello, 
I am using AWS SES to send emails.
There is no compilation issue in my project, but its throws runtime exception.
Here is the full stack trace.

```
java.lang.NoSuchMethodError: com.amazonaws.services.simpleemail.AmazonSimpleEmailServiceClient.beforeClientExecution(Lcom/amazonaws/AmazonWebServiceRequest;)Lcom/amazonaws/AmazonWebServiceRequest;
	at com.amazonaws.services.simpleemail.AmazonSimpleEmailServiceClient.sendEmail(AmazonSimpleEmailServiceClient.java:3492) ~[aws-java-sdk-ses-1.11.281.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:180) ~[spring-messaging-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:112) ~[spring-messaging-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:104) ~[spring-jms-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:69) ~[spring-jms-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:719) ~[spring-jms-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:679) ~[spring-jms-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:649) ~[spring-jms-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:317) [spring-jms-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:255) [spring-jms-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1166) [spring-jms-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1158) [spring-jms-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1055) [spring-jms-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

```

Here is gradle runtime dependency tree.

```
+--- com.amazonaws:aws-java-sdk-ses:1.11.281
|    +--- com.amazonaws:aws-java-sdk-core:1.11.281
|    |    +--- commons-logging:commons-logging:1.1.3 -> 1.2
|    |    +--- org.apache.httpcomponents:httpclient:4.5.2 -> 4.5 (*)
|    |    +--- software.amazon.ion:ion-java:1.0.2
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.6.7.1 -> 2.8.10 (*)
|    |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:2.6.7 -> 2.8.10
|    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.8.10
|    |    \--- joda-time:joda-time:2.8.1 -> 2.7
|    \--- com.amazonaws:jmespath-java:1.11.281 -> 1.11.83
|         \--- com.fasterxml.jackson.core:jackson-databind:2.6.6 -> 2.8.10 (*)
\--- com.amazonaws:aws-java-sdk-core:1.11.281 (*)

``` 
Code to send email is.
```
SendEmailRequest request = new SendEmailRequest()
        .withDestination(
            new Destination().withToAddresses(emailRequest.getTo()).withBccAddresses(emailRequest.getBcc()))
        .withMessage(new Message()
            .withBody(new Body()
                .withHtml(new Content()
                    .withCharset(StringPool.APPLICATION_CONTENT_TYPE_UTF_8).withData(emailRequest.getText()))
                .withText(new Content()
                    .withCharset(StringPool.APPLICATION_CONTENT_TYPE_UTF_8).withData(emailRequest.getText())))
            .withSubject(new Content()
                .withCharset(StringPool.APPLICATION_CONTENT_TYPE_UTF_8).withData(emailRequest.getSubject())))
        .withSource(emailRequest.getFrom()).withConfigurationSetName("email_notification_config_set");


client.sendEmail(request);
```

I also tried with 
```
// https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-ses
compile group: 'com.amazonaws', name: 'aws-java-sdk-ses', version: '1.11.301'
```
but same run time error

**Comment by nitinvavdiya** [comment]
When I change the version of sdks to 
```
compile group: 'com.amazonaws', name: 'aws-java-sdk-ses', version: '1.11.83'
compile group: 'com.amazonaws', name: 'aws-java-sdk-core', version: '1.11.83'
```
It works!!

**Comment by dagnir** [comment]
Hi @nitinvavdiya `beforeClientExecution` didn't exist in `1.11.83` on the `AmazonWebServiceClient` class in core: https://github.com/aws/aws-sdk-java/blob/308100738986512661ae28b444587f73010cd667/aws-java-sdk-core/src/main/java/com/amazonaws/AmazonWebServiceClient.java#L58 which is probably why using `1.11.83` of SES is working fine, but not any of the newer versions.

Can you check to see that you're not actually using an older version of the core package during runtime, possibly by checking the runtime classpath?

**Comment by nitinvavdiya** [comment]
@dagnir 
I already added run time Gradle dependency tree. Do you need the full tree?

**Comment by dagnir** [comment]
The full tree might help, but what I was getting at is we should also check there isn't an older version of the core module getting on the classpath somehow. As you can see here, `beforeClientExecution` is definitely present in `1.11.281`: https://github.com/aws/aws-sdk-java/blob/1.11.281/aws-java-sdk-core/src/main/java/com/amazonaws/AmazonWebServiceClient.java#L664-L670

**Comment by nitinvavdiya** [comment]
Hello, @dagnir 
Here is full [gradle tree ](https://drive.google.com/file/d/16VxAh4DPg14Ku4sypx0_--9eBi0cmqhd/view?usp=sharing)

Here,
 `com.amazonaws:aws-java-sdk-core:1.11.301 -> 1.11.83`

Why it changes the version.
Here is my gradle file

```
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'com.jfrog.artifactory'
apply from: rootProject.file('artifactory.gradle')

dependencies {
	compile('com.myProject:notification-core:' + version)
	compile('com.myProject:notification-api:' + version)
    compile('org.springframework.boot:spring-boot-starter-activemq')
    compile('org.springframework.cloud:spring-cloud-starter-eureka')
    compile('org.springframework.boot:spring-boot-starter-websocket')
    compile('org.springframework.boot:spring-boot-starter-tomcat')
    compile group: 'com.amazonaws', name: 'aws-java-sdk-ses', version: '1.11.301'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

```

**Comment by dagnir** [comment]
Thanks for the extra info! According to this https://discuss.gradle.org/t/dependency-report/3647, the reason is that some other dependency you have has a dependency on `1.11.83` and Gradle is trying to resolve the conflict by pulling in what it thinks is the later version,;`1.11.83` in this case, but it should be `1.11.301`. Can you try the suggestion in the link and run `dependencyInsight` task? Hopefully it will tell us which dependency is pulling in `1.11.83`.

**Comment by nitinvavdiya** [comment]
@dagnir 
Here is output

```
nitin@nitin-vostro:~/projects/notification-web$ gradle -q dependencyInsight --configuration compile --dependency aws-java-sdk-ses
com.amazonaws:aws-java-sdk-ses:1.11.301 (selected by rule)
\--- compile


nitin@nitin-vostro:~/projects/notification-web$ gradle -q dependencyInsight --configuration runtime --dependency aws-java-sdk-ses
com.amazonaws:aws-java-sdk-ses:1.11.301 (selected by rule)
\--- runtime
```

Can you please suggest Gradle command for further analysis?
Publishing my project on the GitHub will helpful to you?

**Comment by shorea** [comment]
Can you run the previous insight commands with core instead of ses?

**Comment by nitinvavdiya** [comment]
@shorea 
Here is the tree for core sdk:

```
com.amazonaws:aws-java-sdk-core:1.11.83 (selected by rule)
com.amazonaws:aws-java-sdk-core:1.11.301 -> 1.11.83
\--- com.amazonaws:aws-java-sdk-ses:1.11.301
     \--- compile

```

**Comment by zoewangg** [comment]
Can you run this and provide the output?```System.out.println(HandlerContextKey.class.getProtectionDomain().getCodeSource().getLocation().getPath());```

**Comment by varunnvs92** [comment]
@nitinvavdiya 
Do you still have the issue?

**Comment by varunnvs92** [comment]
Feel free to reopen if you still have the issue.
