### ISSUE TITLE
[SQS] Periodic spikes of errors when reading messages from SQS

### ISSUE THREAD

**Issue by jdsumsion** [aws/aws-sdk-java#1531]
We've already upgraded to the latest `org.apache.httpcomponents` libraries as suggested in #1212 (not the same stack trace, but couldn't hurt)

We've already disabled the forever DNS cache JVM "feature" as suggested in https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-jvm-ttl.html . This is applied in the first class initializer in the class with the `main()` method, so it should be applied before the cache gets set up.

The spikes of errors are not localized to instances in a single AZ.  And the spikes of errors last for longer than one minute in the most extreme examples.  One example was from Fri 30 Mar 2018 15:30-15:31UTC.  These spikes come in clusters, and those clusters occur at a rate of maybe 2 days out of 30.  No request id is logged.

This feels like a bug in the AWS client if a request is attempted on a closed connection results in an exception being thrown.  In this case, I would expect an exception saying: "Cannot connect to SQS" or something after a reasonable timeout, but not short-circuit failing because of a bad pooled connection.

Here is the stack trace:
```
uncaught exception, exception=com.amazonaws.SdkClientException: Unable to execute HTTP request: Request did not complete before the request timeout configuration.
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.createTunnelToTarget(MainClientExec.java:473)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:398)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1236)
	... 113 common frames omitted
Wrapped by: com.amazonaws.http.exception.HttpRequestTimeoutException: Request did not complete before the request timeout configuration.
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1250)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	... 112 common frames omitted
Wrapped by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Request did not complete before the request timeout configuration.
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2033)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2009)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeSendMessage(AmazonSQSClient.java:1610)
	at com.amazonaws.services.sqs.AmazonSQSClient.sendMessage(AmazonSQSClient.java:1586)
```

In our case this morning, a full JVM restart across all the instances cleared up the last of the spikes.  The JVMs had been running since Wed 28 Mar 2018 23:00UTC, but it's not uncommon to have JVMs up for a few days at a time.

**Comment by dagnir** [comment]
Hi @jdsumsion can you provide the following information?

- SDK version you're using
- Client configuration
  - Do you have the Idle Connection Reaper enabled? https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setUseReaper-boolean-
- Wire logs if applicable https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose

**Comment by jdsumsion** [comment]
Thank you for responding!  SDK version is 1.11.297.  I was not aware of idle connection reaper.

I will enable the reaper and see if we have a recurrence.  It will take a few weeks to see if this recurs.

**Comment by shorea** [comment]
@jdsumsion  The socket closed exception may be misleading. This is a product of how we do request timeouts, we basically submit a timer task that wakes up and closes the socket which forces the client to unblock and throw an IOException. So the socket closed is not a bad connection in the pool, just a request that was interrupted by the timeout. Your underlying problem seems to be the request latencies spike and SQS is not responding. Have you reached out to the SQS team about this?

**Comment by shorea** [comment]
Closing issue, feel free to reopen if you need further assistance from the SDK team.

**Comment by jdsumsion** [comment]
Thank you for your analysis.  I will reach out to the SQS team.  Sorry for not following up, I was unexpectedly at the hospital with a family member.

**Comment by shorea** [comment]
@jdsumsion no worries at all. Hope all is well with your family.
