### ISSUE TITLE
Maven shade fails when we use DynamoDBLocal and aws-java-sdk-dynamodb

### ISSUE THREAD

**Issue by mnkg561** [aws/aws-sdk-java#1533]
When I'm trying to create a fat jar file for my lambda function with DynamoDBLocal and was-java-sdk-dynamodb inside my pom it starts failing with couple of errors

java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.dynamodbv2.local.shared.mapper.DynamoDBObjectMapper
at com.amazonaws.services.dynamodbv2.local.server.AbstractLocalDynamoDBServerHandler.(AbstractLocalDynamoDBServerHandler.java:42)

Here is my pom file

```
<properties>
		<maven.surefire.version>2.18.1</maven.surefire.version>
		<aws.dynamodblocal.version>[1.11.86,2.0)</aws.dynamodblocal.version>
		<sqlite4java.version>1.0.392</sqlite4java.version>
		<aws.java.sdk.version>[1.11.89, 2.0.0)</aws.java.sdk.version>
	</properties>
	<repositories>
              <repository>
			<id>dynamodb-local-oregon</id>
			<name>DynamoDB Local Release Repository</name>
			<url>https://s3-us-west-2.amazonaws.com/dynamodb-local/release</url>
		</repository>
	</repositories>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
					<encoding>UTF-8</encoding>
					<forceJavacCompilerUse>true</forceJavacCompilerUse>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.1.0</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
	               <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.0.2</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<includeScope>test</includeScope>
							<includeTypes>so,dll,dylib</includeTypes>
							<outputDirectory>${project.basedir}/native-libs</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<!--Dependency: -->
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>DynamoDBLocal</artifactId>
			<version>${aws.dynamodblocal.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-events</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-dynamodb</artifactId>
			<version>${aws.java.sdk.version}</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-lambda-java-core</artifactId>
			<version>1.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-lambda</artifactId>
			<version>1.11.281</version>
		</dependency>
```

**Comment by mnkg561** [comment]
After trying multiple attempts, here is what I found.. if aws-java-sdk-dynamodb version is from 1.11.86 to 1.11.93 it works fine but starts failing when I change the version of aws-java-sdk-dynamodb to 1.11.94 and later versions. when I used <version>${aws.java.sdk.version}</version> its downloading latest version of sdk hence I'm getting that error.
Hmm.. something changed in 1.11.94 version which is not compatible with DynamoDBLocal (I guess).  Can we fix it?

**Comment by spfink** [comment]
Can you provide the full stack trace?

**Comment by mnkg561** [comment]
@spfink These are part of mvn install ...unit test case execution phase

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.566 sec <<< FAILURE!
com.xxx.xxx.lambda_ssh_keys_handler.core.PublicKeyReaderTest  Time elapsed: 0.565 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/amazonaws/protocol/StructuredPojo
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90)
	at java.lang.Class.getGenericSuperclass(Class.java:777)
	at com.fasterxml.jackson.core.type.TypeReference.<init>(TypeReference.java:33)
	at com.amazonaws.services.dynamodbv2.local.shared.mapper.DynamoDBObjectMapper$1.<init>(DynamoDBObjectMapper.java:232)
	at com.amazonaws.services.dynamodbv2.local.shared.mapper.DynamoDBObjectMapper.<clinit>(DynamoDBObjectMapper.java:232)
	at com.amazonaws.services.dynamodbv2.local.server.AbstractLocalDynamoDBServerHandler.<init>(AbstractLocalDynamoDBServerHandler.java:42)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.<init>(LocalDynamoDBServerHandler.java:147)
	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServer(ServerRunner.java:127)
	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServerFromCommandLineArgs(ServerRunner.java:120)
	at com.xxx.xxx.lambda_ssh_keys_handler.dao.LocalDynamoDBCreationRule.before(LocalDynamoDBCreationRule.java:41)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.protocol.StructuredPojo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more

and one more is..
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.576 sec <<< FAILURE!
com.xxx.xxx.lambda_ssh_keys_handler.core.PublicKeyWriterTest  Time elapsed: 0.576 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.dynamodbv2.local.shared.mapper.DynamoDBObjectMapper
	at com.amazonaws.services.dynamodbv2.local.server.AbstractLocalDynamoDBServerHandler.<init>(AbstractLocalDynamoDBServerHandler.java:42)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.<init>(LocalDynamoDBServerHandler.java:147)
	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServer(ServerRunner.java:127)
	at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServerFromCommandLineArgs(ServerRunner.java:120)
	at com.xxx.xxx.lambda_ssh_keys_handler.dao.LocalDynamoDBCreationRule.before(LocalDynamoDBCreationRule.java:41)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by shorea** [comment]
@mnkg561 your version of aws-java-sdk-core is out of date. It needs to be greater than or equal to the version of your dynamodb module. The generated code in the dynamo module is referencing new classes that your older version of core doesn't have.
