### ISSUE TITLE
Query : not able to initiate Enum member of the class

### ISSUE THREAD

**Issue by santhosh12992** [aws/aws-sdk-java#1538]
I am querying data but it seems java is not able to instantiate enum member of my class (obviously we can't instantiate an enum with constructors) and i am getting below exception.

> Exception in thread "main" com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: Failed to instantiate new instance of class
	at com.amazonaws.services.dynamodbv2.datamodeling.ConversionSchemas$StandardItemConverter.createObject(ConversionSchemas.java:614)
	at com.amazonaws.services.dynamodbv2.datamodeling.ConversionSchemas$StandardItemConverter.unconvert(ConversionSchemas.java:414)
	at com.amazonaws.services.dynamodbv2.datamodeling.unmarshallers.ObjectUnmarshaller.unmarshall(ObjectUnmarshaller.java:54)
	at com.amazonaws.services.dynamodbv2.datamodeling.unmarshallers.NullableUnmarshaller.unmarshall(NullableUnmarshaller.java:46)
	at com.amazonaws.services.dynamodbv2.datamodeling.ConversionSchemas$StandardItemConverter.unmarshall(ConversionSchemas.java:593)
	at com.amazonaws.services.dynamodbv2.datamodeling.ConversionSchemas$StandardItemConverter.unconvert(ConversionSchemas.java:426)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.privateMarshallIntoObject(DynamoDBMapper.java:630)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.marshallIntoObjects(DynamoDBMapper.java:661)
	at com.amazonaws.services.dynamodbv2.datamodeling.PaginatedQueryList.<init>(PaginatedQueryList.java:65)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.query(DynamoDBMapper.java:1856)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.query(DynamoDBMapper.java:1844)
	at com.amazon.optimus.dynamoHelper.DynamoDBUtil.queryRecord(DynamoDBUtil.java:112)
	at com.amazon.optimus.dynamoHelper.DynamoDBUtil.main(DynamoDBUtil.java:164)
Caused by: java.lang.InstantiationException: com.amazon.optimus.enums.RequestStage
	at java.lang.Class.newInstance(Class.java:427)
	at com.amazonaws.services.dynamodbv2.datamodeling.ConversionSchemas$StandardItemConverter.createObject(ConversionSchemas.java:611)
	... 12 more
Caused by: java.lang.NoSuchMethodException: com.amazon.optimus.enums.RequestStage.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 13 more

refer the java.lang.InstantiationException for constructing enum member.

I searched but still not able to find a solution. How i can make this to work. Your help is highly appreciated and thanks.

**Comment by spfink** [comment]
Can you provide a code sample you are using that results in this error?

**Comment by santhosh12992** [comment]
I have resolved this issue using the latest DynamoDB API @DynamoDBTypeConvertedEnum and closing this issue.
