### ISSUE TITLE
Exceptions with Kinesis Stream Reading

### ISSUE THREAD

**Issue by hysmky** [aws/aws-sdk-java#1539]
Hi, 
I do try to make the AmazonKinesis sample delivered with the SDK work. When all configurations are set, it is possible to connet to the service and put data, but it fails when we try tp get data from stream (all the same stream name and configurations). Some people suggested to add the endpoint to the client configuration, but it does not work in my case.
**If I define the endpoint** e.g. using:
kinesisClientLibConfiguration.withKinesisEndpoint("kinesis.eu-central-1.amazonaws.com");
then I get the error:
Caught throwable while processing data.
java.lang.NoClassDefFoundError: com/amazonaws/util/json/JSONObject
at com.amazonaws.services.kinesis.leases.impl.Lease.toString(Lease.java:231)
at java.lang.String.valueOf(String.java:2994)
at java.lang.StringBuilder.append(StringBuilder.java:131)
at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.determineNewLeasesToCreate(ShardSyncer.java:344)
at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.syncShardLeases(ShardSyncer.java:120)
at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.checkAndCreateLeasesForNewShards(ShardSyncer.java:87)
at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncTask.call(ShardSyncTask.java:68)
at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:48)
at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:389)
at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:324)
at AmazonKinesisApplicationSample.main(AmazonKinesisApplicationSample.java:108)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.util.json.JSONObject
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**If I comment out this line then I get resource not found error:**
com.amazonaws.services.kinesis.model.ResourceNotFoundException: Stream <stream_name> under account <account_ID> not found. (Service: AmazonKinesis; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: c4939036-1391-bd6f-97ae-488f599a0fa6)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630) ....

In fact, the stream exists and I can put data, get the numebr of shards, e.g using the following code
   AmazonKinesis kinesis = AmazonKinesisClientBuilder.standard()
                .withCredentials(credentialsProvider)
                .withRegion("eu-central-1")
                .build();
        int numShards = kinesis.describeStream(SAMPLE_APPLICATION_STREAM_NAME).getStreamDescription().getShards().size();
        System.out.println("num shards: " + numShards);

Am I missing some point in the configuration or is it a bug/problem? Shall I pose it to KCL project?

Thanks and the best,
Heysem

**Comment by spfink** [comment]
It looks like you are getting this error specifically when using the KCL and not when using the SDK directly. I would definitely recommend opening an issue with them to start.

**Comment by spfink** [comment]
Closing in favor of:

https://github.com/awslabs/amazon-kinesis-client/issues/323
