### ISSUE TITLE
 SNS sdk throws java.lang.NoSuchFieldError: SIGNING_REGION

### ISSUE THREAD

**Issue by dev-priporov** [aws/aws-sdk-java#1559]
I try to use latest version  _aws-java-sdk-sns_ and get an exception.
The version is:
_compile 'com.amazonaws:aws-java-sdk-sns:1.11.314'_
I don't have others aws dependencies.
The code is:

        AmazonSNSClientBuilder snsClientBuilder = AmazonSNSClientBuilder.standard()
                .withRegion(US_EAST_2)
                .withCredentials(
                        new AWSStaticCredentialsProvider(new BasicAWSCredentials(accessKey, secretKey))
                );

        AmazonSNS client = snsClientBuilder.build();
        System.out.println(client.listSubscriptions()); // to test, here is I got an exception

the exception message:

java.lang.NoSuchFieldError: SIGNING_REGION
	at com.amazonaws.services.sns.AmazonSNSClient.executeListSubscriptions(AmazonSNSClient.java:1429) ~[aws-java-sdk-sns-1.11.314.jar:na]
	at com.amazonaws.services.sns.AmazonSNSClient.listSubscriptions(AmazonSNSClient.java:1411) ~[aws-java-sdk-sns-1.11.314.jar:na]
	at 
java.lang.NoSuchFieldError: SIGNING_REGION
	at com.amazonaws.services.sns.AmazonSNSClient.executeListSubscriptions(AmazonSNSClient.java:1429) ~[aws-java-sdk-sns-1.11.314.jar:na]
	at com.amazonaws.services.sns.AmazonSNSClient.listSubscriptions(AmazonSNSClient.java:1411) ~[aws-java-sdk-sns-1.11.314.jar:na]
	at com.amazonaws.services.sns.AmazonSNSClient.listSubscriptions(AmazonSNSClient.java:1448) ~[aws-java-sdk-sns-1.11.314.jar:na]com.amazonaws.services.sns.AmazonSNSClient.listSubscriptions(AmazonSNSClient.java:1448) ~[aws-java-sdk-sns-1.11.314.jar:na]

**Comment by jrgleason** [comment]
How did you fix this?

**Comment by spfink** [comment]
@jrgleason, make sure that the version of core you are using is greater than or equal to the version of the service package.

**Comment by dev-priporov** [comment]
for some reason gradle doesn't download jdk-core dependency and intellij idea doesn't highlight that... when I checked the aws sources I immideanly got the problem
