### ISSUE TITLE
S3  Cannot provide multiple Tags with the same key

### ISSUE THREAD

**Issue by animaxcg** [aws/aws-sdk-java#1583]
I am trying to update a Tag on an S3 Object. I get the Tags:
GetObjectTaggingRequest getTaggingRequest = new GetObjectTaggingRequest(bucketName, key);
GetObjectTaggingResult getTagsResult = s3Cli.getObjectTagging(getTaggingRequest);

update the getTagsResult:
getTagsResult.setTagSet(tagList);
That doesn't set the tags. So next I try:
s3Cli.setObjectTagging(new SetObjectTaggingRequest(bucketName, key, new ObjectTagging(getTagsResult.getTagSet())));

this stack traces the following error.

 com.amazonaws.services.s3.model.AmazonS3Exception: Cannot provide multiple Tags with the same key (Service: Amazon S3; Status Code: 400; Error Code: InvalidTag; Request ID: XXXXXXXXXXX; S3 Extended Request ID: null), S3 Extended Request ID: null
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4330)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4277)
        at com.amazonaws.services.s3.AmazonS3Client.setObjectTagging(AmazonS3Client.java:1558)

It doesn't look like you can update a Tag however using any other S3 Client I don't seem to have this issue.

**Comment by animaxcg** [comment]
I had 2 of the same item in the list.. Thought it replaced it. Makes sense no issue.
