### ISSUE TITLE
AWS S3 ListBuckets API

### ISSUE THREAD

**Issue by gowthamsankar312** [aws/aws-sdk-java#1588]
We are using AWS java SDK v1.11.171 jar to create a client to fetch data from S3 buckets.

ListBuckets API throws an exception : **AmazonClientException** - com.amazonaws.SdkClientException: Couldn't initialize a SAX driver to create an XMLReader

How to resolve this?

Thanks,
Garry

**Comment by spfink** [comment]
Are you using Maven? Can you provide your pom? Can you provide the complete stacktrace?

**Comment by gowthamsankar312** [comment]
No we are not using Maven. Find the stacktrace below,

com.amazonaws.SdkClientException: Couldn't initialize a SAX driver to create an XMLReader
at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:113)
at com.amazonaws.services.s3.model.transform.Unmarshallers$ListBucketsUnmarshaller.unmarshall(Unmarshallers.java:39)
at com.amazonaws.services.s3.model.transform.Unmarshallers$ListBucketsUnmarshaller.unmarshall(Unmarshallers.java:36)
at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:31)
at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1502)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1225)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4227)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4174)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4168)
at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:918)
at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:924)

**Comment by gowthamsankar312** [comment]
In AWS jar, 
A class 'XmlResponsesSaxParser' is using the import : org.xml.sax.helpers.XMLReaderFactory;  

Java rt.jar which contains the same class name (XMLReaderFactory) in the same path but still we are getting the above exception.

How to resolve this? Please help us to proceed further. @spfink 

Thanks,
Garry.

**Comment by spfink** [comment]
Can you remove the Crimson.jar from your classpath?

**Comment by shorea** [comment]
Closing due to no response. Feel free to reopen if problem persists.

**Comment by gowthamsankar312** [comment]
The issue occurred because in our one of our JAR, we set the JAVA property for XML parser to a class file in crimson.jar. 
Due to that, breakage happened in our AWS S3 code. It was expecting the same XML parser from crimson. 

Thank you @spfink @shorea
