### ISSUE TITLE
Getting SignatureDoesNotMatch while uploading large number of files

### ISSUE THREAD

**Issue by VineetaSangwangommt** [aws/aws-sdk-java#1590]
I am trying to ship my data from Redshift to Redshift spectrum using Spark. I am using spark-redshift to get data in a dataframe, after which I am simply calculating date and hour and putting the data in S3 with the partition on date and hour.  Find below the code:

parsedDocDF
      .withColumn("__date", udfDatePartition(col(dateColumn)))
      .withColumn("__hour", udfHourPartition(col(dateColumn)))
      .write.partitionBy("__date", "__hour")
      .mode(SaveMode.Append)
      .parquet(s3Location)

This code works fine for fewer data i.e. if I fetch only 10-20 rows from Redshift, but if I try to fetch rows in millions and then try to upload the same to S3 it gives me below specified error:

18/05/16 14:51:02 ERROR Utils: Aborting task
com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: 7F18D5379C89BDCA, AWS Error Code: 
SignatureDoesNotMatch, AWS Error Message: The request signature we calculated does not match the signature you provided. Check your key and sig
ning method., S3 Extended Request ID: M6lVD/uAXUcDun2YFZ179t9l8zmAV3F7yTBMeQX7YtPWZR78O+z5I82ipNwzkYm2Z7C5s0WHcvw=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:798)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:421)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:232)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3528)
        at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1507)
        at com.amazonaws.services.s3.transfer.internal.CopyCallable.copyInOneChunk(CopyCallable.java:143)
        at com.amazonaws.services.s3.transfer.internal.CopyCallable.call(CopyCallable.java:131)
        at com.amazonaws.services.s3.transfer.internal.CopyMonitor.copy(CopyMonitor.java:189)
        at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:134)
        at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Could you please help me in resolving this.

**Comment by spfink** [comment]
What's the size of the data in total? Can you show me how you are instantiating the S3 client?

**Comment by VineetaSangwangommt** [comment]
I was trying to read almost 25GB but the code is breaking even for 2GB.

I am using Spark DataFrameWriter to write to s3 with V4 version. Authenticating S3 using Access Key and Secret Key and not Iamrole.

**Comment by spfink** [comment]
Can you provide wire logging with redacted credentials? 

When using Spark DataFrameWriter, do you just give it credentials and it takes care of everything else? Do they have a support forum? Without seeing how the client is configured and used we might not be able to help as well but we can start with wire logs and go from there.

**Comment by zoewangg** [comment]
Closing due to no response. Feel free to reopen if you have any questions.
