### ISSUE TITLE
S3Objects.withPrefix not working in CompletableFuture.runAsync

### ISSUE THREAD

**Issue by playtowork** [aws/aws-sdk-java#1599]
I have the below code, in a Java class for a Play framework application. The `testSync` function runs as expected. Specifically, it takes a decently long time but it does print out the relevant S3 objects. However, the `testAsync` function does not run as expected. It completes in 10 s (as expected), but it never prints out any S3 object.

It seems that, for some reason, `S3Objects.withPrefix()` does not behave correctly when called inside `CompletableFuture.runAsync()`. Why is that? Is there a workaround?

```
public Result testSync() {
  long startMs = System.currentTimeMillis();
  getObjects();
  long endMs = System.currentTimeMillis();
  return ok("Completed in: " + (endMs - startMs) + " ms.");
}

public Result testAsync() throws InterruptedException {
  long startMs = System.currentTimeMillis();
  CompletableFuture.runAsync(() -> getObjects());
  Thread.sleep(10_000L);
  long endMs = System.currentTimeMillis();
  return ok("Completed in: " + (endMs - startMs) + " ms.");
}

private void getObjects() {
  for (S3ObjectSummary s3ObjectSummary : S3Objects.withPrefix(s3Client, bucket, objectPrefix)) {
    println("got key: " + s3ObjectSummary.getKey());
  }
}
```

**Comment by shorea** [comment]
Can you wait on the future returned by runAsync?

```java
CompletableFuture<Void> future = CompletableFuture.runAsync(() -> getObjects());
future.join();
```

**Comment by zoewangg** [comment]
Hi @playtowork, did shorea's suggestion work for you?

**Comment by playtowork** [comment]
I am not sure at all why I was experiencing the issue. I cannot even reproduce my original issue. I tried again the next day and my original code is running as expected. No need to use `future.join()` either.

By the way, upon trying `future.join()`, I saw the below error. But I did not look into it further, as my original code already works as desired.
```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[CompletionException: com.amazonaws.AmazonClientException: Couldn't initialize a SAX driver to create an XMLReader]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:280)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:206)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:98)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.impl.Promise$DefaultPromise.link(Promise.scala:304)
	at scala.concurrent.impl.Promise$DefaultPromise.linkRootOf(Promise.scala:289)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:249)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:409)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.CompletionException: com.amazonaws.AmazonClientException: Couldn't initialize a SAX driver to create an XMLReader
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.amazonaws.AmazonClientException: Couldn't initialize a SAX driver to create an XMLReader
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:85)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$ListObjectsUnmarshaller.unmarshall(Unmarshallers.java:67)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$ListObjectsUnmarshaller.unmarshall(Unmarshallers.java:57)
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:31)
	at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:1179)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:820)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3787)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3729)
	at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:606)
	at com.amazonaws.services.s3.iterable.S3Objects$S3ObjectIterator.prepareCurrentListing(S3Objects.java:141)
	at com.amazonaws.services.s3.iterable.S3Objects$S3ObjectIterator.hasNext(S3Objects.java:118)
	at topl.S3Service.getPathsWithPrefix(S3Service.java:353)
	at controllers.Leases.voidLongComputation(Leases.java:409)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	... 5 common frames omitted
Caused by: org.xml.sax.SAXException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:230)
	at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:191)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:83)
	... 23 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.xml.sax.helpers.NewInstance.newInstance(NewInstance.java:82)
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:228)
	... 25 common frames omitted
```
