### ISSUE TITLE
ClassNotFoundException when using 1.6.10 with SDK metric capture

### ISSUE THREAD

**Issue by brucej72** [aws/aws-sdk-java#161]
Using 1.6.10 with SDK metric capture enabled, I had the following exception:
```
 Unexpected condition; soldier on
java.lang.NoClassDefFoundError: com/amazonaws/metrics/internal/cloudwatch/MachineMetricFactory$MetricValues
	at com.amazonaws.metrics.internal.cloudwatch.MachineMetricFactory.metricValues(MachineMetricFactory.java:136)
	at com.amazonaws.metrics.internal.cloudwatch.MachineMetricFactory.memoryMetricValues(MachineMetricFactory.java:217)
	at com.amazonaws.metrics.internal.cloudwatch.MachineMetricFactory.addMemoryMetrics(MachineMetricFactory.java:170)
	at com.amazonaws.metrics.internal.cloudwatch.MachineMetricFactory.generateMetrics(MachineMetricFactory.java:146)
	at com.amazonaws.metrics.internal.cloudwatch.BlockingRequestBuilder.toPutMetricDataRequests(BlockingRequestBuilder.java:125)
	at com.amazonaws.metrics.internal.cloudwatch.BlockingRequestBuilder.nextUploadUnits(BlockingRequestBuilder.java:74)
	at com.amazonaws.metrics.internal.cloudwatch.MetricUploaderThread.run(MetricUploaderThread.java:66)
Caused by: java.lang.ClassNotFoundException: Unable to load class 'com.amazonaws.metrics.internal.cloudwatch.MachineMetricFactory$MetricValues' because the bundle wiring for com.amazonaws.aws-java-sdk is no longer valid.
```

Initially, I thought this was a problem with the bundle class loader since I'm running under OSGi, but I created a similar test case (a private static inner class being used by the parent only, and the parent exposing only a single package protected method) and it works fine. Looking at the code, I can't see why this would throw, and given this happened in a running system, I can't tell under what circumstances it failed.

**Comment by hanshuo-aws** [comment]
No updates since last October. I will close the issue for now, but please feel free to reopen if you are still affected.

**Comment by srgplv** [comment]
An article on SDK Java 1.x can be helpful
https://medium.com/@srgplv/amazon-web-services-metrics-6c27d9c5f6f2
