### ISSUE TITLE
Dynamo db call exception Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by adityar2** [aws/aws-sdk-java#1615]
I am facing below issues many times during dynamo db query call : -

```
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114) ~[AWSJavaClientRuntime-1.11.x.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064) ~[AWSJavaClientRuntime-1.11.x.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[AWSJavaClientRuntime-1.11.x.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[AWSJavaClientRuntime-1.11.x.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[AWSJavaClientRuntime-1.11.x.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[AWSJavaClientRuntime-1.11.x.jar:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[AWSJavaClientRuntime-1.11.x.jar:?]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[AWSJavaClientRuntime-1.11.x.jar:?]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:3239) ~[AWSDynamoDBJavaModel-1.11.x.jar:?]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:3215) ~[AWSDynamoDBJavaModel-1.11.x.jar:?]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeQuery(AmazonDynamoDBClient.java:2237) ~[AWSDynamoDBJavaModel-1.11.x.jar:?]
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:2212) ~[AWSDynamoDBJavaModel-1.11.x.jar:?]
        at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.query(DynamoDBMapper.java:1505) ~[AWSPersistenceJavaClient-1.11.x.jar:?]

```

**Comment by millems** [comment]
It sounds like you're sending too many requests for the number of connections to handle. Short of reducing your request latency (eg. by keeping them in-region), you can increase your configured number of connections or increase your connect timeout (both settings are available in your client's `ClientConfiguration`).
