### ISSUE TITLE
com.amazonaws.SdkClientException: Couldn't initialize a SAX driver to create an XMLReader

### ISSUE THREAD

**Issue by binshi** [aws/aws-sdk-java#1622]
I am trying to use s3 client for java to delete objects in batch

```
val deleteObjectsRequest = new DeleteObjectsRequest(bucketName)
        .withKeys(keys.map{s => new KeyVersion(s)}.asJava)
      val delObjRes = s3clientWithRcpGcdDestCredentialRegion.deleteObjects(deleteObjectsRequest)
      val successfulDeletes = delObjRes.getDeletedObjects.size
```
```
com.amazonaws.SdkClientException: Couldn't initialize a SAX driver to create an XMLReader
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:118)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$DeleteObjectsResultUnmarshaller.unmarshall(Unmarshallers.java:284)
	at com.amazonaws.services.s3.model.transform.Unmarshallers$DeleteObjectsResultUnmarshaller.unmarshall(Unmarshallers.java:280)
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
	at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:44)
	at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:30)
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1547)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1272)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312)
	at com.amazonaws.services.s3.AmazonS3Client.deleteObjects(AmazonS3Client.java:2133)
Caused by: org.xml.sax.SAXNotSupportedException: http://xml.org/sax/features/external-general-entities
	at org.apache.xerces.framework.XMLParser.setExternalGeneralEntities(XMLParser.java:431)
	at org.apache.xerces.framework.XMLParser.setFeature(XMLParser.java:1141)
	at org.apache.xerces.parsers.SAXParser.setFeature(SAXParser.java:573)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.disableExternalResourceFetching(XmlResponsesSaxParser.java:234)
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:116)
```

**Comment by varunnvs92** [comment]
Please refer to the following old issues and check if there are any responses that might be useful.
https://github.com/aws/aws-sdk-java/issues/1588#issuecomment-396174776
https://github.com/aws/aws-sdk-java/issues/640
https://github.com/aws/aws-sdk-java/issues/1599

**Comment by binshi** [comment]
The solutions provided in the links did not work.

**Comment by varunnvs92** [comment]
What version of the SDK are you using? Did you try the latest version?
Are you using maven or directly using the sdk jar?

**Comment by varunnvs92** [comment]
SDK disables few features on XMLReader for security purposes 
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/transform/XmlResponsesSaxParser.java#L234-L238

If the XMLReader doesn't support the feature, you will get SAXNotSupportedException.
https://docs.oracle.com/javase/8/docs/api/javax/xml/parsers/SAXParserFactory.html#setFeature-java.lang.String-boolean-

The XMLReader on your classpath doesn't have support for disabling the above feature. It may be due to a XMLReader being loaded from another dependency.

**Comment by binshi** [comment]
I am using sdk version: 1.11.337. I added crimson.jar and it again started working. However after a few days I again started getting the above error. Hence it seems the problem is XML reader being loaded from another jar in the dependency list.

**Comment by varunnvs92** [comment]
Yes, thats my guess too. Were you able to fix the issue?

**Comment by varunnvs92** [comment]
Feel free to reopen if you still have the issue.
