### ISSUE TITLE
Connection timed out while connecting to the SQS endpoint

### ISSUE THREAD

**Issue by sumansamantaray** [aws/aws-sdk-java#1624]
I am getting connection timed out error while trying to consume message from SQS. The application is running on local environment on STS as a Spring boot application behind firewall. 
I am using the below bean to connect to STS through proxy configuration.

 @Bean
    public ClientConfiguration clientConfiguration() {
        final ClientConfiguration clientConfiguration = new ClientConfiguration();
 
        clientConfiguration.setProtocol(Protocol.HTTPS);
        clientConfiguration.setProxyHost("hostname");
        clientConfiguration.setProxyPort(port);
        clientConfiguration.setProxyUsername("username");
        clientConfiguration.setProxyPassword("password");
 
        return clientConfiguration;
    }

I am using the below dependency
          <dependency>
	        <groupId>com.amazonaws</groupId>
	        <artifactId>aws-java-sdk</artifactId>
	        <version>1.11.251</version>
	    </dependency>
<dependency>
	      <groupId>com.amazonaws</groupId>
	      <artifactId>amazon-sqs-java-messaging-lib</artifactId>
	      <version>1.0.4</version>
	    </dependency>
Spring boot starter version 2.0.2.RELEASE.

**P.S. - The proxy connection works fine from the STS. I am able to connect to eclipse market place for plugins.**

Here is the exception stack trace 

2018-06-12 16:50:26.059 ERROR 5164 --- [enerContainer-2] c.a.s.j.AmazonSQSMessagingClientWrapper  : AmazonClientException: getQueueUrl.

com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to sqs.us-east-1.amazonaws.com:443 [sqs.us-east-1.amazonaws.com/52.94.237.45] failed: connect timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2013) ~[aws-java-sdk-sqs-1.11.251.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1989) ~[aws-java-sdk-sqs-1.11.251.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueUrl(AmazonSQSClient.java:1075) ~[aws-java-sdk-sqs-1.11.251.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:1052) ~[aws-java-sdk-sqs-1.11.251.jar:na]
	at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.getQueueUrl(AmazonSQSMessagingClientWrapper.java:280) [amazon-sqs-java-messaging-lib-1.0.4.jar:na]
	at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.getQueueUrl(AmazonSQSMessagingClientWrapper.java:251) [amazon-sqs-java-messaging-lib-1.0.4.jar:na]
	at com.amazon.sqs.javamessaging.SQSSession.createQueue(SQSSession.java:622) [amazon-sqs-java-messaging-lib-1.0.4.jar:na]
	at org.springframework.jms.support.destination.DynamicDestinationResolver.resolveQueue(DynamicDestinationResolver.java:85) [spring-jms-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jms.support.destination.DynamicDestinationResolver.resolveDestinationName(DynamicDestinationResolver.java:59) [spring-jms-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jms.support.destination.JmsDestinationAccessor.resolveDestinationName(JmsDestinationAccessor.java:115) [spring-jms-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.createListenerConsumer(AbstractPollingMessageListenerContainer.java:222) [spring-jms-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.initResourcesIfNecessary(DefaultMessageListenerContainer.java:1216) [spring-jms-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1188) [spring-jms-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) [spring-jms-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) [spring-jms-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_162]
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to sqs.us-east-1.amazonaws.com:443 [sqs.us-east-1.amazonaws.com/52.94.237.45] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373) ~[httpclient-4.5.5.jar:4.5.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_162]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.http.conn.$Proxy70.connect(Unknown Source) ~[na:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.5.jar:4.5.5]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.5.jar:4.5.5]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1236) ~[aws-java-sdk-core-1.11.251.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056) ~[aws-java-sdk-core-1.11.251.jar:na]
	... 22 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_162]
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_162]
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_162]
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_162]
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_162]
	at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_162]
	at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_162]
	at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_162]
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339) ~[httpclient-4.5.5.jar:4.5.5]
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:132) ~[aws-java-sdk-core-1.11.251.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.5.jar:4.5.5]
	... 38 common frames omitted

**Comment by varunnvs92** [comment]
SDK uses same core for all services. If the proxy configuration worked for STS but not for SQS, I don't think this is an issue on SDK end. Please do the following for narrowing the issue:

Instead of using the sqs messaging lib, just write a simple test making any api call using low level sqs client and see if it works or not.
* If it works, then the issue is in [amazon-sqs-java-messaging-lib](https://github.com/awslabs/amazon-sqs-java-messaging-lib). Please open a ticket with them.
* If it doesn't work, try similar test with other services like s3, sns and give us the behavior.

**Comment by sumansamantaray** [comment]
Thanks for the suggestion @varunnvs92. I followed your instruction and created a simple app to connect to SQS. Found out that the way I was providing the proxy information to the SQSConnectionFactory was wrong. It worked fine once I corrected the implementation. Please close this issue.
