### ISSUE TITLE
doesObjectExist throws 403 Forbidden, but sometimes not

### ISSUE THREAD

**Issue by betonetotbo** [aws/aws-sdk-java#1651]
AWS SDK: 1.11.313

My application uses S3 to storage specific dependencies of my customers. This dependencies are jar files with customizations (reports, queries, etc).

My implementation just query S3 if an object exists (doesObjectExist) and download it.

This week I got 2 times in 2 different environments this exception:

```
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: 17F2054E5F763F2B; S3 Extended Request ID: A7dbcyxSl+SDVDKH1Ac7NvjaxInO9FSr825YiExgp7Og0eqOVBgLv6E8l2PSLD8DOeMQ5cbBM5E=)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630) ~[aws-java-sdk-core-1.11.313.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302) ~[aws-java-sdk-core-1.11.313.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056) ~[aws-java-sdk-core-1.11.313.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[aws-java-sdk-core-1.11.313.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[aws-java-sdk-core-1.11.313.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[aws-java-sdk-core-1.11.313.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[aws-java-sdk-core-1.11.313.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[aws-java-sdk-core-1.11.313.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[aws-java-sdk-core-1.11.313.jar!/:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365) ~[aws-java-sdk-s3-1.11.313.jar!/:na]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312) ~[aws-java-sdk-s3-1.11.313.jar!/:na]
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1270) ~[aws-java-sdk-s3-1.11.313.jar!/:na]
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1245) ~[aws-java-sdk-s3-1.11.313.jar!/:na]
	at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1321) ~[aws-java-sdk-s3-1.11.313.jar!/:na]
	at br.com.jjw.besser.complements.api.mavens3.MavenS3Repository.exists(MavenS3Repository.java:218) ~[besser-complements-api-1.0.0.5.jar!/:1.0.0.5]
```
In both cases customers hasn't customizations (the object doesn't exists).

I tried, in both cases, to reproduce my customers environments, but in my tests I wasn't able to reproduce it (in my environment it works fine).

Both environments are Windows, and the same code running at my customer fails and on my environment works!

My S3 policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::maven.jjw.com.br",
                "arn:aws:s3:::maven.jjw.com.br/*"
            ]
        }
    ]
}
```

I have no idea what is happening. Can somebody help me?

**Comment by spfink** [comment]
Are you both using the same credentials?

**Comment by betonetotbo** [comment]
Sorry, the clock of the machine was ahead.
