### ISSUE TITLE
java.util.concurrent.CompletionException: com.amazonaws.SdkClientException: Unable to execute HTTP request: Broken pipe (Write failed

### ISSUE THREAD

**Issue by prabhu-nd** [aws/aws-sdk-java#1683]
We are using below version of aws-s3-sdk
	<dependency>
				<groupId>com.amazonaws</groupId>
				<artifactId>aws-java-sdk-s3</artifactId>
				<version>1.11.86</version>
			</dependency>

We got below exception onec in 10 days.
Log:
com.amazonaws.SdkClientException: Unable to execute HTTP request: Broken pipe (Write failed)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:975) ~[?:1.8.0_151]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_151]
	at com.netradyne.task.health.HealthDataProcessor.getHealthDataJson(HealthDataProcessor.java:104) ~[task-processor-executable.jar:?]
	at com.netradyne.task.health.HealthDataProcessor.processHealthDataEvent(HealthDataProcessor.java:75) ~[task-processor-executable.jar:?]
	at com.netradyne.task.health.HealthDataEventProcessor.handleHealthDataMessage(HealthDataEventProcessor.java:70) ~[task-processor-executable.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212) ~[task-processor-executable.jar:?]
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191) ~[task-processor-executable.jar:?]
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:503) ~[task-processor-executable.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316) ~[task-processor-executable.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [task-processor-executable.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) [task-processor-executable.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440) [task-processor-executable.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [task-processor-executable.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Broken pipe (Write failed)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1043) ~[task-processor-executable.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747) ~[task-processor-executable.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721) ~[task-processor-executable.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704) ~[task-processor-executable.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672) ~[task-processor-executable.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654) ~[task-processor-executable.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518) ~[task-processor-executable.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185) ~[task-processor-executable.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132) ~[task-processor-executable.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1245) ~[task-processor-executable.jar:?]
	at com.amazonaws.services.s3.transfer.TransferManager.doDownload(TransferManager.java:1041) ~[task-processor-executable.jar:?]
	at com.amazonaws.services.s3.transfer.TransferManager.doDownload(TransferManager.java:995) ~[task-processor-executable.jar:?]
	at com.amazonaws.services.s3.transfer.TransferManager.download(TransferManager.java:833) ~[task-processor-executable.jar:?]
	at com.amazonaws.services.s3.transfer.TransferManager.download(TransferManager.java:789) ~[task-processor-executable.jar:?]
	at com.netradyne.external.cloud.storage.S3Service.downloadFileFromS3(S3Service.java:190) ~[task-processor-executable.jar:?]

**Comment by shorea** [comment]
This should be a retryable exception. Is that not happening?

**Comment by shorea** [comment]
Closing issue, these types of errors are generally transient network issues that should be retried if you are using the default retry policy. Feel free to reopen if you have further questions/issues.
