### ISSUE TITLE
1 validation error detected: Value null at 'languageCode' failed to satisfy constraint

### ISSUE THREAD

**Issue by devender-yadav** [aws/aws-sdk-java#1684]
I am using comprehend and folllowing [java sample code](https://docs.aws.amazon.com/comprehend/latest/dg/get-started-api-dominant-language.html#get-started-api-dominant-language-java). 

Sample code:

```
public static String getLanguage(String text) {
System.out.println(text);
DetectDominantLanguageRequest detectDominantLanguageRequest = new DetectDominantLanguageRequest()
				.withText(text);
DetectDominantLanguageResult detectDominantLanguageResult = comprehendClient
				.detectDominantLanguage(detectDominantLanguageRequest);
return detectDominantLanguageResult.getLanguages().get(0).toString();
}
```

I got this exception:
```
 1 validation error detected: Value null at 'languageCode' failed to satisfy constraint: Member must not be null (Service: AmazonComprehend; Status Code: 400; Error Code: ValidationException; Request ID: 1140bf70-8b84-11e8-9c69-7db1af1277f0)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1640)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.comprehend.AmazonComprehendClient.doInvoke(AmazonComprehendClient.java:1847)
	at com.amazonaws.services.comprehend.AmazonComprehendClient.invoke(AmazonComprehendClient.java:1823)
	at com.amazonaws.services.comprehend.AmazonComprehendClient.executeDetectSentiment(AmazonComprehendClient.java:918)
	at com.amazonaws.services.comprehend.AmazonComprehendClient.detectSentiment(AmazonComprehendClient.java:893)
```

**Comment by devender-yadav** [comment]
my bad. mixing dominant language detection and sentiment detection :(
