### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.AmazonS3Client

### ISSUE THREAD

**Issue by ranjankumar03** [aws/aws-sdk-java#1688]
I am facing mentioned issue recently during the deployment. Have not made any changes to java version.

java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.AmazonS3Client
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at aws157.apppusher.AppPusherScheduler.runAppPusherSchedulerWithDelay(AppPusherScheduler.java:193)
        at aws157.apppusher.AppPusherScheduler.runAsDaemon(AppPusherScheduler.java:180)
        at aws157.apppusher.Main.main(Main.java:39)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.AmazonS3Client
        at aws157.apppusher.utils.AppPusherS3Client.getS3TransferManager(AppPusherS3Client.java:59)
        at aws157.apppusher.utils.AppPusherS3Client.<init>(AppPusherS3Client.java:37)
        at aws157.apppusher.AppSystemS3Uploader.uploadAppToS3(AppSystemS3Uploader.java:32)
        at aws157.apppusher.yarn.YarnAppDataCollector.writeApplicationResult(YarnAppDataCollector.java:260)
        at aws157.apppusher.yarn.YarnAppDataCollector.processAppToBeUploaded(YarnAppDataCollector.java:294)
        at aws157.apppusher.AppPusher.run(AppPusher.java:76)
        at aws157.apppusher.AppPusherSchedulerThread.call(AppPusherSchedulerThread.java:17)
        at aws157.apppusher.AppPusherSchedulerThread.call(AppPusherSchedulerThread.java:6)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by shorea** [comment]
Seems like a classpath issue. Can you ensure the proper version of the SDK is on the classpath for your application?

**Comment by dagnir** [comment]
Going to close this due to no response. Per @shorea's guidance, this issue should be fixed by ensuring that the S3 SDK is on the classpath. Please feel free to reopen if you continue to experience this issue.
