### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.util.StringUtils.lowerCase(Ljava/lang/String;)Ljava/lang/String;

### ISSUE THREAD

**Issue by PulkitAppz** [aws/aws-sdk-java#1690]
```
Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.util.StringUtils.lowerCase(Ljava/lang/String;)Ljava/lang/String;
	at com.amazonaws.services.cloudfront.util.SignerUtils.loadPrivateKey(SignerUtils.java:160)
	at com.amazonaws.services.cloudfront.CloudFrontUrlSigner.getSignedURLWithCannedPolicy(CloudFrontUrlSigner.java:101)
	at test.SignedURL.main(SignedURL.java:68)
```

**Comment by zoewangg** [comment]
Which Java sdk version are you using? Can you make sure you have the same versions for aws-sdk-core and cloudfront client?

**Comment by dagnir** [comment]
@PulkitAppz It appears there's a version mismatch between your `aws-java-sdk-cloudfront` dependency and your `aws-java-sdk-core` dependency. Ensuring that both versions are the same should fix this.

**Comment by dagnir** [comment]
Going to go ahead and close this due to no response. Please feel free to reopen if the above suggested solutions don't work for you.
