### ISSUE TITLE
"hostname cannot be null" thrown intermittently by AwsHostNameUtils

### ISSUE THREAD

**Issue by amilbourne** [aws/aws-sdk-java#1691]
This problem only happens intermittently and often goes away after a few seconds or minutes without intervention (although it triggers our fault alerting).  It did persist for several hours on one occasion and required that our containers (running in ECS) be cycled.

The problem seems to happen when we try to send messages to SNS.  We get "hostname cannot be null", which appears to be generated by "AwsHostNameUtils".  The stacktrace looks something like this (full logs attached): 

```
Caused by: java.lang.IllegalArgumentException: hostname cannot be null
 at com.amazonaws.util.AwsHostNameUtils.parseRegion(AwsHostNameUtils.java:79) ~[stormjar.jar:?]
 at com.amazonaws.util.AwsHostNameUtils.parseRegionName(AwsHostNameUtils.java:59) ~[stormjar.jar:?]
 at com.amazonaws.auth.internal.AWS4SignerRequestParams.resolveRegion(AWS4SignerRequestParams.java:121) ~[stormjar.jar:?]
 at com.amazonaws.auth.internal.AWS4SignerRequestParams.<init>(AWS4SignerRequestParams.java:103) ~[stormjar.jar:?]
 at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:225) ~[stormjar.jar:?]
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1212) ~[stormjar.jar:?]
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058) ~[stormjar.jar:?]
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[stormjar.jar:?]
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[stormjar.jar:?]
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[stormjar.jar:?]
 at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[stormjar.jar:?]
 at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[stormjar.jar:?]
 at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[stormjar.jar:?]
 at com.amazonaws.services.sns.AmazonSNSClient.doInvoke(AmazonSNSClient.java:2334) ~[stormjar.jar:?]
 at com.amazonaws.services.sns.AmazonSNSClient.invoke(AmazonSNSClient.java:2310) ~[stormjar.jar:?]
 at com.amazonaws.services.sns.AmazonSNSClient.executePublish(AmazonSNSClient.java:1742) ~[stormjar.jar:?]
```

This was generated by something like the following code (simplified here):
``` java
public class Sender {
    public static final String TOPIC_ARN = "topic.arn";
    public static final String TOPIC_REGION = "topic.region";

    private AmazonSNS snsClient;
    private String topicArn;

    public Sender(Map conf) {
        topicArn = getSnsTopicArn(conf);
        snsClient = getSnsClient(conf);
    }

    protected String getSnsTopicArn(Map conf) {
        return (String) conf.get(TOPIC_ARN);
    }

    protected AmazonSNS getSnsClient(Map conf) {
        return AmazonSNSClientBuilder.standard()
                .withRegion((String) conf.get(TOPIC_REGION))
                .build();
    }

    private void sendMentionToAwsTopic(String json) {
        PublishResult publishResult = snsClient.publish(topicArn, json);
    }
}
```

The stack-trace above was generated using SDK version 1.11.353, which I realise is a couple of weeks out of date, but because it takes a week or so to replicate the error it is hard to report against the latest SDK.

This seems like an issue with the SDK (or underlying infrastructure?).

Thanks,

    Anthony.

**Comment by amilbourne** [comment]
I can't see how to attach a file so I'm adding the full stack-trace below:
```
45:01.000 STDERR Thread-2 [INFO] java.lang.RuntimeException: java.lang.IllegalArgumentException: hostname cannot be null
45:01.000 STDERR Thread-2 [INFO] 2018-07-19 00:45:00.990 o.a.s.util Thread-35-sender-executor[49 49] [ERROR] Async loop died!
45:01.001 STDERR Thread-2 [INFO] at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:522) ~[storm-core-1.2.1.jar:1.2.1]
45:01.001 STDERR Thread-2 [INFO] at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:487) ~[storm-core-1.2.1.jar:1.2.1]
45:01.001 STDERR Thread-2 [INFO] at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:74) ~[storm-core-1.2.1.jar:1.2.1]
45:01.001 STDERR Thread-2 [INFO] at org.apache.storm.daemon.executor$fn__5043$fn__5056$fn__5109.invoke(executor.clj:861) ~[storm-core-1.2.1.jar:1.2.1]
45:01.002 STDERR Thread-2 [INFO] at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:484) [storm-core-1.2.1.jar:1.2.1]
45:01.002 STDERR Thread-2 [INFO] at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
45:01.002 STDERR Thread-2 [INFO] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
45:01.002 STDERR Thread-2 [INFO] 2018-07-19 00:45:01.002 c.m.i.s.RssFeedEventSpout Thread-25-rssFeedSpout-executor[44 44] [INFO] Task 44 emitting item '[Redacted]' for [Redacted] with publication date [Redacted]
45:01.002 STDERR Thread-2 [INFO] Caused by: java.lang.IllegalArgumentException: hostname cannot be null
45:01.002 STDERR Thread-2 [INFO] at com.amazonaws.util.AwsHostNameUtils.parseRegion(AwsHostNameUtils.java:79) ~[stormjar.jar:?]
45:01.002 STDERR Thread-2 [INFO] at com.amazonaws.util.AwsHostNameUtils.parseRegionName(AwsHostNameUtils.java:59) ~[stormjar.jar:?]
45:01.003 STDERR Thread-2 [INFO] at com.amazonaws.auth.internal.AWS4SignerRequestParams.resolveRegion(AWS4SignerRequestParams.java:121) ~[stormjar.jar:?]
45:01.003 STDERR Thread-2 [INFO] at com.amazonaws.auth.internal.AWS4SignerRequestParams.<init>(AWS4SignerRequestParams.java:103) ~[stormjar.jar:?]
45:01.003 STDERR Thread-2 [INFO] at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:225) ~[stormjar.jar:?]
45:01.003 STDERR Thread-2 [INFO] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1212) ~[stormjar.jar:?]
45:01.003 STDERR Thread-2 [INFO] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058) ~[stormjar.jar:?]
45:01.004 STDERR Thread-2 [INFO] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[stormjar.jar:?]
45:01.004 STDERR Thread-2 [INFO] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[stormjar.jar:?]
45:01.004 STDERR Thread-2 [INFO] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[stormjar.jar:?]
45:01.004 STDERR Thread-2 [INFO] at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[stormjar.jar:?]
45:01.004 STDERR Thread-2 [INFO] at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[stormjar.jar:?]
45:01.005 STDERR Thread-2 [INFO] at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[stormjar.jar:?]
45:01.005 STDERR Thread-2 [INFO] at com.amazonaws.services.sns.AmazonSNSClient.doInvoke(AmazonSNSClient.java:2334) ~[stormjar.jar:?]
45:01.005 STDERR Thread-2 [INFO] at com.amazonaws.services.sns.AmazonSNSClient.invoke(AmazonSNSClient.java:2310) ~[stormjar.jar:?]
45:01.005 STDERR Thread-2 [INFO] at com.amazonaws.services.sns.AmazonSNSClient.executePublish(AmazonSNSClient.java:1742) ~[stormjar.jar:?]
45:01.016 STDERR Thread-2 [INFO] 2018-07-19 00:45:01.016 c.m.i.s.EpgSpout Thread-23-epgSpout-executor[21 21] [INFO] Task 21 emitting EPG update Paranormal Survivor on truTV at 2018-07-19T00:00Z (time offset 0, EPG duration 60)
45:01.005 STDERR Thread-2 [INFO] at com.amazonaws.services.sns.AmazonSNSClient.publish(AmazonSNSClient.java:1754) ~[stormjar.jar:?]
45:01.005 STDERR Thread-2 [INFO] at com.mporium.impact.storm.MentionSenderBolt.sendMentionToAwsTopic(MentionSenderBolt.java:210) ~[stormjar.jar:?]
45:01.006 STDERR Thread-2 [INFO] at com.mporium.impact.storm.MentionSenderBolt.execute(MentionSenderBolt.java:75) ~[stormjar.jar:?]
45:01.006 STDERR Thread-2 [INFO] at org.apache.storm.daemon.executor$fn__5043$tuple_action_fn__5045.invoke(executor.clj:739) ~[storm-core-1.2.1.jar:1.2.1]
45:01.006 STDERR Thread-2 [INFO] at org.apache.storm.daemon.executor$mk_task_receiver$fn__4964.invoke(executor.clj:468) ~[storm-core-1.2.1.jar:1.2.1]
45:01.006 STDERR Thread-2 [INFO] at org.apache.storm.disruptor$clojure_handler$reify__4475.onEvent(disruptor.clj:41) ~[storm-core-1.2.1.jar:1.2.1]
45:01.006 STDERR Thread-2 [INFO] at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:509) ~[storm-core-1.2.1.jar:1.2.1]
45:01.006 STDERR Thread-2 [INFO] ... 6 more
```

**Comment by amilbourne** [comment]
We raised this with AWS support who said:

> Hello, 
>
>Thanks for contacting AWS Support.
> 
> I understand you get an intermittent issue with your application making use of the Java SDK to contact the SNS API, with the error  "hostname cannot be null".
> 
> We can see the specific code throwing this error: 
>   if (host == null) {
>             throw new IllegalArgumentException("hostname cannot be null");
> }
> https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/AwsHostNameUtils.java
> 
> It looks like this code path is called when creating a signing request:
> 
> https://github.com/aws/aws-sdk-java/blob/4734de6fb0f80fe5768a6587aad3b9d0eaec388f/aws-java-sdk-core/src/main/java/com/amazonaws/internal/auth/DefaultSignerProvider.java
> 
>  private String getSigningRegionForRequestURI(URI uri) {
>         String regionName = awsClient.getSignerRegionOverride();
>         if (regionName == null) {
>             regionName = AwsHostNameUtils.parseRegion(uri.getHost(), awsClient.getEndpointPrefix());
>         }
>         return regionName;
> }
> 
> Could you try this request using the latest version of the Java SDK? At present, the latest release is 1.11.370:
> https://github.com/aws/aws-sdk-java/releases
> 
> If you continue to have this issue with the latest release, I would advise opening up this issue on the aws-sdk-java issue tracker, at https://github.com/aws/aws-sdk-java/issues, to allow the SDK development team to investigate. If you do open an issue, feel free to respond with the the issue number in this case, and we can ensure that the SDK development team has visibility on the issue. 
> 
> 
> Best regards,
> 
> Nick M.
> Amazon Web Services

**Comment by zoewangg** [comment]
Trying to narrow down the root cause, could you provide information of the following question:

1. What has been changed right before you started to see the error? Did you make code changes around sqs client, or upgrade SDK version?

2. If the error goes away after a few seconds or minutes without intervention and sometimes need to recycle the container, it seems some sort of cache issue. Do you create a new SNS client for every request or use it through the whole application?

3. Are you sending requests to multiple regions or just one region?

**Comment by amilbourne** [comment]
Thanks for your response

1. Because this takes a long time to manifest it is hard to say exactly what changes were made as it is hard to say exactly when the problem started.  However, the software in question has been in maintenance mode (rather than active development) for some time, so no major changes have been made.  There have been some minor changes but upgrades to libraries account for most of the changes.

2. This SNS client object is created at startup and kept for the duration of the program execution - it is never recreated.  There may be other SNS clients created in the same JVM but they are not visible to this code.

3. This SNS client is only sending messages to a single topic in a single region.

**Comment by dagnir** [comment]
Hi @amilbourne sorry for the delayed response. What SDK version are you using? How often does this happen?

Unless the endpoint on the client is changing throughout while the application is running, I'm not sure why this is only happening intermittently. Do you have a sample snippet to repro this?

**Comment by debora-ito** [comment]
@amilbourne Any updates?

**Comment by amilbourne** [comment]
The stack-trace above was generated using SDK version 1.11.353,  We saw this problem 5 or 6 times over a couple of months (and a few SDK versions).  However, ee haven't seen the issue for a while so it is possible that something has changed on your side that has fixed it.  On the other hand it was always intermittent so it may come back.  It is hard to tell.

**Comment by ton3r** [comment]
Hi, I'm running in it to.
We use the latest AWS SDK

```
                <dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-core</artifactId>
			<version>1.11.519</version>
		</dependency>

		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-sqs</artifactId>
			<version>1.11.519</version>
		</dependency>

		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-sns</artifactId>
			<version>1.11.519</version>
		</dependency>
```

Stacktrace looks like the same.

```
Caused by: java.lang.IllegalArgumentException: hostname cannot be null
	at com.amazonaws.util.AwsHostNameUtils.parseRegion(AwsHostNameUtils.java:79) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.util.AwsHostNameUtils.parseRegionName(AwsHostNameUtils.java:59) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.AmazonWebServiceClient.computeSignerByURI(AmazonWebServiceClient.java:370) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.AmazonWebServiceClient.getSignerByURI(AmazonWebServiceClient.java:344) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.services.sqs.internal.auth.SQSSignerProvider.getSigner(SQSSignerProvider.java:40) ~[aws-java-sdk-sqs-1.11.519.jar:na]
	at com.amazonaws.http.ExecutionContext.getSigner(ExecutionContext.java:135) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor$ExecOneRequestParams.newSigner(AmazonHttpClient.java:1846) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1255) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512) ~[aws-java-sdk-core-1.11.519.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2215) ~[aws-java-sdk-sqs-1.11.519.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2182) ~[aws-java-sdk-sqs-1.11.519.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2171) ~[aws-java-sdk-sqs-1.11.519.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueUrl(AmazonSQSClient.java:1163) ~[aws-java-sdk-sqs-1.11.519.jar:na]
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:1136) ~[aws-java-sdk-sqs-1.11.519.jar:na]
	at org.springframework.cloud.aws.messaging.support.destination.DynamicQueueUrlDestinationResolver.resolveDestination(DynamicQueueUrlDestinationResolver.java:94) ~[spring-cloud-aws-messaging-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.aws.messaging.support.destination.DynamicQueueUrlDestinationResolver.resolveDestination(DynamicQueueUrlDestinationResolver.java:38) ~[spring-cloud-aws-messaging-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.messaging.core.CachingDestinationResolverProxy.resolveDestination(CachingDestinationResolverProxy.java:92) ~[spring-messaging-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.queueAttributes(AbstractMessageListenerContainer.java:320) ~[spring-cloud-aws-messaging-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.initialize(AbstractMessageListenerContainer.java:292) ~[spring-cloud-aws-messaging-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer.initialize(SimpleMessageListenerContainer.java:111) ~[spring-cloud-aws-messaging-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.afterPropertiesSet(AbstractMessageListenerContainer.java:267) ~[spring-cloud-aws-messaging-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer.afterPropertiesSet(SimpleMessageListenerContainer.java:45) ~[spring-cloud-aws-messaging-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741) ~[spring-beans-5.1.2.RELEASE.jar:5.1.2.RELEASE]
```

Regarding that the `host` var is null in the `URI` Object

![URIObject](https://user-images.githubusercontent.com/10545359/54520720-9a433400-4969-11e9-86ac-22bc99ff67be.png)
![latestStep](https://user-images.githubusercontent.com/10545359/54520721-9a433400-4969-11e9-8466-d6146da04e71.png)

**Comment by erdeszt** [comment]
I'm still seeing this issue on `1.11.681`

```scala
val clientBuilder = AmazonSNSClientBuilder.standard()
clientBuilder.setRegion(Regions.EU_CENTRAL_1.name())
val client = clientBuilder.build()
client.publish(...) // IllegalArgumentException("hostname cannot be null")
```

It used to work with this code:
```scala
val snsClient = new AmazonSNSClient()
snsClient.setRegion(Region.getRegion(Regions.EU_CENTRAL_1))
```

But both the `AmazonSNSClient` constructor and the `setRegion` methods are deprecated.
