### ISSUE TITLE
com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by dulimitta** [aws/aws-sdk-java#1738]
We are using aws-java-sdk-s3 version 1.11.333
And here is the client configuration we are using.

```
	public AmazonS3 s3client() {
		return AmazonS3ClientBuilder
				.standard()
				.withRegion("us-east-1")
				.withClientConfiguration(new ClientConfiguration().withMaxConnections(100)
                .withConnectionTimeout(120 * 1000)
                .withMaxErrorRetry(15))
				.build();
	}

```

The same code worked for so many days. All of a sudden we could not get even a single S3 connection. 
We used to see the error once in a while but it used to go by itself. I saw many posts suggesting to close the s3object effectively. But if that is the issue, we should get some connection initially then we should get the error. But in our case, we could not get even a single connection now.

**Comment by zoewangg** [comment]
It is recommended to close the s3object as soon as possible so that the connection can be reused by other request. 

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#getObject-com.amazonaws.services.s3.model.GetObjectRequest- 

Also, has there been an increase in your service load? If you started to see spikes of this error recently, it is possible that the number of incoming requests exceeded the number of requests that could be handled therefore leading to the connection pool exhaustion.

**Comment by dulimitta** [comment]
Thank you @zoewangg . But when we restart the server, all the opened connections should be closed and it should work at least for some time, which is not happening in our scenario.

**Comment by millems** [comment]
Ping. Any update?

**Comment by dulimitta** [comment]
Sorry @millems Couldn't reply back. After enabling the debug logs, we realized that the errors are not immediate after restart. We could find where we need to close the s3objects and then it is working. Thank you so much for keeping us in right direction.

**Comment by c4urself** [comment]
@dulimitta -- running into a similar problem, can you shed some light on how to close the stream properly?

**Comment by jakirpatel** [comment]
I am facing similar issues with custom S3 implementation over NetApp.

**Comment by akavijay** [comment]
I am having the same issue but we are using the same s3client object for delete and in TransferManager also, I am not closing either of them.  Is it good a practice to reuse the same s3client object, or need to create for each request and close when done?



Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1163) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1109) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520) [aws-java-sdk-core-1.11.475.jar:]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1807) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:131) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143) [aws-java-sdk-s3-1.11.475.jar:]
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48) [aws-java-sdk-s3-1.11.475.jar:]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [rt.jar:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [rt.jar:1.8.0_181]

**Comment by avisecag** [comment]
I was seeing this error for the first time last night... *in an AWS lambda*!
There is only one access of the file per lambda, and concurrently executing lambdas are never accessing the same file, though there may be dozens to hundreds that access the same bucket concurrently.
Does this pose an issue, and if yes, how would I need to resolve that?

**Comment by chongchaoyu** [comment]
> It is recommended to close the s3object as soon as possible so that the connection can be reused by other request.
> 
> https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#getObject-com.amazonaws.services.s3.model.GetObjectRequest-
> 
> Also, has there been an increase in your service load? If you started to see spikes of this error recently, it is possible that the number of incoming requests exceeded the number of requests that could be handled therefore leading to the connection pool exhaustion.

This is the right solution, because apache http client only releases a connection when the connection reaches its EOF,  S3Object holds InputStream, so the connection's EOF is "read all the data, close or abort.."
