### ISSUE TITLE
S3 Latency issue

### ISSUE THREAD

**Issue by s6usgc** [aws/aws-sdk-java#1740]
Reference to AWS Case - 5236176741 for S3 latency issue.

We are getting errors for S3 operations

com.amazonaws.http.timers.client.ClientExecutionTimeoutException: Client execution did not complete before the specified timeout configuration.
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleAbortedException(AmazonHttpClient.java:811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:703)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
Bucket(s): fnma-audocs-prod-us-east-1-data2
Request ID(s):

**Comment by s6usgc** [comment]
JDK Version used - 1.11.256 - aws-java-sdk-s3

**Comment by zoewangg** [comment]
Closing the issue, feel free to reopen if you have further questions/issues.
