### ISSUE TITLE
amazon-dax-client duplicates part of aws-java-sdk-dynamodb

### ISSUE THREAD

**Issue by dsilvasc** [aws/aws-sdk-java#1747]
The jar for the maven artifact `com.amazonaws:amazon-dax-client:1.0.200704.0` includes some classes that are part of `com.amazonaws:aws-java-sdk-dynamodb`.

Can that be modeled as a dependency instead?

**Comment by millems** [comment]
Thanks for your report. I have forwarded that that feedback to the DAX team (the AWS SDK team doesn't own com.amazonaws:amazon-dax-client).

**Comment by jdhardy** [comment]
Hi, @dsilvasc I work on the DAX team. Can you list which classes are in both the DAX client and the SDK? The DAX client should be using SDK classes as a dependency, not bundling them, and I can't see any overlap.

FYI, there is overlap between the DAX client and DynamoDBLocal, but that'll be fixed in the next release.

**Comment by dsilvasc** [comment]
Hi @jdhardy 

Sorry, you're right -- the overlap seems to be between amazon-dax-client-1.0.200704.0 and DynamoDBLocal-1.11.86 instead of aws-java-sdk-dynamodb.

Here's a stack trace of a failing test:

```
    java.lang.NoSuchMethodError: com.amazon.dynamodb.grammar.DynamoDbExpressionParser.parseCondition(Ljava/lang/String;Lorg/antlr/v4/runtime/ANTLRErrorListener;)Lorg/antlr/v4/runtime/tree/ParseTree;
        at com.amazonaws.services.dynamodbv2.parser.DynamoDbParser.parseExpression(DynamoDbParser.java:134)
        at com.amazonaws.services.dynamodbv2.local.shared.validate.InputConverter.parseConditionExpression(InputConverter.java:842)
        at com.amazonaws.services.dynamodbv2.local.shared.validate.InputConverter.externalToInternalConditionExpression(InputConverter.java:619)
        at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBClient.putItem(LocalDynamoDBClient.java:788)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.amazonaws.services.dynamodbv2.local.embedded.DDBExceptionMappingInvocationHandler.invoke(DDBExceptionMappingInvocationHandler.java:56)
        at com.sun.proxy.$Proxy28.putItem(Unknown Source)
        at com.amazonaws.services.dynamodbv2.document.internal.PutItemImpl.doPutItem(PutItemImpl.java:85)
        at com.amazonaws.services.dynamodbv2.document.internal.PutItemImpl.putItem(PutItemImpl.java:54)
        at com.amazonaws.services.dynamodbv2.document.Table.putItem(Table.java:162)
        at snapchat.dynamo.AsyncTable.$anonfun$putItem$4(AsyncTable.scala:76)
```

Looking forward to the next release.  Hopefully the DynamoDBLocal team can update to the latest sdk versions (1.11.300+) as well.

**Comment by dsilvasc** [comment]
By the way, what are the appropriate github repos and issue trackers for the DAX client and for DynamoDBLocal?
