### ISSUE TITLE
Problem with SES

### ISSUE THREAD

**Issue by allanchua101** [aws/aws-sdk-java#1750]
I am getting the following exception when sending email through SES:

ception in thread "main" java.lang.NoSuchFieldError: SERVICE_ID
	at com.amazonaws.services.simpleemail.AmazonSimpleEmailServiceClient.executeSendRawEmail(AmazonSimpleEmailServiceClient.java:3897)
	at com.amazonaws.services.simpleemail.AmazonSimpleEmailServiceClient.sendRawEmail(AmazonSimpleEmailServiceClient.java:3878)
	at com.amazonaws.services.simpleemail.AWSJavaMailTransport.sendEmail(AWSJavaMailTransport.java:269)
	at com.amazonaws.services.simpleemail.AWSJavaMailTransport.sendMessage(AWSJavaMailTransport.java:100)

**Comment by varunnvs92** [comment]
Please provide the following details:
1) version of the SDK
2) Test code to reproduce the issue
3) Did you start seeing the issue after version upgrade?
4) If possible, enable wire logging and provide the logs. **Make sure there is no sensitive data.**

**Comment by allanchua101** [comment]
Hi,

I fixed the issue by tweaking SQS, SES and S3 versions to the following:

Hope it helps people out there!

```xml
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>amazon-sqs-java-messaging-lib</artifactId>
      <version>1.0.4</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
      <version>1.11.340</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-ses</artifactId>
      <version>1.11.340</version>
    </dependency>
```
