### ISSUE TITLE
I have a dynamodb thread stuck scene, unable to read data normally.

### ISSUE THREAD

**Issue by collbing** [aws/aws-sdk-java#1756]
Environmental Science
The 40 Java reads the dynamodb process.

`"consumer-2-thread-7" #40 prio=5 os_prio=0 tid=0x00007fd7c4518800 nid=0xefc8 in Object.wait() 
[0x00007fd77a58c000]
   java.lang.Thread.State: RUNNABLE
  at com.amazonaws.auth.internal.AWS4SignerRequestParams.<init>(AWS4SignerRequestParams.java:85)
  at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:169)
  at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:814)
  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
  at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
  at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
  at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2000)
  at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1970)
  at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.getItem(AmazonDynamoDBClient.java:1329)
  at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:433)
  at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:496)
  at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:400)
  at com.patsnap.index.common.IndexAwsClient.load(IndexAwsClient.java:75)
  at com.patsnap.index.patent.convert.DynamodbSolrConvertor.convert(DynamodbSolrConvertor.java:40)
  at com.patsnap.index.patent.convert.PatentConvertWorkHandler.onEvent(PatentConvertWorkHandler.java:34)
  at com.patsnap.index.patent.convert.PatentConvertWorkHandler.onEvent(PatentConvertWorkHandler.java:16)
  at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143)
  at java.lang.Thread.run(Thread.java:748)`

![picture](https://user-images.githubusercontent.com/7081953/45262687-3e45a300-b44e-11e8-95b7-75b291ae5759.png)

**Comment by debora-ito** [comment]
Which version of SDK are you using?
And can you provide snippet of you code? Please make sure there's no sensitive data.

**Comment by debora-ito** [comment]
Closing due to inactivity. Feel free to reopen if you're still experiencing this issue.
