### ISSUE TITLE
Getting the "Cost and Usage Reports" Definition Sudden Problem

### ISSUE THREAD

**Issue by bmagic39** [aws/aws-sdk-java#1762]
Hi
I'm using AWS SDK to get the defined CostAndUsageReports by calling "describeReportDefinitions"
it was working fine till today where it suddenly randomly failing with unclear null error

"com.amazonaws.services.costandusagereport.model.AWSCostAndUsageReportException: null (Service: AWSCostAndUsageReport; Status Code: 500; Error Code: null; Request ID: null)"

this is not consistent, it succeed and failed with no reason...
Any help will be appreciated

Majed

**Comment by spfink** [comment]
What version of the SDK are you using?

Is it possible to provide a wire log?

**Comment by bmagic39** [comment]
I tried with both 1.11.405 & 1.11.411 (latest)

I hope error stack will help

Caused by: com.amazonaws.services.costandusagereport.model.AWSCostAndUsageReportException: null (Service: AWSCostAndUsageReport; Status Code: 500; Error Code: null; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1660)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1324)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1074)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.doInvoke(AWSCostAndUsageReportClient.java:530)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.invoke(AWSCostAndUsageReportClient.java:499)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.invoke(AWSCostAndUsageReportClient.java:488)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.executeDescribeReportDefinitions(AWSCostAndUsageReportClient.java:393)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.describeReportDefinitions(AWSCostAndUsageReportClient.java:362)
	....

**Comment by debora-ito** [comment]
Can you provide us the wire logs and/or Request IDs? Please make sure there is no sensitive data.

You can enable wire logging by following these instructions: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html

And also, what has been changed before you started to see the error? Any significant changes in code or configuration?

**Comment by bmagic39** [comment]
It turned to be an issue at the Service
at last 24 hour it is working fine
