### ISSUE TITLE
S3 client throwing SdkClientException: Unable to execute HTTP request: The target server failed to respond

### ISSUE THREAD

**Issue by jksingh** [aws/aws-sdk-java#1790]
Earlier we used to get this error around 100 times per day. But from the last couple of days, we have started getting this error around 80,000 times per day (with spikes up to 13,000). That is around 0.2% of the requests made to S3 per day. 
There no change in SDK, Java or http client version.

SDK version: 1.11.393
Java Version: openjdk version "1.8.0_171"
Apache http client version: 4.5.3

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1134)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1080)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4443)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4390)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1427)
Caused by: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doReceiveResponse(SdkHttpRequestExecutor.java:82)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1256)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1072)
	... 41 more
```

**Comment by zoewangg** [comment]
Looks like the internal AWS case was closed for this issue. Going to go ahead and close this issue. Feel free to re-open if you continue seeing the errors or have further questions.

**Comment by drobert** [comment]
Fwiw, looks related to https://github.com/aws/aws-sdk-java/issues/1212

**Comment by SrishtiSingh-eu** [comment]
I still have the same issue. When the load is higher. I am using 1.11.705 version of aws 
The target server failed to respond
DefaultHttpResponseParser.java in parseHead at line 141
DefaultHttpResponseParser.java in parseHead at line 56
AbstractMessageParser.java in parse at line 259
DefaultBHttpClientConnection.java in receiveResponseHeader at line 163
CPoolProxy.java in receiveResponseHeader at line 157
HttpRequestExecutor.java in doReceiveResponse at line 273
SdkHttpRequestExecutor.java in doReceiveResponse at line 82
HttpRequestExecutor.java in execute at line 125
MainClientExec.java in execute at line 272
ProtocolExec.java in execute at line 186
InternalHttpClient.java in doExecute at line 185
CloseableHttpClient.java in execute at line 83
CloseableHttpClient.java in execute at line 56
SdkHttpClient.java in execute at line 72
AmazonHttpClient.java in executeOneRequest at line 1311
AmazonHttpClient.java in executeHelper at line 1127
AmazonHttpClient.java in doExecute at line 784
AmazonHttpClient.java in executeWithTimer at line 752
AmazonHttpClient.java in execute at line 726
AmazonHttpClient.java in access$500 at line 686
AmazonHttpClient.java in execute at line 668
AmazonHttpClient.java in execute at line 532
AmazonHttpClient.java in execute at line 512
AmazonS3Client.java in invoke at line 5052
AmazonS3Client.java in invoke at line 4998
AmazonS3Client.java in getObject at line 1486
AmazonS3Client.java in getObject at line 1341
S3ObjectStorageClient.java in retrieveAsStorageObject at line 331
S3ObjectStorageClient.java in get at line 247
MediaStorageServiceImpl.java in retrieveAsStorageObject at line 66
MediaStorageServiceImpl.java in retrieveAsMediaFile at line 44
ThumbnailController.java in retrieveThumbnail at line 151
ThumbnailController.java in thumbnailByUrl at line 96
<generated> in invoke
MethodProxy.java in invoke at line 218
CglibAopProxy.java in invokeJoinpoint at line 749
ReflectiveMethodInvocation.java in proceed at line 163
MethodValidationInterceptor.java in invoke at line 119
ReflectiveMethodInvocation.java in proceed at line 186
CglibAopProxy.java in intercept at line 688
<generated> in thumbnailByUrl
InvocableHandlerMethod.java in doInvoke at line 189
InvocableHandlerMethod.java in invokeForRequest at line 138
ServletInvocableHandlerMethod.java in invokeAndHandle at line 102
RequestMappingHandlerAdapter.java in invokeHandlerMethod at line 892
RequestMappingHandlerAdapter.java in handleInternal at line 797
AbstractHandlerMethodAdapter.java in handle at line 87
DispatcherServlet.java in doDispatch at line 1038
DispatcherServlet.java in doService at line 942
FrameworkServlet.java in processRequest at line 1005


Could someone help ?

**Comment by yasarutkuu** [comment]
we are having same issue, any update?
