### ISSUE TITLE
Crash on com.amazonaws.AmazonWebServiceClient.isRequestMetricsEnabled

### ISSUE THREAD

**Issue by snasrudeen** [aws/aws-sdk-java#1791]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
       at com.amazonaws.AmazonWebServiceClient.isRequestMetricsEnabled(AmazonWebServiceClient.java:125)
       at com.amazonaws.AmazonWebServiceClient.createExecutionContext(AmazonWebServiceClient.java:86)
       at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:1571)
       at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:9)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

More Details:

Device
Brand: VMware, Inc.
Model: VMware Virtual Platform
Orientation: Portrait
RAM free: 454.18 MB
Disk free: 7.4 GB

Operating System
Version: 4.2.1
Orientation: Portrait
Rooted: Yes

**Comment by debora-ito** [comment]
It looks like you are using the Mobile SDK for Android, which is maintained in a different repository. Please open an issue over at https://github.com/aws/aws-sdk-android/issues and the Android SDK team should be able to help you out.
