### ISSUE TITLE
Cannot update security group rule descriptions ingress

### ISSUE THREAD

**Issue by cezarykluczynski** [aws/aws-sdk-java#1810]
Hello,

When using latest SDK (1.11.451) the following code fails:

```java
DescribeSecurityGroupsResult describeSecurityGroupsResult = amazonEC2.describeSecurityGroups();
SecurityGroup securityGroup = describeSecurityGroupsResult.getSecurityGroups().get(0);
List<IpPermission> ipPermissions = securityGroup.getIpPermissions();
IpPermission ipPermission = ipPermissions.get(0);
IpRange ipRange = ipPermission.getIpv4Ranges().get(0);
ipRange.setCidrIp("1.2.3.4/32"); // Basically overwrite previous value with anything else
UpdateSecurityGroupRuleDescriptionsIngressRequest updateSecurityGroupRuleDescriptionsIngressRequest
				= new UpdateSecurityGroupRuleDescriptionsIngressRequest();
updateSecurityGroupRuleDescriptionsIngressRequest.setGroupId(securityGroup.getGroupId());
updateSecurityGroupRuleDescriptionsIngressRequest.setIpPermissions(ipPermissions);
amazonEC2.updateSecurityGroupRuleDescriptionsIngress(updateSecurityGroupRuleDescriptionsIngressRequest);
```

Exception is:

```java
Caused by: com.amazonaws.services.ec2.model.AmazonEC2Exception: The specified rule does not exist in this security group. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidPermission.NotFound; Request ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1695) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:18499) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:18468) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:18457) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.services.ec2.AmazonEC2Client.executeUpdateSecurityGroupRuleDescriptionsIngress(AmazonEC2Client.java:18326) ~[aws-java-sdk-bundle-1.11.451.jar:na]
	at com.amazonaws.services.ec2.AmazonEC2Client.updateSecurityGroupRuleDescriptionsIngress(AmazonEC2Client.java:18294) ~[aws-java-sdk-bundle-1.11.451.jar:na]
```

Request works fine when nothing is changed and the originally retrieved ipPermissions are set.

It doesn't matter if the IpRange have description or not.

**Comment by debora-ito** [comment]
Hi @cezarykluczynski, 

that's expected because the `amazonEC2.updateSecurityGroupRuleDescriptionsIngress()` method only updates the description of existing security group rules. The error shows that the API tried to find the security group rule with the set ip permissions but couldn't find it, and that's due to the ip that was changed.

Could you clarify what you are trying to achieve?

**Comment by cezarykluczynski** [comment]
Hello, thanks for answering.

I was trying to update CidrIp in a IpRange. Is there a way to achieve that via API?

**Comment by cezarykluczynski** [comment]
OK, that makes sense. Thanks you.

**Comment by vkkpnm** [comment]
Then what is the point of providing 

> Yes, you'd have to call `amazonEC2.revokeSecurityGroupIngress()` to remove the rule from the security group, and then call `amazonEC2.authorizeSecurityGroupIngress()` with the new values.
> 
> Please check the [revokeSecurityGroupIngress](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/AmazonEC2.html#revokeSecurityGroupIngress-com.amazonaws.services.ec2.model.RevokeSecurityGroupIngressRequest-) and [authorizeSecurityGroupIngress](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/AmazonEC2.html#authorizeSecurityGroupIngress-com.amazonaws.services.ec2.model.AuthorizeSecurityGroupIngressRequest-) documentation for more info.

Then what is the point of providing UpdateSecurityGroupRuleDescriptionsIngressRequest API?
