### ISSUE TITLE
com.amazonaws.SdkClientException: Couldn't initialize a SAX driver to create an XMLReader

### ISSUE THREAD

**Issue by marwb** [aws/aws-sdk-java#1815]
Hi All

com.amazonaws.SdkClientException: Couldn't initialize a SAX driver to create an XMLReader
                at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:124)
                at com.amazonaws.services.s3.model.transform.Unmarshallers$AccessControlListUnmarshaller.unmarshall(Unmarshallers.java:116)
                at com.amazonaws.services.s3.model.transform.Unmarshallers$AccessControlListUnmarshaller.unmarshall(Unmarshallers.java:113)
                at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
                at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:44)
                at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:30)
                at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1610)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1319)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
                at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)
                at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)
                at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4443)
                at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4390)
                at com.amazonaws.services.s3.AmazonS3Client.getAcl(AmazonS3Client.java:3573)
                at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1186)
                at com.amazonaws.services.s3.AmazonS3Client.getBucketAcl(AmazonS3Client.java:1176)
                at com.amazonaws.services.s3.AmazonS3Client.doesBucketExistV2(AmazonS3Client.java:1312)
                at com.here.umob.realtime.sync.impl.AWSCloudSyncImpl.syncToFileStorage(AWSCloudSyncImpl.java:141)
                at com.here.umob.realtime.sync.impl.QueueItemProcessorImpl.processQueue(QueueItemProcessorImpl.java:114)
                at com.here.umob.realtime.sync.RealTimeDeltaSyncApplicationStart.main(RealTimeDeltaSyncApplicationStart.java:33)
Caused by: org.xml.sax.SAXNotSupportedException: http://xml.org/sax/features/external-general-entities
                at org.apache.xerces.framework.XMLParser.setExternalGeneralEntities(XMLParser.java:431)
                at org.apache.xerces.framework.XMLParser.setFeature(XMLParser.java:1141)
                at org.apache.xerces.parsers.SAXParser.setFeature(SAXParser.java:573)
                at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.disableExternalResourceFetching(XmlResponsesSaxParser.java:240)
                at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:122)
                ... 24 more

I am getting above exception while attempting to upload the FILE to S3.Strange thing is this is working fine from my local dev enviornment.

When I deploy dockerized version of this app to our cluster enviornment,it failed by writing above error message in logs.

Upon reading on this issue on internet and github I did not found if any one was able to solve this or got the right answer for this.

on other place someone commented that multiple class path entires in class path for same class.might cause this issue

**Comment by varunnvs92** [comment]
Can you check if the cause in this [comment](https://github.com/aws/aws-sdk-java/issues/1622#issuecomment-397752130) is the issue?

Is this consistently happening in the cluster env? I am thinking it might be a classpath issue. Can you make sure you are only getting `XMLReader` class from only one jar in your hosts

**Comment by debora-ito** [comment]
Closing this due to inactivity. Feel free to reopen if you're still experiencing this issue.
