### ISSUE TITLE
java.lang.NoSuchFieldError: SIGNING_REGION exception from AWSLambda

### ISSUE THREAD

**Issue by brownkw** [aws/aws-sdk-java#1837]
I'm attempting to invoke a Java lambda function from another Java lambda function. Both lambdas are in the same region. However, when I go to invoke I am getting the following error: 

```
java.lang.NoSuchFieldError: SIGNING_REGION
at com.amazonaws.services.lambda.AWSLambdaClient.executeInvoke(AWSLambdaClient.java:1409)
at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1391)
at com.amazonaws.lambda.demo.vrscenes.LambdaFunctionHandler.handleRequest(LambdaFunctionHandler.java:104)
at com.amazonaws.lambda.demo.vrscenes.LambdaFunctionHandler.handleRequest(LambdaFunctionHandler.java:1)
at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:178)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)\n\tat lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:104)
```

Here is my current Maven dependency tree. I do not see any obvious version incompatibilities. In addition to the Lambda java core file, the only other AWS library I'm using is the Lambda Java SDK.
```
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.amazonaws.lambda.demo:vrscenes >-----------------
[INFO] Building vrscenes 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ vrscenes ---
[INFO] com.amazonaws.lambda.demo:vrscenes:jar:1.0.0
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- com.amazonaws:aws-lambda-java-core:jar:1.2.0:compile
[INFO] +- com.google.guava:guava:jar:18.0:compile
[INFO] +- com.google.code.gson:gson:jar:2.8.0:compile
[INFO] +- com.amazonaws:aws-java-sdk-lambda:jar:1.11.307:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.307:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.7.1:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.6.7:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.307:compile
[INFO] \- org.apache.commons:commons-lang3:jar:3.8.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.798 s
[INFO] Finished at: 2018-12-12T13:13:11-06:00
[INFO] ------------------------------------------------------------------------
```
Below is the dependency management and dependencies section of my pom file:

```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-bom</artifactId>
        <version>1.11.328</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-lambda-java-core</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>18.0</version>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.8.0</version>
    </dependency>    
    <dependency>
	    <groupId>com.amazonaws</groupId>
	    <artifactId>aws-java-sdk-lambda</artifactId>		    
	</dependency>
	<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
	<dependency>
	    <groupId>org.apache.commons</groupId>
	    <artifactId>commons-lang3</artifactId>
	    <version>3.8.1</version>
	</dependency>
  </dependencies>
```

**Comment by debora-ito** [comment]
Hi @brownkw, the maven dependency tree shows version `1.11.307` for both core and lambda client, but it is not the version defined in the BOM (`1.11.328`). 

Can you try clearing your dependency cache? This error usually indicates version mismatch between client and core.

**Comment by brownkw** [comment]
I've cleared my dependency cache and updated the project. I've confirmed that the dependency tree is showing version 1.11.328 as specified by the BOM. I'm still getting the same issue though. Here is the latest dependency tree:

```
WAYNBROW-M-T1XQ:VRSceneService wayne.brown$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.amazonaws.lambda.demo:vrscenes >-----------------
[INFO] Building vrscenes 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ vrscenes ---
[INFO] com.amazonaws.lambda.demo:vrscenes:jar:1.0.0
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- com.amazonaws:aws-lambda-java-core:jar:1.2.0:compile
[INFO] +- com.google.guava:guava:jar:18.0:compile
[INFO] +- com.google.code.gson:gson:jar:2.8.0:compile
[INFO] +- com.amazonaws:aws-java-sdk-lambda:jar:1.11.328:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.11.328:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.6.7.1:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.6.0:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.6.7:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.6.7:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.328:compile
[INFO] \- org.apache.commons:commons-lang3:jar:3.8.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.872 s
[INFO] Finished at: 2018-12-12T18:45:44-06:00
[INFO] ------------------------------------------------------------------------
```
I tried moving to version 1.11.467 (the latest showing in the maven repository). But I got a completely different error than the one specified. Is there a version of the AWS Java SDK that I should be using here?

**Comment by debora-ito** [comment]
Closing due to inactivity. Feel free to reopen if you're still experiencing this issue.
