### ISSUE TITLE
S3 TransferManager - no support for SSE-C uploadFileList | JAVA SDK

### ISSUE THREAD

**Issue by bharatnanda** [aws/aws-sdk-java#1840]
I'm trying to upload multiple files using multi-part upload (using SSE-C encryption) and TransferManager API. To upload multiple files asynchronously,  I'm calling uploadFileList, which does not seems to support SSE-C out of the box. There is no clear documentation on this matter. While exploring I encountered a GitHub bug wherein developer suggests to use ObjectMetadataProvider to set Encryption related metadata. Following is URL for the bug.
https://github.com/aws/aws-sdk-java/issues/568

I modified my code to include the headers and it seems to be working for smaller files less than 5 MB. But as soon as I try to upload a bigger file, it complains and throws following Exception:

Exception in thread "main" com.amazonaws.SdkClientException: Unable to complete multi-part upload. Individual part upload failed : The multipart upload initiate requested encryption. Subsequent part requests must include the appropriate encryption parameters. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 72DF5F22D1419C30; S3 Extended Request ID: EVvT39DAnMSwLk0IG0419ON60P9gV/ZZFBheTThMPWTveq/EiPXfnHjQ1zwp4So+jTyjLrg08/4=)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartUpload.collectPartETags(CompleteMultipartUpload.java:127)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartUpload.call(CompleteMultipartUpload.java:89)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartUpload.call(CompleteMultipartUpload.java:40)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The multipart upload initiate requested encryption. Subsequent part requests must include the appropriate encryption parameters. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 72DF5F22D1419C30; S3 Extended Request ID: EVvT39DAnMSwLk0IG0419ON60P9gV/ZZFBheTThMPWTveq/EiPXfnHjQ1zwp4So+jTyjLrg08/4=), S3 Extended Request ID: EVvT39DAnMSwLk0IG0419ON60P9gV/ZZFBheTThMPWTveq/EiPXfnHjQ1zwp4So+jTyjLrg08/4=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4330)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4277)
	at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:3307)
	at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3292)
	at com.amazonaws.services.s3.transfer.internal.UploadPartCallable.call(UploadPartCallable.java:33)
	at com.amazonaws.services.s3.transfer.internal.UploadPartCallable.call(UploadPartCallable.java:23)
	... 4 more

Following is code snippet:

TransferManager xferMgr = TransferManagerBuilder.standard().build();
		MultipleFileUpload xfer = null;
		if (StringUtil.isNullOrEmpty(encryptionKey)) {
			xfer = xferMgr.uploadFileList(tenantBucketId, outputFolder, localDirectory, Arrays.asList(files));
		} else {
			ObjectMetadataProvider objectMetadataProvider = ((File file, ObjectMetadata metadata) -> {
				metadata.setHeader(Headers.SERVER_SIDE_ENCRYPTION_CUSTOMER_ALGORITHM, "AES256");
				metadata.setHeader(Headers.SERVER_SIDE_ENCRYPTION_CUSTOMER_KEY, encryptionKey);
				metadata.setHeader(Headers.SERVER_SIDE_ENCRYPTION_CUSTOMER_KEY_MD5, Md5Utils.md5AsBase64(Base64.getDecoder().decode(encryptionKey)));
			});
			xfer = xferMgr.uploadFileList(tenantBucketId, outputFolder, localDirectory, Arrays.asList(files),
					objectMetadataProvider);
		}
		xfer.waitForCompletion();
		xferMgr.shutdownNow();

Please suggest.

**Comment by debora-ito** [comment]
Hi @bharatnanda I was able to reproduce the issue, investigating the cause.

**Comment by bharatnanda** [comment]
Hi @debora-ito 

Thanks for replicating the issue. Please keep me posted on updates.

Regards,
Bharat Nanda

**Comment by zoewangg** [comment]
For the temporary workaround, you can increase the multipart upload threshold via `setMultipartUploadThreshold` to a larger value so that each file will be uploaded as a single object.

https://github.com/aws/aws-sdk-java/blob/743d7150f721a7f1c94afa09afc801ad053f4eb7/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/TransferManagerConfiguration.java#L167

**Comment by bharatnanda** [comment]
Thanks @zoewangg  I'll try the same, but I guess, it may reduce the performance of uploads.

**Comment by zoewangg** [comment]
A fix has been merged and will be included in the next release

**Comment by bharatnanda** [comment]
@zoewangg 

Thanks for the update, looking forward to the next release, can you please point me to the merge if I can check it out and path the same thing in my code base for now.
