### ISSUE TITLE
DAX Timeout waiting for an available tube

### ISSUE THREAD

**Issue by Yoouuu** [aws/aws-sdk-java#1841]
Hi,
I'm building DAX client and trying to run it from my IntelliJ, but got exception:
```
Dec 13, 2018 9:57:02 PM com.amazon.dax.client.dynamodbv2.ClusterDaxClient <init>
WARNING: exception starting up cluster client: java.io.IOException: failed to configure cluster endpoints from hosts: [<mydaxhost>:8111]
java.io.IOException: failed to configure cluster endpoints from hosts: [r4-large-performance.x630ob.clustercfg.dax.use2.cache.amazonaws.com:8111]
	at com.amazon.dax.client.cluster.Source$AutoconfSource.pull(Source.java:127)
	at com.amazon.dax.client.cluster.Source$AutoconfSource.update(Source.java:59)
	at com.amazon.dax.client.cluster.Source$AutoconfSource.refresh(Source.java:50)
	at com.amazon.dax.client.cluster.Cluster.refresh(Cluster.java:417)
	at com.amazon.dax.client.cluster.Cluster.refresh(Cluster.java:400)
	at com.amazon.dax.client.cluster.Cluster.startup(Cluster.java:323)
	at com.amazon.dax.client.cluster.Cluster.startup(Cluster.java:256)
	at com.amazon.dax.client.dynamodbv2.ClusterDaxClient.<init>(ClusterDaxClient.java:145)
	at com.amazon.dax.client.dynamodbv2.ClusterDaxClient.<init>(ClusterDaxClient.java:116)
	at com.amazon.dax.client.dynamodbv2.AmazonDaxClientBuilder.build(AmazonDaxClientBuilder.java:34)
	at performance.engineering.project.cache.ddb.DDBClientGetter.getDaxClient(DDBClientGetter.java:32)
	at performance.engineering.project.cache.ddb.repositories.DAXRepository.<init>(DAXRepository.java:10)
	at performance.engineering.project.cache.ddb.BenchmarkRunner.main(BenchmarkRunner.java:32)
Caused by: java.net.ConnectException: Timeout waiting for an available tube. Endpoint : /172.31.15.203:8111
	at com.amazon.dax.client.SocketTubePool.alloc(SocketTubePool.java:138)
	at com.amazon.dax.client.generated.DaxClientStubs.endpoints_455855874_1(DaxClientStubs.java:449)
	at com.amazon.dax.client.dynamodbv2.DaxClient.endpoints(DaxClient.java:1943)
	at com.amazon.dax.client.cluster.Source$AutoconfSource.pullFrom(Source.java:137)
	at com.amazon.dax.client.cluster.Source$AutoconfSource.pull(Source.java:105)
	... 12 more
	Suppressed: java.net.ConnectException: Timeout waiting for an available tube. Endpoint : /<myEndpoint>:8111
		... 17 more
	Suppressed: java.net.ConnectException: Timeout waiting for an available tube. Endpoint : /<myEndpoint>:8111
		... 17 more
```

The DAX client builder seems to be changing recently, and I'm using following code to build my DAX client:
```
public static DynamoDB getDaxClient(String daxEndpoint) {
        AmazonDaxClientBuilder daxClientBuilder = AmazonDaxClientBuilder.standard();
        daxClientBuilder.withRegion(region)
                .withCredentials(new EnvironmentVariableCredentialsProvider())
                .withEndpointConfiguration(daxEndpoint);
        AmazonDynamoDB client = daxClientBuilder.build();
        return new DynamoDB(client);
    }
```
I've already set the inbound and outbound for TCP/8111 in security group to be everywhere, but the error still persists.

Please help! Thank you!

**Comment by debora-ito** [comment]
Hi @Yoouuu,  I'll forward your issue to the DAX team, the SDK doesn't own the DAX Client. 
I'm going to close this for now but will post any updates we get from the DAX team.

**Comment by Yoouuu** [comment]
nvm, I think I'm doing something wrong by no running on the EC2 instance.

**Comment by debora-ito** [comment]
So you are not experiencing the problem anymore?
