### ISSUE TITLE
AWS S3 Client throws ReadTimeOut while we expect to throw early

### ISSUE THREAD

**Issue by blacelle** [aws/aws-sdk-java#1842]
Related to https://github.com/aws/aws-sdk-java/issues/1212

aws-java-sdk-core-1.11.381.jar
httpclient-4.5.6.jar
httpcore-4.4.10.jar

On a given quite intensive workload, we succeed reproducing systematically following behavior 👍 

- we do GET on a quite large number of S3 files. 
- At some point, the reading freezes
- After the timeout configured in HttpClient, the connection is resetted

We initially thought our Read timeout was too low, so we increased quite a lot. However, the other issue seems to systematically wait for the Read timeout before failing (and then leading us to retry).

Here are the logs including wire logs:

```

2018-12-14 10:48:16,784 DEBUG org.apache.http.wire -  http-outgoing-9 << "[0xa0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0xb][0x10][0x0][0x1]~[0xbd][0x0][0x0][0x0][0x0][0x0][0x0][0x0]#@A[0x80][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x3][0x0][0x10][0x0][0x0][0x0][0x0][0x0]$[0x1][0x87][0x1][0xae][0x1]@[0x83][0xb0][0x0][0x0][0x0][0x0][0x0]@B[0x80][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0xf][0x3][0x0][0x1]p[0x10][0x0][0x0][0x0][0x0][0x0][0x0][0x1]7@sp[0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x8][0x0][0x10][0x0][0x0][0x0][0x0][0x0]][0x0]r[0x0][0xc9][0x0][0xd3][0x0];[0x1]l[0x1][0xbe][0x1]M[0xe]@[0xb7][0x15][0x0][0x0][0x0][0x0][0x0]@v[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0x10][0x15][0x0][0x1][0x88][0xba][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x2]@[0x0][0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0x0][0x0][0x0][0x0]@,[0x0][0x0][0x0][0x0][0x0][0x0]@[0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0x12]1[0x0][0x1][0x80][0xff][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x9]@"[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0x0][0x0][0xfb][0xf]@k[0x0][0x0][0x0][0x0][0x0][0x0]@"[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0x16][0x1f][0x0][0x1][0x88][0xdf][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x2]@[0x0][0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0x0][0x0][0x0][0x0]@$[0x0][0x0][0x0][0x0][0x0][0x0]@[0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0x17][0x6][0x0][0x1]|[0x9e][0x0][0x0][0x0][0x0][0x0][0x0][0x0]g@Y[0xc0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x10][0x0][0x0][0x0][0x0][0x0][0xa4][0x0][0xd8][0x0]U[0x1]w[0x1]@[0x90][0x18][0x0][0x0][0x0][0x0][0x0]@d [0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0x1c][0x17][0x0][0x1]~[0xc0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][\r]@*[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x1][0x0][0x10][0x0][0x0][0x0][0x0][0x0][0xc9][0x2]@]@[0x0][0x0][0x0][0x0][0x0]@*[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x5][0x8][0x1c][0x0][0x1]s[0xee][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x1b]@;[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x2][0x0][0x10][0x0][0x0][0x0][0xfc][0x0]q[0x1]-[0xe]@[0x86][0xc8][0x0][0x0][0x0][0x0][0x0]@;[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x5][\r][0xf][0x0][0x1]w[0xa7][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x1d]@=[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x2][0x0][0x10][0x0][0x0][0x0][0x0][0x0][0xff][0x0][0xaf][0x1]@[0x89]`[0x0][0x0][0x0][0x0][0x0]@=[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x5][0x15][0x18][0x0][0x1]y[0xa6][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x9]@"[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0x0][0x0][0xff][0x1]@2[0x0][0x0][0x0][0x0][0x0][0x0]"
2018-12-14 10:48:16,784 DEBUG org.apache.http.wire -  http-outgoing-9 << "[0xa0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0xb][0x10][0x0][0x1]~[0xbd][0x0][0x0][0x0][0x0][0x0][0x0][0x0]#@A[0x80][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x3][0x0][0x10][0x0][0x0][0x0][0x0][0x0]$[0x1][0x87][0x1][0xae][0x1]@[0x83][0xb0][0x0][0x0][0x0][0x0][0x0]@B[0x80][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0xf][0x3][0x0][0x1]p[0x10][0x0][0x0][0x0][0x0][0x0][0x0][0x1]7@sp[0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x8][0x0][0x10][0x0][0x0][0x0][0x0][0x0]][0x0]r[0x0][0xc9][0x0][0xd3][0x0];[0x1]l[0x1][0xbe][0x1]M[0xe]@[0xb7][0x15][0x0][0x0][0x0][0x0][0x0]@v[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0x10][0x15][0x0][0x1][0x88][0xba][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x2]@[0x0][0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0x0][0x0][0x0][0x0]@,[0x0][0x0][0x0][0x0][0x0][0x0]@[0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0x12]1[0x0][0x1][0x80][0xff][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x9]@"[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0x0][0x0][0xfb][0xf]@k[0x0][0x0][0x0][0x0][0x0][0x0]@"[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0x16][0x1f][0x0][0x1][0x88][0xdf][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x2]@[0x0][0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0x0][0x0][0x0][0x0]@$[0x0][0x0][0x0][0x0][0x0][0x0]@[0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0x17][0x6][0x0][0x1]|[0x9e][0x0][0x0][0x0][0x0][0x0][0x0][0x0]g@Y[0xc0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x10][0x0][0x0][0x0][0x0][0x0][0xa4][0x0][0xd8][0x0]U[0x1]w[0x1]@[0x90][0x18][0x0][0x0][0x0][0x0][0x0]@d [0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x4][0x1c][0x17][0x0][0x1]~[0xc0][0x0][0x0][0x0][0x0][0x0][0x0][0x0][\r]@*[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x1][0x0][0x10][0x0][0x0][0x0][0x0][0x0][0xc9][0x2]@]@[0x0][0x0][0x0][0x0][0x0]@*[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x5][0x8][0x1c][0x0][0x1]s[0xee][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x1b]@;[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x2][0x0][0x10][0x0][0x0][0x0][0xfc][0x0]q[0x1]-[0xe]@[0x86][0xc8][0x0][0x0][0x0][0x0][0x0]@;[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x5][\r][0xf][0x0][0x1]w[0xa7][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x1d]@=[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x2][0x0][0x10][0x0][0x0][0x0][0x0][0x0][0xff][0x0][0xaf][0x1]@[0x89]`[0x0][0x0][0x0][0x0][0x0]@=[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x5][0x15][0x18][0x0][0x1]y[0xa6][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x9]@"[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0x0][0x0][0xff][0x1]@2[0x0][0x0][0x0][0x0][0x0][0x0]"
2018-12-14 10:48:20,339 DEBUG org.apache.http.wire -  http-outgoing-9 << "@"[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x5][0x19] [0x0][0x1][0x8a][0xb1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x6]@[0x18][0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x1][0x0][0x10][0x0][0x0][0x0].[0x4]F[0x6]@P[0x80][0x0][0x0][0x0][0x0][0x0]@[0x18][0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x5][0x1d][0x4][0x0][0x1]u[0x14][0x0][0x0][0x0][0x0][0x0][0x0]8[0x14]@[0xcc][\n]"
2018-12-14 10:48:20,339 DEBUG org.apache.http.wire -  http-outgoing-9 << "@"[0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x5][0x19] [0x0][0x1][0x8a][0xb1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x6]@[0x18][0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x1][0x0][0x10][0x0][0x0][0x0].[0x4]F[0x6]@P[0x80][0x0][0x0][0x0][0x0][0x0]@[0x18][0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x5][0x1d][0x4][0x0][0x1]u[0x14][0x0][0x0][0x0][0x0][0x0][0x0]8[0x14]@[0xcc][\n]"
2018-12-14 10:48:20,339 DEBUG org.apache.http.wire -  http-outgoing-9 << "[0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0]9[0x0][0x10][0x0][0x0][0x0][0x0][0x0][0x5][0x0][0xe][0x0][0xf][0x0][0x10][0x0][0x11][0x0][0x13][0x0][0x14][0x0][0x17][0x0][0x1c][0x0][0x1d][0x0][0x1e][0x0]![0x0]#[0x0]%[0x0]([0x0])[0x0]*[0x0]E[0x0]J[0x0]N[0x0]P[0x0]X[0x0]\[0x0]f[0x0]p[0x0]u[0x0]z[0x0][0x90][0x0][0x91][0x0][0x92][0x0][0x93][0x0][0x95][0x0][0x9c][0x0][0x9f][0x0][0xae][0x0][0xaf][0x0][0xc0][0x0][0xc8][0x0][0xd0][0x0][0xdb][0x0][0xe0][0x0][0xe9][0x0][0xf7][0x0][0x13][0x1][0x1c][0x1]<[0x1]_[0x1]c[0x1][0xb2][0x1][0xd7][0x1][0xf4][0x1]v[0x2]4[0x5][0xf9][0x5][0xfa][0x5][\n]"
2018-12-14 10:48:20,339 DEBUG org.apache.http.wire -  http-outgoing-9 << "[0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0]9[0x0][0x10][0x0][0x0][0x0][0x0][0x0][0x5][0x0][0xe][0x0][0xf][0x0][0x10][0x0][0x11][0x0][0x13][0x0][0x14][0x0][0x17][0x0][0x1c][0x0][0x1d][0x0][0x1e][0x0]![0x0]#[0x0]%[0x0]([0x0])[0x0]*[0x0]E[0x0]J[0x0]N[0x0]P[0x0]X[0x0]\[0x0]f[0x0]p[0x0]u[0x0]z[0x0][0x90][0x0][0x91][0x0][0x92][0x0][0x93][0x0][0x95][0x0][0x9c][0x0][0x9f][0x0][0xae][0x0][0xaf]
[0x0][0xc0][0x0][0xc8][0x0][0xd0][0x0][0xdb][0x0][0xe0][0x0][0xe9][0x0][0xf7][0x0][0x13][0x1][0x1c][0x1]<[0x1]_[0x1]c[0x1][0xb2][0x1][0xd7][0x1][0xf4][0x1]v[0x2]4[0x5][0xf9][0x5][0xfa][0x5][\n]"
2018-12-14 10:48:20,339 DEBUG org.apache.http.wire -  http-outgoing-9 << "[0xe][0x1f][0xe]A[0x5][0x7][0x80][0x0][0x0][0x0][0x0]@[0xce][0x87][0x80][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x6][0x4][0x6][0x0][0x1]{[0xa1][0x0][0x0][0x0][0x0][0x0][0x0][0x0]C@P[0xc0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x3][0x0][0x10][0x0][0x0][0x0][0x0][0x0][0xd8][0x0]w[0x1][0xad][0x3]@[0x94][0xf0][0x0][0x0][0x0][0x0][0x0]@V@[0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x6][0x8][0x14][0x0][0x1][0x89]|[0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x4]@[0x10][0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0x0][0x0][0x0][0x0]@[[0x0][0x0][0x0][0x0][0x0][0x0]@[0x10][0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x6][0x9][0x3][0x0][0x1]t[0x18][0x0][0x0][0x0][0x0][0x0][0x0][0x1][0xe]@p[0xe0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x9][0x0][0x10][0x0][0x0][0x0][0x0][0x0]][0x0]r[0x0][0x94][0x0][0xc9][0x0][0xd3][0x0];[0x1][0xba][0x3][0x83][0x4]Y[0xe]@[0xbe][0x96][0x0][0x0][0x0][0x0][0x0]@t`[0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x6][\r][0x10][0x0][0x1]{[0xb3][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x1d]@=[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x2][0x0][0x10][0x0][0x0][0x0][0x0][0x0][0x92][0x1][0xae][0x1]@[0x89]`[0x0][0x0][0x0][0x0][0x0]@C"
2018-12-14 10:48:20,339 DEBUG org.apache.http.wire -  http-outgoing-9 << "[0xe][0x1f][0xe]A[0x5][0x7][0x80][0x0][0x0][0x0][0x0]@[0xce][0x87][0x80][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x6][0x4][0x6][0x0][0x1]{[0xa1][0x0][0x0][0x0][0x0][0x0][0x0][0x0]C@P[0xc0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x3][0x0][0x10][0x0][0x0][0x0][0x0][0x0][0xd8][0x0]w[0x1][0xad][0x3]@[0x94][0xf0][0x0][0x0][0x0][0x0][0x0]@V@[0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x6][0x8][0x14][0x0][0x1][0x89]|[0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x4]@[0x10][0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x10][0x0][0x0][0x0][0x0][0x0]@[[0x0][0x0][0x0][0x0][0x0][0x0]@[0x10][0x0][0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x6][0x9][0x3][0x0][0x1]t[0x18][0x0][0x0][0x0][0x0][0x0][0x0][0x1][0xe]@p[0xe0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x9][0x0][0x10][0x0][0x0][0x0][0x0][0x0]][0x0]r[0x0][0x94][0x0][0xc9][0x0][0xd3][0x0];[0x1][0xba][0x3][0x83][0x4]Y[0xe]@[0xbe][0x96][0x0][0x0][0x0][0x0][0x0]@t`[0x0][0x0][0x0][0x0][0x0][0x4][0x0][0x9][0x0][0x6][\r][0x10][0x0][0x1]{[0xb3][0x0][0x0][0x0][0x0][0x0][0x0][0x0][0x1d]@=[0x0][0x0][0x0][0x0][0x0][0x0]:0[0x0][0x0][0x1][0x0][0x0][0x0][0x0][0x0][0x2][0x0][0x10][0x0][0x0][0x0][0x0][0x0][0x92][0x1][0xae][0x1]@[0x89]`[0x0][0x0][0x0][0x0][0x0]@C"

2018-12-14 10:53:17,490 DEBUG org.apache.http.wire -  http-outgoing-9 << "[read] I/O error: Connection reset"
2018-12-14 10:53:17,490 DEBUG org.apache.http.wire -  http-outgoing-9 << "[read] I/O error: Connection reset"
2018-12-14_10:53:17 ERROR io.SomeClass - Error :
...
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:210) ~[?:1.8.0_162]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_162]
        at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:84) ~[httpclient-4.5.6.jar:4.5.6]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137) ~[httpcore-4.4.10.jar:4.4.10]
        at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198) ~[httpcore-4.4.10.jar:4.4.10]
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176) ~[httpcore-4.4.10.jar:4.4.10]
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135) ~[httpclient-4.5.6.jar:4.5.6]
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82) ~[aws-java-sdk-core-1.11.381.jar:?]
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180) ~[aws-java-sdk-core-1.11.381.jar:?]
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82) ~[aws-java-sdk-core-1.11.381.jar:?]
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82) ~[aws-java-sdk-core-1.11.381.jar:?]
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82) ~[aws-java-sdk-core-1.11.381.jar:?]
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180) ~[aws-java-sdk-core-1.11.381.jar:?]
        at java.security.DigestInputStream.read(DigestInputStream.java:161) ~[?:1.8.0_162]
        at com.amazonaws.services.s3.internal.DigestValidationInputStream.read(DigestValidationInputStream.java:59) ~[aws-java-sdk-s3-1.11.381.jar:?]
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82) ~[aws-java-sdk-core-1.11.381.jar:?]
        at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125) ~[aws-java-sdk-s3-1.11.381.jar:?]
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:82) ~[aws-java-sdk-core-1.11.381.jar:?]
        at io.XXX.XXX(XXX.java:666) ~[XXX.jar:?]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_162]
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_162]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_162]
        at java.io.DataInputStream.readFully(DataInputStream.java:195) ~[?:1.8.0_162]
        at java.io.DataInputStream.readLong(DataInputStream.java:416) ~[?:1.8.0_162]
        at java.io.DataInputStream.readDouble(DataInputStream.java:468) ~[?:1.8.0_162]
        at io.XXX.XXX(XXX.java:666) ~[XXX.jar:?]
        ... 3 more
```

We see a pause of 5 minutes before the Connection reset, these 5 minutes being our custom timeout.

**Comment by blacelle** [comment]
If helpful: amz-sdk-invocation-id: 12addecf-9a60-fb31-a8e0-fa4000ea5487

**Comment by debora-ito** [comment]
Closing issue. Feel free to reopen if you have further questions.
