### ISSUE TITLE
Glue SDK GetPartitions Expression filter not working

### ISSUE THREAD

**Issue by KevinMellott91** [aws/aws-sdk-java#1843]
I'm attempting to use the Glue SDK within a Java application to get a filtered list of existing partitions from a Redshift Spectrum table. When I run the query below to view partitions within Redshift, I get the following results.

_Query_
`select * from SVV_EXTERNAL_PARTITIONS;`

_Result_
<img width="620" alt="screen shot 2018-12-14 at 2 50 21 pm" src="https://user-images.githubusercontent.com/6477529/50026889-0485ba80-ffb0-11e8-804d-e7d32d551916.png">

When I use the Java Glue SDK to call _GetPartitions_ without an _Expression_ filter, it locates this partition without issue.

_Code_
```
GetPartitionsResult getPartitionsResult = client.getPartitions(new GetPartitionsRequest()
    .withDatabaseName("mdwpoc")
    .withTableName("client_log")
);
```

_Result_
<img width="328" alt="screen shot 2018-12-14 at 2 56 01 pm" src="https://user-images.githubusercontent.com/6477529/50026997-6c3c0580-ffb0-11e8-9ab7-925a38ea14fb.png">

My problem, is that if I attempt to add an _Expression_ filter to my Java code, then I am getting an exception. I'm not entirely sure that I am using the filter correctly, but I also was not able to find any examples online or in the product documentation.

_Code_
```
GetPartitionsResult getPartitionsResult = client.getPartitions(new GetPartitionsRequest()
    .withDatabaseName("mdwpoc")
    .withTableName("client_log")
    .withExpression("recordType='client-logs'")
);
```

_Exception_
```
Exception in thread "main" com.amazonaws.services.glue.model.InvalidInputException: Unknown type : 'varchar(30)' (Service: AWSGlue; Status Code: 400; Error Code: InvalidInputException; Request ID: XXXXXX...)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.glue.AWSGlueClient.doInvoke(AWSGlueClient.java:4675)
	at com.amazonaws.services.glue.AWSGlueClient.invoke(AWSGlueClient.java:4651)
	at com.amazonaws.services.glue.AWSGlueClient.executeGetPartitions(AWSGlueClient.java:2935)
	at com.amazonaws.services.glue.AWSGlueClient.getPartitions(AWSGlueClient.java:2910)
	at com.kevin.isawesome.Main.glueSdk(Main.java:297)
	at com.kevin.isawesome.Main.main(Main.java:127)
```

Does anybody know what I am doing wrong and/or has anybody gotten this functionality to work in their own experiences? Any help or suggestions are greatly appreciated.

**Comment by debora-ito** [comment]
Hi @KevinMellott91,  I'm not familiar with AWS Glue but the [GetPartitionRequest.withExpression() ](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/glue/model/GetPartitionsRequest.html#withExpression-java.lang.String-) documentation mentions that the following are the the supported partition key types:
- string
- date
- timestamp
- int
- bigint
- long
- tinyint
- smallint
- decimal

If an invalid type is encountered, an exception is thrown.
So can it be the case of `recordType` type is not supported?

**Comment by KevinMellott91** [comment]
HI @debora-ito, thanks for the reply. My _recordType_ partition key is setup as a _varchar(30)_ type, but the code fails if I try to go more generic by specifying _string_ instead.

```sql
create external table data_lake.client_log (
  sessionId VARCHAR(80),
  "timeStamp" VARCHAR(40),
  description VARCHAR(100)
)
partitioned by (fiCode VARCHAR(30), recordType VARCHAR(20), "year" INT, "month" INT, "day" INT)
stored as PARQUET
location 's3://<my path>'
table properties (
  'compression_type' = 'snappy'
);
```

**Comment by debora-ito** [comment]
Closing due to no response, feel free to reopen if you have further questions.
