### ISSUE TITLE
[CMS + KMS + Assume Role] Bug in AmazonS3EncryptionClient#uploadObject by UploadObjectObserver#newInitiateMultipartUploadRequest

### ISSUE THREAD

**Issue by taklwu** [aws/aws-sdk-java#1851]
We have a use case of CMS + KMS + Assume Role, where credentials of assume role are overrided in each request by using `withRequestCredentialsProvider` or `setRequestCredentialsProvider`. 

We found a potential bug that caused by the use of [com.amazonaws.services.s3.AmazonS3EncryptionClient#uploadObject](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3EncryptionClient.java#L804) where stated as below.

1. [com.amazonaws.services.s3.AmazonS3EncryptionClient#uploadObject](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3EncryptionClient.java#L804)
    1. String uploadId = observer.onUploadInitiation(req);

2. [UploadObjectObserver.java#onUploadInitiation](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/UploadObjectObserver.java#L114-L118)
3. [UploadObjectObserver.java#newInitiateMultipartUploadRequest](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/UploadObjectObserver.java#L89-L103) 
    1. here , if the request has withRequestCredentialsProvider/setRequestCredentialsProvider, it's missing! <- bug ?

Seems like we should add `withRequestCredentialsProvider` back to [UploadObjectObserver.java#newInitiateMultipartUploadRequest](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/UploadObjectObserver.java#L89-L103) as part of the redirection.

let me know what you think.

this is the stacktrace from our client program.

```
18/12/19 18:12:21 ERROR cse.CSEMultipartUploadOutputStream: ERROR stacktrace:
com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 982AC5684230F093; S3 Extended Request ID: 3W33u74coXq+PvLvDm0s6ke1ZSN0e8oAfrYyFAurOB5ot7cTjvnFrSflrka1WbE8SWgHv32nGe8=), S3 Extended Request ID: 3W33u74coXq+PvLvDm0s6ke1ZSN0e8oAfrYyFAurOB5ot7cTjvnFrSflrka1WbE8SWgHv32nGe8=
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1695)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3500)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3EncryptionClient.access$501(AmazonS3EncryptionClient.java:81)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3EncryptionClient$S3DirectImpl.initiateMultipartUpload(AmazonS3EncryptionClient.java:712)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.internal.crypto.S3CryptoModuleBase.initiateMultipartUploadSecurely(S3CryptoModuleBase.java:256)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.internal.crypto.CryptoModuleDispatcher.initiateMultipartUploadSecurely(CryptoModuleDispatcher.java:149)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3EncryptionClient.initiateMultipartUpload(AmazonS3EncryptionClient.java:620)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.UploadObjectObserver.onUploadInitiation(UploadObjectObserver.java:116)
        at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3EncryptionClient.uploadObject(AmazonS3EncryptionClient.java:804)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.call.UploadObjectCall.performCall(UploadObjectCall.java:44)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.call.UploadObjectCall.performCall(UploadObjectCall.java:15)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.call.AbstractUploadingS3Call.perform(AbstractUploadingS3Call.java:61)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.executor.GlobalS3Executor.execute(GlobalS3Executor.java:93)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.AmazonS3LiteClient.invoke(AmazonS3LiteClient.java:189)
        at com.amazon.ws.emr.hadoop.fs.s3.lite.AmazonS3EncryptionLiteClient.uploadObject(AmazonS3EncryptionLiteClient.java:26)
        at com.amazon.ws.emr.hadoop.fs.cse.CSEMultipartUploadOutputStream$2.run(CSEMultipartUploadOutputStream.java:146)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by taklwu** [comment]
ping here ? and on the PR https://github.com/aws/aws-sdk-java/pull/1852 as well

**Comment by taklwu** [comment]
any updates?

**Comment by debora-ito** [comment]
Hi @taklwu apologies for the long silence here. I'm taking a look.

**Comment by zoewangg** [comment]
Apologies again on the delay. We will discuss internally about this change and provide an update shortly.

**Comment by varunnvs92** [comment]
PR https://github.com/aws/aws-sdk-java/pull/1852 merged. Will be included in next release.
