### ISSUE TITLE
java.lang.NoSuchFieldError: ALLOW_FINAL_FIELDS_AS_MUTATORS

### ISSUE THREAD

**Issue by waynehong666** [aws/aws-sdk-java#1856]
Whenever I have the following dependencies in my maven project:
<dependency>
          <groupId>com.amazonaws</groupId>
          <artifactId>aws-java-sdk-s3</artifactId>
          <version>1.11.475</version>
        </dependency>

        <dependency>
            <groupId>ar.com.fdvs</groupId>
            <artifactId>DynamicJasper</artifactId>
            <version>5.1.1</version>
        </dependency>
I always got the following error:

java.lang.NoSuchFieldError: ALLOW_FINAL_FIELDS_AS_MUTATORS
	at com.amazonaws.partitions.PartitionsLoader.<clinit>(PartitionsLoader.java:52)
	at com.amazonaws.regions.RegionMetadataFactory.create(RegionMetadataFactory.java:30)
	at com.amazonaws.regions.RegionUtils.initialize(RegionUtils.java:64)
	at com.amazonaws.regions.RegionUtils.getRegionMetadata(RegionUtils.java:52)
	at com.amazonaws.regions.RegionUtils.getRegion(RegionUtils.java:105)
	at com.amazonaws.client.builder.AwsClientBuilder.getRegionObject(AwsClientBuilder.java:256)
	at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:245)

I tried different versions, but always got the same error. Does anyone know which version of these libraries are compatible?

Best,
Wayne

**Comment by debora-ito** [comment]
Closing this based on @shorea's response. Please feel free to reopen if you have further questions.

**Comment by abhilash1994** [comment]
I face the same issue, my jackson databind version is 2.9.8

**Comment by azizo08** [comment]
I face the same issue, my jackson databind version is 2.7.6, have you any suggestion ? thkx

**Comment by prabhu18r-bv** [comment]
i am facing same with issue. my jackson databind is 2.13.2.1

**Comment by prabhu18r-bv** [comment]
> i am facing same with issue. my jackson databind is 2.13.2.1

resolved, intellij had multiple jackson jar. After sorting this out, it worked.
