### ISSUE TITLE
Incorrect ValidationException: No provisioned throughput specified for the table

### ISSUE THREAD

**Issue by IvoNet** [aws/aws-sdk-java#1886]
**Changed**

Added support for BillingMode (PAY_PER_REQUEST / on-demand)
and removed Provisionedthroughput according to the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-provisionedthroughput)

**Expected behavior**

Updated stack without validation errors

**Actual behavior**

The following error was generated

```
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: No provisioned throughput specified for the table (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: ...)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1695)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1350)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)
[...]
```
It seems that the Billingmode / on-demand is not yet supported. 
This makes testing very difficult.

Are there plans to implement this feature?

**Comment by debora-ito** [comment]
Hi @IvoNet, both Billing Modes PROVISIONED and PAY_PER_REQUEST are already supported, as specified in the `UpdateTableRequest` [documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/UpdateTableRequest.html#withBillingMode-java.lang.String-). 

I haven't had any problems in changing a table from provisioned to pay-per-request, here's my code example:

```java
AmazonDynamoDB ddbClient = AmazonDynamoDBClientBuilder.defaultClient();

UpdateTableRequest request = new UpdateTableRequest()
        .withTableName(tableName)
        .withBillingMode(BillingMode.PAY_PER_REQUEST);

UpdateTableResult result = ddbClient.updateTable(request);
```

If you're still experiencing issues, can you please provide a sample code?

**Comment by IvoNet** [comment]
Debora,

Thanks for the reply.

I see that it is indeed implemented in the SDK. I am finding out that it has to do with the **dynamodb-local** version.

If I download the latest from aws: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html

then I get this version:

```text
Release Notes
-----------------------------

2017-04-13 (1.11.119)

  * Add TTL implementation
  * Update aws libs to 1.11.119

```

Still resulting in the following error when running the new scripts against them:

```text
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: No provisioned throughput specified for the table (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 614fddfd-504a-4e0c-8bb5-0e158552c0d4)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1356)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1102)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:759)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:733)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:675)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:657)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:521)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:4230)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4197)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeCreateTable(AmazonDynamoDBClient.java:1051)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.createTable(AmazonDynamoDBClient.java:1018)
	at sim.cloudformation.mock.DDBTableCreator$$anonfun$create$1.apply(DDBTableCreator.scala:93)
	at sim.cloudformation.mock.DDBTableCreator$$anonfun$create$1.apply(DDBTableCreator.scala:91)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
```

**Comment by debora-ito** [comment]
The SDK team doesn't own `DynamoDB Local`, so I've forwarded your request to the service team. 

I'm going to close this for now since this isn't an issue with the Java SDK, but will post any updates we get from the DynamoDB Local team

**Comment by debora-ito** [comment]
@IvoNet the service team replied, saying yes it is in the roadmap and they expect to release it soon.

**Comment by UmeshKrishnanB** [comment]
Did they solved the issue? if any updates then please update here also!
