### ISSUE TITLE
Upgrading 'org.apache.httpcomponents:httpclient' to version 4.5.7 breaks lambda invocation

### ISSUE THREAD

**Issue by CatalinaMoisuc** [aws/aws-sdk-java#1898]
I have these aws dependencies in my pom:
<details>
<summary>See Dependencies</summary>
<br>
pom.xml
<br><br>
<pre>

```
<dependencyManagement>
    <dependencies>
      <!-- AWS SDK BOM (providing version for individual components below) -->
      <!-- see https://github.com/aws/aws-sdk-java -->
      <dependency>
        <groupId>com.amazonaws</groupId>
        <artifactId>aws-java-sdk-bom</artifactId>
        <version>1.11.490</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <!-- AWS SDK components (version derived from AWS SDK BOM) -->
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-lambda</artifactId>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-s3</artifactId>
    </dependency>
    <!-- AWS transitive dependency   -->
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <version>4.5.6</version>
    </dependency>
</dependencies>
```

</pre>
</details>
 <br/><br/>

Upgrading org.apache.httpcomponents:httpclient from version 4.5.6 to version 4.5.7 breaks my lambda invocation. I get this error:
<details>
<summary>See Error</summary>
<br>
Stacktrace:
<br><br>
<pre>

```
com.amazonaws.services.lambda.model.AWSLambdaException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AWSLambda; Status Code: 403; Error Code: InvalidSignatureException; Request ID: 7a834ac7-31a7-43c4-b64a-ec29f854eaba)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1356)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1102)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:759)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:733)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:675)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:657)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:521)
	at com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:3137)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3104)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3093)
	at com.amazonaws.services.lambda.AWSLambdaClient.executeInvoke(AWSLambdaClient.java:1744)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1716)
	at com.amazonaws.services.lambda.invoke.LambdaInvokerFactory$LambdaInvocationHandler.invoke(LambdaInvokerFactory.java:243)
```

</pre>
</details>

**Comment by debora-ito** [comment]
Hi @CatalinaMoisuc, I couldn't reproduce the issue, I was able to invoke a super simple Lambda function using httpclient `4.5.7`. 

Was there any other change that may have triggered the error?
Are you using a proxy?

**Comment by CatalinaMoisuc** [comment]
Hi, @debora-ito our app runs on an AWS EC2 instance so normally I would say that it has direct access and there is no proxy (that we know of, maybe AWS does some magic).

**Comment by debora-ito** [comment]
Do you have the same issue when you run it locally?

In the meanwhile, I'll try to reproduce in EC2.

**Comment by CatalinaMoisuc** [comment]
@debora-ito yes.

**Comment by debora-ito** [comment]
Can you provide a simple repro case we can use?

**Comment by debora-ito** [comment]
Closing this due to inactivity. Please feel free to reopen if you're still experiencing this issue.

**Comment by debora-ito** [comment]
This may be related to #1919.

**Comment by CatalinaMoisuc** [comment]
aws-java-sdk-bom#1.11.534 still doesn't work with org.apache.httpcomponents:httpclient#4.5.8.
