### ISSUE TITLE
NoSuchMethodError for AwsSyncClientParams.getAdvancedConfig

### ISSUE THREAD

**Issue by zeeshan-m** [aws/aws-sdk-java#1901]
I keep getting when trying to create the the ASG Client (`AmazonAutoScaling`). My SDK Version is: 1.11.490.

```
Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.client.AwsSyncClientParams.getAdvancedConfig()Lcom/amazonaws/client/builder/AdvancedConfig;
	at com.amazonaws.services.autoscaling.AmazonAutoScalingClient.<init>(AmazonAutoScalingClient.java:274)
	at com.amazonaws.services.autoscaling.AmazonAutoScalingClient.<init>(AmazonAutoScalingClient.java:258)
	at com.amazonaws.services.autoscaling.AmazonAutoScalingClientBuilder.build(AmazonAutoScalingClientBuilder.java:61)
	at com.amazonaws.services.autoscaling.AmazonAutoScalingClientBuilder.build(AmazonAutoScalingClientBuilder.java:27)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.services.autoscaling.AmazonAutoScalingClientBuilder.defaultClient(AmazonAutoScalingClientBuilder.java:45)
```

**Comment by zeeshan-m** [comment]
Turns out my gradle versions forces were messed up, and the aws core was being forced to 1.11.319

**Comment by eranpeer** [comment]
Here is what worked for me:
From https://github.com/aws/aws-sdk-java 

Add this to the dependencyManagement section of your POM:
```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>aws-java-sdk-bom</artifactId>
      <version>1.11.549</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```
And then use the SDK Maven modules without specifying a version:
```xml
<dependencies>
  <dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-ec2</artifactId>
  </dependency>
  <dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-s3</artifactId>
  </dependency>
  <dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-dynamodb</artifactId>
  </dependency>
</dependencies>
```
