### ISSUE TITLE
InputStream prematurely closed, "couldn't reset the stream to retry"

### ISSUE THREAD

**Issue by ehrmann** [aws/aws-sdk-java#191]
I noticed this exception: ```Encountered an exception and couldn't reset the stream to retry```. It came from here (ignore the top few frames; those are mine):

```
at glacierpipe.io.MemoryIOBuffer$MemoryInputStream.reset(MemoryIOBuffer.java:282)
at java.io.FilterInputStream.reset(FilterInputStream.java:226)
at java.io.FilterInputStream.reset(FilterInputStream.java:226)
at glacierpipe.io.ObservedInputStream.reset(ObservedInputStream.java:131)
at com.amazonaws.http.AmazonHttpClient.resetRequestAfterError(AmazonHttpClient.java:519)
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
at com.amazonaws.services.glacier.AmazonGlacierClient.invoke(AmazonGlacierClient.java:2065)
at com.amazonaws.services.glacier.AmazonGlacierClient.uploadMultipartPart(AmazonGlacierClient.java:1713)
```

And more interestingly, here's the stack trace with where the InputStream gets closed:
```
at glacierpipe.io.MemoryIOBuffer$MemoryInputStream.close(MemoryIOBuffer.java:189)
at java.io.FilterInputStream.close(FilterInputStream.java:181)
at java.io.FilterInputStream.close(FilterInputStream.java:181)
at glacierpipe.io.ObservedInputStream.close(ObservedInputStream.java:81)
at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:147)
at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:153)
at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:89)
at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:117)
at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:265)
at org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:203)
at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:236)
at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:47)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:682)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:486)
at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:380)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
at com.amazonaws.services.glacier.AmazonGlacierClient.invoke(AmazonGlacierClient.java:2065)
at com.amazonaws.services.glacier.AmazonGlacierClient.uploadMultipartPart(AmazonGlacierClient.java:1713)
```

**Comment by david-at-aws** [comment]
Hey David, sorry for the long radio-silence on this one. Recent versions of the SDK [filter out](https://github.com/aws/aws-sdk-java/blob/1.10.6/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L302) any `InputStream.close()` calls from the Apache HttpClient and wait to close the InputStream until after the call has completed, so this should be working now. Please feel free to reopen if you're still seeing problems.
