### ISSUE TITLE
ResponseCode: 403, ResponseStatus: Forbidden, The AWS Access Key Id you provided does not exist in our records

### ISSUE THREAD

**Issue by eromoe** [aws/aws-sdk-java#1911]
First, the aws key and secret are correct .

I am using pyspark 2.3.2 and spark-2.3.2-bin-hadoop2.7, it cost me much time to figure out I need put `aws-java-sdk-1.7.4.jar` and `hadoop-aws-2.7.7.jar` into sparks jars folder. 

I have also tried many combination with `aws-java-sdk-xxxx.jar` and `hadoop-aws-xxx.jar` by `os.environ['PYSPARK_SUBMIT_ARGS']` . This automatically downloaded the dependencies.

```

# os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.amazonaws:aws-java-sdk:1.11.496,org.apache.hadoop:hadoop-aws:2.7.3 pyspark-shell'
# os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.amazonaws:aws-java-sdk-s3:1.11.496,org.apache.hadoop:hadoop-aws:2.7.3 pyspark-shell'
os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.3 pyspark-shell'

spark = SparkSession\
    .builder\
    .appName("Demo")\
    .getOrCreate()

sc = spark.sparkContext

sc._jsc.hadoopConfiguration().set("fs.s3.awsAccessKeyId", access_key)
sc._jsc.hadoopConfiguration().set("fs.s3.awsSecretAccessKey", secret_key)
sc._jsc.hadoopConfiguration().set("fs.s3.impl", "org.apache.hadoop.fs.s3.S3FileSystem")
sc._jsc.hadoopConfiguration().set("fs.s3.endpoint", "s3.cn-north-1.amazonaws.com.cn")

sc._jsc.hadoopConfiguration().set("fs.s3n.awsAccessKeyId", access_key)
sc._jsc.hadoopConfiguration().set("fs.s3n.awsSecretAccessKey", secret_key)
sc._jsc.hadoopConfiguration().set("fs.s3n.impl", "org.apache.hadoop.fs.s3native.NativeS3FileSystem")
sc._jsc.hadoopConfiguration().set("fs.s3n.endpoint", "s3.cn-north-1.amazonaws.com.cn")

sc._jsc.hadoopConfiguration().set("fs.s3a.access.key", access_key)
sc._jsc.hadoopConfiguration().set("fs.s3a.secret.key", secret_key)
sc._jsc.hadoopConfiguration().set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
sc._jsc.hadoopConfiguration().set("fs.s3a.endpoint", "s3.cn-north-1.amazonaws.com.cn")

spark = SQLContext(sc)
df = spark.read.parquet("s3://test/R/storeincomelogs/*.parquet")

```

I have already tried many ways, always output below error
```
2019-02-13 09:34:32 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
read
2019-02-13 09:34:41 WARN  FileStreamSink:66 - Error while looking for metadata directory.
Traceback (most recent call last):
  File "income_revenue.py", line 548, in <module>
    send_comparison_report()
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "income_revenue.py", line 312, in send_comparison_report
    dfa = spark.read.parquet(*date_range_paths(SOURCE_DIR_PATH + 'arch/R/storeincomelogs/', start_date, end_date))
  File "C:\Anaconda3\lib\site-packages\pyspark\sql\readwriter.py", line 303, in parquet
    return self._df(self._jreader.parquet(_to_seq(self._spark._sc, paths)))
  File "C:\Anaconda3\lib\site-packages\py4j\java_gateway.py", line 1257, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "C:\Anaconda3\lib\site-packages\pyspark\sql\utils.py", line 63, in deco
    return f(*a, **kw)
  File "C:\Anaconda3\lib\site-packages\py4j\protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o28.parquet.
: org.apache.hadoop.fs.s3.S3Exception: org.jets3t.service.S3ServiceException: Service Error Message. -- ResponseCode: 403, ResponseStatus: Forbidden, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>xxxxxxxxxxxxx</AWSAccessKeyId><RequestId>AE7B376C5ED69D56</RequestId><HostId>oKNYIIYhiPHspHjHDEn/aBtqfywhXEHXd1Sxf16D+aHGiBjOBJw2fsJlf/QZcPQmfsGjZdP3DTk=</HostId></Error>
        at org.apache.hadoop.fs.s3.Jets3tFileSystemStore.get(Jets3tFileSystemStore.java:175)
        at org.apache.hadoop.fs.s3.Jets3tFileSystemStore.retrieveINode(Jets3tFileSystemStore.java:221)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
        at com.sun.proxy.$Proxy12.retrieveINode(Unknown Source)
        at org.apache.hadoop.fs.s3.S3FileSystem.listStatus(S3FileSystem.java:191)
        at org.apache.hadoop.fs.Globber.listStatus(Globber.java:69)
        at org.apache.hadoop.fs.Globber.glob(Globber.java:217)
        at org.apache.hadoop.fs.FileSystem.globStatus(FileSystem.java:1657)
        at org.apache.spark.deploy.SparkHadoopUtil.globPath(SparkHadoopUtil.scala:243)
        at org.apache.spark.deploy.SparkHadoopUtil.globPathIfNecessary(SparkHadoopUtil.scala:253)
        at org.apache.spark.sql.execution.datasources.DataSource$.org$apache$spark$sql$execution$datasources$DataSource$$checkAndGlobPathIfNecessary(DataSource.scala:711)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:390)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$15.apply(DataSource.scala:390)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:389)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
        at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:622)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jets3t.service.S3ServiceException: Service Error Message. -- ResponseCode: 403, ResponseStatus: Forbidden, XML Error Message: <?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>XXXXXXXXXXXXXXXXXXX</AWSAccessKeyId><RequestId>AE7B376C5ED69D56</RequestId><HostId>oKNYIIYhiPHspHjHDEn/aBtqfywhXEHXd1Sxf16D+aHGiBjOBJw2fsJlf/QZcPQmfsGjZdP3DTk=</HostId></Error>
        at org.jets3t.service.S3Service.getObject(S3Service.java:1470)
        at org.apache.hadoop.fs.s3.Jets3tFileSystemStore.get(Jets3tFileSystemStore.java:163)
        ... 37 more
```

**Comment by debora-ito** [comment]
Hi @eromoe, we don't really have the expertise with Spark to help out here. This repository is specifically for issues and feature requests for the AWS SDK for Java.

I found two questions on StackOverflow that might help:
- [(python) Spark .textFile(s3://…) access denied 403 with valid credentials](https://stackoverflow.com/questions/42651235/python-spark-textfiles3-access-denied-403-with-valid-credentials)
- [Spark is inventing his own AWS secretKey](https://stackoverflow.com/questions/42669246/spark-is-inventing-his-own-aws-secretkey)

For further support, I'd suggest asking your question on StackOverflow.

**Comment by ibirite** [comment]
Hi there. I was facing the same issue here. I was able to find the solution after a while and I dont know if this is your problem. But my problem was the fact that I was imediatly using new generated credentials in my code. So, I've added some sleeping seconds after generating the new credentials and everything went normal.
