### ISSUE TITLE
ECR: Unable to execute HTTP request: api.ecr.us-west-2.amazonaws.com happens randomly when redeploy to EKS

### ISSUE THREAD

**Issue by keaxu-exp** [aws/aws-sdk-java#1944]
I have an app running on EKS and talking to ECR, when deploying, this happens randomly and pretty frequent. 

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: api.ecr.us-west-2.amazonaws.com
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1175) ~[aws-java-sdk-core-1.11.509.jar!/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1121) ~[aws-java-sdk-core-1.11.509.jar!/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.509.jar!/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.509.jar!/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726) ~[aws-java-sdk-core-1.11.509.jar!/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.509.jar!/:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668) ~[aws-java-sdk-core-1.11.509.jar!/:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532) ~[aws-java-sdk-core-1.11.509.jar!/:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512) ~[aws-java-sdk-core-1.11.509.jar!/:?]
	at com.amazonaws.services.ecr.AmazonECRClient.doInvoke(AmazonECRClient.java:2050) ~[aws-java-sdk-ecr-1.11.509.jar!/:?]
	at com.amazonaws.services.ecr.AmazonECRClient.invoke(AmazonECRClient.java:2017) ~[aws-java-sdk-ecr-1.11.509.jar!/:?]
	at com.amazonaws.services.ecr.AmazonECRClient.invoke(AmazonECRClient.java:2006) ~[aws-java-sdk-ecr-1.11.509.jar!/:?]
	at com.amazonaws.services.ecr.AmazonECRClient.executeGetAuthorizationToken(AmazonECRClient.java:1059) ~[aws-java-sdk-ecr-1.11.509.jar!/:?]
	at com.amazonaws.services.ecr.AmazonECRClient.getAuthorizationToken(AmazonECRClient.java:1030) ~[aws-java-sdk-ecr-1.11.509.jar!/:?]
```

**Comment by debora-ito** [comment]
@keaxu-exp Intermittent errors are always hard to reproduce... 

Can you share how are you creating the client?
And are you seeing the error only when you redeploy, but the same code works fine after?

**Comment by keaxu-exp** [comment]
simply
```
AmazonECRClientBuilder.defaultClient();
```

I also tried, got same behavior
```
AmazonECRClientBuilder.standard()
                .withRegion(awsRegion)
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("xxx","xxx")))
                .build();
```

version:
```
com.amazonaws:aws-java-sdk-ecr:1.11.509
```

my service run on EKS

**Comment by keaxu-exp** [comment]
is this possible to be an DNS cache issue ?

**Comment by millems** [comment]
Sorry about the delay in response. Are you still encountering this issue?
