### ISSUE TITLE
AWS Lambda Client giving timeout

### ISSUE THREAD

**Issue by akshaykumar3** [aws/aws-sdk-java#1956]
I am trying to invoke AWS Lambda via my java code, I am using aws-sdk-java version 1.11.525 for it. I am getting the following error:
com.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1175)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1121)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:3139)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3106)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3095)
	at com.amazonaws.services.lambda.AWSLambdaClient.executeInvoke(AWSLambdaClient.java:1746)
	at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1718)
	at com.sn.verticles.LambdaVerticle.lambda$start$0(LambdaVerticle.java:44)
	at io.vertx.rxjava.core.eventbus.EventBus$3.handle(EventBus.java:258)
	at io.vertx.rxjava.core.eventbus.EventBus$3.handle(EventBus.java:256)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:264)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:242)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:565)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:524)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.WorkerContext.lambda$wrapTask$0(WorkerContext.java:34)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

**Comment by debora-ito** [comment]
Hi @akshaykumar3 it seems that your Lambda function is taking longer to respond than your configured client-side timeout. 

Could you try increasing the [socket timeout](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setSocketTimeout-int-)? The default value is 50 seconds.

**Comment by akshaykumar3** [comment]
Hi @debora-ito the lambda function usually takes less than a second to respond. In fact, I am getting this error once in a while not every time even when we hit the lambda with the same request. Could this be related to lambda cold start? In case yes does cold start take so much time?
The client-side timeout is 30 seconds for now. I got this error even when I increased the client-side timeout to 60 seconds.

**Comment by debora-ito** [comment]
It could be due to Lambda cold-start, although 60 seconds seems a bit too long, but it's hard for us to analyze it without knowing the details of your Lambda environment. 

As far as why it's slow, @zoewangg gave some details here: #1774, where she also points out that the team made several changes in [aws-sdk-java-v2](https://github.com/aws/aws-sdk-java-v2/) to minimize the cold-start, and you are welcome to try it out and send us feedback.

**Comment by debora-ito** [comment]
Closing the issue, feel free to reopen if you have further questions.
