### ISSUE TITLE
Unable to getObjectMetadata in ap-south-1 region

### ISSUE THREAD

**Issue by timmi05** [aws/aws-sdk-java#1957]
I am trying to work with S3 bucket in the ap-south-1 region.
`client.getObject(String bucketName, String key)` works as expected, but I am getting error when I try to get `client.getObjectMetadata(String bucketName, String key)` with the same input parameters

com.amazonaws.services.s3.model.AmazonS3Exception: Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: ***)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4158)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4105)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1218)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1194)

**Comment by debora-ito** [comment]
Hi @timmi05 That's odd. Can you [enable wire logging](http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) to get additional information and provide the logs? Please make sure there is **no sensitive data**

**Comment by debora-ito** [comment]
Also, which version of SDK are you using?

**Comment by timmi05** [comment]
I reproduced on different versions from 1.11.11 to 1.11.529.

**Comment by debora-ito** [comment]
Were you able to get the wire logs with no sensitive data?

**Comment by timmi05** [comment]
@debora-ito 
[wire_log_getObjectMetadata.txt](https://github.com/aws/aws-sdk-java/files/3053068/wire_log_getObjectMetadata.txt)

**Comment by timmi05** [comment]
The reason is incorrect use of setSignerOverride. As a result I get authentication exceptions. For some reason, the getObject method worked without exceptions.

**Comment by debora-ito** [comment]
So are you still having issues?

**Comment by timmi05** [comment]
No.

**Comment by debora-ito** [comment]
Great! In this case I'll go ahead and close this. Feel free to reopen if any further questions come up.
