### ISSUE TITLE
InvokeRequest - signature mismatch when using function ARN

### ISSUE THREAD

**Issue by mousedownmike** [aws/aws-sdk-java#1961]
I'm making the following call with `'com.amazonaws:aws-java-sdk-lambda:1.11.530'` in a Lambda function written with Groovy:

```groovy
def functionName = 'arn:aws:lambda:us-west-2:123456789012:function:SampleLambda'
AWSLambda lambda = AWSLambdaClientBuilder.defaultClient()
lambda.invoke(
   new InvokeRequest()
      .withFunctionName(functionName)
      .withInvocationType(InvocationType.EVENT)
    )
```
I get the following error (full stack trace at the end of this bug):
`The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

If I set `functionName` to just the function name `'SampleLambda'`, the call succeeds.

The [JavaDoc for InvokeRequest](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/lambda/model/InvokeRequest.html#withFunctionName-java.lang.String-) indicates the `functionName` parameter may be one of "Function name, Function ARN, Partial ARN".  Those same JavaDocs also state:

> The length constraint applies only to the full ARN. 

That statement appears 6 times in the doc but I can't find anything that defines the mentioned "lenght constraint".  My full function ARN is 59 characters.  Please advise if I should open a separate issue under Documentation.

Thanks,
Mike

Full Stack Trace:
```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AWSLambda; Status Code: 403; Error Code: InvalidSignatureException; Request ID: 57b1784a-9917-4739-8e5d-9e71049e4288): com.amazonaws.services.lambda.model.AWSLambdaException
com.amazonaws.services.lambda.model.AWSLambdaException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AWSLambda; Status Code: 403; Error Code: InvalidSignatureException; Request ID: 57b1784a-9917-4739-8e5d-9e71049e4288)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
at com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:3139)
at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3106)
at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3095)
at com.amazonaws.services.lambda.AWSLambdaClient.executeInvoke(AWSLambdaClient.java:1746)
at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:1718)
at com.amazonaws.services.lambda.AWSLambda$invoke.call(Unknown Source)
...
```

**Comment by debora-ito** [comment]
Hi @mousedownmike which version of Apache's `httpclient` are you using, is it `4.5.7`?
They introduced some changes in version `4.5.7` in their URL-enconding and `:` may be one of the characters affected. We are tracking the changes here: #1919.

Could you try using `4.5.5` and see if it works calling the function ARN?

**Comment by mousedownmike** [comment]
I can confirm that I was using `4.5.7` and changing it to `4.5.5` resolved the issue.  I also checked `4.5.6` and that works as well. 

Should I open a separate issue regarding the ambiguous documentation about the "length constraint"? Clearly it's not related to the issue I was encountering.

> The length constraint applies only to the full ARN.

Thanks @debora-ito

**Comment by debora-ito** [comment]
There's no need to create a new issue, I'll contact the service team internally and ask them to make the documentation more clear, as they are the documentation owners.

Would that be OK?

**Comment by mousedownmike** [comment]
That works for me, thanks again for your help.
