### ISSUE TITLE
Streaming job throwing exceptions

### ISSUE THREAD

**Issue by spachari** [aws/aws-sdk-java#1962]
I am running a streaming job that runs fine for 12 odd hours and then throws this exception.

java.lang.RuntimeException: Cannot create staging directory 's3://hcom-data-prod-users/spachari/bot_filtering_poc/.hive-staging_hive_2019-04-03_08-05-38_564_5681060932056678635-1': com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.SdkClientException: Unable to execute HTTP request: hcom-data-prod-users.s3.us-west-2.amazonaws.com
        at org.apache.spark.sql.hive.execution.SaveAsHiveFile$class.getStagingDir(SaveAsHiveFile.scala:249)
        at org.apache.spark.sql.hive.execution.SaveAsHiveFile$class.getExternalScratchDir(SaveAsHiveFile.scala:206)
        at org.apache.spark.sql.hive.execution.SaveAsHiveFile$class.newVersionExternalTempPath(SaveAsHiveFile.scala:191)
        at org.apache.spark.sql.hive.execution.SaveAsHiveFile$class.getExternalTmpPath(SaveAsHiveFile.scala:130)
        at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.getExternalTmpPath(InsertIntoHiveTable.scala:66)
        at org.apache.spark.sql.hive.execution.InsertIntoHiveTable.run(InsertIntoHiveTable.scala:96)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:104)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:102)
        at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:122)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
        at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:656)
        at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:656)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:656)
        at org.apache.spark.sql.DataFrameWriter.insertInto(DataFrameWriter.scala:322)
        at org.apache.spark.sql.DataFrameWriter.insertInto(DataFrameWriter.scala:308)

This looks like an aws connection issue. Kindly let me know if there is a workaround for this issue. If this happens can we do a re-try for this error?

**Comment by zoewangg** [comment]
Hi, what SDK version are you using? Could you provide the complete stacktrace? Yes, this looks like a network hiccup and should be retried and likely succeed in the next attempt.

**Comment by debora-ito** [comment]
Closing this due to no response. Please feel free to reopen if you're still experiencing this issue.
