### ISSUE TITLE
TransferManager hangs after failure from main thread.

### ISSUE THREAD

**Issue by saurabhere** [aws/aws-sdk-java#1972]
Related to #457 .

Issue seen on aws-java-sdk-s3:1.11.327.

It seems that transfermanager.downloadDirectory()(com/amazonaws/services/s3/transfer/TransferManager.java:1190) fetches objectMetadata from the main thread before giving the actual download to the worker threads.
It does so by setting a CountdownLatch and resetting it only after metadata is fetched for all. However, if this metadata call fails like this:
```
com.amazonaws.SdkClientException: Unable to execute HTTP request: The target server failed to respond
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1116) 
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1066) 
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) 
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) 
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) 
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) 
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) 
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) 
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4365) 
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4312) 
at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1270) 
at com.amazonaws.services.s3.transfer.TransferManager.doDownload(TransferManager.java:1050) 
at com.amazonaws.services.s3.transfer.TransferManager.downloadDirectory(TransferManager.java:1284) 
at com.amazonaws.services.s3.transfer.TransferManager.downloadDirectory(TransferManager.java:1152) 
```

the uncaught exception skips the resetting of the latch at : `com/amazonaws/services/s3/transfer/TransferManager.java:1298` and causes all the workers to keep waiting for the latch forever:

```
"pool-1-thread-10" #139 prio=5 os_prio=0 cpu=34656.51ms elapsed=140733.58s tid=0x00007f2284010000 nid=0x15472 waiting on condition  [0x00007f223a06d000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.2/Native Method)
        - parking to wait for  <0x00007f286b5c7d80> (a java.util.concurrent.CountDownLatch$Sync)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.2/LockSupport.java:194)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.2/AbstractQueuedSynchronizer.java:885)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(java.base@11.0.2/AbstractQueuedSynchronizer.java:1039)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@11.0.2/AbstractQueuedSynchronizer.java:1345)
        at java.util.concurrent.CountDownLatch.await(java.base@11.0.2/CountDownLatch.java:232)
        at com.amazonaws.services.s3.transfer.MultipleFileTransferStateChangeListener.transferStateChanged(MultipleFileTransferStateChangeListener.java:40)
        at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.setState(AbstractTransfer.java:165)
        at com.amazonaws.services.s3.transfer.internal.DownloadImpl.setState(DownloadImpl.java:164)
        at com.amazonaws.services.s3.transfer.DownloadCallable.call(DownloadCallable.java:129)
        at com.amazonaws.services.s3.transfer.DownloadCallable.call(DownloadCallable.java:53)
        at java.util.concurrent.FutureTask.run(java.base@11.0.2/FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.2/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.2/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.2/Thread.java:834)
```

I am able to reproduce this easily using the following:

```
    ExecutorService transferManagerPool = Executors.newFixedThreadPool(2);
    AmazonS3 s3client = new MyS3Client(AmazonS3ClientBuilder.standard().build());
    TransferManager transferManager = TransferManagerBuilder.standard().withS3Client(s3client)
        .withExecutorFactory(() -> transferManagerPool)
        .build();
    for(int i=0;i< 4;i++){
        try{
        transferManager.downloadDirectory("mybucket","mykeywith10itemsInside",
        new File("myfile_",Integer.toString(i)),null)
        .waitForCompletion();
        }catch(Exception e){
        e.printStackTrace();
        }
    }
```
[MyS3Client.java.txt](https://github.com/aws/aws-sdk-java/files/3078644/MyS3Client.java.txt)

**Comment by saurabhere** [comment]
I see the same behaviour in the latest https://github.com/aws/aws-sdk-java/releases/tag/1.11.534 too.

**Comment by zoewangg** [comment]
@saurabhere Hi sorry for the delayed response. We were able to identity the issue and has pushed out a fix. Could you try with the latest version?

**Comment by saurabhere** [comment]
Thanks. Since this is not always happening. It would be hard to verify if the fix works.. I will take your word for it and update the dependency to a version greater than 1.11.576.
We can close this.
Will reopen if this issue still persists.
