### ISSUE TITLE
Unable to read file with "+" symbol in key path eg:  "\test\folder\test + file.pdf"

### ISSUE THREAD

**Issue by ArunPonnusamyS** [aws/aws-sdk-java#1988]
Hi,
Error while getObject() only for file name contains + symbol (ex : "\test\folder\test + file.pdf")

Note : Only occur while using  (httpclient-4.5.7.jar, httpclient-4.5.8.jar) versions
- Not occur while using 4.5.5(this will work fine).

but we cant downgrade httpclient.jar 
-----

Error Msg :
getObjectRequest = new GetObjectRequest("Bucket name"), "XXX");				
s3Object = AmazonS3.getObject(getObjectRequest);
----

com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch;
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712) ~[aws-java-sdk-core-1.11.530.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367) ~[aws-java-sdk-core-1.11.530.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113) ~[aws-java-sdk-core-1.11.530.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.530.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.530.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726) ~[aws-java-sdk-core-1.11.530.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.530.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668) ~[aws-java-sdk-core-1.11.530.jar:?]

--------------
Please look into it.

Thanks in advance
Arun S

**Comment by debora-ito** [comment]
Thank you for reaching out to us @ArunPonnusamyS. We are aware of the problem, Apache `httpclient` changed the behavior of its URI builder in `4.5.7`, and using versions `4.5.7` or `4.5.8` you'll see the `SignatureDoesNotMatch` error in some cases.

We are tracking the issue in #1919 and actively working on a solution, you can check that issue for updates.

I'll go ahead and close this, but feel free to reopen if you have any other question.

**Comment by nikhil-bidgely** [comment]
@debora-ito Even after new HTTPClient fix, files with special characters in their names like información is failing. I'm using put object call with SDK version 1.11.547 and it's showing the SignatureDoesNotMatch exception with special characters, file names containing letters of the English alphabet is working fine.
Please let me know what can be the resolution for this and are we following it with the httpclient team if it's an issue on their side?

**Comment by debora-ito** [comment]
@nikhil-bidgely we are still working on the change needed to make the newer versions of `httpclient` work with the SDK, we were blocked by the release of `httpclient-4.5.9` (see the discussion in #1919). 

In the meantime, you can use `httpclient-4.5.5` or `httpclient-4.5.6`.

**Comment by nikhil-bidgely** [comment]
@debora-ito version 4.5.9 has already been released but that too isn't working with say french/spanish letters

**Comment by debora-ito** [comment]
@nikhil-bidgely Have you checked the Object Key Naming Guidelines [documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html)? You may want to avoid using some special characters in the object key.

If you still think it's an issue with the SDK, please create a new github issue with a code sample we can use to reproduce (showing the special characters you're having problem with), and also the version of the SDK you're using.
