### ISSUE TITLE
S3 V4 upload Invalid signature when key contains '+'

### ISSUE THREAD

**Issue by kny78** [aws/aws-sdk-java#2031]
I cannot upload files containg a timestamp as part of the key. I narrowed it down to the '+' sign being the trigger.

Example that triggers the bug:

```
@Test
    fun putFileWithError() {
        var client: S3Client = S3Client.builder().build()

        println("""THIS IS OK:""")
        client.putObject(
                PutObjectRequest.builder()
                        .key("key/with-no-pluss-sign.json")
                        .bucket("ambitalab-junit-test")
                        .build(),
                RequestBody.fromString("Same what ever")
        )
        println("Ok with no '+' sign")


        println("""
             |
             |   THIS WILL FAIL:""".trimMargin())
        client.putObject(
                PutObjectRequest.builder()
                        .key("key/with+sign.json")
                        .bucket("ambitalab-junit-test")
                        .build(),
                RequestBody.fromString("Same what ever")
        )
    }
```

This produces the output/stacktrace:
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
  THIS IS OK:

Ok with no '+' sign

   THIS WILL FAIL:



software.amazon.awssdk.services.s3.model.S3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: S3, Status Code: 403, Request ID: 45C369D0D7B722E2)

	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleErrorResponse(HandleResponseStage.java:115)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:58)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:63)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:113)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:86)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:62)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:51)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:33)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:79)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120)
	at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.s3.DefaultS3Client.putObject(DefaultS3Client.java:3053)
	at com.ambita.felles.billing.service.aws.AwsS3BugIT.putFileWithError(AwsS3BugIT.kt:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
```

**Comment by debora-ito** [comment]
Hi @kny78  can you confirm you are using Apache `httpclient-4.5.7` or older? Apache made some breaking changes in `4.5.7` and it impacted S3 APIs, we are tracking the issue in #1919 where you can see more details about it. 

The SDK team is working on a solution to make the SDK work with the newer versions of httpclient, but in the meantime you can use `httpclient-4.5.5` or `httpclient-4.5.6`.

**Comment by kny78** [comment]
Good morning Debora,
The downgrade fixed the issue.
However I don't see the "+" issue mentioned in #1919.
I also see that there is a deep discussion about specifications in the
upstream issue.

-Kjetil 
On Tue, 2019-06-25 at 15:55 -0700, Debora Naomi Ito wrote:
> Hi @kny78  can you confirm you are using Apache httpclient-4.5.7 or
> older? Apache made some breaking changes in 4.5.7 and it impacted S3
> APIs, we are tracking the issue in #1919 where you can see more
> details about it.
> 
> The SDK team is working on a solution to make the SDK work with the
> newer versions of httpclient, but in the meantime you can use
> httpclient-4.5.5 or httpclient-4.5.6.
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/aws/aws-sdk-java/issues/2031?email_source=notifications\u0026email_token=AAFYG6O6YSWHAEWLRMNDQPTP4KO6NA5CNFSM4H3CJZ6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYR2JFQ#issuecomment-505652374
> ",
> "url": "
> https://github.com/aws/aws-sdk-java/issues/2031?email_source=notifications\u0026email_token=AAFYG6O6YSWHAEWLRMNDQPTP4KO6NA5CNFSM4H3CJZ6KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYR2JFQ#issuecomment-505652374
> ",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]
-- 
Kjetil Nygård
pulk.hesten@gmail.com
Tlf +47 4147 4337

**Comment by debora-ito** [comment]
The `+` issue was mentioned on this comment [here](https://github.com/aws/aws-sdk-java/issues/1919#issuecomment-471451804). We'll post updates about this issue in #1919, so I'll go ahead and close this one.

Feel free to reach out if you have more questions.
