### ISSUE TITLE
Cannot compile Amazon Rekognition Client to GraalVM native image

### ISSUE THREAD

**Issue by solveretur** [aws/aws-sdk-java#2032]
Hi I created a simple AWS lambda to face rekognition and now I would like to compile it to native image using GraalVM. Unfortunately I get this exception. Has anyone in great big Amazon tried to do this and could help me with configuration ?

```
Exception in thread "main" com.xxxx.recognition.RecognitionException: com.amazonaws.SdkClientException: Unable to load partition metadata from com/amazonaws/partitions/endpoints.json
    at com.xxx.recognition.AwsRekognitionService.<init>(AwsRekognitionService.java:26)
    at com.xxx.service.AwsRekognitionPictureMatcherService.<init>(AwsRekognitionPictureMatcherService.java:17)
    at com.xxx.Lambda.main(Lambda.java:13)
Caused by: com.amazonaws.SdkClientException: Unable to load partition metadata from com/amazonaws/partitions/endpoints.json
    at com.amazonaws.partitions.PartitionsLoader.build(PartitionsLoader.java:82)
    at com.amazonaws.regions.RegionMetadataFactory.create(RegionMetadataFactory.java:30)
    at com.amazonaws.regions.RegionUtils.initialize(RegionUtils.java:64)
    at com.amazonaws.regions.RegionUtils.getRegionMetadata(RegionUtils.java:52)
    at com.amazonaws.regions.RegionUtils.getRegion(RegionUtils.java:105)
    at com.amazonaws.client.builder.AwsClientBuilder.getRegionObject(AwsClientBuilder.java:256)
    at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:245)
    at com.amazonaws.client.builder.AwsClientBuilder.withRegion(AwsClientBuilder.java:232)
    at com.xxx.recognition.AwsRekognitionService.<init>(AwsRekognitionService.java:23)
    ... 2 more
````

My pom.xml dependencies

```
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-rekognition</artifactId>
            <version>1.11.578</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-events</artifactId>
            <version>2.2.6</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j18-impl</artifactId>
            <version>2.11.2</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-lambda-java-log4j</artifactId>
            <version>1.0.0</version>
        </dependency>
```

**Comment by debora-ito** [comment]
@solveretur We don't have the knowledge to help out with GraalVM issues here really. 

I found this StackOverflow question with the same exception you are seeing, maybe it's helpful in your case  - https://stackoverflow.com/questions/54931286/micronaut-serverless-application-using-dynamodb-and-graal-custom-runtime-throws
