### ISSUE TITLE
Unable to evaluate the expression Method threw 'com.amazonaws.SdkClientException' exception while query on dynamodb

### ISSUE THREAD

**Issue by divyanshu16** [aws/aws-sdk-java#2092]
When I try to query operation on dynamodb, it throws an exception `Unable to evaluate the expression Method threw 'com.amazonaws.SdkClientException' exception.` 

Environment: MacOS and this issue is also on Amazon Linux Box
Java: 1.8
In my build.gradle, I have these dependencies:
```
compile 'com.amazonaws:aws-lambda-java-events:1.1.0'
compile 'com.amazonaws:aws-lambda-java-log4j:1.0.0'
compile 'com.amazonaws:aws-java-sdk-s3:1.11.412'
compile 'com.amazonaws:aws-java-sdk-sts:1.11.412'
compile 'com.amazonaws:aws-java-sdk-core:1.11.412'
compile group: 'com.amazonaws', name: 'aws-lambda-java-core', version: '1.1.0'
compile group: 'com.amazonaws', name: 'aws-dynamodb-encryption-java', version: '1.12.0'
```

```
com.amazonaws.SdkClientException: Unable to unmarshall error response (null). Response Code: 400, Response Text: Bad Request

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1708)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:3443)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:3419)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeQuery(AmazonDynamoDBClient.java:2318)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:2293)
	at com.amazonaws.services.dynamodbv2.datamodeling.PaginatedQueryList.fetchNextPage(PaginatedQueryList.java:86)
	at com.amazonaws.services.dynamodbv2.datamodeling.PaginatedList.loadNextResults(PaginatedList.java:161)
	at com.amazonaws.services.dynamodbv2.datamodeling.PaginatedList.nextResultsAvailable(PaginatedList.java:148)
	at com.amazonaws.services.dynamodbv2.datamodeling.PaginatedList.loadAllResults(PaginatedList.java:132)
	at com.amazonaws.services.dynamodbv2.datamodeling.PaginatedList.size(PaginatedList.java:427)
	at worker.CronJobRestAPITest.testFunctionality(CronJobRestAPITest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at com.amazonaws.http.JsonErrorResponseHandler.unmarshallException(JsonErrorResponseHandler.java:134)
	at com.amazonaws.http.JsonErrorResponseHandler.createException(JsonErrorResponseHandler.java:124)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:91)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:37)
	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:53)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:41)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:26)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1694)
	... 41 more
```

**Comment by debora-ito** [comment]
Hi @divyanshu16, it looks like you are using SDK's `aws-java-sdk-dynamodb` lib in your code, but referencing [`aws-dynamodb-encryption-java`](https://github.com/aws/aws-dynamodb-encryption-java)  as a dependency in your gradle.build file, which is a different lib maintained in a different github project.

Try adding `aws-java-sdk-dynamodb` as a dependency, as you did with s3 and sts.

**Comment by divyanshu16** [comment]
@debora-ito While debugging, I can see that my code goes into aws-java-sdk-dynamodb but I have not put this in my build.gradle . Could it be that ` aws-dynamodb-encryption-java` happens to have  dependency of aws-java-sdk-dynamodb? I am asking because I could not find this in pom.xml of ` aws-dynamodb-encryption-java`. Do you happen to have any idea about it?

**Comment by debora-ito** [comment]
> While debugging, I can see that my code goes into aws-java-sdk-dynamodb but I have not put this in my build.gradle. 

If your code is using `aws-java-sdk-dynamodb` you need to add it as a dependency in your build.gradle file.

If you want to use `aws-dynamodb-encryption-java` instead (since it is declared in your build.gradle file), you'll need to change your code to use the Amazon DynamoDB Encryption Client, which is a different library. You can check its documentation [here](https://docs.aws.amazon.com/dynamodb-encryption-client/latest/devguide/what-is-ddb-encrypt.html) and its github repository [here](https://github.com/aws/aws-dynamodb-encryption-java/) for more information and code examples.

**Comment by debora-ito** [comment]
@thangavel-projects a quick search for the `Unable to unmarshall error response (null). Response Code: 400, Response Text: Bad Request` error message on the AWS Forums brought two results ([1](https://forums.aws.amazon.com/thread.jspa?threadID=309660), [2](https://forums.aws.amazon.com/thread.jspa?threadID=174408)) and their root cause was conflicting versions of dependencies.

**Comment by debora-ito** [comment]
Closing this. Feel free to reopen if you're still experiencing this issue.
