### ISSUE TITLE
Cannot catch exception thrown by com.amazonaws.util.DateUtils when invalid AWS credentials were provided

### ISSUE THREAD

**Issue by xorinox** [aws/aws-sdk-java#2098]
Hello, I have upgraded aws-java-sdk-s3 from v1.11.375 to 1.11.602. My code checkAwsS3() does no longer work. It seems impossible to catch the exceptions thrown by com.amazonaws.util.DateUtils.parseRFC822Date() etc.

My workaround is to NOT use v1.11.602.

Any suggestions welcome.
Michel

public static boolean checkAwsS3(final String signer, final String accessKeyID, final String secretAccessKey, final String host) {
        try {
            final ClientConfiguration clientConfiguration = new ClientConfiguration();
            final BasicAWSCredentials credentials = new BasicAWSCredentials(accessKeyID, secretAccessKey);

            if (signer.equals("v2")) {
                clientConfiguration.setSignerOverride("S3SignerType");//v2
            } else if (signer.equals("v4")) {
                clientConfiguration.setSignerOverride("AWSS3V4SignerType");//v4
            } else {
                LOG.error(String.format("signer %s not supported", signer));
                System.exit(Codes.AWS_SIGNER_ERROR);
            }
            clientConfiguration.setConnectionTimeout(3000);

            final AmazonS3 s3Client = AmazonS3ClientBuilder
                    .standard()
                    .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(host, Regions.DEFAULT_REGION.name()))
                    .withPathStyleAccessEnabled(true)
                    .withClientConfiguration(clientConfiguration)
                    .withCredentials(new AWSStaticCredentialsProvider(credentials))
                    .build();

            s3Client.listBuckets();

            return true;
        } catch (Exception ex) {
            LOG.error("AWS S3 check failed: " + ex.getMessage());
            return false;
        }
    }

10:04:45,440 INFO  Run:161 - using the client hosts default ssl configuration
10:04:45,445 WARN  Run:185 - SSL certificate checking was turned off
10:04:47,414 WARN  AmazonHttpClient:131 - SSL Certificate checking for endpoints has been explicitly disabled.
10:04:48,823 WARN  ClockSkewAdjuster:171 - Unable to parse clock skew offset from response: Mon, 16 Sep 2019 14:04:48 +0000
java.lang.IllegalArgumentException: Invalid format: "Mon, 16 Sep 2019 14:04:48 +0000" is malformed at " +0000"
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
	at com.amazonaws.util.DateUtils.parseRFC822Date(DateUtils.java:196)
	at com.amazonaws.retry.ClockSkewAdjuster.getServerDate(ClockSkewAdjuster.java:156)
	at com.amazonaws.retry.ClockSkewAdjuster.clientRequestWasSkewed(ClockSkewAdjuster.java:113)
	at com.amazonaws.retry.ClockSkewAdjuster.isAdjustmentRecommended(ClockSkewAdjuster.java:101)
	at com.amazonaws.retry.ClockSkewAdjuster.getAdjustment(ClockSkewAdjuster.java:78)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4921)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4867)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4861)
	at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:978)
	at com.amazonaws.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:984)
	at com.arcitecta.mfs3.S3.checkAws(S3.java:105)
	at com.arcitecta.mfs3.Run.main(Run.java:195)

**Comment by debora-ito** [comment]
Hi @xorinox, the stacktrace shows the problem is a parser error in the Date value in the response, that for some reason is in the wrong format. The expected format is something like `Mon, 16 Sep 2019 14:04:48 GMT` and not with the offset value +0000 like in `Mon, 16 Sep 2019 14:04:48 +0000`.

The Date value is obtained from the response you get after calling the service API, so it's not something that was changed in the SDK newer versions. Was there any other change in your environment at the same time? For example, are you behind a proxy?

**Comment by debora-ito** [comment]
Closing this due to inactivity. Feel free to reopen if you're still experiencing this issue.
