### ISSUE TITLE
AmazonDynamoDBException: The supplied Item contains a null AttributeValue

### ISSUE THREAD

**Issue by helloahau** [aws/aws-sdk-java#2103]
1. Test with below code line, got exception: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: The supplied Item contains a null AttributeValue 

2. save success if remove this line: listName.add("");

  @Test
  public void testError() {
    TestPojo testPojo= new TestPojo();
    testPojo.setKey(UUID.randomUUID().toString());
    testPojo.setName("");
    List<String> listName = new ArrayList();
    listName.add("name1");
    listName.add(null);
    listName.add("");
    testPojo.setListName(listName);

    new DynamoDBMapper(AmazonDynamoDBClientBuilder.defaultClient()).save(testPojo);
  }

  @DynamoDBTable(tableName = "Test")
  public class TestPojo {
    @DynamoDBHashKey
    private String key;
    private String name;
    private List<String> listName;

    public String getName() {
      return name;
    }

    public void setName(String name) {
      this.name = name;
    }

    public List<String> getListName() {
      return listName;
    }

    public void setListName(List<String> listName) {
      this.listName = listName;
    }

    public String getKey() {
      return key;
    }

    public void setKey(String key) {
      this.key = key;
    }
  }

3. exception details:
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: The supplied Item contains a null AttributeValue (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: JOHOGE0642CV9T7AG0KPV0E1ENVV4KQNSO5AEMVJF66Q9ASUAAJG)

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:4805)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4772)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeUpdateItem(AmazonDynamoDBClient.java:4476)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:4442)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.doUpdateItem(DynamoDBMapper.java:872)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$2.executeLowLevelRequest(DynamoDBMapper.java:612)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.execute(DynamoDBMapper.java:751)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.save(DynamoDBMapper.java:641)
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.save(AbstractDynamoDBMapper.java:123)

5. aws-java-sdk-dynamodb version  1.11.629

**Comment by debora-ito** [comment]
Hi @helloahau, DynamoDB does not support empty strings - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-attributes

**Comment by helloahau** [comment]
> Hi @helloahau, DynamoDB does not support empty strings - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-attributes

**Comment by helloahau** [comment]
1. Yes, the doc illustrate empty is not support, but the actual behavior is ignore empty string attribute, for the code line i posted before (testPojo.setName("");), DynamoDB just ignore the empty String without exception, save action will success. 

2. But for String List empty element(listName.add("");), DynamoDB throw AmazonDynamoDBException instead of just ignore the empty, and the save action will fail. 

3. Please check my posted code carefully. Why DynamoDB have diff behavior? I think this is can fixed issue.

**Comment by debora-ito** [comment]
Did a little investigation, and found out that `testPojo.setName("")` has a specific behavior in DynamoDBMapper when the field is a String, it deletes a previous value set in the Name field. E.g. if an item has a "Foo" Name value and you want to remove it, you can call `setName("")`.

That is different from `listName.add("")` which is trying to add an empty string value in a list field. This is not permitted.

**Comment by debora-ito** [comment]
Closing this, feel free to reopen if you have further questions.

**Comment by Anja05** [comment]
Hi @debora-ito 
I m facing the similar issue with the below exception details. I m trying to load the item by passing hash key and range key

Exception:

Caused by: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: null (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: null; Request ID: null; Proxy: proxy.bmwweb.consol.de)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[aws-java-sdk-core-1.11.825.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:1974) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1950) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.getItem(AmazonDynamoDBClient.java:1118) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:416) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:433) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.load(AbstractDynamoDBMapper.java:85) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
	at com.bmw.cc.serviced

2) My DynamoDb mapper configuration

public DynamoDBMapper dynamoDBMapper(final AwsDynamoDbConfiguration awsDynamoDbConfiguration) {
        final AmazonDynamoDBClientBuilder amazonDynamoDBClientBuilder = AmazonDynamoDBClientBuilder //
                .standard() //
                .withCredentials(new AWSStaticCredentialsProvider(
                        new BasicAWSCredentials(awsDynamoDbConfiguration.getAccessKeyId(),
                                awsDynamoDbConfiguration.getSecretAccessKey()))); //
        if (null != awsDynamoDbConfiguration.getEndpointOverride()) {
            amazonDynamoDBClientBuilder.withEndpointConfiguration(
                    new com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration(
                            awsDynamoDbConfiguration.getEndpointOverride().toString(),
                            awsDynamoDbConfiguration.getRegion())).build();
        } else {
            amazonDynamoDBClientBuilder.withRegion(awsDynamoDbConfiguration.getRegion());
        }

        return new DynamoDBMapper(amazonDynamoDBClientBuilder.build(), DynamoDBMapperConfig.builder()
                .withTableNameOverride(
                        new DynamoDBMapperConfig.TableNameOverride(awsDynamoDbConfiguration.getTableName())) //
                .withSaveBehavior(DynamoDBMapperConfig.SaveBehavior.UPDATE).build());
    }

3) the place where it throws exception

this.dynamoDBMapper.load(ServiceDemand.class, vin, cbsId);

Please suggest what could be the issue
