### ISSUE TITLE
Lambda S3 put object call give "socket is closed" error

### ISSUE THREAD

**Issue by Biswajit88** [aws/aws-sdk-java#2111]
Hi, I have a lambda which gets triggered on a s3 put object. What it does is, after it is triggered, it get some s3 objects does some business validation and put s3 object. 

It works well when there is no load in the system. But when I do load testing I am observing below stack trace very frequently when s3 put object.

I need to understand how lambda environment socket resource is used and why am I getting such error when in load testing.

Please note that I am already doing s3 TransferManager.shutdownNow(true) in a finally{} block after processing is done.

My lambda ARN is: "arn:aws:lambda:us-east-1:782406712095:function:perf-o-and-o-export-framework-DocumentAggregatorLambda"

Error logs:

```
[2019-09-18 10:20:07.847] perfnbcuni [] bf23767b-4147-4edc-adcd-c91d2196cf40 ERROR c.o.a.u.AWSConnector - perfnbcuniAvailsyS4vFo4MbhG9RFVt - DEFAULT_XLSX - AmazonClientException uploadFileToS3: DocumentGenerator/perfnbcuni/Avails/report/2019-09-18_10.06.39_*ABBOT LAB_*ACTION MEDIA GROUP,INC_Export_125products_284.XLSX
com.amazonaws.SdkClientException: Unable to execute HTTP request: Socket is closedr at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1163)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1109)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)r at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)r at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)r at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705)r at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652)r at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1807)r at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:131)r at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123)r at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143)r at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48)r at java.util.concurrent.FutureTask.run(FutureTask.java:266)r at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)r at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)r at java.lang.Thread.run(Thread.java:748)rCaused by: java.net.SocketException: Socket is closedr at java.net.Socket.setSoTimeout(Socket.java:1137)r at sun.security.ssl.BaseSSLSocketImpl.setSoTimeout(BaseSSLSocketImpl.java:633)r at sun.security.ssl.SSLSocketImpl.setSoTimeout(SSLSocketImpl.java:2556)r at com.amazonaws.internal.DelegateSSLSocket.setSoTimeout(DelegateSSLSocket.java:133)r at org.apache.http.impl.BHttpConnectionBase.fillInputBuffer(BHttpConnectionBase.java:346)r at org.apache.http.impl.BHttpConnectionBase.awaitInput(BHttpConnectionBase.java:354)r at org.apache.http.impl.DefaultBHttpClientConnection.isResponseAvailable(DefaultBHttpClientConnection.java:130)r at org.apache.http.impl.conn.CPoolProxy.isResponseAvailable(CPoolProxy.java:150)r at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:219)r at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)r at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)r at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)r at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)r at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)r at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)r at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)r at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1285)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)r ... 17 common frames omittedr
[2019-09-18 10:20:07.847] perfnbcuni [] bf23767b-4147-4edc-adcd-c91d2196cf40 ERROR c.o.a.l.DocumentAggregatorLambda - Error in executing lambda function :
com.operative.aws.exception.AWSException: AmazonClientException uploadFileToS3. error: Unable to execute HTTP request: Socket is closedr at com.operative.aws.util.AWSConnector.uploadFileToS3(AWSConnector.java:72)r at com.operative.aws.lambda.DocumentAggregatorLambda.lambda$handleRequest$0(DocumentAggregatorLambda.java:226)r at java.util.ArrayList.forEach(ArrayList.java:1257)r at com.operative.aws.lambda.DocumentAggregatorLambda.handleRequest(DocumentAggregatorLambda.java:63)r at com.operative.aws.lambda.DocumentAggregatorLambda.handleRequest(DocumentAggregatorLambda.java:52)r at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:178)r at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:888)r at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:293)r at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:64)r at java.lang.Class.forName0(Native Method)r at java.lang.Class.forName(Class.java:348)r at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:114)rCaused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Socket is closedr at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1163)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1109)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674)r at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656)r at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520)r at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705)r at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652)r at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1807)r at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:131)r at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123)r at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:143)r at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:48)r at java.util.concurrent.FutureTask.run(FutureTask.java:266)r at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)r at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)r at java.lang.Thread.run(Thread.java:748)rCaused by: java.net.SocketException: Socket is closedr at java.net.Socket.setSoTimeout(Socket.java:1137)r at sun.security.ssl.BaseSSLSocketImpl.setSoTimeout(BaseSSLSocketImpl.java:633)r at sun.security.ssl.SSLSocketImpl.setSoTimeout(SSLSocketImpl.java:2556)r at com.amazonaws.internal.DelegateSSLSocket.setSoTimeout(DelegateSSLSocket.java:133)r at org.apache.http.impl.BHttpConnectionBase.fillInputBuffer(BHttpConnectionBase.java:346)r at org.apache.http.impl.BHttpConnectionBase.awaitInput(BHttpConnectionBase.java:354)r at org.apache.http.impl.DefaultBHttpClientConnection.isResponseAvailable(DefaultBHttpClientConnection.java:130)r at org.apache.http.impl.conn.CPoolProxy.isResponseAvailable(CPoolProxy.java:150)r at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:219)r at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)r at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)r at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)r at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)r at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)r at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)r at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)r at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1285)r at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101)r ... 17 common frames omittedr
[2019-09-18 10:20:07.848] perfnbcuni [] bf23767b-4147-4edc-adcd-c91d2196cf40 WARN c.a.s.s.i.S3AbortableInputStream - Not all bytes were read from the S3ObjectInputStream, aborting HTTP connection. This is likely an error and may result in sub-optimal behavior. Request only the bytes you need via a ranged GET or drain the input stream after use.
```

**Comment by zoewangg** [comment]
The error logs indicate that the connection had been closed before all bytes were read from the `S3ObjectInputStream`.  

Can you share the code snippets of how you create and use transfermanager and s3client?

**Comment by debora-ito** [comment]
Closing due to inactivity. Feel free to reopen if you're still experiencing this issue.
