### ISSUE TITLE
 When I used multithreaded requests, the following stack appeared, as if it was always blocked. 

### ISSUE THREAD

**Issue by ZhuoSiChen** [aws/aws-sdk-java#2117]
The result is that the program TCP connection is always in close_wait state.

The vision of jdk is 1.11.442

```console “http-nio-127.0.0.1-9901-exec-75" - Thread t@199
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	- locked <530ca39> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	- locked <681c4338> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.services.sns.message.SignatureVerifier.downloadCert(SignatureVerifier.java:159)
	at com.amazonaws.services.sns.message.SignatureVerifier.downloadCertWithRetries(SignatureVerifier.java:121)
	at com.amazonaws.services.sns.message.SignatureVerifier.fetchPublicKey(SignatureVerifier.java:107)
	- locked <74cbcaec> (a com.amazonaws.services.sns.message.SignatureVerifier)
	at com.amazonaws.services.sns.message.SignatureVerifier.verifySignature(SignatureVerifier.java:91)
	at com.amazonaws.services.sns.message.SnsMessageManager.parseMessage(SnsMessageManager.java:93)

**Comment by debora-ito** [comment]
@ZhuoSiChen Can you provide a sample code we can use to reproduce?

**Comment by ZhuoSiChen** [comment]
Sorry, I can't provide demo.It just happen

**Comment by debora-ito** [comment]
Without a reproducible code is hard for us to understand what your code is trying to do and to help finding the cause of the problem. 

Please reopen this if you have a code sample.
