### ISSUE TITLE
amazonRedshiftClient.describeClusters() throws exception for some regions even though the regions are supported by the service.

### ISSUE THREAD

**Issue by shira-bendor** [aws/aws-sdk-java#2119]
SDK version: 1.11.603

I'm writing a function that iterates over all of the supported regions (using RegionUtils.getRegionsForService(AmazonRedshift.ENDPOINT_PREFIX)

And for most of the regions it returns a normal response with the clusters (or empty list if I don't have clusters in that region) but for 6 regions is throws this exception below.

The failing regions are:
me-south-1,
us-gov-east-1,
ap-east-1,
cn-north-1,
us-gov-west-1,
cn-northwest-1

Is this the expected behavior?

com.amazonaws.services.redshift.model.AmazonRedshiftException: The security token included in the request is invalid. (Service: AmazonRedshift; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: a3461303-eb45-11e9-9559-4100a7786604)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.redshift.AmazonRedshiftClient.doInvoke(AmazonRedshiftClient.java:6053)
	at com.amazonaws.services.redshift.AmazonRedshiftClient.invoke(AmazonRedshiftClient.java:6020)
	at com.amazonaws.services.redshift.AmazonRedshiftClient.invoke(AmazonRedshiftClient.java:6009)
	at com.amazonaws.services.redshift.AmazonRedshiftClient.executeDescribeClusters(AmazonRedshiftClient.java:3078)
	at com.amazonaws.services.redshift.AmazonRedshiftClient.describeClusters(AmazonRedshiftClient.java:3049)
	at com.amazonaws.services.redshift.AmazonRedshiftClient.describeClusters(AmazonRedshiftClient.java:3090)

**Comment by debora-ito** [comment]
Hi @shira-bendor, this is the expected behavior.

The `RegionUtils.getRegionsForService()` method returns all regions supported by a service. In this case, Redshift is available in, among other regions, US GovClouds (us-gov-east-1, us-gov-west-1), China (cn-northwest-1, cn-north-1), Hong Kong (ap-east-1) and Bahrain (me-south-1), which are regions that are disabled by default or that require a special account for you to access. That's why you're seeing the exception when using this regions.

**Comment by debora-ito** [comment]
Closing. Feel free to reopen if you have any more questions.
