### ISSUE TITLE
AmazonSNSClientBuilder throws java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier;

### ISSUE THREAD

**Issue by mores** [aws/aws-sdk-java#2127]
using implementation 'com.amazonaws:aws-java-sdk-sns:1.11.654'
compileSdkVersion 28

AllowAllHostnameVerifier was deprecated in level 22
https://developer.android.com/reference/org/apache/http/conn/ssl/AllowAllHostnameVerifier

Stack Trace:
java.lang.NoSuchFieldError: No field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
        at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.getPreferredSocketFactory(ApacheConnectionManagerFactory.java:89)
        at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:66)
        at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:59)
        at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:50)
        at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38)
        at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:324)
        at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:308)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:237)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:223)
        at com.amazonaws.services.sns.AmazonSNSClient.<init>(AmazonSNSClient.java:272)
        at com.amazonaws.services.sns.AmazonSNSClient.<init>(AmazonSNSClient.java:258)
        at com.amazonaws.services.sns.AmazonSNSClientBuilder.build(AmazonSNSClientBuilder.java:61)
        at com.amazonaws.services.sns.AmazonSNSClientBuilder.build(AmazonSNSClientBuilder.java:27)
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)

**Comment by mores** [comment]
Same as https://github.com/aws/aws-sdk-java-v2/issues/1180

**Comment by debora-ito** [comment]
@mores have you tried the [AWS SDK for Android](https://github.com/aws-amplify/aws-sdk-android/issues)? We cannot assure this SDK for Java will work in Android environments.

**Comment by mores** [comment]
Could you make an update to https://github.com/aws/aws-sdk-java/blob/master/README.md
"If you are looking for the AWS SDK for Android source go here: https://github.com/aws-amplify/aws-sdk-android" ?

**Comment by debora-ito** [comment]
Will do. I'll go ahead and close this, feel free to reopen if you have any more questions.
