### ISSUE TITLE
Cannot send SDK metrics to Cloudwatch VPC endpoint

### ISSUE THREAD

**Issue by ryanhall07** [aws/aws-sdk-java#2137]
My team would like to send metrics from the aws-sdk running in our on-prem DC to AWS CloudWatch using the VPC endpoint in our Account. It appears that the `MetricUploaderThread` does not support this since it uses the Deprecated `AmazonWebServiceClient#setEndpoint`

https://github.com/aws/aws-sdk-java/blob/7bf0fbec42de8a7d54875510f27fb363ca2d19f5/aws-java-sdk-cloudwatchmetrics/src/main/java/com/amazonaws/metrics/internal/cloudwatch/MetricUploaderThread.java#L74

https://github.com/aws/aws-sdk-java/blob/f59a8902bb171e216c3b68c278e18e60f3b53741/aws-java-sdk-core/src/main/java/com/amazonaws/AmazonWebServiceClient.java#L313

I tried just setting the `String endpoint` to my account vpc endpoint `vpce-[redacted].monitoring.us-west-2.vpce.amazonaws.com`, and I get the following error

```
java-sdk-metric-uploader Unexpected condition; soldier on
com.amazonaws.services.cloudwatch.model.AmazonCloudWatchException: Credential should be scoped to a valid region, not 'vpce'. (Service: AmazonCloudWatch; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 4f374df0-08bf-4283-a9b1-bd586a3a810f)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:2027)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:1994)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:1983)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.executePutMetricData(AmazonCloudWatchClient.java:1754)
	at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.putMetricData(AmazonCloudWatchClient.java:1726)
	at com.amazonaws.metrics.internal.cloudwatch.MetricUploaderThread.run(MetricUploaderThread.java:87)
```

I'm hoping it's as simple as setting an `EndpointConfiguration` in the `CloudWatchMetricConfig` and passing that to the `AmazonCloudWatchClient`

**Comment by zoewangg** [comment]
Hi @ryanhall07  thank you for reporting the issue! We will work on the fix.

**Comment by zoewangg** [comment]
We have added `endpointConfiguration` in `CloudWatchMetricConfig` to allow customers to provide both endpoint and region and it's available in the latest SDK. 

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111700-2020-01-02
