### ISSUE TITLE
Discrepancy while generating AWS s3 presigned url's

### ISSUE THREAD

**Issue by suman-jv** [aws/aws-sdk-java#2138]
We are seeing couple issues on our Photopass Prod application.
Our services basically generates the pre-signed urls..
Issue # 1 : We observed that our services on lower environments (STAGE) are using V2 signing and on PROD they are using sigV4.
Our artifacts are same across the board, Java AWS SDK versions are same as well so not sure what's forcing V4 on Prod Vs V2 on Stage 

Issue # 2:
As mentioned above, because V4 is being used on PROD, starting last Sunday i.e. 10/27 we see our requests started failing with error 
for eg:
" com.amazonaws.SdkClientException: Requests that are pre-signed by SigV4 algorithm are valid for at most 7 days. The expiration date set on the current request [20191107T192437Z] has exceeded this limit"  

We did some local tests with the same artifacts and noticed that the time we are passing to AWS Java sdk in in EASTERN Timezone and sdk converts that to validate the duration and as part of conversion and because of DST window the UTC converted time for the EASTERN time passed by application is converting to 7days+1Hour resulting in failing as it exceeded 7days which is the max limit for V4 signing.

Below is the example console output as part of our local tests:

Expiry time being passed :Thu Nov 07 14:24:37 EST 2019
Exception in thread "main" com.amazonaws.SdkClientException: Requests that are pre-signed by SigV4 algorithm are valid for at most 7 days. The expiration date set on the current request [20191107T192437Z] has exceeded this limit.
	at com.amazonaws.auth.AWS4Signer.generateExpirationDate(AWS4Signer.java:614)
	at com.amazonaws.auth.AWS4Signer.presignRequest(AWS4Signer.java:269)
	at com.amazonaws.services.s3.AmazonS3Client.generatePresignedUrl(AmazonS3Client.java:2977)

20191107T192437Z is the UTC converted time and 
   difference between Thu Oct 31 14:24:37 EDT 2019 and Thu Nov 07 14:24:37 EST 2019 is 7Days 
   difference between Thu Oct 31 14:24:37 EDT 2019 and 20191107T192437Z is 7Days + 1hour ==> and this is what causing failure.

Java AWS SDK versions we are using is : 1.11.115 (we also tried with 1.11.264) both shows the same behavior.

**Comment by bmaizels** [comment]
@suman-jv Hi there, we believe the issue you are seeing with the 7 days + 1 hour was due to you adding 7 calendar days to a Calendar object over the daylight savings adjustment period (thus an extra hour was being added to the duration by your own code). I recommend using Instant or some other zoneless time representation to make the 7 day calculation.

**Comment by bmaizels** [comment]
@suman-jv Hi there, I examined the SDK code, and it looks like whatever Date is passed to us is converted into milliseconds since epoch and then from that the current time also converted to milliseconds since epoch is subtracted. The difference between those two times is then used to determine whether the 7 day limit has been exceeded. This should be resilient to zone skew (due to the conversion to epoch), unless you are actually passing in a zoned time that is more than 7 days in the future. This could easily happen depending on how your code is actually written during the daylight savings adjustment window. For instance if you take a calendar object and then add 7 days to it over that window, you will actually end up adding 7 days and one hour of actual time.

**Comment by suman-jv** [comment]
thanks @bmaizels  I did a quick check and with just passing the seconds, I see expected behavior while with calendar days + 7 is considering the extra hour before DST and hence it's failing. 

Do you have any update on Issue #1 ? I'm curious to see whey the same service is showing different behavior ?
Also I did a check with my colleague and I see the same, i.e. same java-aws-SDK version is generating V2 persigned URL' s on my machine (I'm using Mac) while on my colleagues PC (windows) it's generating with sigV4. I don't think OS here is the the one that's causing to flip as our OS's are for applications deployed on lower environments vs Production.

**Comment by bmaizels** [comment]
@suman-jv Without deep-diving into your environment and code there are two factors off the top of my head that could likely influence this behavior, region and duration. If the region is unknown the presigner will use sigV2. It's possible the duration could affect it too as we know that Sigv4 doesn't support more than 7 days out. Could you verify your region configuration on the client and see if that might be it.

**Comment by debora-ito** [comment]
@suman-jv do you have any new findings?

**Comment by debora-ito** [comment]
Closing due to inactivity. Feel free to reopen if you have more questions.
