### ISSUE TITLE
Unable to unmarshall response (weblogic.xml.jaxp.RegistryXMLInputFactory cannot be cast to javax.xml.stream.XMLInputFactory)

### ISSUE THREAD

**Issue by SuhasKaranth** [aws/aws-sdk-java#2159]
While sending and receiving message via SQS using AWS SDK in a weblogic container (12.1.3), I am getting the below issue when the SDK is trying to parse the response XML from AWS.

I am using the SDK version as below:

```
 compile group: 'com.amazonaws', name: 'aws-java-sdk', version: '1.11.679'
 compile group: 'com.amazonaws', name: 'aws-java-sdk-sqs', version: '1.11.679'
```
```
AmazonClientException::
com.amazonaws.SdkClientException: Unable to unmarshall response (weblogic.xml.jaxp.RegistryXMLInputFactory cannot be cast to javax.xml.stream.XMLInputFactory). Response Code: 200, Response Text: OK
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1651)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1336)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2215)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2182)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2171)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeSendMessage(AmazonSQSClient.java:1742)
	at com.amazonaws.services.sqs.AmazonSQSClient.sendMessage(AmazonSQSClient.java:1715)
```

**Comment by KaibaLopez** [comment]
Hi @SuhasKaranth ,
Could you provide a code snippet of what  you're trying to do?  That way I can try and reproduce the error.

**Comment by SuhasKaranth** [comment]
Hi @KaibaLopez ,

Here is the code I am using to send message to the SQS queue. This same code works on a Spring boot project hosted on tomcat but on Weblogic server, I am getting the above error.

```
public void sendMessage(final String message) {

		try {
			AmazonSQSClientBuilder builder = AmazonSQSClientBuilder.standard();
			final AmazonSQS sqs = builder.withClientConfiguration(
					PredefinedClientConfigurations.defaultConfig()
							.withProxyHost("web-proxy.corp.hp.com")
							.withProxyPort(8080)
							.withNonProxyHosts("no proxy hosts"))
					.build();
			String messageJSON = "{\n" +
					"\t\"transactionID\":\"" + message + "\"\n" +
					"}";

			SendMessageResult result = sqs.sendMessage(new SendMessageRequest(orderQueueUrl, messageJSON));

			log.info("result.getMessageId():{}" + result.getMessageId());

		} catch (final AmazonServiceException ase) {
			log.error("Error Message:    " + ase.getMessage());
		} catch (final AmazonClientException ace) {
			log.error("Error Message: " + ace.getMessage());
		}
	}
```

**Comment by SuhasKaranth** [comment]
I added the below in the jvm args :

`
-Djavax.xml.stream.XMLInputFactory=com.sun.xml.internal.stream.XMLInputFactoryImpl
`

now I am getting the below error : 

```
com.amazonaws.SdkClientException: Unable to unmarshall response (com.sun.xml.internal.stream.XMLInputFactoryImpl cannot be cast to javax.xml.stream.XMLInputFactory). Response Code: 200, Response Text: OK
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1651)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1336)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2215)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2182)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2171)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeSendMessage(AmazonSQSClient.java:1742)
	at com.amazonaws.services.sqs.AmazonSQSClient.sendMessage(AmazonSQSClient.java:1715)
```
even though com.sun.xml.internal.stream.XMLInputFactoryImpl extends XMLInputFactory and provides implementation.

**Comment by debora-ito** [comment]
@SuhasKaranth apologies for the super long silence here. Are you still experiencing this issue?
If so please reply with a comment and I'll investigate.
