### ISSUE TITLE
Get object request not allow a key with "=" 

### ISSUE THREAD

**Issue by adam-lin-dragon** [aws/aws-sdk-java#2160]
![image](https://user-images.githubusercontent.com/49673917/69608595-c23f7700-1062-11ea-80f8-77bd819cb72e.png)
We got object under folder like this, but the object key in getObject/getObjectRequest does not accept "=" or its URI equivalent "%3D"

**Comment by KaibaLopez** [comment]
Hi @adam-lin-dragon ,
I was not able to reproduce your error, the call : 
`object = s3.getObject(new GetObjectRequest(bucket_name,"year=2019/month=11/day=27"));`
works for me.
Can you provide a code snippet of what you're trying to do and what error are you getting?

**Comment by Debiao-Su-dragon** [comment]
![image](https://user-images.githubusercontent.com/49930250/69774473-fd5fb880-11d0-11ea-90ea-dfb9c2033bac.png)

I upload file to s3 bucket with this function, when input parameter remoteFileName = "CustomerSnapshot/year%3D19/month%3D11/day%3D27/fileName.dat"

**Comment by adam-lin-dragon** [comment]
@KaibaLopez Debiao and I are working together. We are using kotlin instead of Java, but since kotlin can invoke java sdk directly, I think it should not be an issue.

**Comment by adam-lin-dragon** [comment]
@KaibaLopez Here is a summary.

Here is our code snippet
![image](https://user-images.githubusercontent.com/49673917/69860908-29af2e00-12d2-11ea-98bf-43633c7ad1ca.png)

The key I use "CustomerSnapshot/year=2019/month=11/day=25/GNS_Periodic_TextData.json"

error:
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: BC3B2D05A8C18579)
, S3 Extended Request ID: lAnSqmg0Eokx5p0ndy+QxEgd/DZWwj1EiVJYa4IS9JxqYu548/5Gs30l46NO4M27TjZblfgCQdw=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1305)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:852)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:318)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3787)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1137)
	at com.amazonaws.services.s3.AmazonS3Client$3.getS3ObjectStream(AmazonS3Client.java:1218)
	at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:388)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1214)
	at com.projectdrgn.periodicgnsgateway.utility.aws.AwsClient.downFromS3(AwsClient.kt:111)
	at com.projectdrgn.periodicgnsgateway.utility.AWSClientTest.downFromS3Test(AWSClientTest.kt:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)



If use %3D instead of =, then error is key not found

**Comment by adam-lin-dragon** [comment]
@KaibaLopez May i know what version you are using. We are using 1.11.5. I saw post like https://github.com/aws/aws-sdk-java/issues/1919 , not sure whether they are related

**Comment by KaibaLopez** [comment]
Hi @adam-lin-dragon,
sorry for the late responses, I tested on version 1.11.678, so yea, it may be related to that issue, could you try a newer version??

**Comment by debora-ito** [comment]
Hi @adam-lin-dragon, the issue is probably related to #1919. Please check the version of Apache `httpclient` you are using: 

For SDK versions < 1.11.596 you need to use `httpclient-4.4.5` or `httpclient-4.5.6`. 
For SDK versions >= 1.11.596 you can use `httpclient-4.5.8` or newer.

**Comment by adam-lin-dragon** [comment]
@debora-ito Thanks. We fixed it with httpclient-4.5.8 before. But forgot to update this ticket.
