### ISSUE TITLE
Managing API Gateway through Java Lambda function

### ISSUE THREAD

**Issue by Bauxite-camcom** [aws/aws-sdk-java#2162]
HI,

I have a lambda function that is accessed through the API Gateway in response to a REST request (from our portal), to create a new client. In it I am trying to create, and obtain an API Key (x-api-key) that is unique for that client, and attach it to a number of pre-existing Usage plans. 

Also, if the client is a member of a "group" that shares an API Key, I want to assign a known API Key to the client (and not create a new one), and thus retrieve an existing API Key.

The Lambda is written in java.

At t his stage I am having trouble even creating the AmazonApiGateway Object.

`AmazonApiGateway client = AmazonApiGatewayClientBuilder.standard().withRegion(Regions.AP_SOUTHEAST_1).build();`

When I execute this call it throws an exception:
`Implementing class: java.lang.IncompatibleClassChangeError
java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at biz.camcom.wasp.function.merchant.PutMerchant.getApiKey(PutMerchant.java:148)`

Within the same Lambda function I can access DynamoDB without any problems.

`this.dynamoDBClient = AmazonDynamoDBClientBuilder.standard().build();`

Thanks for your assistance.

**Comment by Bauxite-camcom** [comment]
Additionally, when I perform 
`mvn clean install`

I see 
` error: cannot find symbol 
  symbol:   class CreateApiKeyInput
  location: package com.amazonaws.services.apigateway.model`

**Comment by debora-ito** [comment]
Hi @Bauxite-camcom, the `IncompatibleClassChangeError` is thrown when an incompatible class change has occurred to some class definition. The definition of some class, on which the currently executing method depends, has since changed.

Check for mismatch versions of `PutMerchant` class in your deployment package. This StackOverflow question also offers a good explanation on the problem: https://stackoverflow.com/questions/1980452/what-causes-java-lang-incompatibleclasschangeerror

**Comment by debora-ito** [comment]
Closing due to inactivity. Feel free to reopen if you have more questions.
