### ISSUE TITLE
ClientConfiguration should ignore empty proxy env variables

### ISSUE THREAD

**Issue by pedrolauro** [aws/aws-sdk-java#2176]
Although my proxy env variables are all set to empty, SDK keeps trying to parse that:

```
[WARN ] 2019-12-10 12:11:11.068-0200 [restartedMain] ClientConfiguration - Unable to parse HTTPS_PROXY environment variable value '' as URL. It is malformed.
java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:593) ~[?:1.8.0_191]
	at java.net.URL.<init>(URL.java:490) ~[?:1.8.0_191]
	at java.net.URL.<init>(URL.java:439) ~[?:1.8.0_191]
	at com.amazonaws.ClientConfiguration.getUrlEnvVar(ClientConfiguration.java:2449) ~[aws-java-sdk-core-1.11.688.jar:?]
	at com.amazonaws.ClientConfiguration.getHttpProxyEnvironmentVariable(ClientConfiguration.java:2440) ~[aws-java-sdk-core-1.11.688.jar:?]
	at com.amazonaws.ClientConfiguration.getProxyHostEnvironment(ClientConfiguration.java:700) ~[aws-java-sdk-core-1.11.688.jar:?]
	at com.amazonaws.ClientConfiguration.getProxyHost(ClientConfiguration.java:728) ~[aws-java-sdk-core-1.11.688.jar:?]
	at com.amazonaws.http.settings.HttpClientSettings.getProxyHost(HttpClientSettings.java:84) ~[aws-java-sdk-core-1.11.688.jar:?]
	at com.amazonaws.http.settings.HttpClientSettings.isProxyEnabled(HttpClientSettings.java:176) ~[aws-java-sdk-core-1.11.688.jar:?]
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.addProxyConfig(ApacheHttpClientFactory.java:88) ~[aws-java-sdk-core-1.11.688.jar:?]

...
```

My suggestion is to change method `ClientConfiguration.getUrlEnvVar` to check not only for null values, but also for empty ones:

```
package com.amazonaws;
...
public class ClientConfiguration {
....

private URL getUrlEnvVar(AtomicReference<URLHolder> cache, String name) {
        if (cache.get() == null) {
            URLHolder holder = new URLHolder();
            String value = getEnvironmentVariableCaseInsensitive(name);
            // if (value != null) { -- old version
            if (value != null && !value.trim().isEmpty()) { // new one
                try {
                    holder.url = new URL(value);
                } catch (MalformedURLException e) {
                    if (log.isWarnEnabled()) {
                        log.warn(String.format("Unable to parse %s environment variable value '%s' as URL. It is " +
                                "malformed.", name, value), e);
                    }
                }
            }
            cache.compareAndSet(null, holder);
        }
        return cache.get().url;
    }
....
}
```

Or even parse that condition on the `getEnvironmentVariable` method:

```
package com.amazonaws;
...
public class ClientConfiguration {
....
    private String getEnvironmentVariable(String environmentVariable) {
         String value = System.getenv(environmentVariable);
          return value != null && !value.trim().isEmpty() ? value : null;
    }
...
}
```

**Comment by KaibaLopez** [comment]
Hi @pedrolauro,
thanks for pointing this out, sounds reasonable to check for empty values... could you make a PR with these changes?

**Comment by pedrolauro** [comment]
@KaibaLopez Sure!
