### ISSUE TITLE
 private.com.amazonaws.services.datapipeline.poller.PollWorker: Poller threw exception private.com.amazonaws.AmazonClientException: Unable to execute HTTP request: connect timed out

### ISSUE THREAD

**Issue by rupeshpanneer** [aws/aws-sdk-java#2181]
When I am trying to start taskrunner using proxy I am getting the below error when I submit jobs in the datapipeline.

18 Dec 2019 12:31:19,647 [ERROR] (TaskRunnerService-testworkgroup-0)  private.com.amazonaws.services.datapipeline.poller.PollWorker: Poller threw exception
private.com.amazonaws.AmazonClientException: Unable to execute HTTP request: connect timed out
        at private.com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:620)
        at private.com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:378)
        at private.com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:340)
        at private.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:289)
        at private.com.amazonaws.services.datapipeline.DataPipelineClient.doInvoke(DataPipelineClient.java:1547)
        at private.com.amazonaws.services.datapipeline.DataPipelineClient.invoke(DataPipelineClient.java:1517)
        at private.com.amazonaws.services.datapipeline.DataPipelineClient.pollForTask(DataPipelineClient.java:963)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at private.com.amazonaws.services.datapipeline.retrier.RetryProxy.invokeInternal(RetryProxy.java:36)
        at private.com.amazonaws.services.datapipeline.retrier.RetryProxy.invoke(RetryProxy.java:48)
        at com.sun.proxy.$Proxy32.pollForTask(Unknown Source)
        at amazonaws.datapipeline.client.DataPipelineWsClientImpl.pollForTask(DataPipelineWsClientImpl.java:49)
        at amazonaws.datapipeline.taskrunner.TaskPoller.poll(TaskPoller.java:73)
        at amazonaws.datapipeline.taskrunner.TaskRunnerService$TaskRunnerPoller.actualPoll(TaskRunnerService.java:25)
        at private.com.amazonaws.services.datapipeline.poller.IntervalPoller.poll(IntervalPoller.java:23)
        at private.com.amazonaws.services.datapipeline.poller.PollWorker.pollForWork(PollWorker.java:87)
        at private.com.amazonaws.services.datapipeline.poller.PollWorker.run(PollWorker.java:51)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:542)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
        at private.com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:135)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:885)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at private.com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:839)
        at private.com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:609)

**Comment by debora-ito** [comment]
@rupeshpanneer apologies for the long silence here.

Are you passing the proxy server settings to the Data Pipeline client?
Can you call other operations behind the proxy? 

I'm trying to isolate the cause, if it is an environment configuration problem or a network problem...

**Comment by rupeshpanneer** [comment]
@debora-ito yes we use proxy settings in the bashrc and we are trying to communicate all other services via proxy, And I can say "Yes" all other services works fine with the proxy settings and I tried launching in NAT it works well but I am not supposed to open my EMR public facing..

**Comment by debora-ito** [comment]
If you are able to call other APIs using the DataPipeline client, this is probably a networking issue.

Also found this in the PollForTask [API reference](https://docs.aws.amazon.com/datapipeline/latest/APIReference/API_PollForTask.html):

> If tasks are ready in the work queue, PollForTask returns a response immediately. If no tasks are available in the queue, PollForTask uses long-polling and holds on to a poll connection for up to a 90 seconds, during which time the first newly scheduled task is handed to the task runner. To accomodate this, set the socket timeout in your task runner to 90 seconds. The task runner should not call PollForTask again on the same workerGroup until it receives a response, and this can take up to 90 seconds. 

Is it possible that there are no tasks in the queue?

**Comment by debora-ito** [comment]
Closing this due to no response, feel free to reopen if problem persists.
