### ISSUE TITLE
org.xml.sax.driver getting this exception. What is the fix? 

### ISSUE THREAD

**Issue by anishpr9** [aws/aws-sdk-java#2184]
om.amazonaws.SdkClientException: Couldn't initialize a SAX driver to create an XMLReader
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:123) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.services.s3.model.transform.Unmarshallers$BucketLoggingConfigurationnmarshaller.unmarshall(Unmarshallers.java:167) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.services.s3.model.transform.Unmarshallers$BucketLoggingConfigurationnmarshaller.unmarshall(Unmarshallers.java:164) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:31) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:70) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1610) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1319) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1101) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:758) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:732) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:714) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:674) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:656) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:520) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4705) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4652) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4646) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]

Caused by: org.xml.sax.SAXException: Can't create default XMLReader; is system property org.xml.sax.driver set?
	at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(Unknown Source) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:1.8.0_222]
	at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.<init>(XmlResponsesSaxParser.java:120) ~[blob_p-65d489eaa5db2f66b59973f0472bec32cf1c689d-d277f75fb4db0e4e5a2e7bde9bd7bdda:?]
	... 29 more

**Comment by debora-ito** [comment]
Hi @anishpr9, there are some issues reporting the same error (#1622, #1588) and their analysis suggest it may be due to having different, conflicting XMLReader classes in the classpath.

Do you think this might be the case?

**Comment by debora-ito** [comment]
Closing due to inactivity. Feel free to reopen if you have more questions.
