### ISSUE TITLE
 cdk init app --language  java does not work

### ISSUE THREAD

**Issue by abhinav-jain09** [aws/aws-sdk-java#2199]
I just did cdk init app --langauge java and gives me following error

```
cdk init app --language  java
Applying project template app for java
Executing mvn package...
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< com.myorg:content-api-lambda-cdk >------------------
[INFO] Building content-api-lambda-cdk 0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ content-api-lambda-cdk ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/abhinav/development/workspace/content-api-lambda-cdk/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ content-api-lambda-cdk ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/abhinav/development/workspace/content-api-lambda-cdk/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ content-api-lambda-cdk ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/abhinav/development/workspace/content-api-lambda-cdk/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ content-api-lambda-cdk ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/abhinav/development/workspace/content-api-lambda-cdk/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ content-api-lambda-cdk ---
[INFO] Surefire report directory: /Users/abhinav/development/workspace/content-api-lambda-cdk/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.myorg.ContentApiLambdaCdkTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.615 sec <<< FAILURE!
testStack(com.myorg.ContentApiLambdaCdkTest)  Time elapsed: 0.458 sec  <<< ERROR!
software.amazon.jsii.JsiiException: Child process exited unexpectedly: internal/fs/utils.js:229
            throw err;
            ^
        
        Error: EAGAIN: resource temporarily unavailable, read
            at Object.readSync (fs.js:532:3)
            at SyncStdio.readLine (/private/var/folders/gj/tkpbbh1101v2_f5_3zpcql2h0000gp/T/jsii-java-runtime5901543068906257364/jsii-runtime.js:13350:25)
            at InputOutput.read (/private/var/folders/gj/tkpbbh1101v2_f5_3zpcql2h0000gp/T/jsii-java-runtime5901543068906257364/jsii-runtime.js:13300:34)
            at KernelHost.run (/private/var/folders/gj/tkpbbh1101v2_f5_3zpcql2h0000gp/T/jsii-java-runtime5901543068906257364/jsii-runtime.js:7231:32)
            at Immediate.<anonymous> (/private/var/folders/gj/tkpbbh1101v2_f5_3zpcql2h0000gp/T/jsii-java-runtime5901543068906257364/jsii-runtime.js:7239:37)
            at processImmediate (internal/timers.js:445:21) {
          errno: -35,
          syscall: 'read',
          code: 'EAGAIN'
        }
        at software.amazon.jsii.JsiiRuntime.readNextResponse(JsiiRuntime.java:272)
        at software.amazon.jsii.JsiiRuntime.requestResponse(JsiiRuntime.java:80)
        at software.amazon.jsii.JsiiClient.createObject(JsiiClient.java:82)
        at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:510)
        at software.amazon.awscdk.core.App.<init>(App.java:46)
        at com.myorg.ContentApiLambdaCdkTest.testStack(ContentApiLambdaCdkTest.java:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error: 
  testStack(com.myorg.ContentApiLambdaCdkTest): Child process exited unexpectedly: internal/fs/utils.js:229(..)

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.998 s
[INFO] Finished at: 2020-01-10T14:13:10+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project content-api-lambda-cdk: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/abhinav/development/workspace/content-api-lambda-cdk/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
mvn exited with status 1
```

**Comment by debora-ito** [comment]
@abhinav-jain09 please open an issue in the CDK repository: https://github.com/aws/aws-cdk/

Again, the `aws/aws-sdk-java` repository is for issues relating to the [AWS SDK for Java](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/welcome.html). The CDK is a different project maintained in its own repo.
