### ISSUE TITLE
AbortedException in SDK aws-sdk-java

### ISSUE THREAD

**Issue by RaulSimoes** [aws/aws-sdk-java#2201]
I generated a SKD through API Gateway and it woks well, but sometimes, for same inputs of data a exception is throws:

jjan 07, 2020 5:52:24 PM com.amazonaws.http.AmazonHttpClient$RequestExecutor closeQuietlyForRuntimeExceptions
ADVERTÊNCIA: Unable to close closeable
com.amazonaws.AbortedException: 
	at com.amazonaws.internal.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:53)
	at com.amazonaws.internal.SdkFilterInputStream.close(SdkFilterInputStream.java:100)
	at com.amazonaws.event.ProgressInputStream.close(ProgressInputStream.java:211)
	at com.amazonaws.util.IOUtils.closeQuietly(IOUtils.java:70)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.closeQuietlyForRuntimeExceptions(AmazonHttpClient.java:767)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:760)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.client.ClientHandlerImpl.doInvoke(ClientHandlerImpl.java:204)
	at com.amazonaws.client.ClientHandlerImpl.invoke(ClientHandlerImpl.java:185)
	at com.amazonaws.client.ClientHandlerImpl.execute(ClientHandlerImpl.java:93)
	at com.amazonaws.opensdk.protect.client.SdkClientHandler.execute(SdkClientHandler.java:42)
	at br.com.teste.aws.nuvem.BibliotecaAWSBootloaderClient.postFirmware(BibliotecaAWSBootloaderClient.java:83)
	at br.com.teste.protocoloBootloader.nuvem.AWSApiGateway.getResultByPostInputBody(AWSApiGateway.java:69)
	at br.com.teste.protocoloBootloader.ProtocoloBootloader.conectarNuvem(ProtocoloBootloader.java:167)
	at br.com.teste.protocoloBootloader.ProtocoloBootloader.iniciarProtocolo(ProtocoloBootloader.java:150)
	at br.com.teste.programadorLinhaMonitorada.bootloader.Bootloader.configurar(Bootloader.java:98)
	at br.com.teste.programadorLinhaMonitorada.bootloader.Bootloader.<init>(Bootloader.java:67)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.ComunicacaoService.configurarProtocoloBootloader(ComunicacaoService.java:141)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.Active20UltraComunicacaoService.processarComandoLogar(Active20UltraComunicacaoService.java:438)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.Active20UltraComunicacaoService.processarMensagem(Active20UltraComunicacaoService.java:189)
	at br.com.teste.programadorLinhaMonitorada.model.comunicacao.Comunicacao.update(Comunicacao.java:154)
	at br.com.teste.programadorLinhaMonitorada.model.comunicacao.Serial.notifyObservers(Serial.java:230)
	at br.com.teste.programadorLinhaMonitorada.model.ThreadTratarMensagemRecebida.run(ThreadTratarMensagemRecebida.java:27)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

jan 07, 2020 5:52:24 PM br.com.teste.protocoloBootloader.ProtocoloBootloader conectarNuvem
GRAVE: null
com.amazonaws.AbortedException: 
	at com.amazonaws.internal.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:53)
	at com.amazonaws.internal.SdkFilterInputStream.markSupported(SdkFilterInputStream.java:117)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1026)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.client.ClientHandlerImpl.doInvoke(ClientHandlerImpl.java:204)
	at com.amazonaws.client.ClientHandlerImpl.invoke(ClientHandlerImpl.java:185)
	at com.amazonaws.client.ClientHandlerImpl.execute(ClientHandlerImpl.java:93)
	at com.amazonaws.opensdk.protect.client.SdkClientHandler.execute(SdkClientHandler.java:42)
	at br.com.teste.aws.nuvem.BibliotecaAWSBootloaderClient.postFirmware(BibliotecaAWSBootloaderClient.java:83)
	at br.com.teste.protocoloBootloader.nuvem.AWSApiGateway.getResultByPostInputBody(AWSApiGateway.java:69)
	at br.com.teste.protocoloBootloader.ProtocoloBootloader.conectarNuvem(ProtocoloBootloader.java:167)
	at br.com.teste.protocoloBootloader.ProtocoloBootloader.iniciarProtocolo(ProtocoloBootloader.java:150)
	at br.com.teste.programadorLinhaMonitorada.bootloader.Bootloader.configurar(Bootloader.java:98)
	at br.com.teste.programadorLinhaMonitorada.bootloader.Bootloader.<init>(Bootloader.java:67)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.ComunicacaoService.configurarProtocoloBootloader(ComunicacaoService.java:141)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.Active20UltraComunicacaoService.processarComandoLogar(Active20UltraComunicacaoService.java:438)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.Active20UltraComunicacaoService.processarMensagem(Active20UltraComunicacaoService.java:189)
	at br.com.teste.programadorLinhaMonitorada.model.comunicacao.Comunicacao.update(Comunicacao.java:154)
	at br.com.teste.programadorLinhaMonitorada.model.comunicacao.Serial.notifyObservers(Serial.java:230)
	at br.com.teste.programadorLinhaMonitorada.model.ThreadTratarMensagemRecebida.run(ThreadTratarMensagemRecebida.java:27)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

jan 07, 2020 5:52:24 PM br.com.teste.programadorLinhaMonitorada.bootloader.Bootloader exception
GRAVE: null
com.amazonaws.AbortedException: 
	at com.amazonaws.internal.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:53)
	at com.amazonaws.internal.SdkFilterInputStream.markSupported(SdkFilterInputStream.java:117)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1026)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651)
	at com.amazonaws.client.ClientHandlerImpl.doInvoke(ClientHandlerImpl.java:204)
	at com.amazonaws.client.ClientHandlerImpl.invoke(ClientHandlerImpl.java:185)
	at com.amazonaws.client.ClientHandlerImpl.execute(ClientHandlerImpl.java:93)
	at com.amazonaws.opensdk.protect.client.SdkClientHandler.execute(SdkClientHandler.java:42)
	at br.com.teste.aws.nuvem.BibliotecaAWSBootloaderClient.postFirmware(BibliotecaAWSBootloaderClient.java:83)
	at br.com.teste.protocoloBootloader.nuvem.AWSApiGateway.getResultByPostInputBody(AWSApiGateway.java:69)
	at br.com.teste.protocoloBootloader.ProtocoloBootloader.conectarNuvem(ProtocoloBootloader.java:167)
	at br.com.teste.protocoloBootloader.ProtocoloBootloader.iniciarProtocolo(ProtocoloBootloader.java:150)
	at br.com.teste.programadorLinhaMonitorada.bootloader.Bootloader.configurar(Bootloader.java:98)
	at br.com.teste.programadorLinhaMonitorada.bootloader.Bootloader.<init>(Bootloader.java:67)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.ComunicacaoService.configurarProtocoloBootloader(ComunicacaoService.java:141)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.Active20UltraComunicacaoService.processarComandoLogar(Active20UltraComunicacaoService.java:438)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.Active20UltraComunicacaoService.processarMensagem(Active20UltraComunicacaoService.java:189)
	at br.com.teste.programadorLinhaMonitorada.model.comunicacao.Comunicacao.update(Comunicacao.java:154)
	at br.com.teste.programadorLinhaMonitorada.model.comunicacao.Serial.notifyObservers(Serial.java:230)
	at br.com.teste.programadorLinhaMonitorada.model.ThreadTratarMensagemRecebida.run(ThreadTratarMensagemRecebida.java:27)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

INTERRUPTED while loading Image
Disposal was interrupted:
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1343)
	at java.awt.Window.doDispose(Window.java:1210)
	at java.awt.Dialog.doDispose(Dialog.java:1198)
	at java.awt.Window.dispose(Window.java:1147)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:870)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at br.com.teste.programadorLinhaMonitorada.bootloader.Bootloader.exception(Bootloader.java:198)
	at br.com.teste.protocoloBootloader.log.Logs.saveLog(Logs.java:45)
	at br.com.teste.protocoloBootloader.ProtocoloBootloader.conectarNuvem(ProtocoloBootloader.java:182)
	at br.com.teste.protocoloBootloader.ProtocoloBootloader.iniciarProtocolo(ProtocoloBootloader.java:150)
	at br.com.teste.programadorLinhaMonitorada.bootloader.Bootloader.configurar(Bootloader.java:98)
	at br.com.teste.programadorLinhaMonitorada.bootloader.Bootloader.<init>(Bootloader.java:67)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.ComunicacaoService.configurarProtocoloBootloader(ComunicacaoService.java:141)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.Active20UltraComunicacaoService.processarComandoLogar(Active20UltraComunicacaoService.java:438)
	at br.com.teste.programadorLinhaMonitorada.model.service.comunicacao.Active20UltraComunicacaoService.processarMensagem(Active20UltraComunicacaoService.java:189)
	at br.com.teste.programadorLinhaMonitorada.model.comunicacao.Comunicacao.update(Comunicacao.java:154)
	at br.com.teste.programadorLinhaMonitorada.model.comunicacao.Serial.notifyObservers(Serial.java:230)
	at br.com.teste.programadorLinhaMonitorada.model.ThreadTratarMensagemRecebida.run(ThreadTratarMensagemRecebida.java:27)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
       Look attachment the alllog of exception.

      Sometimes when I call the method getResultByPostInputBody I receive a exception, but the SDK was generated by AWS platform:
      Look my methods:

private void conectarNuvem() {
	try {
		AWSApiGateway aWSApiGateway = new AWSApiGateway();
		Output data = aWSApiGateway.getResultByPostInputBody(
		BootloaderDados.getDados().getProduto().getCodigoModelo(),
		BootloaderDados.getDados().getNumeroSerie(),
		BootloaderDados.getDados().getVersaoHardware(),
		BootloaderDados.getDados().getVersaoFirmware().replace("b", "."),
		BootloaderDados.getDados().getRemetente(),
		BootloaderDados.getDados().getKeyBeta()
		);
		if (data != null) {
			getBootloaderListener().atualizarDados(data.getNomeProduto(), BootloaderDados.getDados().getVersaoFirmware(), data.getNovaVersaoFirmware(), data.getAtualizar(), data.getCriticidade(), data.getTempo(), data.getNotas());
		} else {
			getBootloaderListener().erro("Erro ao coletar dados da nuvem");
		}
	} catch (Throwable ex) {
		Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
		Logs.getLog().saveLog(ex);
	}
}

public Output getResultByPostInputBody(byte[] modelo, String... dados) {
	Input input = new Input()
				.modelo(Util.getUtil().addZeroEsquerda(modelo))
                .numeroSerie(dados[0])
                .versaoHardware(dados[1])
                .versaoAtualFirmware(dados[2])
                .remetente(dados[3])
                .keyBeta(dados[4]);
	PostFirmwareRequest postFirmwareRequest= new PostFirmwareRequest().input(input);
	postFirmwareRequest.setApiKey("XXXXXXXXXXXXXXXXXXXXX");// configurar chave de API de acordo com a chave cadastrada no console da AWS
	PostFirmwareResult postResult = sdkClient.postFirmware(postFirmwareRequest);        
	Nuvem.getNuvem().setDadosRecebidosNuvem(postResult.getOutput());
	Nuvem.getNuvem().setDadosEnviadosNuvem(input);
	return postResult.getOutput();
}

       Can you help me understand does it happen?

**Comment by debora-ito** [comment]
Hi @RaulSimoes, unfortunately I'm not able to help you a whole lot, because this repo is for issues with the SDK for the AWS Service APIs - I don't know what your API postFirmware() do. 

`Unable to close closeable` seems to indicate that an exception was thrown at the end of the request execution when trying to close the inputstream.

I'll go ahead and close this. Please feel free to reach out if you have any other question or issue.
