### ISSUE TITLE
Regression in EC2MetadataUtils.getItems() in 1.11.702

### ISSUE THREAD

**Issue by tauparticle** [aws/aws-sdk-java#2203]
EC2MetadataUtils.getItems() is currently logging noisy exception logging in the event of a connection timeout to get resource items.  Furthermore, it will not attempt retry as a result.  This is due to an underlying change in the upstream code: 

`InstanceMetadataServiceResourceFetcher.getInstance().readResource(new URI(hostAddress + path));`

which is now throwing AmazonClientException rather than IOException as it previously did with

`EC2CredentialsUtils.getInstance().readResource(new URI(hostAddress + path));`

So rather than handling the IOException with a retry, the code is handling AmazonClientException early and bombing out.

**Comment by zoewangg** [comment]
Hi @tauparticle could you provide the stack trace of the exception you got?

**Comment by tauparticle** [comment]
Exception stack trace 

> com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100) ~[aws-java-sdk-core-1.11.702.jar:?]
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70) ~[aws-java-sdk-core-1.11.702.jar:?]
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75) ~[aws-java-sdk-core-1.11.702.jar:?]
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:62) ~[aws-java-sdk-core-1.11.702.jar:?]
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:400) ~[aws-java-sdk-core-1.11.702.jar:?]
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:369) ~[aws-java-sdk-core-1.11.702.jar:?]
	at org.springframework.cloud.aws.context.support.env.AwsCloudEnvironmentCheckUtils.isRunningOnCloudEnvironment(AwsCloudEnvironmentCheckUtils.java:38) ~[spring-cloud-aws-context-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at com.netflix.springboot.discovery.aws.CompositeInstanceConfigFactory.isInEc2(CompositeInstanceConfigFactory.java:48) ~[spring-boot-netflix-discovery-2.1.35.jar:2.1.35]
	at com.netflix.springboot.discovery.aws.CompositeInstanceConfigFactory.get(CompositeInstanceConfigFactory.java:32) ~[spring-boot-netflix-discovery-2.1.35.jar:2.1.35]
	at com.netflix.springboot.discovery.NetflixInternalEurekaAutoConfiguration.eurekaApplicationInfoManager(NetflixInternalEurekaAutoConfiguration.java:84) ~[spring-boot-netflix-discovery-2.1.35.jar:2.1.35]
	at com.netflix.springboot.discovery.NetflixInternalEurekaAutoConfiguration$$EnhancerBySpringCGLIB$$94d515d1.CGLIB$eurekaApplicationInfoManager$6(<generated>) ~[spring-boot-netflix-discovery-2.1.35.jar:2.1.35]
	at com.netflix.springboot.discovery.NetflixInternalEurekaAutoConfiguration$$EnhancerBySpringCGLIB$$94d515d1$$FastClassBySpringCGLIB$$557be5b3.invoke(<generated>) ~[spring-boot-netflix-discovery-2.1.35.jar:2.1.35]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.11.RELEASE.jar:5.1.11.RELEASE]
	at com.netflix.springboot.discovery.NetflixInternalEurekaAutoConfiguration$$EnhancerBySpringCGLIB$$94d515d1.eurekaApplicationInfoManager(<generated>) ~[spring-boot-netflix-discovery-2.1.35.jar:2.1.35]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]

>

**Comment by tauparticle** [comment]
@zoewangg Even though this is a regression in exception logging, it's also a regression in the behavior of the retries.  If for some reason we timeout obtaining the resource items, we do not retry anymore and log an exception whereas before the code would retry multiple times.  So in the even of a transient networking latency, we will see a regression in behavior, which is potentially a breaking change for this edge case.

**Comment by zoewangg** [comment]
@tauparticle Apologies for the delayed response. This does look like a regression. We will work on the fix.

**Comment by aidan-plenert-macdonald** [comment]
@zoewangg Could you please specify the affected versions and last known working version?

**Comment by tauparticle** [comment]
@zoewangg Last working version I tested was 1.11.656.

**Comment by zoewangg** [comment]
We have added back retry for `EC2MetadataUtils` and the change has been released in `1.11.716`.

https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111716-2020-02-05

Could you try with the latest version? Feel free to reopen if you continue to see the issue

**Comment by williamdelvalle** [comment]
I have the latest version (1.11.864) and I have this issue:

`com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:402)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:371)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:367)
	at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:282)
	at com.amazonaws.regions.Regions.getCurrentRegion(Regions.java:104)`
