### ISSUE TITLE
S3 FileDownload fails during joining parts and gives filelock exception

### ISSUE THREAD

**Issue by zerobugy** [aws/aws-sdk-java#2210]
Hi,
We are testing our client application, trying to download one 880mb txt file from one bucket on s3 to 6 machines (EC on aws), where 7-8 same client applications run on each machine, totally 55-60 client application starts to download. We trigger download process on each client application with 1sec delay. Each client has different settings to download into different locations on the same PC. 
After each download we rename or delete the downloaded files. 
I get into the aws code and realized that during appending downloaded parts into the destination (file name), code gives filelock exception, cannot unlock, and fails to download. Each download process of differen clients (on same mashine), downloads parts into a different folder in temp different files with different key that have the same file name to one temp location (C:\Users\xxxx\AppData\Local\Temp\FtTemp) 
This fail occures on random 3-4 clients under 60 clients on each test.

**Comment by debora-ito** [comment]
Can you provide the logs with the exceptions you're seeing?

**Comment by debora-ito** [comment]
Also, which version of the SDK are you using?

**Comment by zerobugy** [comment]
Hi,
used s3 sdk version: aws-java-sdk-s3-1.11.382
Part of the logs are:
LT 2020-02-05T12:03:51.824 | ST 2020-02-05T12:03:51.195 | s3-transfer-manager-worker-3 | DEBUG | com.amazonaws.request | Received successful response: 200, AWS Request ID: B085F14F93D13724
LT 2020-02-05T12:03:51.824 | ST 2020-02-05T12:03:51.195 | s3-transfer-manager-worker-3 | DEBUG | com.amazonaws.requestId | x-amzn-RequestId: 796ae07b-13a4-4ef0-9b8a-e8a5395d164b
LT 2020-02-05T12:03:51.824 | ST 2020-02-05T12:03:51.195 | s3-transfer-manager-worker-3 | DEBUG | com.amazonaws.requestId | AWS Extended Request ID: coPUpzPtHJ82aPGY0JUGr+iXYHX5bvUvBEN0iXm9PD0D4pU1RtQV3nMuGOws80DKLzCor+xyThI=
LT 2020-02-05T12:03:51.925 | ST 2020-02-05T12:03:51.296 | ThreadPoolTaskScheduler-26 | DEBUG | xxx.client.ftutils.fts3.DownloadTask | Amazon error: 
com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock C:\Users\SYSTEM~1\AppData\Local\Temp\2\FtTemp\85344\2020Feb880MBFileUpload.txt
	at com.amazonaws.services.s3.transfer.DownloadCallable.truncateDestinationFileIfNecessary(DownloadCallable.java:193)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:139)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:99)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:100)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by zerobugy** [comment]
another point of Lock:
LT 2020-02-05T12:03:58.610 | ST 2020-02-05T12:03:57.981 | s3-transfer-manager-worker-1 | DEBUG | com.amazonaws.request | Received successful response: 200, AWS Request ID: B8E8EE5EA033F405
LT 2020-02-05T12:03:58.610 | ST 2020-02-05T12:03:57.981 | s3-transfer-manager-worker-1 | DEBUG | com.amazonaws.requestId | x-amzn-RequestId: fd8a7d4f-6757-4f34-91e5-570115b1b803
LT 2020-02-05T12:03:58.610 | ST 2020-02-05T12:03:57.981 | s3-transfer-manager-worker-1 | DEBUG | com.amazonaws.requestId | AWS Extended Request ID: PhBlN1HxkJpK2BEFTaPbnqKzJIyQQfHTaNDOxWcTr2055FJoRzVeyL8kxWVvqED0tv1tG1Cm/RI=
LT 2020-02-05T12:03:58.625 | ST 2020-02-05T12:03:57.996 | ThreadPoolTaskScheduler-26 | DEBUG | xxx.client.ftutils.fts3.DownloadTask | Amazon error: 
com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock C:\Users\SYSTEM~1\AppData\Local\Temp\2\FtTemp\85344\2020Feb880MBFileUpload.txt
	at com.amazonaws.services.s3.transfer.DownloadCallable.truncateDestinationFileIfNecessary(DownloadCallable.java:193)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:139)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:99)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:100)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
LT 2020-02-05T12:03:58.828 | ST 2020-02-05T12:03:58.199 | ThreadPoolTaskScheduler-26 | ERROR | xxx.client.ftutils.fts3.DownloadTask | Amazon error: 
com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock C:\Users\SYSTEM~1\AppData\Local\Temp\2\FtTemp\85344\2020Feb880MBFileUpload.txt
	at com.amazonaws.services.s3.transfer.DownloadCallable.truncateDestinationFileIfNecessary(DownloadCallable.java:193)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:139)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:99)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:100)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
LT 2020-02-05T12:03:59.234 | ST 2020-02-05T12:03:58.605 | ThreadPoolTaskScheduler-26 | DEBUG | xxx.client.ftutils.fts3.DownloadTaskListener | Download failed: 
xxx.client.commonutils.exception.CrspngFileTransferException: com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock C:\Users\SYSTEM~1\AppData\Local\Temp\2\FtTemp\85344\2020Feb880MBFileUpload.txt
	at xxx.client.ftutils.fts3.DownloadTask.download(DownloadTask.java:145)
	at xxx.client.ftutils.fts3.DownloadTask.downloadWithNewToken(DownloadTask.java:193)
	at xxx.client.ftutils.fts3.DownloadTask.download(DownloadTask.java:142)
	at xxx.client.ftutils.fts3.DownloadTask.call(DownloadTask.java:69)
	at xxx.client.ftutils.fts3.DownloadTask.call(DownloadTask.java:35)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock C:\Users\SYSTEM~1\AppData\Local\Temp\2\FtTemp\85344\2020Feb880MBFileUpload.txt
	at com.amazonaws.services.s3.transfer.DownloadCallable.truncateDestinationFileIfNecessary(DownloadCallable.java:193)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:139)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:99)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:100)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	... 3 more
LT 2020-02-05T12:03:59.312 | ST 2020-02-05T12:03:58.683 | ThreadPoolTaskScheduler-26 | ERROR | xxx.client.ftclient.transfer.TransferHandler | Unable to download 14277/2020Feb880MBFileUpload.txt Fail to lock C:\Users\SYSTEM~1\AppData\Local\Temp\2\FtTemp\85344\2020Feb880MBFileUpload.txt: 
LT 2020-02-05T12:03:59.577 | ST 2020-02-05T12:03:58.948 | ThreadPoolTaskScheduler-26 | DEBUG | xxx.client.ftclient.transfer.TransferHandler | Exception occurred during file transfer
java.util.concurrent.ExecutionException: xxx.client.commonutils.exception.CrspngFileTransferException: com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock C:\Users\SYSTEM~1\AppData\Local\Temp\2\FtTemp\85344\2020Feb880MBFileUpload.txt
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at crspng.client.ftclient.transfer.TransferHandler.getTransferStatus(TransferHandler.java:534)
	at crspng.client.ftclient.transfer.TransferHandler.notifyTransferRequest(TransferHandler.java:498)
	at crspng.client.ftclient.transfer.TransferHandler.onFailure(TransferHandler.java:474)
	at crspng.client.ftutils.fts3.TransferTaskListener.onFailure(TransferTaskListener.java:28)
	at org.springframework.util.concurrent.ListenableFutureCallbackRegistry.notifyFailure(ListenableFutureCallbackRegistry.java:86)
	at org.springframework.util.concurrent.ListenableFutureCallbackRegistry.failure(ListenableFutureCallbackRegistry.java:158)
	at org.springframework.util.concurrent.ListenableFutureTask.done(ListenableFutureTask.java:100)
	at java.util.concurrent.FutureTask.finishCompletion(Unknown Source)
	at java.util.concurrent.FutureTask.setException(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: crspng.client.commonutils.exception.CrspngFileTransferException: com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock C:\Users\SYSTEM~1\AppData\Local\Temp\2\FtTemp\85344\2020Feb880MBFileUpload.txt
	at xxx.client.ftutils.fts3.DownloadTask.download(DownloadTask.java:145)
	at xxx.client.ftutils.fts3.DownloadTask.downloadWithNewToken(DownloadTask.java:193)
	at xxx.client.ftutils.fts3.DownloadTask.download(DownloadTask.java:142)
	at xxx.client.ftutils.fts3.DownloadTask.call(DownloadTask.java:69)
	at xxx.client.ftutils.fts3.DownloadTask.call(DownloadTask.java:35)
	... 9 more
Caused by: com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock C:\Users\SYSTEM~1\AppData\Local\Temp\2\FtTemp\85344\2020Feb880MBFileUpload.txt
	at com.amazonaws.services.s3.transfer.DownloadCallable.truncateDestinationFileIfNecessary(DownloadCallable.java:193)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:139)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:99)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:100)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	... 3 more

**Comment by debora-ito** [comment]
@zerobugy I'm sorry for the long silence here. The TransferManager download received some optimizations in version 1.11.472 (see [changelog](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md#111472-2018-12-18)). 

Can you run your tests using a newer version of the sdk and check if you still see the FileLockException ?

**Comment by debora-ito** [comment]
Closing issue. Feel free to reopen if you have more questions.

**Comment by dhikrahashim** [comment]
I am facing the same lock issue with my jenkins job



com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock /var/jenkins_home/jobs/xxxxxxxxxxx/xxxxxx/workspace/tests.zip
	at com.amazonaws.services.s3.transfer.DownloadCallable.truncateDestinationFileIfNecessary(DownloadCallable.java:194)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:139)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:99)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:100)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:40)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
