### ISSUE TITLE
Invalid format: "2020-02-13T12:24.00.000Z" is malformed at ".00.000Z"

### ISSUE THREAD

**Issue by seasuresh** [aws/aws-sdk-java#2225]
I'm trying to retrieve DynamoDB items using the hash key and range key as Date. I'm using between operator to get the items. I see SDK is able to retrieve the items but failing while transforming the date.

Here is the Model class

```
public class Person{
@DynamoDBHashKey(attributeName = "personId")
private String id;
private Date createDate;
//Setters and getters with no addtional annotations
}

```
DynamoDBQueryExpression

 ```
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSz");
        String formattedStartDate = format.format(skStartTime);
        String formattedEndDate = format.format(skEndTime);

        expressionAttributesNames.put("#" + skAttributeName, skAttributeName);
        expressionAttributeValues.put(":from", new AttributeValue().withS(formattedStartDate));
        expressionAttributeValues.put(":to", new AttributeValue().withS(formattedEndDate));
        keyExpressionConditions.append("and #").append(skAttributeName).append(" BETWEEN :from AND :to ");

        DynamoDBQueryExpression<Person> dynamoDBQueryExpression = new DynamoDBQueryExpression<Person>()
                .withIndexName(INDEX)
                .withKeyConditionExpression(keyExpressionConditions.toString())
                .withExpressionAttributeNames(expressionAttributesNames)
                .withExpressionAttributeValues(expressionAttributeValues)
                .withScanIndexForward(FALSE)
                .withConsistentRead(FALSE)
                .withLimit(10);
```
After getting the data, I see the following error. What i'm doing wrong here?

```
java.lang.IllegalArgumentException: Invalid format: "2020-02-13T12:24.00.000Z" is malformed at ".00.000Z"
	at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187) ~[joda-time-2.10.5.jar:2.10.5]
	at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:826) ~[joda-time-2.10.5.jar:2.10.5]
	at com.amazonaws.util.DateUtils.doParseISO8601Date(DateUtils.java:98) ~[aws-java-sdk-core-1.11.415.jar:na]
	at com.amazonaws.util.DateUtils.parseISO8601Date(DateUtils.java:77) ~[aws-java-sdk-core-1.11.415.jar:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.unmarshallers.DateUnmarshaller.unmarshall(DateUnmarshaller.java:38) ~[aws-java-sdk-dynamodb-1.11.34.jar:na]
```

**Comment by seasuresh** [comment]
This is the version I currently use
`compile group: 'com.amazonaws', name: 'aws-java-sdk', version: '1.11.700'`

**Comment by debora-ito** [comment]
Hi @seasuresh, it looks like you are trying to parse `2020-02-13T12:24.00.000Z` which is an invalid format as the message says. 

A valid format would be `2020-02-13T12:24:00.000Z` (note the hh:mm:ss.sss in the time portion).

**Comment by debora-ito** [comment]
I'll go ahead and close this, feel free to reopen if you still have questions about this.
