### ISSUE TITLE
Facing same on java 11

### ISSUE THREAD

**Issue by aseetpadhi** [aws/aws-sdk-java#2257]
Facing same issue 

com.amazonaws.SdkClientException: Unable to execute HTTP request: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1201)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1147)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
        at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2207)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2174)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2163)
        at com.amazonaws.services.sqs.AmazonSQSClient.executeCreateQueue(AmazonSQSClient.java:812)
        at com.amazonaws.services.sqs.AmazonSQSClient.createQueue(AmazonSQSClient.java:784)

**Comment by debora-ito** [comment]
@aseetpadhi this is most likely caused by missing Amazon's Root Trust Services certificates in your trust store. 

You can check what certificates are installed in your trust store with the following command:

```
keytool -list -v /path/to/keystore
```

And ensure the certificates [from this page are present](https://aws.amazon.com/blogs/security/how-to-prepare-for-aws-move-to-its-own-certificate-authority/):

- CN=Amazon Root CA 1,O=Amazon,C=US
- CN=Amazon Root CA 2,O=Amazon,C=US
- CN=Amazon Root CA 3,O=Amazon,C=US
- CN=Amazon Root CA 4,O=Amazon,C=US
- CN=Starfield Services Root Certificate Authority – G2,O=Starfield Technologies\, Inc.,L=Scottsdale,ST=Arizona,C=US
- Starfield Class 2 Certification Authority

Also, if you search for "PKIX path building failed" in this repository, you'll find reports of this error message in different environments (using proxy server, OpenJDK, third party apps), maybe some of the reports can be helpful to you.

**Comment by debora-ito** [comment]
Closing this, feel free to reopen if you have any more questions.
