### ISSUE TITLE
AmazonS3Client getRegion ignores custom endpoint configuration

### ISSUE THREAD

**Issue by xfrancois** [aws/aws-sdk-java#2281]
If we provide a custom endpoint configuration at the creation of `AmazonS3` object and then try to retrieve the region with the `AmazonS3.java` `getRegion()` method, an `IllegalStateException `is thrown.

## Describe the bug

An `IllegalStateException` is thrown because in this case, the `getRegion()` method is not checking if a value is set by the user in `signing region` field. It only checks if the host is matching the amazonaws.com regional pattern

## Expected Behavior

The getRegion() method should take  `AwsClientBuilder.EndpointConfiguration` values into account.

## Current Behavior

Stacktrace generated from my application using `spring-aws-integration` which uses `aws-sdk-java-s3` under the hood.

```
2020-03-30 19:05:21,008 ERROR [scheduling-1] org.springframework.integration.handler.LoggingHandler:  org.springframework.messaging.MessagingException: nested exception is java.lang.IllegalStateException: S3 client with invalid S3 endpoint configured: localhost:9001
    at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:342)
    at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$null$1(AbstractPollingEndpoint.java:275)
    at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
    at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
    at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:55)
    at org.springframework.integration.endpoint.AbstractPollingEndpoint.lambda$createPoller$2(AbstractPollingEndpoint.java:272)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
    at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: S3 client with invalid S3 endpoint configured: localhost:9001
    at com.amazonaws.services.s3.AmazonS3Client.getRegion(AmazonS3Client.java:4270)
    at org.springframework.integration.aws.support.S3Session.getHostPort(S3Session.java:228)
    at org.springframework.integration.file.remote.AbstractRemoteFileStreamingMessageSource.doReceive(AbstractRemoteFileStreamingMessageSource.java:214)
    at org.springframework.integration.endpoint.AbstractMessageSource.receive(AbstractMessageSource.java:167)
    at org.springframework.integration.endpoint.SourcePollingChannelAdapter.receiveMessage(SourcePollingChannelAdapter.java:250)
    at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:359)
    at org.springframework.integration.endpoint.AbstractPollingEndpoint.pollForMessage(AbstractPollingEndpoint.java:328)
```

## Steps to Reproduce

To reproduce, create an AmazonS3 object with a custom endpoint configuration :
```java
 @Bean
    public AmazonS3 amazonS3(ConfigProperties configProperties) {

        return AmazonS3ClientBuilder.standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:9001","eu-west-0")) // Region matches with minio region
                .withPathStyleAccessEnabled(configProperties.getS3().isPathStyle())
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(
                        configProperties.getS3().getAccessKey(), configProperties.getS3().getSecretKey()
                ))).build();
    }
```
Then, make a call to the `getRegion()` method.

```java
 @Override
    public synchronized Region getRegion() {
        String authority = super.endpoint.getAuthority();
        if (Constants.S3_HOSTNAME.equals(authority)) {
            return Region.US_Standard;
        } else {
            Matcher m = Region.S3_REGIONAL_ENDPOINT_PATTERN.matcher(authority);
            if (m.matches()) {
                return Region.fromValue(m.group(1));
            } else {
                throw new IllegalStateException(
                    "S3 client with invalid S3 endpoint configured: " + authority);
            }
        }
    }
```
For example: `spring-integration-aws` is doing this call like that : 

```java
@Override
	public String getHostPort() {
		Region region = this.amazonS3.getRegion().toAWSRegion();
		return String.format("%s.%s.%s:%d", AmazonS3.ENDPOINT_PREFIX, region.getName(), region.getDomain(), 443);
	}
```

## Context

I try to poll files from a minio S3 bucket to trigger `spring-batch` jobs.
Full context detailled [here on Stackoverflow](https://stackoverflow.com/questions/60930518/cant-poll-from-s3-with-a-custom-endpoint-configuration). 
[I also raised an issue on `spring-integration-aws` side](https://github.com/spring-projects/spring-integration-aws/issues/160).

## Your Environment

* AWS Java SDK version used: 1.11.415
* JDK version used: 11
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
Hi @xfrancois, 

the intended use of `getRegion()` is to obtain the AWS S3 service endpoint region, and not the signing region. In addition, changing this would break customers that rely in this behavior, and for this reason we don't want to make this change. 

I see you are working on a fix within the _spring-integration-aws_ project, this would the best way to get unblocked.

Closing this, feel free to reopen if you have any further issues or comments.
