### ISSUE TITLE
Getting error "Unable to execute HTTP request: Request did not complete before the request timeout configuration."

### ISSUE THREAD

**Issue by tijoparacka** [aws/aws-sdk-java#2284]
While putting record to Kinesis I am getting the following error. 
```com.amazonaws.SdkClientException: Unable to execute HTTP request: Request did not complete before the request timeout configuration.
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1201)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1147)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2809)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2776)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2765)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executePutRecords(AmazonKinesisClient.java:2169)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecords(AmazonKinesisClient.java:2140)`
om.amazonaws.SdkClientException: Unable to execute HTTP request: Request did not complete before the request timeout configuration.
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1201)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1147)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2809)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2776)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2765)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executePutRecords(AmazonKinesisClient.java:2169)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecords(AmazonKinesisClient.java:2140)```
## Describe the bug
The following sample code is used 
` AmazonKinesisClientBuilder clientBuilder = AmazonKinesisClientBuilder.standard();
      clientBuilder.setRegion(region);
      clientBuilder.setCredentials(new DefaultAWSCredentialsProviderChain());
      //KinesisProducerConfiguration awsConfig = new KinesisProducerConfiguration();
      ClientConfiguration awsConfig = new ClientConfiguration();
      awsConfig.setMaxConnections(maxConnection);
      awsConfig.setRequestTimeout(requestTimeOut);
      awsConfig.setMaxConsecutiveRetriesBeforeThrottling(60);
      awsConfig.setUserAgentPrefix("sim");
      awsConfig.setConnectionTimeout(50 *1000);
      awsConfig.setSocketTimeout(50 *1000);

      clientBuilder.setClientConfiguration(awsConfig);

      kinesisClient = clientBuilder.build();
      putRecordsRequest = new PutRecordsRequest();
      putRecordsRequest.setStreamName(streamName);

       PutRecordsRequestEntry putRecordsRequestEntry  = new PutRecordsRequestEntry();
        byte[] bytes= message.getBytes();
        putRecordsRequestEntry.setData(ByteBuffer.wrap(bytes));
        putRecordsRequestEntry.setPartitionKey(String.format( "sim-%d",MurmurHash3.hash32x86(bytes)));
        putRecordsRequestEntryList.add(putRecordsRequestEntry);

        if(sequenceNumber.addAndGet(1) %  batchSize ==0){
          putRecordsRequest.setRecords(putRecordsRequestEntryList);
          PutRecordsResult putRecordsResult  = kinesisClient.putRecords(putRecordsRequest);
          putRecordsRequestEntryList.clear();

          if(putRecordsResult.getFailedRecordCount() > 0 ){
            logger.error(String.format("Failed to insert %d records", putRecordsResult.getFailedRecordCount()) );
            numberOfEventsProcessed = numberOfEventsProcessed  + batchSize - putRecordsResult.getFailedRecordCount();
          }
        }
`

## Expected Behavior
The message should be inserted with out error 
## Current Behavior
com.amazonaws.SdkClientException: Unable to execute HTTP request: Request did not complete before the request timeout configuration.  


## Steps to Reproduce
Create a sample program and execute.


## Context
We are blocked with this . Currently we are using older version of producer.  Wish to upgrade the SDK version and to use PutRecordsRequestEntry
## Your Environment
Using MAC.  

* AWS Java SDK version used: aws-java-sdk   1.11.759
* JDK version used:Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
* Operating System and version:   MAC

**Comment by debora-ito** [comment]
@tijoparacka the error indicates that the request did not complete before the request timeout configuration, which you provided in the `ClientConfiguration`:
```
      awsConfig.setRequestTimeout(requestTimeOut);
```

What value are you setting for `requestTimeOut`? Note that this is in milliseconds.

**Comment by tijoparacka** [comment]
I set this value as 600. Is this a good figure ?

**Comment by tijoparacka** [comment]
Even i tried with 6000. But no luck .

**Comment by debora-ito** [comment]
Setting `requestTimeout` to 6000 and still seeing the issue means that is taking more than 6000 milliseconds to make the API call and receive a response from the service. 

Some things can impact the request time: if the size of `message` is too big, or how close you are geographically from the region of the kinesis endpoint. 

Have you tested not setting `requestTimeout` in the ClientConfiguration and running the code, to see how long `putRecords` is taking to run? You can then use this time to estimate a good requestTimeout value.

**Comment by debora-ito** [comment]
Closing this. Feel free to reopen if you have further questions.
