### ISSUE TITLE
Unable to load AWS credentials from any provider in the chain

### ISSUE THREAD

**Issue by taylorbradyodaly** [aws/aws-sdk-java#2286]
I am new to AWS and have been trying to fix this error I have been having. I have already created a new IAM user with access keys but still having the same issue regarding credentials. I have been reading the AWS documents but not understanding how to store the credentials. I have stored the access keys in my C:/ but it is still not recognizing the file. 

**This is the error I keep getting:** 

Exception in thread "main" com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1164)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:762)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:724)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2925)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2901)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeUpdateItem(AmazonDynamoDBClient.java:2647)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:2623)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.doUpdateItem(DynamoDBMapper.java:854)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$2.executeLowLevelRequest(DynamoDBMapper.java:594)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.execute(DynamoDBMapper.java:733)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.save(DynamoDBMapper.java:623)
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.save(AbstractDynamoDBMapper.java:123)
	at com.amazonaws.samples.ProductCatalog.testCRUDOperations(ProductCatalog.java:97)
	at com.amazonaws.samples.ProductCatalog.main(ProductCatalog.java:28)

I am currently Eclipse Java IDE 2020

**Comment by debora-ito** [comment]
Hi @taylorbradyodaly, take a look at the docs that explain the different ways to supply the credentials to the SDK - https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html

**Comment by debora-ito** [comment]
Let us know if that helps.

**Comment by debora-ito** [comment]
Closing this, feel free to reopen if you have any other question.

**Comment by emyes** [comment]
@debora-ito : Hope you are doing good. 

I'm facing similar kind of issue.  I'm trying to publish the message from my app which is running in Fargate. I'm not facing any problem while spinning up my app and running in my local dev machine. It works fine without any issues. It reads credentials from my local machine and performs operation. But when i running the same app in ECS  I'm getting below exception

com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
at com.amazonaws.services.sns.AmazonSNSClient.invoke(AmazonSNSClient.java:2333)
at com.amazonaws.services.sns.AmazonSNSClient.publish(AmazonSNSClient.java:1462)
