### ISSUE TITLE
Warning of illegal reflective access by jackson.databind

### ISSUE THREAD

**Issue by andreasg123** [aws/aws-sdk-java#2288]
When running a Java app, a warning is displayed that jackson.databind performs an illegal reflective access.

## Describe the bug

There is a warning of an illegal reflective access. From the stack trace, it happens here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/JsonErrorResponseHandler.java#L185
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/transform/JsonErrorUnmarshaller.java#L52

## Expected Behavior

There shouldn't be a warning because the indication is that future Java versions will not allow this at all.

## Current Behavior

With `java --illegal-access=debug`, the following is displayed.

    WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil (file:...) to field java.lang.Throwable.cause
        at com.fasterxml.jackson.databind.util.ClassUtil.checkAndFixAccess(ClassUtil.java:939)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.fixAccess(FieldProperty.java:104)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:494)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder.build(BeanDeserializerBuilder.java:350)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildThrowableDeserializer(BeanDeserializerFactory.java:411)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:112)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:479)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4405)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4184)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2476)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2929)
        at com.amazonaws.transform.JsonErrorUnmarshaller.unmarshall(JsonErrorUnmarshaller.java:52)
        at com.amazonaws.http.JsonErrorResponseHandler.doLegacyUnmarshall(JsonErrorResponseHandler.java:185)
        at com.amazonaws.http.JsonErrorResponseHandler.unmarshallException(JsonErrorResponseHandler.java:147)
        at com.amazonaws.http.JsonErrorResponseHandler.createException(JsonErrorResponseHandler.java:131)
        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:94)
        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:40)
        at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:53)
        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:41)
        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:26)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1781)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1383)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1359)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
    WARNING: Illegal reflective access by com.fasterxml.jackson.databind.util.ClassUtil (file:...) to field java.lang.Throwable.cause
        at com.fasterxml.jackson.databind.util.ClassUtil.checkAndFixAccess(ClassUtil.java:939)
        at com.fasterxml.jackson.databind.deser.impl.FieldProperty.fixAccess(FieldProperty.java:104)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder._fixAccess(BeanDeserializerBuilder.java:494)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBuilder.build(BeanDeserializerBuilder.java:350)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildThrowableDeserializer(BeanDeserializerFactory.java:411)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:112)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:414)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(DeserializationContext.java:469)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:473)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:293)
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:479)
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4405)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4184)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2476)
        at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2929)
        at com.amazonaws.transform.JsonErrorUnmarshaller.unmarshall(JsonErrorUnmarshaller.java:52)
        at com.amazonaws.http.JsonErrorResponseHandler.doLegacyUnmarshall(JsonErrorResponseHandler.java:185)
        at com.amazonaws.http.JsonErrorResponseHandler.unmarshallException(JsonErrorResponseHandler.java:147)
        at com.amazonaws.http.JsonErrorResponseHandler.createException(JsonErrorResponseHandler.java:131)
        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:94)
        at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:40)
        at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:53)
        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:41)
        at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:26)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1781)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1383)

## Your Environment

Ubuntu 18.04, aws-java-sdk-dynamodb 1.11.762, jackson-databind 2.10.3

    openjdk version "11.0.6" 2020-01-14
    OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
    OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)

**Comment by zoewangg** [comment]
Hi @andreasg123 thanks for reporting the issue, but unfortunately, we cannot fix it easily at this point without breaking existing customers. We are concentrating efforts on V2 new features at the moment. https://github.com/aws/aws-sdk-java-v2

**Comment by andreasg123** [comment]
Thanks for the response. While I have a fairly new code base, it doesn't seem to be prudent to move to V2 because of missing functionality, e.g., [DynamoDB document API](https://github.com/aws/aws-sdk-java-v2/issues/36) or [Lambda events](https://github.com/aws/aws-sdk-java-v2/issues/1319). 

Also, it is difficult to get started with V2 because there are so few examples. The [migration guide](https://docs.aws.amazon.com/sdk-for-java/v2/migration-guide/what-is-java-migration.html) doesn't cover specific issues, e.g., how to replace [`com.amazonaws.services.dynamodbv2.document.Table`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/document/Table.html).

**Comment by zoewangg** [comment]
Thank your for your feedback! We are currently working on adding more samples to make it easier to get started with v2 and migrate from v1 to v2. 

DynamodbMapper v2 is one of our top priorities right now and document api is on our roadmap. It would help us get it prioritized if you could +1 on that github issue. Lambda events is not owned by our team and I'll pass the message to the team that maintains the library.

**Comment by debora-ito** [comment]
Closing this. Feel free to reopen if you have further questions.

**Comment by edudar** [comment]
Hm, could you please elaborate on why existing customers will have a breaking change with this? This happens way too deep inside JSON error handler where SDK tries to create an exception based on http response. What's needed is to handle this case cause neither input (JSON structure) nor output (AmazonServiceException) change. `JsonErrorUnmarshaller.MAPPER` just needs proper custom serializer/deserializer implementation for exceptions instead of a default metadata-driven one.

**Comment by bowbahdoe** [comment]
@zoewangg This is the only thing blocking us from upgrading to java 16. If it can't be resolved, can the `--add-opens` required be documented?
