### ISSUE TITLE
AmazonHttpClient does not retries on 5xx errors

### ISSUE THREAD

**Issue by salebab** [aws/aws-sdk-java#2291]
It's seems that `AmazonHttpClient` constructed with default `ClientConfiguration` does not retries on 5xx response codes. It only retries on IOExceptions such as `HttpRequestTimeoutException` that extends `IOException`. 

Since, default `RetryPolicy` defined in `ClientConfiguration` consist of `SDKDefaultRetryCondition` that contains retry logic for 500 and 503 error codes, the expected behavior for client is to automatically retry, but unfortunately, `AmazonServiceException` is thrown. 

Here is the stack trace:
```
com.amazonaws.services.s3.model.AmazonS3Exception: Internal Server Error (Service: Amazon S3; Status Code: 500; Error Code: 500 Internal Server Error; Request ID: null; S3 Extended Request ID: null), S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1799)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1383)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1359)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
```

In the case of IO exceptions, following stack trace shows that method `AmazonHttpClient.RequestExecutor#handleRetryableException` is called which means retry is performed:

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: Request did not complete before the request timeout configuration.

	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1201)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1147)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
```
* `SdkClientException` wraps `IOException` in the method.

I've noticed also that method `handleRetryableException` [is called only for IOException](https://github.com/aws/aws-sdk-java/blob/1.11.762/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L1147), and obviously since  `SdkClientException` is not extending `IOException`, configured retry policy is never executed. 

Possible fix should be trivial. Code needs to be changed from:
```java
} catch (IOException ioe) {
  savedException = ioe;
  handleRetryableException(execOneParams, ioe);
``` 
to catch both: 
```java
} catch (IOException | SdkClientException e) {
  savedException = e;
  handleRetryableException(execOneParams, e);
``` 
and since `handleRetryableException` already contains logic that can handle all kind of exceptions, this should do a job.

**Comment by salebab** [comment]
I've figured out that actually retry mechanism works well, but from the stack trace it is not obvious. I've tested with mocked amazon service and everything is fine, just probably in my case default max retries count exceed.
