### ISSUE TITLE
Upgrading cloudwatch sdk from 1.11.659 to 1.11.762 yields errors on Fargate

### ISSUE THREAD

**Issue by alexmnyc** [aws/aws-sdk-java#2304]
```
15:50:01
WARNING: Fail to retrieve token
15:50:01
com.amazonaws.SdkClientException: Failed to connect to service endpoint:
com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
15:50:01
at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)

15:50:01
at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.getToken(InstanceMetadataServiceResourceFetcher.java:91)

15:50:01
at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:69)

15:50:01
at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)

15:50:01
at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsEndpoint(InstanceMetadataServiceCredentialsFetcher.java:58)

15:50:01
at com.amazonaws.auth.InstanceMetadataServiceCredentialsFetcher.getCredentialsResponse(InstanceMetadataServiceCredentialsFetcher.java:46)

15:50:01
at com.amazonaws.auth.BaseCredentialsFetcher.fetchCredentials(BaseCredentialsFetcher.java:112)

15:50:01
at com.amazonaws.auth.BaseCredentialsFetcher.getCredentials(BaseCredentialsFetcher.java:68)

15:50:01
at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:166)

15:50:01
at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)

15:50:01
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1251)

15:50:01
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:827)

15:50:01
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:777)

15:50:01
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)

15:50:01
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)

15:50:01
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)

15:50:01
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)

15:50:01
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)

15:50:01
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)

15:50:01
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:2587)

15:50:01
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:2554)

15:50:01
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:2543)

15:50:01
at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.executePutMetricData(AmazonCloudWatchClient.java:2297)

15:50:01
at com.amazonaws.services.cloudwatch.AmazonCloudWatchAsyncClient$27.call(AmazonCloudWatchAsyncClient.java:1203)

15:50:01
at com.amazonaws.services.cloudwatch.AmazonCloudWatchAsyncClient$27.call(AmazonCloudWatchAsyncClient.java:1197)

15:50:01
at java.util.concurrent.FutureTask.run(FutureTask.java:266)

15:50:01
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

15:50:01
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

15:50:01
at java.lang.Thread.run(Thread.java:748)

15:50:01
Caused by: java.net.ConnectException: Invalid argument (connect failed)

15:50:01
at java.net.PlainSocketImpl.socketConnect(Native Method)

15:50:01
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

15:50:01
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

15:50:01
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

15:50:01
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

15:50:01
at java.net.Socket.connect(Socket.java:607)

15:50:01
at sun.net.NetworkClient.doConnect(NetworkClient.java:175)

15:50:01
at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)

15:50:01
at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)

15:50:01
at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)

15:50:01
at sun.net.www.http.HttpClient.New(HttpClient.java:339)

15:50:01
at sun.net.www.http.HttpClient.New(HttpClient.java:357)

15:50:01
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)

15:50:01
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)

15:50:01
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)

15:50:01
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)

15:50:01
at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)

15:50:01
at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)

15:50:01
... 28 more
```

**Comment by debora-ito** [comment]
@alexmnyc I'm not super familiar with Fargate, but "java.net.ConnectException: Invalid argument (connect failed)" indicates a connectivity issue. Are you using a proxy?
Is the version upgrade the only thing that have changed when this error started to show ? 
Was there any change in the container configuration? 

Give us some context so we can be more helpful.

**Comment by alexmnyc** [comment]
I had a Fargate service running without any proxies using https://github.com/alonsodomin/kamon-cloudwatch/releases/tag/v1.1.4

Then I upgraded to https://github.com/alonsodomin/kamon-cloudwatch/releases/tag/v1.1.5 which pulled in the new AWS SDK version and the above errors started happening.

**Comment by debora-ito** [comment]
In this case I suggest you contact the maintainers of Kamon Cloudwatch extension, the connectivity issue seems to be on their side.

If you experience the same issue when using the Cloudwatch dependency directly, please reach out to us, providing a sample code we can use to reproduce.
