### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.internal.ServiceUtils

### ISSUE THREAD

**Issue by SandeepRJ** [aws/aws-sdk-java#2309]
Jenkins build fails when multiple versions of the aws-sdk-core and aws-sdk-s3 library exists

## Describe the bug

I am using the latest version of jenkins pipeline plugin and the aws steps plugin. S3 upload fails with the following error 

`java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.internal.ServiceUtils
	at com.amazonaws.services.s3.AmazonS3Client.setEndpoint(AmazonS3Client.java:722)
	at com.amazonaws.services.s3.AmazonS3Client.init(AmazonS3Client.java:706)
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:696)
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at de.taimos.pipeline.aws.AWSClientFactory.create(AWSClientFactory.java:65)
	at de.taimos.pipeline.aws.S3UploadStep$RemoteListUploader.invoke(S3UploadStep.java:606)
	at de.taimos.pipeline.aws.S3UploadStep$RemoteListUploader.invoke(S3UploadStep.java:570)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3073)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused: java.io.IOException: Remote call on EC2 (Java Build Agent) - M3.6.1 G5.5.1 N8.16.0 (i-09bdb64207a103448) failed
	at hudson.remoting.Channel.call(Channel.java:1004)
	at hudson.FilePath.act(FilePath.java:1069)
	at hudson.FilePath.act(FilePath.java:1058)
	at de.taimos.pipeline.aws.S3UploadStep$Execution.run(S3UploadStep.java:416)
	at de.taimos.pipeline.aws.S3UploadStep$Execution.run(S3UploadStep.java:262)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE`

![image](https://user-images.githubusercontent.com/46587836/80929635-42fd5e80-8dcb-11ea-8357-01aa3720ac4b.png)

## Current Behavior

Till now I have been using the versions mentioned above in the image above for the 1.11.420 version.
S3 Upload fails whenever there is 1.11.420 version added to the maven repository and runs without issues when 1.11.420 version is removed.

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
> Jenkins build fails when multiple versions of the aws-sdk-core and aws-sdk-s3 library exists

> S3 Upload fails whenever there is 1.11.420 version added to the maven repository and runs without issues when 1.11.420 version is removed.

Hi @SandeepRJ I'm not familiar with the Jenkins plugins, but by your description there's conflicting versions of core and s3 dependencies in your environment and this can cause runtime errors like `NoClassDefFoundError`. 

Can you check your dependency tree for how the versions are being resolved? Ideally they should be the same.
