### ISSUE TITLE
o.apache.coyote.http11.Http11Processor : Error parsing HTTP request header java.io.EOFException: null

### ISSUE THREAD

**Issue by sumit4209211** [aws/aws-sdk-java#2316]
Exception coming in logs

org.apache.catalina.session.ManagerBase  : Start expire sessions StandardManager at 1588823341079 sessioncount 1
{"@timestamp":"2020-05-07T09:19:01.079+05:30","@version":"1","message":"Start expire sessions StandardManager at 1588823341079 sessioncount 1","logger_name":"org.apache.catalina.session.ManagerBase","thread_name":"Catalina-utility-2","level":"DEBUG","level_value":10000}
2020-05-07 09:19:01.079 DEBUG [,,,] 15884 --- [alina-utility-2] org.apache.catalina.session.ManagerBase  : End expire sessions StandardManager processingTime 0 expired sessions: 0
{"@timestamp":"2020-05-07T09:19:01.079+05:30","@version":"1","message":"End expire sessions StandardManager processingTime 0 expired sessions: 0","logger_name":"org.apache.catalina.session.ManagerBase","thread_name":"Catalina-utility-2","level":"DEBUG","level_value":10000}
2020-05-07 09:19:53.629 DEBUG [,,,] 15884 --- [o-9288-Acceptor] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-9288-Acceptor] latch=1
{"@timestamp":"2020-05-07T09:19:53.629+05:30","@version":"1","message":"Counting up[http-nio-9288-Acceptor] latch=1","logger_name":"org.apache.tomcat.util.threads.LimitLatch","thread_name":"http-nio-9288-Acceptor","level":"DEBUG","level_value":10000}
2020-05-07 09:19:53.630 DEBUG [,,,] 15884 --- [o-9288-Acceptor] o.apache.tomcat.util.threads.LimitLatch  : Counting up[http-nio-9288-Acceptor] latch=2
2020-05-07 09:19:53.630 DEBUG [,,,] 15884 --- [nio-9288-exec-5] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@31807916:org.apache.tomcat.util.net.NioChannel@71b7af05:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9288 remote=/0:0:0:0:0:0:0:1:53786]], Read from buffer: [0]
{"@timestamp":"2020-05-07T09:19:53.630+05:30","@version":"1","message":"Counting up[http-nio-9288-Acceptor] latch=2","logger_name":"org.apache.tomcat.util.threads.LimitLatch","thread_name":"http-nio-9288-Acceptor","level":"DEBUG","level_value":10000}
{"@timestamp":"2020-05-07T09:19:53.630+05:30","@version":"1","message":"Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@31807916:org.apache.tomcat.util.net.NioChannel@71b7af05:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9288 remote=/0:0:0:0:0:0:0:1:53786]], Read from buffer: [0]","logger_name":"org.apache.tomcat.util.net.SocketWrapperBase","thread_name":"http-nio-9288-exec-5","level":"DEBUG","level_value":10000}
2020-05-07 09:19:53.630 DEBUG [,,,] 15884 --- [nio-9288-exec-5] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1235)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1143)
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:735)
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:353)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

{"@timestamp":"2020-05-07T09:19:53.630+05:30","@version":"1","message":"Error parsing HTTP request header","logger_name":"org.apache.coyote.http11.Http11Processor","thread_name":"http-nio-9288-exec-5","level":"DEBUG","level_value":10000,"stack_trace":"java.io.EOFException: null\r\n\tat org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1235)\r\n\tat org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1143)\r\n\tat org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:735)\r\n\tat org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:353)\r\n\tat org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260)\r\n\tat org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)\r\n\tat org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)\r\n\tat org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1598)\r\n\tat org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\r\n\tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)\r\n\tat java.lang.Thread.run(Thread.java:748)\r\n"}
2020-05-07 09:19:53.631 DEBUG [,,,] 15884 --- [nio-9288-exec-2] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5657fb55:org.apache.tomcat.util.net.NioChannel@3503ede7:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9288 remote=/0:0:0:0:0:0:0:1:53787]], Read from buffer: [0]
{"@timestamp":"2020-05-07T09:19:53.631+05:30","@version":"1","message":"Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5657fb55:org.apache.tomcat.util.net.NioChannel@3503ede7:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9288 remote=/0:0:0:0:0:0:0:1:53787]], Read from buffer: [0]","logger_name":"org.apache.tomcat.util.net.SocketWrapperBase","thread_name":"http-nio-9288-exec-2","level":"DEBUG","level_value":10000}
2020-05-07 09:19:53.631 DEBUG [,,,] 15884 --- [nio-9288-exec-5] o.apache.coyote.http11.Http11Processor   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@31807916:org.apache.tomcat.util.net.NioChannel@71b7af05:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9288 remote=/0:0:0:0:0:0:0:1:53786]], Status in: [OPEN_READ], State out: [CLOSED]
{"@timestamp":"2020-05-07T09:19:53.631+05:30","@version":"1","message":"Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@31807916:org.apache.tomcat.util.net.NioChannel@71b7af05:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9288 remote=/0:0:0:0:0:0:0:1:53786]], Status in: [OPEN_READ], State out: [CLOSED]","logger_name":"org.apache.coyote.http11.Http11Processor","thread_name":"http-nio-9288-exec-5","level":"DEBUG","level_value":10000}
2020-05-07 09:19:53.631 DEBUG [,,,] 15884 --- [nio-9288-exec-2] org.apache.tomcat.util.net.NioEndpoint   : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5657fb55:org.apache.tomcat.util.net.NioChannel@3503ede7:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9288 remote=/0:0:0:0:0:0:0:1:53787]], Read direct from socket: [590]
{"@timestamp":"2020-05-07T09:19:53.631+05:30","@version":"1","message":"Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@5657fb55:org.apache.tomcat.util.net.NioChannel@3503ede7:java.nio.channels.SocketChannel[connected local=/0:0:0:0:0:0:0:1:9288 remote=/0:0:0:0:0:0:0:1:53787]], Read direct from socket: [590]","logger_name":"org.apache.tomcat.util.net.NioEndpoint","thread_name":"http-nio-9288-exec-2","level":"DEBUG","level_value":10000}
2020-05-07 09:19:53.632 DEBUG [,,,] 15884 --- [nio-9288-exec-5] o.apache.tomcat.util.threads.LimitLatch  : Counting down[http-nio-9288-exec-5] latch=2
2020-05-07 09:19:53.632 DEBUG [,,,] 15884 --- [nio-9288-exec-2] o.a.coyote.http11.Http11InputBuffer      : Received [POST /selfie HTTP/1.1
image: image.jpg
User-Agent: PostmanRuntime/7.24.1
Accept: */*
Cache-Control: no-cache
Postman-Token: ab33c360-fb87-4d3a-914b-f1cfa55d365f
Host: localhost:9288
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: multipart/form-data; boundary=--------------------------794444009395957859673194
Cookie: JSESSIONID=973DAABC39BC3EA594131B3B606EDE07
Content-Length: 169

----------------------------794444009395957859673194
Content-Disposition: form-data; name="image"

image.jpg

@RestController
public class SelfieUploadController {

   private static final Logger LOG = LoggerFactory.getLogger(SelfieUploadController.class);

    private final StorageService storageService;

    @Autowired
    public SelfieUploadController(StorageService storageService) {
        this.storageService = storageService;
    }

    @GetMapping("/")
    public String listUploadedFiles(Model model) throws IOException {

        model.addAttribute("files", storageService.loadAll().map(
                path -> MvcUriComponentsBuilder.fromMethodName(SelfieUploadController.class,
                        "serveFile", path.getFileName().toString()).build().toUri().toString())
                .collect(Collectors.toList()));

        return "uploadForm";
    }

    @GetMapping("/files/{filename:.+}")
    @ResponseBody
    public ResponseEntity<Resource> serveFile(@PathVariable String filename) {

        Resource file = storageService.loadAsResource(filename);
        return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,
                "attachment; filename=\"" + file.getFilename() + "\"").body(file);
    }

    @PostMapping("/")
    public String handleFileUpload(@RequestParam("file") MultipartFile file,
            RedirectAttributes redirectAttributes) {

        storageService.store(file);
        redirectAttributes.addFlashAttribute("message",
                "You successfully uploaded " + file.getOriginalFilename() + "!");

        return "redirect:/";
    }

    @ExceptionHandler(StorageFileNotFoundException.class)
    public ResponseEntity<?> handleStorageFileNotFound(StorageFileNotFoundException exc) {
        return ResponseEntity.notFound().build();
    }

    @PostMapping(value = "/selfie")
    @ApiResponses({
            @ApiResponse(code = 200, message = "Success"),
            @ApiResponse(code = 400, message = "Bad request"),
            @ApiResponse(code = 415, message = "Unsupported Media Type"),
            @ApiResponse(code = 500, message = "Server Error")
    })
    public ResponseEntity<String> updateSelfieImage(
            @RequestParam("files") MultipartFile[] files,
            RedirectAttributes redirectAttributes, HttpSession session)
            throws IOException {
        StringJoiner sj = new StringJoiner(" , ");
        for (MultipartFile file : files) {
            if (file.isEmpty()) {
                continue; // next pls
            }
            try {

                byte[] bytes = file.getBytes();
                Properties prop = new Properties();
                String resourceName = "app.properties";
                ClassLoader loader = Thread.currentThread()
                        .getContextClassLoader();
                InputStream resourceStream = loader
                        .getResourceAsStream(resourceName);
                try {
                    prop.load(resourceStream);
                } catch (IOException e1) {
                    // TODO Auto-generated catch block
                    e1.printStackTrace();
                }
                String image_path = prop.getProperty("selfieSource");
                String dest_path=prop.getProperty("selfieDest");
                Path path = Paths.get(dest_path
                        + file.getOriginalFilename());
                Files.write(path, bytes);

                sj.add(file.getOriginalFilename());

            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        return new ResponseEntity<String>("Success", HttpStatus.OK);

    }

    @GetMapping(value="/selfieImage")
    public @ResponseBody byte[] getImage() throws IOException{
        InputStream in=getClass().getResourceAsStream("/image.jpg");
        return IOUtils.toByteArray(in);

    }

}
Application.yml
spring:
  application:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
server:
  port: 9288

logging:
  level:
    root: DEBUG
    com.tenxbanking: DEBUG

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
 
    git:
      mode: full
  metrics:
    binders:
      jvm.enabled: true
      logback.enabled: true
    export:
      prometheus:
        descriptions: true
        enabled: true
        step: 1m
    distribution:
      percentiles-histogram[http.server.requests]: true
      percentiles:
        http.server.requests: 0.95, 0.99
      sla:
        http.server.requests: 10ms,100ms

selfieSource: C:/Users/sumrawal/Desktop

selfieDest: C:/Users/sumrawal/Pictures

**Comment by debora-ito** [comment]
@sumit4209211 I don't see anything related to AWS SDK for Java in the logs. Can you give us more context of what you're trying to do?

**Comment by roostinghawk** [comment]
Same issue after I upgraded springboot. How did you fixed this issue?
