### ISSUE TITLE
assumeRole throws AWSSecurityTokenServiceException

### ISSUE THREAD

**Issue by rachedanis** [aws/aws-sdk-java#2317]
## Bug description

Can't assume role using stsClient with anonymous Credentials  

## Current Behavior
```java
Exception in thread "main" com.amazonaws.services.securitytoken.model.AWSSecurityTokenServiceException: Request is missing Authentication Token (Service: AWSSecurityTokenService; Status Code: 403; Error Code: MissingAuthenticationToken; Request ID: 4d745eda-d71e-4965-a217-8b86f39730d1; Proxy: null)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1719)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1686)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1675)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRole(AWSSecurityTokenServiceClient.java:589)
        at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRole(AWSSecurityTokenServiceClient.java:561)
        at mytest.Main.test(Main.java:23)
        at mytest.Main.main(Main.java:36)
```

## Steps to Reproduce

I'm using kubernetes with kube2iam ( that's assuming a role "ROLE-1" ( which is able to assume ROLE-2 ) on my pod  ) ( no need to create an AWS config file )

In my pod I have this Main class :

```java
package mytest;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.AnonymousAWSCredentials;
import com.amazonaws.auth.BasicSessionCredentials;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.cloudformation.AmazonCloudFormation;
import com.amazonaws.services.cloudformation.AmazonCloudFormationClientBuilder;
import com.amazonaws.services.securitytoken.AWSSecurityTokenService;
import com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder;
import com.amazonaws.services.securitytoken.model.AssumeRoleRequest;
import com.amazonaws.services.securitytoken.model.AssumeRoleResult;
import com.amazonaws.services.securitytoken.model.Credentials;

public class Main {

    public static void test(String roleArnToAssume, String roleSessionName, Regions region) {
        AWSSecurityTokenService stsClient = AWSSecurityTokenServiceClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(new AnonymousAWSCredentials())).withRegion(region).build();

        AssumeRoleRequest roleRequest = new AssumeRoleRequest().withRoleArn(roleArnToAssume)
                .withRoleSessionName(roleSessionName);
        
        AssumeRoleResult assumeRoleResult = stsClient.assumeRole(roleRequest); // Exception here

        Credentials sessionCredentials = assumeRoleResult.getCredentials();
        BasicSessionCredentials awsCredentials = new BasicSessionCredentials(sessionCredentials.getAccessKeyId(),
                sessionCredentials.getSecretAccessKey(), sessionCredentials.getSessionToken());

        AmazonCloudFormation stackbuilder = AmazonCloudFormationClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(awsCredentials)).withRegion(region).build();

        System.out.println(stackbuilder);
    }
    public static void main(String[] argv) {
        final Regions region = Regions.EU_WEST_1;
        test("arn:aws:iam::ID:role/ROLE-2", "MySession", region);
    }
}

```

## Context
**Without configuring an aws config** and using boto3 python lib, it's working fine : 
```python
 sts_client = boto3.client(
        "sts"
    )
    assumed_role_object = sts_client.assume_role(
        RoleArn="arn:aws:iam::ID:role/ROLE-1",
        RoleSessionName="MySession",
    )
```

**But using Java SDK it throws the exception above.**

## My Environment
* AWS Java SDK version used: 1.11.775
* JDK version used: 11
* Operating System and version: Docker container from image : softinstigate/maven-aws:latest
* Kube2iam : docker.io/jtblin/kube2iam:0.10.9

**Comment by debora-ito** [comment]
@rachedanis I believe it is not possible to call AssumeRole with anonymous credentials. Evidences for this are 1) the `MissingAuthenticationToken` error you are seeing - it indicates the request must contain a valid AWS access key ID as per [API Reference](https://docs.aws.amazon.com/STS/latest/APIReference/CommonErrors.html); and 2) the AWS [IAM User Guide](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#api_assumerole) states that the AssumeRole operation must be called using valid AWS security credentials.

**Comment by ytddqzv** [comment]
How to access the S3 bucket by assume using camel xml beans. The above code is written in java language but i need the code in xml beans like below. can you provide the code in xml beans as i am getting issues for the below code.
 
    <bean class="com.amazonaws.auth.BasicAWSCredentials" id="basicAWSCredentialsBean">
	<constructor-arg name="accessKey" value="accessKey"/>	
	<constructor-arg name="secretKey"  value="secretKey"/>	
	</bean>

	<bean class="com.amazonaws.ClientConfiguration" id="stsClientConfiguration">
	    <property name="protocol" >
	    	<value type="com.amazonaws.Protocol">protocol</value>
	    </property>    
        <property name="proxyHost" value="host"/>
        <property name="proxyPort" >
          <value>port</value>
          </property>
	</bean>
	<bean id="awsCredentialsProvider" class="com.amazonaws.auth.AWSStaticCredentialsProvider">
        <constructor-arg ref="basicAWSCredentialsBean"/>
    </bean>
    
	<bean id="stsClient" class="com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClientBuilder" factory-method="standard">
    <property name="region" value="eu-central-1"/>
    <property name="clientConfiguration" ref="stsClientConfiguration"/>
    <property name="credentials" ref="awsCredentialsProvider"/>
	</bean>

<bean id="assumeRoleRequest" class="com.amazonaws.services.securitytoken.model.AssumeRoleRequest">
      <property name="roleArn" value="arnRole"/>
      <property name="roleSessionName" value="session"/>
    </bean>
    
    

<bean id="s3SessionCredentials" class="com.amazonaws.auth.BasicSessionCredentials">
    <constructor-arg value="#{stsClient.assumeRole(assumeRoleRequest).credentials.accessKeyId}"/>
    <constructor-arg value="#{stsClient.assumeRole(assumeRoleRequest).credentials.secretAccessKey}"/>
    <constructor-arg value="#{stsClient.assumeRole(assumeRoleRequest).credentials.sessionToken}"/>
</bean>

<bean id="s3ClientConfiguration" class="com.amazonaws.ClientConfiguration">
    <property name="protocol" value="HTTPS"/>
    <property name="proxyHost" value="proxy"/>
    <property name="proxyPort" value="8080"/>
</bean>

<bean id="s3Client" class="com.amazonaws.services.s3.AmazonS3ClientBuilder" factory-method="standard">
    <property name="region" value="eu-central-1"/>
    <property name="credentials" ref="s3SessionCredentials"/>
    <property name="clientConfiguration" ref="s3ClientConfiguration"/>
</bean>
