### ISSUE TITLE
Testing SQS with Localstack in Docker trying to connect to localhost:4566

### ISSUE THREAD

**Issue by MatthewEdge** [aws/aws-sdk-java#2342]
When attempting to test SQS Listeners in a local Docker environment the application fails on a Connection Refused error to localhost:4566. Running Localstack in Docker which is exposed on `http://awslocal:4566`.

Running the application outside of Docker (gradle bootRun) works as expected. Running the application inside Docker fails with the connection-refused error.

## Describe the bug

A demo repository is available here: https://github.com/MatthewEdge/boot-sqs-test
Run the following Docker commands:

```
docker-compose up -d localstack
docker-compose up --build app
```

## Expected Behavior

Running the application in Docker and sending an SQS message through the CLI using:

```
aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test
{
    "QueueUrl": "http://localhost:4566/queue/test"
}

aws --endpoint-url=http://localhost:4566 sns create-topic --name test
{
    "TopicArn": "arn:aws:sns:us-east-1:000000000000:test"
}

aws --endpoint-url=http://localhost:4566 sns subscribe --topic-arn arn:aws:sns:us-east-1:000000000000:test --protocol sqs --notification-endpoint arn:aws:sqs:us-east-1:000000000000:test
{
    "SubscriptionArn": "arn:aws:sns:us-east-1:000000000000:test:de195743-b616-4c13-8539-fe17d8e00084"
}

aws --endpoint-url=http://localhost:4566 sns publish --topic-arn arn:aws:sns:us-east-1:000000000000:test --message "TEST"
```

I expect to see the "TEST" message show in the logs of the application.

## Current Behavior

Application fails on startup with the following stacktrace:

```
app_1         | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simpleMessageListenerContainer' defined in class path resource [org/springframework/cloud/aws/messaging/config/annotation/SqsConfiguration.class]: Invocation of init method failed; nested exception is com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to localhost:4566 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
app_1         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
app_1         | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
app_1         | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
app_1         | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
app_1         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
app_1         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
app_1         | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.0.RELEASE.jar!/:2.3.0.RELEASE]
app_1         | 	at com.example.demo.DemoApplication.main(DemoApplication.java:38) ~[classes!/:na]
app_1         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
app_1         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
app_1         | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
app_1         | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
app_1         | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:na]
app_1         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:109) ~[app.jar:na]
app_1         | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:na]
app_1         | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:na]
app_1         | Caused by: com.amazonaws.SdkClientException: Unable to execute HTTP request: Connect to localhost:4566 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1136) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1082) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:745) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:719) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:701) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:669) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:651) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:515) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:2147) ~[aws-java-sdk-sqs-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2116) ~[aws-java-sdk-sqs-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2105) ~[aws-java-sdk-sqs-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueAttributes(AmazonSQSClient.java:1071) ~[aws-java-sdk-sqs-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueAttributes(AmazonSQSClient.java:1042) ~[aws-java-sdk-sqs-1.11.415.jar!/:na]
app_1         | 	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.queueAttributes(AbstractMessageListenerContainer.java:336) ~[spring-cloud-aws-messaging-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
app_1         | 	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.initialize(AbstractMessageListenerContainer.java:293) ~[spring-cloud-aws-messaging-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
app_1         | 	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer.initialize(SimpleMessageListenerContainer.java:111) ~[spring-cloud-aws-messaging-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
app_1         | 	at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.afterPropertiesSet(AbstractMessageListenerContainer.java:268) ~[spring-cloud-aws-messaging-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
app_1         | 	at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer.afterPropertiesSet(SimpleMessageListenerContainer.java:45) ~[spring-cloud-aws-messaging-2.2.1.RELEASE.jar!/:2.2.1.RELEASE]
app_1         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
app_1         | 	... 25 common frames omitted
app_1         | Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:4566 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
app_1         | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156) ~[httpclient-4.5.12.jar!/:4.5.12]
app_1         | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.12.jar!/:4.5.12]
app_1         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
app_1         | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
app_1         | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
app_1         | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
app_1         | 	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.http.conn.$Proxy69.connect(Unknown Source) ~[na:na]
app_1         | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.12.jar!/:4.5.12]
app_1         | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.12.jar!/:4.5.12]
app_1         | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.12.jar!/:4.5.12]
app_1         | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.12.jar!/:4.5.12]
app_1         | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.12.jar!/:4.5.12]
app_1         | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.12.jar!/:4.5.12]
app_1         | 	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1074) ~[aws-java-sdk-core-1.11.415.jar!/:na]
app_1         | 	... 43 common frames omitted
app_1         | Caused by: java.net.ConnectException: Connection refused (Connection refused)
app_1         | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
app_1         | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:na]
app_1         | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:na]
app_1         | 	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:na]
app_1         | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source) ~[na:na]
app_1         | 	at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
app_1         | 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) ~[httpclient-4.5.12.jar!/:4.5.12]
app_1         | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) ~[httpclient-4.5.12.jar!/:4.5.12]
app_1         | 	... 59 common frames omitted
app_1         |
```

## Context

I've tried many iterations of credentials configuration, Endpoint configuration, with/without Spring in the mix, etc with no success running in Docker. I cannot figure out what piece of code is insisting to look at `localhost:4566` instead of `http://awslocal:4566`. It seems to be somewhere in the AmazonSQS client creation according to my debugging.

Am I missing a configuration item to make this work?

**Comment by MatthewEdge** [comment]
Closing as this appears to be a value returned by Localstack. In case anyone else is googling this: set the `HOSTNAME_EXTERNAL` environment variable on your Localstack Docker container to have it respond with the correct hostname. For example:

```
  localstack:
    image: localstack/localstack
    container_name: awslocal
    hostname: awslocal
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      HOST_TMP_FOLDER: /tmp/localstack
      HOSTNAME_EXTERNAL: awslocal
    ports:
      - "4566:4566"
      - "8055:8080"
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by hieudiginex** [comment]
Hi @MatthewEdge 

Thank you so much for posting this 💯 . I experienced the same issue and I have no idea why I have try to set all the properties correctly but it always try to connect to localhost. 
Stuck for a couple days day until I found your comment. 

I own you a beer :D 🙇‍♂️

**Comment by schowdiah** [comment]
I declared HOSTNAME_EXTERNAL in my docker-compose and I am still seeing the same problem

**Comment by ritr12** [comment]
Found a good explanation on why we need to set the HOSTNAME_EXTERNAL property, though of sharing it here https://www.w3spot.com/2021/06/how-to-solve-localstack-always-connecting-to-localhost.html

**Comment by arunkumarg26** [comment]
@MatthewEdge , I'm still facing the same issue. Here is my docker compose 

``` localstack:
    image: localstack/localstack
    container_name: awslocal
    hostname: awslocal
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      HOST_TMP_FOLDER: /tmp/localstack
      HOSTNAME_EXTERNAL: awslocal
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
      - "8055:8080"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      ```
and when I tried getting the list of queues by using aws --endpoint-url=http://awslocal:4566 sqs list-queues, I'm getting 
Could not connect to the endpoint URL: "http://awslocal:4566/"

Could you please assist @MatthewEdge

**Comment by Kumel-Ahmed** [comment]
@arunkumarg26 , were you able to resolve this? I am kinda a stuck with the same problem. would appreciate If somebody could help me get this resolved

MBP:~$aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name hello-world
{
    "QueueUrl": "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/hello-world"
}

MBP:~$aws --endpoint-url=http://awslocal:4566 sqs create-queue --queue-name hello-world

Could not connect to the endpoint URL: "http://awslocal:4566/"


// docker-compose.yml
  localstack:
    container_name: awslocal
    hostname: awslocal
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,sqs
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp/localstack
      - HOSTNAME_EXTERNAL=awslocal
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

**Comment by murtaza-n26** [comment]
@Kumel-Ahmed consider setting the following property in your env variables:
SQS_ENDPOINT_STRATEGY=off

more details here: https://docs.localstack.cloud/user-guide/aws/sqs/#queue-urls

**Comment by magicianseeker** [comment]
> @Kumel-Ahmed consider setting the following property in your env variables: SQS_ENDPOINT_STRATEGY=off
> 
> more details here: https://docs.localstack.cloud/user-guide/aws/sqs/#queue-urls

Mine's working after change it to `dynamic` so I use this:
```
localstack:
    image: localstack/localstack:3.5
    restart: always
    container_name: awslocal
    hostname: awslocal
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs
      - DEBUG=1
      - AWS_EXECUTION_ENV=True
      - DEFAULT_REGION=ap-southeast-1
      - AWS_DEFAULT_REGION=ap-southeast-1
      - HOSTNAME_EXTERNAL=awslocal
      - SQS_ENDPOINT_STRATEGY=dynamic
    volumes:
      - ./.localstack:/tmp
```

**Comment by nMark007** [comment]
I had the same problem with not being able to validate the cert with the localstack during by spring-boot bootrun, I have tried all the suggestions provided, but the problem in my application was there was a wrong URL of the queues in my properties files I dug a little deep and found that the local stack building the rest urls differently. Thought it would help if you check the URL properties being passed while using java AmazonSQS.

`version: '3.0'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: awslocal
    hostname: awslocal
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - EDGE_PORT=4566
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=awslocal
      - SQS_ENDPOINT_STRATEGY=dynamic
      - AWS_EXECUTION_ENV=True
    ports:
      - '4566-4597:4566-4597'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"`
This is the command I used to create the Queue: 
      ` aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name "local_sqs"`
This is the URL:
      `http://localhost:4566/queue/us-east-1/000000000000/local_sqs`
I hope it's helpful.
Thank you
