### ISSUE TITLE
AbortedException in REST API SDK generated via API Gateway

### ISSUE THREAD

**Issue by sachin-dimble** [aws/aws-sdk-java#2350]
aws-sdk version - 1.11.792
Java Version - 1.8
Solution stack - 64bit Amazon Linux 2018.03 v2.10.7 running Java 8

This is custom sdk generated through AWS API gateway using swagger, the client and rest service both runs on aws cloud however client system is throwing the 'com.amazonaws.AbortedException' intermittently and occurrences in log is quite high. I contacted the support team but they said since its not related to service i should raise the issue here for developers. 

I would also like to track number of active connections in pool when this exception happens, is there a way in existing sdk api to trace the http connection level details?

Things I tried - Increasing max connections and socket timeout, thinking that thread interruption is happening due to time out but this doesn't help.

Complete stack trace -

com.amazonaws.AbortedException:
at com.amazonaws.internal.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:61)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:89)
	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:140)
	at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:160)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:160)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1297)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.client.ClientHandlerImpl.doInvoke(ClientHandlerImpl.java:204)
	at com.amazonaws.client.ClientHandlerImpl.invoke(ClientHandlerImpl.java:185)
	at com.amazonaws.client.ClientHandlerImpl.execute(ClientHandlerImpl.java:93)
	at com.amazonaws.opensdk.protect.client.SdkClientHandler.execute(SdkClientHandler.java:42)

I also looked for other similar issues reported here but team has closed it without the resolution. Appreciate any pointer/help on this issue.

Thanks.

**Comment by debora-ito** [comment]
@sachin-dimble `AbortedException` is thrown if the thread is interrupted while it's executing the request. If it was caused by a timeout configured in the SDK you'd probably see a Timeout Exception instead of Aborted, so it is very likely something other than the SDK is interrupting the thread, and that is why tuning the timeouts is having no effect.

You can enable [AWS Java SDK Metrics](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/generating-sdk-metrics.html) to gather more information about your application. If you also enable [Latency Metrics Logging](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-latency-logging), request metrics including connection pool stats will also get added to the logs.

**Comment by sachin-dimble** [comment]
@debora-ito Below are the aws latency metrics when this exception occurred -
`ServiceName=[LandFlagApi], StatusCode=[201], ServiceEndpoint=[https://land-flag-api.qual.us.i01.c01.johndeerecloud.com], Exception=[com.amazonaws.AbortedException: ], RequestType=[CreateFlagCategoryByOrgIdRequest], HttpClientPoolPendingCount=0, RetryCapacityConsumed=0, HttpClientPoolAvailableCount=8, RequestCount=1, Exception=1, HttpClientPoolLeasedCount=6, RequestMarshallTime=[0.031], ResponseProcessingTime=[0.069], ClientExecuteTime=[84.206], HttpClientSendRequestTime=[0.04], HttpRequestTime=[83.924], ApiCallLatency=[84.15], RequestSigningTime=[0.066], CredentialsRequestTime=[0.002, 0.0], HttpClientReceiveResponseTime=[83.784], `  

Please let me know if you need further details.
