### ISSUE TITLE
Does TransferManager support multi instance transfer?

### ISSUE THREAD

**Issue by kiril-dayradzhiev** [aws/aws-sdk-java#2363]
Hi there,
In the code below you can see a test using 2 mocked(embedded) instances of S3, running on different ports. I have a source instance and destination instance, respectively using a source and destination bucket and region. The test that I am performing creates an object in the source instance/region/bucket using TransferManager trying to copy the object to a destination instance/region/bucket and verifying that the object is transferred. 
This test fails because it cannot find the source bucket in the destination instance, so my question is this a feature that is not supported by TransferManager if yes, is there something else that I can use as an alternative? 

```
import static org.assertj.core.api.Assertions.assertThat;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.stream.Collectors;

import org.awaitility.Awaitility;
import org.awaitility.Duration;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.AnonymousAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.CopyObjectRequest;
import com.amazonaws.services.s3.transfer.Copy;
import com.amazonaws.services.s3.transfer.TransferManager;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;
import io.findify.s3mock.S3Mock;

public class TransferManagerCopyTest {
    public static final int SOURCE_S3_PORT = 8796;
    public static final int DESTINATION_S3_PORT = 8797;

    public static final String SOURCE_REGION = "us-east-1";
    public static final String DESTINATION_REGION = "us-west-1";

    public static final String SOURCE_BUCKET = "source-bucket";
    public static final String DESTINATION_BUCKET = "destination-bucket";

    public static final String OBJECT_KEY = "file/name";
    public static final String OBJECT_CONTENT = "content";

    private S3Mock sourceS3;
    private S3Mock destinationS3;

    private AmazonS3 sourceS3Client;
    private AmazonS3 destinationS3Client;

    @Before
    public void setUp() {
        sourceS3 = new S3Mock.Builder().withPort(SOURCE_S3_PORT).withInMemoryBackend().build();
        sourceS3.start();
        destinationS3 = new S3Mock.Builder().withPort(DESTINATION_S3_PORT).withInMemoryBackend().build();
        destinationS3.start();

        sourceS3Client = createS3Client(SOURCE_S3_PORT, SOURCE_REGION);
        destinationS3Client = createS3Client(DESTINATION_S3_PORT, DESTINATION_REGION);

        sourceS3Client.createBucket(SOURCE_BUCKET);
        destinationS3Client.createBucket(DESTINATION_BUCKET);

    }

    @After
    public void tearDown() {
        sourceS3.shutdown();
        destinationS3.shutdown();
    }

    @Test
    public void test() throws InterruptedException {
        sourceS3Client.putObject(SOURCE_BUCKET, OBJECT_KEY, OBJECT_CONTENT);

        TransferManager transferManager = TransferManagerBuilder.standard()
                .withS3Client(destinationS3Client)
                .build();

        CopyObjectRequest copyRequest = new CopyObjectRequest(SOURCE_BUCKET, OBJECT_KEY,
                DESTINATION_BUCKET, OBJECT_KEY);

        Copy copy = transferManager.copy(copyRequest, sourceS3Client, null);
        copy.waitForCopyResult();

        Awaitility.await()
                .atMost(Duration.ONE_MINUTE)
                .untilAsserted(() -> assertThat(getObjectContent()).isEqualTo(OBJECT_CONTENT));
    }

    private String getObjectContent() {
        try {
            InputStream contentStream = destinationS3Client.getObject(DESTINATION_BUCKET, OBJECT_KEY)
                    .getObjectContent()
                    .getDelegateStream();

            return new BufferedReader(new InputStreamReader(contentStream, StandardCharsets.UTF_8))
                    .lines()
                    .collect(Collectors.joining("\n"));
        } catch (Exception ex) { // NOSONAR
            return null;
        }

    }

    private AmazonS3 createS3Client(int port, String region) {
        EndpointConfiguration endpoint = new EndpointConfiguration(String.format("http://localhost:%s", port), region);
        return AmazonS3ClientBuilder
                .standard()
                .withPathStyleAccessEnabled(true)
                .withEndpointConfiguration(endpoint)
                .withCredentials(new AWSStaticCredentialsProvider(new AnonymousAWSCredentials()))
                .build();
    }
}

```

**Comment by debora-ito** [comment]
TransferManager supports it, according to the Copy [docs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#copy-com.amazonaws.services.s3.model.CopyObjectRequest-com.amazonaws.services.s3.AmazonS3-com.amazonaws.services.s3.transfer.internal.TransferStateChangeListener-):
> Note: You need to use this method if the TransferManager is created with a regional S3 client and the source & destination buckets are in different regions.


I don't know if S3Mock supports it. For example, would the destination client have permission to access the source resources?

What's the error you're seeing?

**Comment by kiril-dayradzhiev** [comment]
It cannot find the source bucket in the destination instance(I will paste the entire stacktrace below), if such bucket is created it cannot find the object itself. The actual usage that I have in my mind is transferring(replicating) objects between different object store(cloud) cloud providers(for example from AWS S3 to GCP object store[via minio] or vice versa, or AZURE to AWS or vice versa). I have tested it also with AWS to GCP(via minio) setup and still getting the same problem(it is not S3Mock specific). So is such cross-cloud transfer supported?


Stacktrace:
```
Jun 17, 2020 9:42:08 AM io.findify.s3mock.route.CopyObject $anonfun$route$4
INFO: cannot copy object source-bucket/file/name: no such bucket

com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: null; S3 Extended Request ID: null)
, S3 Extended Request ID: null
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1799)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1383)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1359)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4914)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4860)
	at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1996)
	at com.amazonaws.services.s3.transfer.internal.CopyCallable.copyInOneChunk(CopyCallable.java:145)
	at com.amazonaws.services.s3.transfer.internal.CopyCallable.call(CopyCallable.java:133)
	at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:132)
	at com.amazonaws.services.s3.transfer.internal.CopyMonitor.call(CopyMonitor.java:43)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by debora-ito** [comment]
S3Mock does not list TransferManager as a supported library in their [README](https://github.com/findify/s3mock/blob/master/README.md), I suggest you open an issue in their repo to ask about the port configuration - I found one open issue using TransferManager upload ([link](https://github.com/findify/s3mock/issues/72#issuecomment-460571422)).

> So is such cross-cloud transfer supported?

No, TransferManager only supports AWS S3, but that's an interesting use case.

**Comment by kiril-dayradzhiev** [comment]
Do you have any plans supporting such functionality :) ?
