### ISSUE TITLE
Error when creating node group for an eks cluster

### ISSUE THREAD

**Issue by ArundathiGV** [aws/aws-sdk-java#2373]
## Describe the bug
When creating a node group for EKS cluster the following exception is returned com.amazonaws.services.eks.model.InvalidParameterException: desiredSize is not valid (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 16eae0bb-fcf0-4069-96c1-a7a10a164821; Proxy: null)

## Expected Behavior
The node group to be created.

## Current Behavior
The following exception is thrown:
com.amazonaws.services.eks.model.InvalidParameterException: desiredSize is not valid (Service: AmazonEKS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 16eae0bb-fcf0-4069-96c1-a7a10a164821; Proxy: null)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.eks.AmazonEKSClient.doInvoke(AmazonEKSClient.java:1822)
        at com.amazonaws.services.eks.AmazonEKSClient.invoke(AmazonEKSClient.java:1789)
        at com.amazonaws.services.eks.AmazonEKSClient.invoke(AmazonEKSClient.java:1778)
        at com.amazonaws.services.eks.AmazonEKSClient.executeCreateNodegroup(AmazonEKSClient.java:457)
        at com.amazonaws.services.eks.AmazonEKSClient.createNodegroup(AmazonEKSClient.java:428)

## Steps to Reproduce
            RemoteAccessConfig remoteAccess = new RemoteAccessConfig().withEc2SshKey(eks.getKeyName())
                .withSourceSecurityGroups(eks.getNodeSecurityGroups());

            NodegroupScalingConfig scalingConfig = new NodegroupScalingConfig()
                .withDesiredSize(Integer.valueOf(eks.getDesiredNodeCount()))
                .withMaxSize(Integer.valueOf(eks.getMaxNodeCount()))
                .withMinSize(Integer.valueOf(eks.getMaxNodeCount()));

            CreateNodegroupRequest createNodegroupRequest = new CreateNodegroupRequest()
                .withClusterName(eks.getClusterName())
                .withDiskSize(Integer.getInteger(eks.getNodeVolumeSize()))
                .withNodegroupName(eks.getStackName())
                .withInstanceTypes(eks.getInstanceTypes())
                .withAmiType(eks.getAmiType())
                .withNodeRole(eks.getNodeRoleArn())
                .withSubnets(eks.getSubnetId())
                .withRemoteAccess(remoteAccess)
                .withScalingConfig(scalingConfig);

            CreateNodegroupResult result = client.createNodegroup(createNodegroupRequest);
## Your Environment

* AWS Java SDK version used:1.11.811
* JDK version used:13.0.2

**Comment by debora-ito** [comment]
Hi @ArundathiGV you are providing the same value `eks.getMaxNodeCount()` for both minSize and maxSize node count in scaling config:
```
...
    .withMaxSize(Integer.valueOf(eks.getMaxNodeCount()))
    .withMinSize(Integer.valueOf(eks.getMaxNodeCount()));
```

The Desired size is expected to be between Minimum and Maximum. In this case, if you are providing a desired size different from `eks.getMaxNodeCount()` you'll get the exception.

Let us know if that helps.
