### ISSUE TITLE
Uncaught java.lang.Error stalls whole http client connections pool

### ISSUE THREAD

**Issue by fathersson** [aws/aws-sdk-java#239]
I've faced an issue that AmazonKinesisClient leased all 50 (default number) http connections and didn't release them back. As it turns out I had a jvm flag -Xss160k, which leads to java.lang.StackOverflowError. Because of that my threads were basically killed, but  dying they do not release http connection inside the ApacheHttpClient.
I believe it make sense to catch throwable inside that AmazonHttpClient to at least release http connection and ideally to log the error.

Here are additional details of my case.
java.lang.StackOverflowError
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:150)
        at java.net.SocketInputStream.read(SocketInputStream.java:121)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
        at sun.security.ssl.InputRecord.read(InputRecord.java:480)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:884)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:166)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:90)
        at org.apache.http.impl.io.SocketInputBuffer.isDataAvailable(SocketInputBuffer.java:101)
        at org.apache.http.impl.conn.LoggingSessionInputBuffer.isDataAvailable(LoggingSessionInputBuffer.java:78)
        at org.apache.http.impl.AbstractHttpClientConnection.isStale(AbstractHttpClientConnection.java:318)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.isStale(ManagedClientConnectionImpl.java:152)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:467)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:402)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:245)
        at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2130)
        at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecord(AmazonKinesisClient.java:499)

The only way for to me to catch this guy was to amend my ExecutorService (that runs Runnables that send PutRequest) with following.
        executorService = Executors.newFixedThreadPool(DEFAULT_NUMBERS_OF_WRITER,
                new ThreadFactoryBuilder()
                        .setUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
                            @Override
                            public void uncaughtException(Thread t, Throwable e) {
                                log.error("Uncaught exception:", e);
                            }
                        })
                        .build()
                );

**Comment by manikandanrs** [comment]
From the previous comments, I see the issue has been resolved. Please feel free to re open if you still see any issues.
