### ISSUE TITLE
StringIndexOutOfBounds exception while building s3 client with 1.11.621 aws version

### ISSUE THREAD

**Issue by Shreyabol** [aws/aws-sdk-java#2401]
started getting below exception from july inly, earlier it worked fine::

java.lang.StringIndexOutOfBoundsException: String index out of range: -21
	at java.lang.String.substring(String.java:1931)
	at org.springframework.boot.loader.jar.JarURLConnection.<init>(JarURLConnection.java:86)
	at org.springframework.boot.loader.jar.Handler.openConnection(Handler.java:88)
	at java.net.URL.openConnection(URL.java:1002)
	at sun.misc.URLClassPath$Loader.findResource(URLClassPath.java:715)
	at sun.misc.URLClassPath.findResource(URLClassPath.java:225)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:572)
	at java.net.URLClassLoader$2.run(URLClassLoader.java:570)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findResource(URLClassLoader.java:569)
	at org.springframework.boot.loader.LaunchedURLClassLoader.findResource(LaunchedURLClassLoader.java:87)
	at org.springframework.boot.loader.LaunchedURLClassLoader.getResource(LaunchedURLClassLoader.java:76)
	at com.amazonaws.util.ClassLoaderHelper.getResourceViaContext(ClassLoaderHelper.java:91)
	at com.amazonaws.util.ClassLoaderHelper.getResource(ClassLoaderHelper.java:70)
	at com.amazonaws.internal.config.InternalConfig.getResource(InternalConfig.java:294)
	at com.amazonaws.internal.config.InternalConfig.load(InternalConfig.java:279)
	at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(InternalConfig.java:336)
	at com.amazonaws.util.VersionInfoUtils.userAgent(VersionInfoUtils.java:142)
	at com.amazonaws.util.VersionInfoUtils.initializeUserAgent(VersionInfoUtils.java:137)
	at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:100)
	at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:78)
	at com.helper.aws.S3Helper.<init>(S3Helper.java:45)

**Comment by debora-ito** [comment]
Hi @Shreyabol, to be able to help you out I'll need more details, details we ask you to fill in the issue template. So please provide:

- A sample code I can use to reproduce the issue
- The Java version and OS you're using
- Which version of the AWS SDK you changed from

**Comment by Shreyabol** [comment]
> * A sample code I can use to reproduce the issue:

AmazonS3 client = AmazonS3ClientBuilder.standard().withRegion(region).build();

> * The Java version and OS you're using:

       spring version:  2.1.9.RELEASE
       


> * Which version of the AWS SDK you changed from:

did not change any version, using 1.11.621 only.

**Comment by Shreyabol** [comment]
Also this stacktrace is coming on datadog . It is happening whenever I am trying to deploy code to ecs.
