### ISSUE TITLE
Uploading a file in AWS Lambda crashes the Lambda

### ISSUE THREAD

**Issue by coding-bunny** [aws/aws-sdk-java#2406]
## Describe the bug
We have a Lambda function written in Scala, running on the Java 8 environment of our AWS.
The source code is based on the AWS-SDK and online documentation on how to write functions.
Whenever we try to use the `S3Client.putObject`, our Lambda crashes with a stacktrace, resulting in a non-working application stack.

## Expected Behavior
I expect the upload to simply work

## Current Behavior
We have created a simple class called `S3Upload` that has a dedicated function for uploading a file to the correct S3 Bucket. The function looks like this:

```
object S3Upload {

  private val s3BucketName : String = scala
    .util
    .Properties
    .envOrElse("AWS_S3_BUCKET", "represent-com-separo")
  private val s3Client : AmazonS3 = AmazonS3ClientBuilder.defaultClient()

  def uploadFile(data: Array[Byte], s3Path: String, contentType: String, logger: LambdaLogger)
    (implicit executor: ExecutionContext): Future[S3UploadUrls] = {

    logger.log(s"Starting upload of file $s3Path to S3 Bucket $s3BucketName.")

    val stream : ByteArrayInputStream = new ByteArrayInputStream(data)
    val key : String = s3Path.replaceAll(" ", "_")
    val metadata : ObjectMetadata = new ObjectMetadata()

    // Set the Content-Type and Content-Length for the object being uploaded.
    // This is required according the AWS SDK documentation
    metadata.setContentType(contentType)
    metadata.setContentLength(data.length)

    Future {
      s3Client.putObject(s3BucketName, key, stream, metadata)
      urlsFromPath(key)
    }
  }

  def uploadImageAsPng(image: Image[PackedSRgb], s3Path: String, logger: LambdaLogger)
    (implicit executor: ExecutionContext): Future[S3UploadUrls] = {
    val output = using(new ByteArrayOutputStream) { outputStream =>
      ImageOutput.saveAsPngToStream(image, outputStream)
      outputStream
    }
    uploadFile(output.toByteArray, s3Path, ImageType.Png.PrimaryMimeType, logger)
  }
}
```

The function is really nothing special, and just wraps the functionality for uploading a processed image to a specific path on one of our S3 Buckets. However, every time it reaches the `s3Client.putObject` line, it crashes with the following:

```
Caused by: java.lang.ClassCastException: class org.apache.http.client.utils.URIUtils$UriFlag not an enum
at java.util.EnumSet.noneOf(EnumSet.java:112)
at org.apache.http.client.utils.URIUtils.<clinit>(URIUtils.java:66)
... 29 more
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5140)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5086)
at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:394)
at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6032)
at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1812)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1772)
at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1710)
at com.represent.separo.lambda.S3Upload$$anonfun$uploadFile$1.apply(S3Upload.scala:84)
at com.represent.separo.lambda.S3Upload$$anonfun$uploadFile$1.apply(S3Upload.scala:83)
at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.ExceptionInInitializerError
at org.apache.http.impl.client.CloseableHttpClient.determineTarget(CloseableHttpClient.java:93)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1330)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
Finished palette extraction with size 4 for image https://separo-dashboard-staging.s3.amazonaws.com/normalized_artworks/52df319d28c11d8c2718007dfea0f4ec.png
Starting upload of file proofs/a4fc0a9068e34877b4dc4c24c09fd95e/proof-size-4.png to S3 Bucket customink-separo-staging.
11:20:29.542 DEBUG c.r.s.p.ExtractProductionPalette$ - Extracted a production palette: 4 colors: [#19f438, #ffb303, #d803e9, #1b000a]
11:20:29.538 DEBUG c.r.s.palette.PaletteSubsetSelector$ - Palette fitness after hill climbing: 0.04783009
11:20:29.398 DEBUG c.r.s.palette.PaletteSubsetSelector$ - Palette fitness after simulated annealing: 0.04783009
```

Based on the output, I can see it definitely enters our function, and writes the log entries to CloudWatch.
The stacktrace definitely mentions the call of the `putObject` functionality, so that's why I'm blaming the SDK for now.

## Context
At the moment our Lambda is simply not functional. We're in the process of updating the entire source of this things to be more up to date, and actually rely on the SDK instead of the open-source projects we used in the past.
We have a functional version in production using the old code, so it's not a permission/configuration problem.

## Your Environment
* AWS Java SDK version used: 1.11.845
* JDK version used: OpenJDK 8, Scala 2.11.12
* Operating System and version: Linux distro from Amazon

**Comment by coding-bunny** [comment]
Okay, I've added the `sbt-dependency-graph` plugin to our project so I can visualize the dependency trees.
I've started with the JAR filethat we actually upload to the Lambda, and it has the following entry for the `httpclient`:

```
[info] org.apache.commons:commons-math3:3.6.1
[info] org.apache.httpcomponents:httpclient:4.5.9
[info] org.apache.httpcomponents:httpcore:4.4.11
```

I've also taken a look at the `core` jar, an additional project that we build, and include in the top one, but this one does not have a reference to the `httpclient`.
Last, I checked the web-project that's actually calling the Lambda:

```
[info] org.apache.commons:commons-lang3:3.4
[info] org.apache.commons:commons-math3:3.6.1
[info] org.apache.httpcomponents:httpclient:4.5.9
[info] org.apache.httpcomponents:httpcore:4.4.11
```

So it seems all components in our setup are using the `httpclient` 4.5.9

**Comment by coding-bunny** [comment]
I'm going to close this issue.
It seems the problem was caused by ProGuard, which most likely threw out some dependencies it considered "not used".
Swapping to `sbt-assembly` and living with the fact our JAR file will be 60MB makes it all work right now.
