### ISSUE TITLE
	Setting ClientExecutionTimeout on AmazonDynamoDB causes Kinesis exceptions

### ISSUE THREAD

**Issue by shadowstriker9** [aws/aws-sdk-java#2426]
## Describe the bug
Recently I tried [setting `ClientExecutionTimeout`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#withClientExecutionTimeout-int-) to have a timeout for ddb queries, and it worked as expected in local and staging, but once it was released to production we started getting a ton of kinesis errors like below. The application works with no problems when `ClientExecutionTimeout` is not set, and we are unable to reproduce the errors in local or staging so far. 

## Expected Behavior
Setting the `ClientExecutionTimeout` for ddb queries should not cause kinesis exceptions

## Current Behavior
```
[http-nio-8080-exec-312] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.amazonaws.services.kinesis.producer.DaemonException: The child process has been shutdown and can no longer accept messages.] with root cause
com.amazonaws.services.kinesis.producer.DaemonException: The child process has been shutdown and can no longer accept messages.
	at com.amazonaws.services.kinesis.producer.Daemon.add(Daemon.java:176)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:536)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:349)
```

```
[http-nio-8080-exec-312] WARN  o.a.c.connector.CoyoteAdapter - Exception while attempting to add an entry to the access log
com.amazonaws.services.kinesis.producer.DaemonException: The child process has been shutdown and can no longer accept messages.
	at com.amazonaws.services.kinesis.producer.Daemon.add(Daemon.java:176)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:536)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:349)
```

```
[http-nio-8080-exec-367] ERROR c.a.s.k.producer.KinesisProducer - Error in child process
java.lang.RuntimeException: Unexpected error
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:521)
	at com.amazonaws.services.kinesis.producer.Daemon.fatalError(Daemon.java:501)
	at com.amazonaws.services.kinesis.producer.Daemon.add(Daemon.java:183)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:536)
	at com.amazonaws.services.kinesis.producer.KinesisProducer.addUserRecord(KinesisProducer.java:349)
...
Caused by: java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
	at com.amazonaws.services.kinesis.producer.Daemon.add(Daemon.java:181)
```

```
[kpl-daemon-0007] WARN  c.a.s.kinesis.producer.Daemon - Exception during updateCredentials
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at com.amazonaws.services.kinesis.producer.Daemon$5.run(Daemon.java:321)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Context
We want to be able to set a timeout for our ddb requests so that if the requests take too long our app will stop waiting for them.

## Your Environment

* AWS Java SDK version used: 
```
com.amazonaws:aws-java-sdk-core:1.11.259
com.amazonaws:aws-java-sdk-dynamodb:1.11.259
com.amazonaws:aws-java-sdk-kinesis:1.11.490
com.amazonaws:amazon-kinesis-producer:0.12.8
```
* JDK version used:
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
* Operating System and version:
```
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

**Comment by debora-ito** [comment]
Hi @shadowstriker9 setting a ClientConfiguration in a DynamoDB client should not impact other clients. Was this the only change made in the production environment? 

In addition, we recommend the use of all SDK modules in the same version, otherwise you may run into weird runtime errors - in your case, aws-java-sdk-kinesis version is different from dynamodb and core.

That said, we are not the owners of `amazon-kinesis-producer`, I don't have enough knowledge to troubleshoot. I suggest you open an issue in the KPL repository: https://github.com/awslabs/amazon-kinesis-producer

**Comment by shadowstriker9** [comment]
Hello @debora-ito, thank you for your response. That was the only change when the errors started appearing, and the errors all disappeared after we reverted the change. However in order to set the `ClientExecutionTimeout` value we changed the way we instantiated our `AmazonDynamoDB` object a little - the old code was directly instantiating a `AmazonDynamoDBAsyncClient` object with the deprecated constructor, the new code uses `AmazonDynamoDBAsyncClientBuilder`. Let me try to release the instantiation change without setting `ClientExecutionTimeout` to see if we still get the errors or not.

**Comment by debora-ito** [comment]
@shadowstriker9 any luck?

**Comment by shadowstriker9** [comment]
@debora-ito Sorry for the slow response, the instantiation change is set to go into production sometime this week.

**Comment by debora-ito** [comment]
Marking this to auto close soon, just reply with a comment if you are still seeing the issue.

**Comment by shadowstriker9** [comment]
I deployed some of the instantiation change without seeing any errors, so I still suspect using the timeout is what's causing the issue, however it looks like we will be going in a different direction and won't end up trying to use the timeout anymore.
