### ISSUE TITLE
Java AmazonDynamoDBClient swallows exception

### ISSUE THREAD

**Issue by umeetiusbaar** [aws/aws-sdk-java#2436]
## Describe the bug
When saving data to DynamoDB with 
DynamoDBMapper.batchWrite(Iterable<? extends Object> objectsToWrite,
                                        Iterable<? extends Object> objectsToDelete,
                                        DynamoDBMapperConfig config)
if there is an exception of type "HTTP/1.1 413 Request Entity Too Large" the Exception is logged but not thrown so the caller thinks all went well. 

## Expected Behavior
I'd expect an exception to be thrown for the caller so that the error can be handled accordingly.

## Current Behavior
The Exception is logged but swallowed - caller thinks the request went ok.

```
2020-10-18 09:03:31,009|INFO |JsonErrorResponseHandler                |Unable to unmarshall exception content
java.lang.NullPointerException: null
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:2745)
	at com.amazonaws.transform.JsonErrorUnmarshaller.unmarshall(JsonErrorUnmarshaller.java:52)
	at com.amazonaws.http.JsonErrorResponseHandler.unmarshallException(JsonErrorResponseHandler.java:108)
	at com.amazonaws.http.JsonErrorResponseHandler.createException(JsonErrorResponseHandler.java:96)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:63)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33)
	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:53)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:41)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:26)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1694)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:4279)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4246)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeBatchWriteItem(AmazonDynamoDBClient.java:695)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.batchWriteItem(AmazonDynamoDBClient.java:661)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.doBatchWriteItemWithRetry(DynamoDBMapper.java:1334)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.writeOneBatch(DynamoDBMapper.java:1276)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.batchWrite(DynamoDBMapper.java:1247)
```

The swallowing happens at com.amazonaws.http.JsonErrorResponseHandler.unmarshallException:
```
    private AmazonServiceException unmarshallException(String errorCode, JsonContent jsonContent) {
        for (JsonErrorUnmarshaller unmarshaller : unmarshallers) {
            if (unmarshaller.matchErrorCode(errorCode)) {
                try {
                    return unmarshaller.unmarshall(jsonContent.getJsonNode());
                } catch (Exception e) {
                    LOG.info("Unable to unmarshall exception content", e);
                    return null;
                }
            }
        }
        return null;
    }
```
The NullPointerException occurs here at com.amazonaws.transform.JsonErrorUnmarshaller because jsonContent.getJsonNode() returns null (well, actually it happens inside treeToValue but the reason is the same: jsonContent.getJsonNode() is null):
```
    @Override
    public AmazonServiceException unmarshall(JsonNode jsonContent) throws Exception {
        return MAPPER.treeToValue(jsonContent, exceptionClass);
    }

```
Going up in stack trace I can locate that real error mentioned above: HTTP/1.1 413 Request Entity Too Large
It is visible at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest:
```
            final SdkBaseException exception = handleErrorResponse(execOneParams.apacheRequest,
                                                             execOneParams.apacheResponse,
                                                             localRequestContext);

```
Here I can see that execOneParams.apacheRequest contains apacheResponse with the error description. For some reason the error is mistreated during the handleErrorResponse processing.

## Steps to Reproduce
Basically, this error can be reproduced by calling DynamoDBMapper.batchWrite(list-of-objects-too-large, new ArrayList())
My list-of-objects-too-large is this size in the request:
```
[Content-Type: application/x-amz-json-1.0,Content-Length: 29442845,Chunked: false]
```
The list itself has only 2 items but they are too large in size.

I can avoid the error by saving smaller chunks with smaller items at a time. But even when the size is too large the exception should not be swallowed but thrown to the caller.

As stated in https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html the max size of an item is 400 KB and total max size of the batch is 16 MB. In my case both of these rules are violated.

## Possible Solution
Handle the error so that the exception is thrown to the caller 

## Your Environment
* AWS Java SDK version used: 1.11.882
* JDK version used: OpenJDK 11
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
@umeetiusbaar so maybe the issue is why it's passing the initial size validation... Quick question before we investigate it deeper: is the item being returned in the FailedBatch list of batchWrite operation?

**Comment by umeetiusbaar** [comment]
@debora-ito my apologizes, you are quite right and I totally missed that DynamoDB API feature that batchWrite will return the failed batches and I should always check those before concluding whether all was well or not. My too large items are there among the failed batches. So, no need to investigate further. Sorry.
