### ISSUE TITLE
"Error while getting AWS metric list com.amazonaws.services.cloudwatch.model.AmazonCloudWatchException: The security token included in the request is invalid."

### ISSUE THREAD

**Issue by ThanujIn** [aws/aws-sdk-java#2437]
**"Error while getting AWS metric list com.amazonaws.services.cloudwatch.model.AmazonCloudWatchException: The security token included in the request is invalid."** 

Error when using java API calls only at **some servers**.. Error is only for some API calls used to retrieve **AWS Metrics**.. But with same credentials the same API calls retrieves data successfully in other servers like this.

Error while getting AWS metric list
com.amazonaws.services.cloudwatch.model.AmazonCloudWatchException: The security token included in the request is invalid. (Service: AmazonCloudWatch; Status Code: 403; Error Code: InvalidClientTokenId; Request ID: xxxxxxxx-59cb-4d3b-a0b0-224e4b328557)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1799)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1383)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1359)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
        at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:2446)
        at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:2413)
        at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:2402)
        at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.executeListMetrics(AmazonCloudWatchClient.java:1674)
        at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.listMetrics(AmazonCloudWatchClient.java:1646)
        at com.virtusa.gto.polycloud.extractor.extractor.aws.metric.AWSMetricList.getMetricList(AWSMetricList.java:27)
        at com.virtusa.gto.polycloud.extractor.extractor.aws.metric.MetricList.getEBSMetrics(MetricList.java:59)
        at com.virtusa.gto.polycloud.extractor.extractor.aws.metric.Metrics.getMetricData(Metrics.java:43)
        at com.virtusa.gto.polycloud.extractor.extractor.aws.metric.MetricObjectExtractor.ebsObjects(MetricObjectExtractor.java:49)
        at com.virtusa.gto.polycloud.extractor.extractor.aws.metric.AWSMetricsImpl.execute(AWSMetricsImpl.java:37)
        at com.virtusa.gto.polycloud.extractor.extractor.aws.AWSCloudDataFetcher.persistMetrics(AWSCloudDataFetcher.java:78)
        at com.virtusa.gto.polycloud.extractor.job.MetricsJob$MetricsRunnable.run(MetricsJob.java:96)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)

* AWS Java SDK version used: 1.11.728
* JDK version used: openJDK version 12
* Operating System and version: WINDOWS 10

**Comment by debora-ito** [comment]
@ThanujIn `InvalidClientTokenId` indicates that the access key or session token provided is not valid, what you can do is try to identify which configuration can be causing the error. 
You said you get the error only at some servers. Is it intermittent? What's the difference from these servers from the ones that are working?  Is the region configured correctly? Can you reproduce the error locally?
