### ISSUE TITLE
com.amazonaws.SdkClientException: Unable to execute HTTP request: noaa-nexrad-level2

### ISSUE THREAD

**Issue by idoor88** [aws/aws-sdk-java#2445]
Hi, I have the following aws cli command which works:
aws s3 cp s3://noaa-nexrad-level2/2019/05/06/KTLX/ ./  --recursive --no-sign-request

The endpoint is a public s3 bucket, no credentials needed.

Now I need to change to use was-java-sdk:

     String bucket_name = "2019/05/06/KTLX/";
      
     final AmazonS3 s3 = AmazonS3ClientBuilder.standard() 
    		 .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://noaa-nexrad-level2","us-east-1")) 
    		 .withCredentials(new MyCreds())
    		 .build();
      
     ListObjectsV2Result result = s3.listObjectsV2(bucket_name);
     List<S3ObjectSummary> objects = result.getObjectSummaries();
     for (S3ObjectSummary os : objects) {
         System.out.println("* " + os.getKey());
     }

 class MyCreds extends DefaultAWSCredentialsProviderChain {
	       @Override
	       public AWSCredentials getCredentials() {
	               try {
	                     return super.getCredentials();
	                } catch (AmazonClientException ace) { 
	              } 
	             System.out.println("No credentials available; falling back to anonymous access");
	             return null;//new AnonymousAWSCredentials();
	      }
        }

When I run the code, I got the exception:

Exception in thread "main" com.amazonaws.SdkClientException: Unable to execute HTTP request: noaa-nexrad-level2
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4325)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4272)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4266)
	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:876)
	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:840)
	at com.kinetica.s3list.S3List.main(S3List.java:64)
Caused by: java.net.UnknownHostException: noaa-nexrad-level2
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:800)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1495)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1354)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1288)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy4.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1236)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)

 I also tried with s3:// instead of http://...., but I got com.amazonaws.SdkClientException: Unable to execute HTTP request: null
.

**Comment by debora-ito** [comment]
Hi @idoor88 using the `s3://noaa-nexrad-level2/2019/05/06/KTLX/` format is one of the ways to [access a bucket](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro), and in this case `noaa-nexrad-level2` would be the bucket name and `2019/05/06/KTLX/` would be the prefix.

So the client creation would be something like this:

```
String bucket_name = "noaa-nexrad-level2";
String prefix = "2019/05/06/KTLX/";

AmazonS3 s3 = AmazonS3ClientBuilder.standard() 
		 .withCredentials(new MyCreds())
		 .build();
  
ListObjectsV2Result result = s3.listObjectsV2(bucket_name, prefix);
```

See [here](https://docs.aws.amazon.com/AmazonS3/latest/dev/ListingKeysHierarchy.html) for more on object key prefix and delimiters.
Let us know if that helps.
