### ISSUE TITLE
com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset

### ISSUE THREAD

**Issue by romelabed** [aws/aws-sdk-java#2448]
import com.amazonaws.AmazonServiceException;
import com.amazonaws.SdkClientException;
import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.ObjectMetadata;
import com.amazonaws.services.s3.model.PutObjectRequest;
import java.io.File;
import java.io.IOException;

public boolean processRow(StepMetaInterface smi, StepDataInterface sdi) throws KettleException{
	Object[] row = getRow();
 
    if (row == null) {
		setOutputDone();
		return false;
	}

    String fileObjKeyName = getParameter("FILENAME");
    String fileName = getParameter("LOCALDIR");
	String accessKeyId = getParameter("ACCESSKEYID");
	String secretAccessKey = getParameter("SECRETACCESSKEY");
	String bucketName = getParameter("BUCKETNAME");
	Regions clientRegion = Regions.US_EAST_1;
    
    final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(accessKeyId, secretAccessKey);
    AmazonS3 s3Client = (AmazonS3)AmazonS3ClientBuilder.standard().withRegion(clientRegion).withCredentials(new AWSStaticCredentialsProvider(basicAWSCredentials)).build();
    PutObjectRequest request = new PutObjectRequest(bucketName, fileObjKeyName, new File(fileName));
    ObjectMetadata metadata = new ObjectMetadata();
    metadata.setContentType("plain/text");
    metadata.addUserMetadata("title", "NewYorkTimes File MetaData");
    metadata.setSSEAlgorithm(ObjectMetadata.AES_256_SERVER_SIDE_ENCRYPTION);
    request.setMetadata(metadata);
    s3Client.putObject(request);
   	putRow(data.outputRowMeta, row);
    return true;
}

The above code is to load a file into the S3 bucket from Pentaho job  - I think this is path style; 

But as per https://docs.amazonaws.cn/en_us/AmazonS3/latest/dev/VirtualHosting.html#virtual-hosted-style-access, path style access will be depreciated by amazon; 

Have anyone implemented (in Java) file upload into S3 in virtual hosted style?

Because of path style implementation, it generates the following error:

com.amazonaws.SdkClientException: Unable to execute HTTP request: Connection reset
	com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
	com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
	com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5155)
	com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5101)
	com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:396)
	com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6048)
	com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1814)
	com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1774)
	Processor.processRow(Processor.java:36)
	org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClass.processRow(UserDefinedJavaClass.java:1018)
	org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
	java.lang.Thread.run(Thread.java:748)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5155)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5101)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:396)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6048)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1814)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1774)
	at Processor.processRow(Processor.java:36)
	at org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClass.processRow(UserDefinedJavaClass.java:1018)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at com.amazonaws.thirdparty.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at com.amazonaws.thirdparty.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
	at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142)
	at com.amazonaws.thirdparty.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at com.amazonaws.thirdparty.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy62.connect(Unknown Source)
	at com.amazonaws.thirdparty.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at com.amazonaws.thirdparty.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at com.amazonaws.thirdparty.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at com.amazonaws.thirdparty.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at com.amazonaws.thirdparty.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.amazonaws.thirdparty.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1330)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)

* AWS Java SDK version used:
* JDK version used: aws-java-sdk-bundle-1.11.869.jar

**Comment by debora-ito** [comment]
@romelabed the SDK uses virtual hosted style by default for S3 operations (save some edge cases), and using path style hosts would not cause `Connection reset`.

Connection resets are likely due to networking issues, like proxy or firewall configurations. If you're using a proxy check its configuration, and check if you're able to execute other S3 operations or you're seeing this issue only with putObject.

**Comment by romelabed** [comment]
BUCKETNAME = "fioprod-s3-addon-us-east-1/s3-roll-1331";  Do you think the front slash in between could cause issue?

**Comment by debora-ito** [comment]
Yes, slash is an invalid character for bucket names.

**Comment by jrgleason** [comment]
How did you resolve the issues with the char?
