### ISSUE TITLE
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: null (Service: AmazonDynamoDBv2; Status Code: 500

### ISSUE THREAD

**Issue by Anja05** [aws/aws-sdk-java#2451]
Closing this, feel free to reopen if you have further questions.

_Originally posted by @debora-ito in https://github.com/aws/aws-sdk-java/issues/2103#issuecomment-540124019_

Hi @debora-ito
I m facing the similar issue with the below exception details. I m trying to load the item by passing hash key and range key

Exception:

Caused by: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: null (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: null; Request ID: null; Proxy: proxy.****l.de)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[aws-java-sdk-core-1.11.825.jar:?]
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:1974) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1950) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.getItem(AmazonDynamoDBClient.java:1118) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:416) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.load(DynamoDBMapper.java:433) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.load(AbstractDynamoDBMapper.java:85) ~[aws-java-sdk-dynamodb-1.11.99.jar:?]
at com.bmw.cc.serviced

My DynamoDb mapper configuration

    public DynamoDBMapper dynamoDBMapper(final AwsDynamoDbConfiguration awsDynamoDbConfiguration) {
final AmazonDynamoDBClientBuilder amazonDynamoDBClientBuilder = AmazonDynamoDBClientBuilder //
.standard() //
.withCredentials(new AWSStaticCredentialsProvider(
new BasicAWSCredentials(awsDynamoDbConfiguration.getAccessKeyId(),
awsDynamoDbConfiguration.getSecretAccessKey()))); //
if (null != awsDynamoDbConfiguration.getEndpointOverride()) {
amazonDynamoDBClientBuilder.withEndpointConfiguration(
new com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration(
awsDynamoDbConfiguration.getEndpointOverride().toString(),
awsDynamoDbConfiguration.getRegion())).build();
} else {
amazonDynamoDBClientBuilder.withRegion(awsDynamoDbConfiguration.getRegion());
}
    return new DynamoDBMapper(amazonDynamoDBClientBuilder.build(), DynamoDBMapperConfig.builder()
            .withTableNameOverride(
                    new DynamoDBMapperConfig.TableNameOverride(awsDynamoDbConfiguration.getTableName())) //
            .withSaveBehavior(DynamoDBMapperConfig.SaveBehavior.UPDATE).build());
}
the place where it throws exception
this.dynamoDBMapper.load(ServiceDemand.class, vin, cbsId);

Please suggest what could be the issue

@shorea please suggest

**Comment by debora-ito** [comment]
@Anja05 you are using a version of the `aws-java-sdk-dynamodb` (1.11.99) that is different from `aws-java-sdk-core` (1.11.825), this can cause unexpected runtime errors. We recommend using all modules in the same version as core.

Status code 500 is Internal Server Error, which indicates an issue on the server side like service unavailability. 

How often are you seeing the errors, are they intermittent? Are they being retried?

**Comment by Anja05** [comment]
Hi @debora-ito  I recently implemented this and I m trying on my local machine and I l facing the same error for all operations of dynamodb mapper. Load , save, delete also.

**Comment by debora-ito** [comment]
Can you update the `aws-java-sdk-dynamodb` to version 1.11.825 and try again? Version 1.11.99 is from 1917 and we should eliminate this as a possible cause before investigating further.

**Comment by Anja05** [comment]
> aws-java-sdk-dynamodb

@debora-ito i tried using the version 1.11.825 but still i m getting the same error.

**Comment by debora-ito** [comment]
Can you turn the [verbose wire logging](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose) on and provide us the logs? Make sure to redact any sensitive information the logs may have, like credentials. Hopefully we can get additional information about the requests.
