### ISSUE TITLE
s3 reporting wrong region

### ISSUE THREAD

**Issue by iceback** [aws/aws-sdk-java#2456]
The s3 client is confused about where a bucket resides
## Describe the bug

A correct s3 object is being interpreted as is in a different bucket. This application has run successfully in the past week.
## Expected Behavior

s3 java client should download the requested object (and has in the past)
## Current Behavior

The s3 client is rejecting the request on the false presumption that the requested object is a different bucket

16:11:34,591 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@5fe1ce85 - Setting level of logger [edu.utah.camplab.jx] to DEBUG
16:11:34,594 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@5fe1ce85 - Setting level of logger [edu.utah.camplab.sgs] to DEBUG
16:11:34,594 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@5fe1ce85 - Setting level of logger [edu.utah.camplab.server] to DEBUG
16:11:34,594 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@5fe1ce85 - Setting level of logger [edu.utah.camplab.app] to DEBUG
16:11:34,594 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@5fe1ce85 - Setting level of logger [edu.utah.camplab.tools] to DEBUG
16:11:34,594 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@5fe1ce85 - Setting level of logger [log4j.logger.com.amazonaws] to DEBUG
16:11:34,595 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@5fe1ce85 - Setting level of logger [log4j.logger.org.apache.http.wire] to DEBUG
16:11:34,595 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@5fe1ce85 - Setting level of logger [jpsgcs] to DEBUG
16:11:34,596 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@5fe1ce85 - Setting level of logger [ROOT] to DEBUG
16:11:34,597 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@5fe1ce85 - Attaching appender named [sgsLOG] to Logger[ROOT]

From the get go we know these peoples:
Treating GEV7 as new pedigree
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: The bucket is in this region: us-east-1. Please use this region to retry the request (Service: Amazon S3; Status Code: 301; Error Code: PermanentRedirect; Request ID: F0E7E5979AC45767; S3 Extended Request ID: m3tgI92cAj0BkFMveBZ3SemSxF65aMTvHW53m12snRoIUyjxogQJIAU3HwyEvA52vng9dFE6dek=; Proxy: null), S3 Extended Request ID: m3tgI92cAj0BkFMveBZ3SemSxF65aMTvHW53m12snRoIUyjxogQJIAU3HwyEvA52vng9dFE6dek=
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1828)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1412)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1374)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5227)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5173)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1512)
	at edu.utah.camplab.tools.S3FileInputStream.getS3Reader(S3FileInputStream.java:31)
	at edu.utah.camplab.app.PedParLoader.buildMarkerAlleleMap(PedParLoader.java:872)
	at edu.utah.camplab.app.PedParLoader.lambda$load$0(PedParLoader.java:225)
	at org.jooq.impl.DefaultDSLContext$3.run(DefaultDSLContext.java:636)
	at org.jooq.impl.DefaultDSLContext$3.run(DefaultDSLContext.java:633)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:564)
	at org.jooq.impl.Tools$12$1.block(Tools.java:4926)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)
	at org.jooq.impl.Tools$12.get(Tools.java:4923)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:616)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:533)
	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:633)
	at edu.utah.camplab.app.PedParLoader.load(PedParLoader.java:214)
	at edu.utah.camplab.app.PedParLoader.main(PedParLoader.java:116)

adding log4j jar caused
Caused by: java.lang.ClassNotFoundException: org.apache.http.protocol.HttpRequestExecutor

## Steps to Reproduce

Here's my AWS interaction code
public class S3FileInputStream {
  private static final AmazonS3 s3Client = AmazonS3ClientBuilder
    .standard()
    .withRegion(Regions.DEFAULT_REGION)
    .withCredentials(new ProfileCredentialsProvider())
    .build();

  private S3FileInputStream() {
    ;
  }
// My "file" reading done through here with 
// url = 6...........-sgs-input/rjs/pro/GEV7.chr1.ped

  public static BufferedReader getS3Reader(String url) {
    String[] parts = S3FileInputStream.parseS3URI(url);
    InputStream istr = S3FileInputStream.s3Client.getObject(new GetObjectRequest(parts[0], parts[1])).getObjectContent();
    BufferedReader reader = new BufferedReader(new InputStreamReader(istr));
    return reader;
  }
}

## Context

Dead in the water
## Your Environment

* AWS Java SDK version used:
aws configure
AWS Access Key ID [****************UJHF]: 
AWS Secret Access Key [****************tpk5]: 
Default region name [us-west-2]: 
Default output format [json]: 

aws-java-sdk-s3-1.11.898.jar:
aws-java-sdk-kms-1.11.898.jar:
jmespath-java-1.11.898.jar:
aws-java-sdk-core-1.11.898.jar:

* JDK version used:
 java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (build 11.0.9+11-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9+11-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
* Operating System and version:
ubuntu 20.04

**Comment by iceback** [comment]
Close this.  The only problem is the error message.  I was passing in a non-existent object descriptor and was complete confused by the "wrong region" error message.  Perhaps the error message could echo the input or at least "file not found"

**Comment by debora-ito** [comment]
@iceback S3 bucket names are globally unique, meaning after a bucket is created its name cannot be used by another AWS account in any region.
