### ISSUE TITLE
Getting  java.lang.NoSuchFieldError: SERVICE_ID 

### ISSUE THREAD

**Issue by harischandra335464** [aws/aws-sdk-java#2477]
Hi Colleagues,

Could you please look into the issue.

I am getting  java.lang.NoSuchFieldError: SERVICE_ID,
Here is the logs :-
   2020-12-21T15:15:47.66+0530 [APP/PROC/WEB/0] ERR SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: SERVICE_ID] with root cause
   2020-12-21T15:15:47.66+0530 [APP/PROC/WEB/0] ERR java.lang.NoSuchFieldError: SERVICE_ID
   2020-12-21T15:15:47.66+0530 [APP/PROC/WEB/0] ERR 	at com.amazonaws.services.s3.AmazonS3Client.createRequest(AmazonS3Client.java:4693)
   2020-12-21T15:15:47.66+0530 [APP/PROC/WEB/0] ERR 	at com.amazonaws.services.s3.AmazonS3Client.createRequest(AmazonS3Client.java:4679)
   2020-12-21T15:15:47.66+0530 [APP/PROC/WEB/0] ERR 	at com.amazonaws.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:918)

here is the  version details
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-s3</artifactId>
            <version>1.11.808</version>

dependency hierarchy 
![image](https://user-images.githubusercontent.com/25028190/102771031-268a5280-43ab-11eb-9bfa-c6d802539cc1.png)

**Comment by debora-ito** [comment]
@harischandra335464 mixing different versions of SDK modules can result in runtime errors like `NoSuchFieldError`. Your environment is resolving to `1.11.251` in some SDK modules for some reason when it should resolve to `1.11.808`.

Are you using Maven? We recommend using the BOM module to manage all your dependencies on the SDK: https://aws.amazon.com/blogs/developer/managing-dependencies-with-aws-sdk-for-java-bill-of-materials-module-bom/

**Comment by harischandra335464** [comment]
thank you so much ...it worked 👍
