### ISSUE TITLE
App is crashed when try to upload the files.

### ISSUE THREAD

**Issue by marimuthugovi** [aws/aws-sdk-java#2492]
SDK Versions       
implementation 'com.amazonaws:aws-android-sdk-core:2.13.1'
implementation 'com.amazonaws:aws-android-sdk-s3:2.13.1'

Fatal Exception: h.a
       at com.innothink.innomaint.feature.attachment.fragment.AttachmentUploadFragment$uploadFileToS3$1.onStateChanged(AttachmentUploadFragment.java:290)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$1.run(TransferStatusUpdater.java:6)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6820)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)

**Comment by debora-ito** [comment]
Please open an issue in https://github.com/aws-amplify/aws-sdk-android, the Amplify Team maintains the android libraries.
