### ISSUE TITLE
Not able to connect to ec2 machine

### ISSUE THREAD

**Issue by bhanupraveeng** [aws/aws-sdk-java#2508]
Not able to connect to ec2 machine with endpoint
## Describe the issue

I have a aws java sdk code which was developed long back and it was working fine. Now our company changed few policies that ec2 machine should not be having public and created VPC groups to connect via private ip. Now the same code is not working.

## Steps to Reproduce
Execute below code:
```
String aSingletonInstanceId="i-08140asd3395";
    	//File AwscredentialsFile=new File(aCurDir + File.separator + "AwsCredentials.properties"); 
    	File AwscredentialsFile=new File("H:/AwsCredentials.properties");
		AWSCredentials credentials = new PropertiesCredentials(AwscredentialsFile);
		AmazonEC2Client ec2 = new AmazonEC2Client(credentials);
		ec2.setEndpoint("https://ec2.us-east-1b.amazonaws.com");		
		StartInstancesRequest startInstanceRequest = new StartInstancesRequest();
		ArrayList<String> list = new ArrayList<String>();
		list.add(aSingletonInstanceId);
		startInstanceRequest.setInstanceIds(list);
		ec2.startInstances(startInstanceRequest);
```

## Current Behavior

```
Exception in thread "main" com.amazonaws.SdkClientException: Unable to execute HTTP request: ec2.us-east-1b.amazonaws.com
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:26040)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:26007)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:25996)
	at com.amazonaws.services.ec2.AmazonEC2Client.executeStartInstances(AmazonEC2Client.java:25286)
	at com.amazonaws.services.ec2.AmazonEC2Client.startInstances(AmazonEC2Client.java:25257)
	at RnD.Samples.App.main(App.java:37)
Caused by: java.net.UnknownHostException: ec2.us-east-1b.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy2.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1330)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	... 13 more
ERROR: JDWP Unable to get JNI 1.2 environment, jvm->GetEnv() return code = -2
JDWP exit error AGENT_ERROR_NO_JNI_ENV(183):  [util.c:840]
```

## Your Environment

* AWS Java SDK version used: 1.11
* JDK version used: 8
* Operating System and version:Windows

Kindly look into issue and let me know if i need to change my code connecting via VPC/private IP and how to do?

**Comment by debora-ito** [comment]
@bhanupraveeng  `ec2.us-east-1b.amazonaws.com` is not a valid EC2 endpoint.

Try setting the region to the client without overriding the endpoint:

```
AmazonEC2 ec2Client = AmazonEC2ClientBuilder.standard()
        .withRegion(Regions.US_EAST_1)
        .withCredentials(new AWSStaticCredentialsProvider(credentials))
        .build();
```

**Comment by bhanupraveeng** [comment]
Hi,

I did the changes as you mentioned. I am getting below error. Credentials mentioned are working if i try to validate by AWS Configure.

`Exception in thread "main" com.amazonaws.services.ec2.model.AmazonEC2Exception: AWS was not able to validate the provided access credentials (Service: AmazonEC2; Status Code: 401; Error Code: AuthFailure; Request ID: a2896007-0245-43fe-a268-1903291398d9; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:26040)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:26007)
	at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:25996)
	at com.amazonaws.services.ec2.AmazonEC2Client.executeStartInstances(AmazonEC2Client.java:25286)
	at com.amazonaws.services.ec2.AmazonEC2Client.startInstances(AmazonEC2Client.java:25257)
	at RnD.Samples.App.main(App.java:44)
`

Thanks,
Bhanu

**Comment by debora-ito** [comment]
From the list of common errors of [EC2 API Reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html#CommonErrors):

>AuthFailure
The provided credentials could not be validated. You may not be authorized to carry out the request; for example, associating an Elastic IP address that is not yours, or trying to use an AMI for which you do not have permissions. Ensure that your account is authorized to use the Amazon EC2 service, that your credit card details are correct, and that you are using the correct access keys.

You can use STS [GetCallerIdentity](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AWSSecurityTokenServiceClient.html#getCallerIdentity-com.amazonaws.services.securitytoken.model.GetCallerIdentityRequest-) to check which credentials are being used to make the call, and then make sure those credentials have the right permissions and its access key is valid; you mentioned that the credentials are working when validated by AWS Configure but I'm not sure what AWS Configure is.
