### ISSUE TITLE
Failure to invoke lambda from another account using an alias

### ISSUE THREAD

**Issue by Rudolf-Vector** [aws/aws-sdk-java#2511]
## Describe the issue
When using the Java SDK, Invoking a lambda with an alias from a different lambda in a different account fails, A signature error is thrown.

## Steps to Reproduce
Create a Java lambda in Account A
Create an execution role in Account A with the following policy
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sts:AssumeRole"
            ],
            "Resource": "arn:aws:iam::123456789012:role/lambda-invoke-role",
            "Effect": "Allow"
        }
    ]
}`
Create a Java lambda in Account B
Create an alias for lambda in Account B
Create a lambda-invoke-role role in Account B with the following policy
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "lambda:*",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}`
Create a lambda execution role with basic execution permissions for lambda replacing <lambda-name> and <alias> with the account B's lambda name and alias.
Upload a jar to lambda in account A with the following code to execute

`final String invokeRole = "arn:aws:iam::123456789012:role/lambda-invoke-role";
final AWSSecurityTokenService securityTokenService = AWSSecurityTokenServiceClientBuilder.standard().build();
final STSAssumeRoleSessionCredentialsProvider credentialsProvider = new STSAssumeRoleSessionCredentialsProvider.Builder(invokeRole, "RoleSession").withStsClient(securityTokenService).build();
        AWSLambda awsLambda = AWSLambdaClientBuilder.standard()
                .withRegion("ap-southeast-2")
                .withCredentials(credentialsProvider)
                .build();
InvokeRequest invokeRequest = new InvokeRequest();
invokeRequest.setFunctionName("<lambda-name>:<alias>");
invokeRequest.setPayload("{key: value}");
awsLambda.invoke(invokeRequest);`

## Current Behavior
AWSLambdaClient throws the following error

`Caused by: com.amazonaws.services.lambda.model.AWSLambdaException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AWSLambda; Status Code: 403; Error Code: InvalidSignatureException; Request ID: a7559c55-5fba-41e0-9477-ccc875babfda; Proxy: null)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
            at com.amazonaws.services.lambda.AWSLambdaClient.doInvoke(AWSLambdaClient.java:3965)
            at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3932)
            at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:3921)
            at com.amazonaws.services.lambda.AWSLambdaClient.executeInvoke(AWSLambdaClient.java:2208)
            at com.amazonaws.services.lambda.AWSLambdaClient.invoke(AWSLambdaClient.java:2179)
            at nz.co.vectormetering.platform.asset.client.LambdaClient.invokeDataLambda(LambdaClient.java:43)`

## Your Environment

AWS Java SDK version used: 1.11.837
JDK version used: Java 11 (Corretto) (Target 1.8)
Operating System and version: AWS Lambda Runtime Java 11 (Corretto)

**Comment by debora-ito** [comment]
Hi @Rudolf-Vector apologies for the delayed reply. 

Can you provide the verbose wire logs of the Lambda call? The Developer Guide docs show how to turn on the verbose wire logs: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose.
Please make sure to redact any sensitive information it might contain.

In cases of signature mismatch, sometimes the wire logs show in the response what was the expected canonical string, and we can troubleshoot by comparing with what was sent instead - see more info in this Troubleshooting guide: https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html.

**Comment by Rudolf-Vector** [comment]
Hello Debora, We have discovered the issue.
The general documentation indicates you can use your function with alias as your target. 
`Function name - my-function (name-only), my-function:v1 (with alias). `
This would match with how other services work with aliases. However this sdk does not allow for this. Using the qualifier fixes our issue. 

It may be worth putting a note against documentation here to indicate that you have to use the qualifier or change the behavior of lambda invoke. however we are happy to close this issue.
https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html

**Comment by debora-ito** [comment]
@Rudolf-Vector If the service API allows the use of alias then it should work using the SDK, there's no input validation on the client side. But since you're not blocked anymore I'll mark this to auto close soon. Feel free to reach out if you have further questions.
