### ISSUE TITLE
S3 client-side encryption requires KMS

### ISSUE THREAD

**Issue by MariusVolkhart** [aws/aws-sdk-java#2530]
## Describe the bug
Attempting to use S3 client-side encryption, as documented in https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/UsingClientSideEncryption.md#option-2-using-a-master-key-stored-within-your-application fails for me.

## Current Behavior
The SDK is trying to create and connect an "internal" `KMSClient`.

## Expected Behavior
I'm not sure why, and in this case, it is not desired. I'm trying to use a master key that is on the client, and not the AWS KMS service.

My ideal outcome is for the SDK to not try to create a KMS client when I have no intention of using one. My next ideal is that the SDK ignores errors that happen with the KMS client along this path.

```java
  KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("RSA");
  keyPairGenerator.initialize(2048);

  KeyPair keyPair = keyPairGenerator.generateKeyPair();

  String s3ObjectKey = "test.txt";
  String s3ObjectContent = "This should be encrypt";

  AmazonS3EncryptionV2 s3EncryptionClientV2 = AmazonS3EncryptionClientV2Builder.standard()
          .withRegion(Regions.DEFAULT_REGION)
          .withClientConfiguration(new ClientConfiguration())
          .withCryptoConfiguration(new CryptoConfigurationV2().withCryptoMode(CryptoMode.AuthenticatedEncryption))
          .withEncryptionMaterialsProvider(new StaticEncryptionMaterialsProvider(new EncryptionMaterials(keyPair)))
          .build();

  s3EncryptionClientV2.putObject(bucketName, s3ObjectKey, s3ObjectContent);
  s3EncryptionClientV2.shutdown();
```

```java
Mar 16, 2021 7:47:51 PM com.amazonaws.util.EC2MetadataUtils getItems
WARNING: Unable to retrieve the requested metadata (/latest/dynamic/instance-identity/document). Failed to connect to service endpoint: 
com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:70)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:75)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:403)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:372)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:368)
	at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:283)
	at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:59)
	at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:50)
	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
	at com.amazonaws.client.builder.AwsClientBuilder.determineRegionFromRegionProvider(AwsClientBuilder.java:475)
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:458)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.services.s3.AmazonS3EncryptionClientV2.newAWSKMSClient(AmazonS3EncryptionClientV2.java:197)
	at com.amazonaws.services.s3.AmazonS3EncryptionClientV2.<init>(AmazonS3EncryptionClientV2.java:115)
	at com.amazonaws.services.s3.AmazonS3EncryptionClientV2Builder.build(AmazonS3EncryptionClientV2Builder.java:101)
	at com.amazonaws.services.s3.AmazonS3EncryptionClientV2Builder.build(AmazonS3EncryptionClientV2Builder.java:23)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)


Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:462)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.services.s3.AmazonS3EncryptionClientV2.newAWSKMSClient(AmazonS3EncryptionClientV2.java:197)
	at com.amazonaws.services.s3.AmazonS3EncryptionClientV2.<init>(AmazonS3EncryptionClientV2.java:115)
	at com.amazonaws.services.s3.AmazonS3EncryptionClientV2Builder.build(AmazonS3EncryptionClientV2Builder.java:101)
	at com.amazonaws.services.s3.AmazonS3EncryptionClientV2Builder.build(AmazonS3EncryptionClientV2Builder.java:23)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
```

## Your Environment

* AWS Java SDK version used: `com.amazonaws:aws-java-sdk-s3:1.11.975`
* JDK version used: 11
* Operating System and version: MacOS Catalina

**Comment by debora-ito** [comment]
Hi @MariusVolkhart, a KMS client is needed to generate the one-time-use symmetric key mentioned in step `i` of the process, described in the [link](https://github.com/awsdocs/amazon-s3-userguide/blob/main/doc_source/UsingClientSideEncryption.md#option-2-using-a-master-key-stored-within-your-application) you referenced:

> i. The Amazon S3 encryption client generates a one-time-use symmetric key (also known as a data encryption key or data key) locally. It uses the data key to encrypt the data of a single Amazon S3 object. The client generates a separate data key for each object.

The operation `KMSClient#generateDataKey` is called for this.

I think we can do a better job in make it clear in the docs that if a KMS client is not provided in `AmazonS3EncryptionV2#withKmsClient`, a client will be created internally. What do you think?

**Comment by MariusVolkhart** [comment]
Hi @debora-ito 

Thanks for looking into this!

Documenting that a KMS client will be created, and that providing a no-op implementation disabled this behavior and is safe would be helpful. Providing a no-op `AWSKMS` implementation would be nice too (make `AbstractAWSKMS`'s constructor public?).

From what I could tell, the KMS Client isn't actually used to create the DEK if `EncryptionMaterials#isKMSEnabled()` is `false`. All call sites to `AWSKMS#generateDataKey()` seem to be guarded by a check. In that case, it'd be great to not create the `KMSClient` unless it will actually be used, or to defer creation, or to defer network traffic on behalf of the `KMSClient`.

In my testing I've used a `Mockito.mock(AWSKMS.class)` without any additional configuration, and can verify that there are no interactions with the object when `EncryptionMaterials#isKMSEnabled()` is `false`.

**Comment by debora-ito** [comment]
I see what you are saying now. When providing your own secret key with `new EncryptionMaterials(secretKey)` the encryption material is not "KMS enabled", but the KMS client is built before reaching the check point.

I'll discuss with the team the options we have around this.

**Comment by MariusVolkhart** [comment]
Yes, exactly. Thanks for looking into it.

**Comment by debora-ito** [comment]
@MariusVolkhart  We apologize but this won't get fixed in v1.

The equivalent of S3 encryption client in the Java SDK v2 is the standalone AWS Encryption SDK for Java - https://github.com/aws/aws-encryption-sdk-java and it's maintained by the AWS Crypto Tools team. Please check the [Developer Guide](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html) for more info, including some [migration tips](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/migration.html).

#### Reference:
- Announcing end-of-support for AWS SDK for Java v1.x effective December 31, 2025 - [blog post](
https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/)
