### ISSUE TITLE
RequestSpotInstancesRequest should support launching into any VPC subnet

### ISSUE THREAD

**Issue by jxtps** [aws/aws-sdk-java#2532]
## Describe the Feature
Java SDK v2 supports specifying multiple subnetIds in [ReqeustSpotLaunchSpecification.subnetId()](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/ec2/model/RequestSpotLaunchSpecification.Builder.html#subnetId-java.lang.String-)

Java SDK v1 however does not - providing multiple, comma-separated subnet ids in the LaunchSpecification used with a RequestSpotInstancesRequest results in an exception. 

This appears to make it impossible to create a spot instance request that can be filled in any subnet using the Java SDK v1. 

## Proposed Solution
Add support for specifying multiple subnet IDs when creating spot instance requests. 

## Describe alternatives you've considered
- Upgrading to v2 (problematic for unrelated reasons)
- Maybe it can be done via a spot fleet request?

## Your Environment

* AWS Java SDK version used: 1.11.979
* JDK version used: 8
* Operating System and version: Win10

**Comment by debora-ito** [comment]
Hi @jxtps this is weird, both v1 and v2 should be calling the same API underneath, it should not be an issue.

Can you share a repro code? And also the stacktrace with the error you're seeing in v1?

**Comment by jxtps** [comment]
The scala code I used was basically: 

```scala
      val req = new RequestSpotInstancesRequest("33.00")
        .withInstanceCount(1)
        .withLaunchSpecification(new LaunchSpecification()
          .withImageId(amiId)
          .withUserData(userDataB64)
          .withInstanceType(instanceType)
          .withIamInstanceProfile(iamInstanceProfileSpecification)
          .withKeyName(keyName)
          .withMonitoringEnabled(true)
          .withAllSecurityGroups(securityGroupIdentifiers: _*)
          .withSubnetId(Azs.map(_.subnet().id).mkString(", "))
        )
      val res = Aws.UsEast1.ec2.requestSpotInstances(req)
```

That's not really copy-pasteable as it relies on a bunch of app-specific constants etc, but it should give you the jist of it. 

The exception is: 

```
Exception in thread "main" com.amazonaws.services.ec2.model.AmazonEC2Exception: The subnet ID 'subnet-aaa, subnet-bbb, subnet-ccc, subnet-ddd, subnet-eee, subnet-fff' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidSubnetID.NotFound; Request ID: [UUID goes here]; Proxy: null)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1819)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1403)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1372)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:28653)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:28620)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:28609)
        at com.amazonaws.services.ec2.AmazonEC2Client.executeRequestSpotInstances(AmazonEC2Client.java:26541)
        at com.amazonaws.services.ec2.AmazonEC2Client.requestSpotInstances(AmazonEC2Client.java:26509)
```
(specific subnet identifiers obfuscated, they all individually exist)

I've also tried separating by just "," (i.e. no space), but that didn't help.

**Comment by debora-ito** [comment]
@jxtps thank you for the repro code, I see the same error message in v1. I tried to call the same operation in v2, and interestingly I see the error in v2 too, I cannot specify multiple subnets in neither. Are you also using `requestSpotInstances` is v2?

**Comment by jxtps** [comment]
I haven’t tried v2, I assumed the documentation I cited was accurate ;)

**Comment by debora-ito** [comment]
I see! So this seems to be an issue with EC2 documentation, I will contact them and ask for an update.

**Comment by jxtps** [comment]
Well, I mean, you could see it that way, but then this is even more a feature request: add this capability, don’t just change the docs to say it’s not possible!

**Comment by debora-ito** [comment]
Hi @jxtps, the EC2 Team removed the text lines that mentioned multiple subnet ids, to avoid confusion.
I've ask them to add support for specifying more than one subnet id, they've add it to their feature request backlog.

I'll go ahead and close this, as there's nothing more pending on the SDK side.
Feel free to reach out if you have any other question.
