### ISSUE TITLE
com.amazonaws.AbortedException on KMS java cllient

### ISSUE THREAD

**Issue by BhaviJagwani** [aws/aws-sdk-java#2552]
## Issue Description
we're using KMS to encrypt and decrypt data in our service via the AWS SDK (without caching, each encryption operation uses a new key)
We've intermittently observed the decrypt calls to KMS failing with 
```
com.amazonaws.AbortedException:
at com.amazonaws.internal.SdkFilterInputStream.abortIfNeeded(SdkFilterInputStream.java:61)
at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:83)
at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:158)
at com.amazonaws.util.IOUtils.drainInputStream(IOUtils.java:142)
at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:123)
at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:43)
at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:69)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1726)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleSuccessResponse(AmazonHttpClient.java:1446)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1368)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
at com.amazonaws.services.kms.AWSKMSClient.doInvoke(AWSKMSClient.java:4552)
at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:4519)
at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:4508)
at com.amazonaws.services.kms.AWSKMSClient.executeDecrypt(AWSKMSClient.java:1348)
at com.amazonaws.services.kms.AWSKMSClient.decrypt(AWSKMSClient.java:1319)
...
```

During this time, the requests some times also appear to take longer to fail than the configured requestTimeOut
configuration:
```
  clientExecutionTimeout: 120
  requestTimeout: 50
  socketTimeout: 50
  connectionTimeout: 50
  maxConnections: 50
  backOff: 5
  maxErrorRetry: 2
```
the request however is observed to some times fail after > 50ms

## Steps to Reproduce
The issue is not reproducible and it happens intermittently. The frequency however, increases with the increase in the rate of requests to KMS

code to call KMS decrypt:
```
DecryptRequest decryptRequest = new DecryptRequest().withCiphertextBlob(ByteBuffer.wrap(source));
        DecryptResult decryptResponse = kmsClient.decrypt(decryptRequest);
        return new String(decryptResponse.getPlaintext().array());
```

We have verified with the AWS support team that we aren't hitting any account limits w.r.t. KMS neither are we facing any network related issues

## Environment
* AWS Java SDK version used: aws-java-sdk-kms-1.11.580.jar
* JDK version used: 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
* Operating System and version: Amazon linux2
* the service runs on ECS Fargate and KMS calls are via the KMS VPC endpoint

Please help with possible causes for this exception and any steps we can take to mitigate/avoid this failure

**Comment by debora-ito** [comment]
Intermittent issues are always hard to troubleshoot, and it's probably caused by some network issue.

`AbortedException` indicates that the thread is interrupted while it's executing the request. Check if there's any unintentional thread interruption in your code.

You can enable [AWS Java SDK Metrics](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/generating-sdk-metrics.html) to gather more information about your application. If you also enable [Latency Metrics Logging](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-latency-logging), request metrics including connection pool stats will also get added to the logs.
