### ISSUE TITLE
AmazonWebServiceClient should have a toBuilder method

### ISSUE THREAD

**Issue by blitz555** [aws/aws-sdk-java#2570]
Currently we have a use case where we are saving a client for reuse and sometimes change its endpoint. Because setEndpoint is deprecated in favour of builder, we cannot provide such a use case.
Would you consider supporting a method such as AmazonEC2Client.toBuilder().withEndpointConfiguration() to support copying existing properties, then change select properties?
`
class ClientProvider {
		
    private AmazonEC2Client ec2Client;
    
    public ClientProvider(AmazonEC2Client ec2Client) {
        this.ec2Client = ec2Client;
    }

    public AmazonEC2Client getEc2Client() {
        return ec2Client;
    }

    public void setEndpoint(String endpoint) {
        if(ec2Client != null) {
            ec2Client.setEndpoint(endpoint);
        }
    }
}
`

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by blitz555** [comment]
@debora-ito Hi, thank you for your continued support with my questions. I attempted to save reference of the client factory in lieu of a copy constructor, in replace of the client in code sample. 
Previously, out Client provider class used client constructors, and .setRegion and .setEndpoint after creation of client. 
This worked fine until I switched to using builder.withRegion and builder.withEndpointConfiguration as recommended by documentation. However, now that I ran a functional test on a code path that may have called both .withRegion and .withEndpointConfiguration, I encountered the following error, 
`java.lang.IllegalStateException: Only one of Region or EndpointConfiguration may be set.
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:450)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)`
