### ISSUE TITLE
com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by bpradeeptime** [aws/aws-sdk-java#2594]
com.amazonaws.SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1069)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:2089)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2065)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeQuery(AmazonDynamoDBClient.java:1500)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:1476)
        at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.queryPage(DynamoDBMapper.java:1517)
        at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.queryPage(AbstractDynamoDBMapper.java:277)
        at com.util.main.DataVerificationUtil.getScmHistoryByFilter(DataVerificationUtil.java:1161)
        at com.util.main.DataVerificationUtil$MyRunnable.run(DataVerificationUtil.java:1305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:286)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:263)
        at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
        at com.amazonaws.http.conn.$Proxy22.get(Unknown Source)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1190)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
        ... 17 more

**Comment by debora-ito** [comment]
@bpradeeptime please provide the context information we ask in the new issue template. I cannot help you out properly only looking at the stacktrace.

**Comment by bpradeeptime** [comment]
Hi @debora-ito Please find the more details below 

OS : Windows 10(In any OS this issue is occurring)
JDK: jdk-11.0.3 and jdk1.8.0_291 (Both versions This issue is occurring)
SDK : 1.12.1 and 1.11.903 (Both versions This issue is occurring)
Scenario : If more requests are coming same time then this issue occurring ( i tried with 100+ requests at a time then this issue is occurred) and we are using the local DynamoDB.

**Comment by debora-ito** [comment]
Can you share a code sample showing how you are creating the DynamoDB client?
And what are your DynamoDB Local settings?

**Comment by chongchaoyu** [comment]
I had encountered the same issue, but not got help at issue page:(:(

I solved this issue by closing S3Object(You use AmazonS3.getObject() to get this object) when it was not needed, because S3Object holds InputStream, if you don't close it, apache http client won't release the connection, and the pool will be full soon, you can't get any connection at all.

Hope this can help some guys.
