### ISSUE TITLE
S3 FileDownload fails during joining parts and gives filelock exception

### ISSUE THREAD

**Issue by dhikrahashim** [aws/aws-sdk-java#2604]
I am facing the  lock issue with my jenkins job

com.amazonaws.services.s3.transfer.exception.FileLockException: Fail to lock /var/jenkins_home/jobs/xxxxxxxxxxx/xxxxxx/workspace/tests.zip
	at com.amazonaws.services.s3.transfer.DownloadCallable.truncateDestinationFileIfNecessary(DownloadCallable.java:194)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:139)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:99)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:100)
	at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:40)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE

_Originally posted by @dhikrahashim in https://github.com/aws/aws-sdk-java/issues/2210#issuecomment-870239106_

**Comment by debora-ito** [comment]
Hi @dhikrahashim in order to investigate the issue, we need more information about how you are using the SDK. Preferably fill all the fields of the following issue template:

```
<!--- Provide a general summary of the issue in the Title above -->

## Describe the issue
<!--- A clear and concise description of the issue -->

## Steps to Reproduce
<!--- Provide a self-contained, concise snippet of code that can be used to reproduce the issue -->
<!--- For more complex issues provide a repo with the smallest reproducible example -->
<!--- Avoid including business logic or unrelated code, it makes diagnosis more difficult -->

## Current Behavior
<!--- Tell us what happens instead of the expected behavior -->

<!--- Include full errors, uncaught exceptions, stack traces, and relevant logs -->
<!--- To turn on SDK logging, follow instructions here: http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html -->
<!--- If service responses are relevant, please include wirelogs -->

## Your Environment
<!--- Include as many relevant details as possible about your environment -->
* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

```

**Comment by sherman** [comment]
Hi, having the same problem. Do you find any solution?

**Comment by dhikrahashim** [comment]
@sherman I renamed the job to fix this issue temporarily. Issue occurring again. The last job got aborted and after that all the jobs are locked with the same error
