### ISSUE TITLE
com.amazonaws.SdkClientException: Input stream is not a fast infoset document

### ISSUE THREAD

**Issue by thetroubleshootingguy** [aws/aws-sdk-java#2616]
## Steps to Reproduce
Configure the tool locally and run the import.

## Current Behavior
It fails with below error:

2021-07-27 15:53:59,405+0300 http-nio-8080-exec-87 url: /rest/insight/1.0/import/module/test/insight-aws-import; user: asolou ERROR asolou 953x56841x1 1gqz4se 10.1.220.53,10.60.176.82 /rest/insight/1.0/import/module/test/insight-aws-import [io.riada.CacheProvider] Error getting cache data key: -364272955STS
com.google.common.util.concurrent.UncheckedExecutionException: com.amazonaws.SdkClientException: Unable to unmarshall response (com.sun.xml.internal.org.jvnet.fastinfoset.FastInfosetException: Input stream is not a fast infoset document). Response Code: 200, Response Text: OK
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4871)
	at io.riada.CacheProvider.get(CacheProvider.java:49)
	at com.riadalabs.jira.plugins.aws.imports.manager.AWSClientProvider.getClients(AWSClientProvider.java:155)
	at com.riadalabs.jira.plugins.aws.imports.manager.AWSClientProvider.validClient(AWSClientProvider.java:169)
	at com.riadalabs.jira.plugins.aws.imports.ImportModule.validateAndTestConfiguration(ImportModule.java:251)
	at com.riadalabs.jira.plugins.aws.imports.ImportModule.validateAndTestConfiguration(ImportModule.java:48)
	at com.riadalabs.jira.plugins.insight.services.jira.module.ImportModuleDelegator.validateAndTestConfiguration(ImportModuleDelegator.java:135)
	at com.riadalabs.jira.plugins.insight.services.imports.common.DefaultImportService.testModuleConnection(DefaultImportService.java:407)
	at com.riadalabs.jira.plugins.insight.services.imports.common.DefaultImportService.testConnectionWithConfiguration(DefaultImportService.java:353)
	at com.riadalabs.jira.plugins.insight.services.imports.common.DefaultImportService.testConnection(DefaultImportService.java:349)
	at com.riadalabs.jira.plugins.insight.channel.web.api.rest.services.imports.ImportResource.testConnection(ImportResource.java:200)
	... 2 filtered
	at java.lang.reflect.Method.invoke(Method.java:498)
	... 19 filtered
	at com.atlassian.plugins.rest.module.RestDelegatingServletFilter$JerseyOsgiServletContainer.doFilter(RestDelegatingServletFilter.java:160)
	... 1 filtered
	at com.atlassian.plugins.rest.module.RestDelegatingServletFilter.doFilter(RestDelegatingServletFilter.java:70)
	... 32 filtered
	at com.intenso.jira.plugins.it.transform.CleanupFilter.doFilter(CleanupFilter.java:21)
	... 3 filtered
	at com.atlassian.servicedesk.internal.web.ExternalCustomerLockoutFilter.doFilter(ExternalCustomerLockoutFilter.java:55)
	... 8 filtered
	at com.atlassian.jira.plugin.mobile.web.filter.MobileAppRequestFilter.doFilter(MobileAppRequestFilter.java:59)
	... 4 filtered
	at com.atlassian.jira.plugin.mobile.login.MobileLoginSuccessFilter.doFilter(MobileLoginSuccessFilter.java:54)
	... 3 filtered
	at com.atlassian.diagnostics.internal.platform.monitor.http.HttpRequestMonitoringFilter.doFilter(HttpRequestMonitoringFilter.java:55)
	... 8 filtered
	at com.atlassian.web.servlet.plugin.request.RedirectInterceptingFilter.doFilter(RedirectInterceptingFilter.java:21)
	... 43 filtered
	at com.resolution.atlasplugins.samlsso.servlet.RedirectToSsoFilter.doFilter(RedirectToSsoFilter.java:60)
	... 3 filtered
	at com.atlassian.plugins.slack.analytics.SlackAnalyticsFilter.doFilter(SlackAnalyticsFilter.java:35)
	... 3 filtered
	at com.atlassian.ratelimiting.internal.filter.RateLimitFilter.doFilter(RateLimitFilter.java:73)
	... 3 filtered
	at com.atlassian.troubleshooting.thready.filter.AbstractThreadNamingFilter.doFilter(AbstractThreadNamingFilter.java:46)
	... 17 filtered
	at com.atlassian.jira.security.JiraSecurityFilter.lambda$doFilter$0(JiraSecurityFilter.java:66)
	... 1 filtered
	at com.atlassian.jira.security.JiraSecurityFilter.doFilter(JiraSecurityFilter.java:64)
	... 16 filtered
	at com.atlassian.plugins.rest.module.servlet.RestSeraphFilter.doFilter(RestSeraphFilter.java:38)
	... 7 filtered
	at com.atlassian.pats.web.filter.TokenBasedAuthenticationFilter.doFilter(TokenBasedAuthenticationFilter.java:82)
	... 19 filtered
	at com.atlassian.jira.servermetrics.CorrelationIdPopulatorFilter.doFilter(CorrelationIdPopulatorFilter.java:30)
	... 5 filtered
	at com.resolution.atlasplugins.samlsso.servlet.SetSameSiteCookieAttributeToNoneAttributeFilter.doFilter(SetSameSiteCookieAttributeToNoneAttributeFilter.java:51)
	... 3 filtered
	at com.idalko.tgng.jira.server.models.servicedesk.ServletRequestContextFilter.$anonfun$doFilter$1(ServletRequestContextFilter.scala:13)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at com.idalko.tgng.jira.server.models.servicedesk.ServletRequestContextFilter.doFilter(ServletRequestContextFilter.scala:13)
	... 3 filtered
	at com.atlassian.servicedesk.internal.web.CustomerContextSettingFilter.lambda$invokeFilterChain$0(CustomerContextSettingFilter.java:215)
	at com.atlassian.servicedesk.internal.api.util.context.ReentrantThreadLocalBasedCodeContext.rteInvoke(ReentrantThreadLocalBasedCodeContext.java:136)
	at com.atlassian.servicedesk.internal.api.util.context.ReentrantThreadLocalBasedCodeContext.runOutOfContext(ReentrantThreadLocalBasedCodeContext.java:89)
	at com.atlassian.servicedesk.internal.utils.context.CustomerContextServiceImpl.runOutOfCustomerContext(CustomerContextServiceImpl.java:47)
	at com.atlassian.servicedesk.internal.web.CustomerContextSettingFilter.outOfCustomerContext(CustomerContextSettingFilter.java:206)
	at com.atlassian.servicedesk.internal.web.CustomerContextSettingFilter.doFilterImpl(CustomerContextSettingFilter.java:134)
	at com.atlassian.servicedesk.internal.web.CustomerContextSettingFilter.doFilter(CustomerContextSettingFilter.java:123)
	... 4 filtered
	at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:37)
	... 8 filtered
	at com.atlassian.ratelimiting.internal.filter.RateLimitPreAuthFilter.doFilter(RateLimitPreAuthFilter.java:71)
	... 3 filtered
	at com.atlassian.web.servlet.plugin.request.RedirectInterceptingFilter.doFilter(RedirectInterceptingFilter.java:21)
	... 4 filtered
	at com.atlassian.troubleshooting.thready.filter.AbstractThreadNamingFilter.doFilter(AbstractThreadNamingFilter.java:46)
	... 3 filtered
	at com.atlassian.web.servlet.plugin.LocationCleanerFilter.doFilter(LocationCleanerFilter.java:36)
	... 26 filtered
	at com.atlassian.jira.servermetrics.MetricsCollectorFilter.doFilter(MetricsCollectorFilter.java:25)
	... 25 filtered
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.SdkClientException: Unable to unmarshall response (com.sun.xml.internal.org.jvnet.fastinfoset.FastInfosetException: Input stream is not a fast infoset document). Response Code: 200, Response Text: OK
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1767)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleSuccessResponse(AmazonHttpClient.java:1463)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.doInvoke(AWSSecurityTokenServiceClient.java:1652)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1619)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.invoke(AWSSecurityTokenServiceClient.java:1608)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.executeAssumeRole(AWSSecurityTokenServiceClient.java:515)
	at com.amazonaws.services.securitytoken.AWSSecurityTokenServiceClient.assumeRole(AWSSecurityTokenServiceClient.java:486)
	at com.riadalabs.jira.plugins.aws.imports.manager.AWSClientProvider$ConfigurationLoader.createTemporaryCredentials(AWSClientProvider.java:1164)
	at com.riadalabs.jira.plugins.aws.imports.manager.AWSClientProvider$ConfigurationLoader.get(AWSClientProvider.java:325)
	at com.riadalabs.jira.plugins.aws.imports.manager.AWSClientProvider$ConfigurationLoader.get(AWSClientProvider.java:301)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4876)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	... 328 more
Caused by: javax.xml.stream.XMLStreamException: com.sun.xml.internal.org.jvnet.fastinfoset.FastInfosetException: Input stream is not a fast infoset document
	at com.sun.xml.internal.fastinfoset.stax.StAXDocumentParser.next(StAXDocumentParser.java:469)
	at com.sun.xml.internal.fastinfoset.stax.events.StAXEventReader.<init>(StAXEventReader.java:60)
	at com.sun.xml.internal.fastinfoset.stax.factory.StAXInputFactory.createXMLEventReader(StAXInputFactory.java:132)
	at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:94)
	at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:42)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1743)
	... 351 more
Caused by: com.sun.xml.internal.org.jvnet.fastinfoset.FastInfosetException: Input stream is not a fast infoset document
	at com.sun.xml.internal.fastinfoset.Decoder.decodeHeader(Decoder.java:1287)
	at com.sun.xml.internal.fastinfoset.stax.StAXDocumentParser.next(StAXDocumentParser.java:220)
	... 357 more

## Your Environment

* AWS Java SDK version used: 1.11.901
* JDK version used: AdoptOpenJDK 1.8.0_202
* Operating System and version: Linux 3.10.0-1160.31.1.el7.x86_64

**Comment by debora-ito** [comment]
@thetroubleshootingguy can you give us more context on what you are trying to do, which APIs you're calling? Ideally with a self-contained code sample we can use to reproduce the error.

I see the error is coming from an STS AssumeRole operation, can you tell us how the credentials are being provided?

**Comment by thetroubleshootingguy** [comment]
Thanks for responding @debora-ito! Sorry for responding late, I was on leave. 

I am supporting a product that does this import of AWS object using STS client API. So I might not be able to point out self contained sample code. But from the stack you will notice all we are doing is before the AWS objects could be imported, we are trying to test the connection and in turn testing configuration using already existing AWSClient that is cached.

This is how getting the AWSClientProvider.getClients() body looks like:
```
 List<AWSLocalWebServiceClient> result = (List<AWSLocalWebServiceClient>) CacheProvider.getInstance()
                .get(String.valueOf(awsConfiguration.hashCode()) + awsClientType,
                        new ConfigurationLoader(awsConfiguration, awsClientType));

        return result;
```
And this is how the definition of ConfigurationLoader that implements Supplier<List<AWSLocalWebServiceClient>> and its supplier entity looks like:

```
public ConfigurationLoader(ImportConfiguration awsConfiguration, AWSClientType awsClientType) {

            this.awsConfiguration = awsConfiguration;
            this.awsClientType = awsClientType;
            this.credentials =
                    new BasicAWSCredentials(awsConfiguration.getAccessKey(), awsConfiguration.getSecretKey());
            this.clientConfiguration = new ClientConfiguration().withThrottledRetries(false)
                    .withConnectionTimeout(0)
                    .withMaxErrorRetry(maxErrorRetry);
        }

        @Override
        public List<AWSLocalWebServiceClient> get() {
            List<AWSLocalWebServiceClient> awsClients = new ArrayList<>();
            HashMap<String, AWSCredentials> temporaryCredentials = createTemporaryCredentials(awsConfiguration.getRoles());
            try {
                if (!Utilities.isCollectionNullOrEmpty(awsConfiguration.getRegions())) {
                    readGlobalClientsForOwnAccount(awsClients, awsConfiguration.getRegions().get(0), credentials);
                    readGlobalClientsFromRoles(awsClients, awsConfiguration.getRegions().get(0),temporaryCredentials);
                }
                for (String region : awsConfiguration.getRegions()) {
                    readClientsForOwnAccount(awsClients, region, credentials);
                    readClientsFromRoles(awsClients, region, temporaryCredentials);
                }
            } catch (Exception ex) {
                logger.error("Error trying to authenticate AWSClients.", ex);
            }
            return awsClients.isEmpty() ? null : awsClients;
        }
```
This should answer your query on how the credentials are being provided. Do let us know if you need any further information.

**Comment by thetroubleshootingguy** [comment]
team, any help is appreciated!

**Comment by thetroubleshootingguy** [comment]
@debora-ito any help is appreciated :)

**Comment by thetroubleshootingguy** [comment]
@debora-ito , Team, could someone help me with this please?

**Comment by debora-ito** [comment]
@thetroubleshootingguy apologies for the super long silence in this thread. I've finally figured out where the error comes from.

Comparing your stacktrace to the stacktrace in my local tests, I can see a difference here:
```
at com.sun.xml.internal.fastinfoset.stax.factory.StAXInputFactory.createXMLEventReader(StAXInputFactory.java:132)
at com.amazonaws.http.StaxResponseHandler.handle(StaxResponseHandler.java:94)
```

In my local tests, the `createXMLEventReader()` method called is from the XMLInputFactoryImpl class, and not from StAXInputFactory.

After some research I learned you can customize the XMLInputFactory by using a JVM System Property:
```
-Djavax.xml.stream.XMLInputFactory=com.sun.xml.internal.fastinfoset.stax.factory.StAXInputFactory
```

The error is saying that `com.sun.xml.internal.fastinfoset.stax.factory.StAXInputFactory` expected the XML to be encoded with the Fast Infoset format, which it was not the case with the response sent by the service.

My suggestion is to not customize the XMLInputFactory and use the default implementation, if possible.
