### ISSUE TITLE
WorkDocs - Upload document - Memory leak

### ISSUE THREAD

**Issue by miguel-ruiz-walfen** [aws/aws-sdk-java#2639]
UploadDocumentStreamRequest is causing OutOfMemoryError for big files following the documentation examples.

## Describe the bug
Following the developer guide for uploading documents to WorkDocs is throwing OutOfMemoryError 

## Expected Behavior
It should work without error

## Current Behavior
`Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3536)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
	at java.base/sun.net.www.http.PosterOutputStream.write(PosterOutputStream.java:78)
	at com.amazonaws.util.IOUtils.copy(IOUtils.java:126)
	at com.amazonaws.util.IOUtils.copy(IOUtils.java:111)
	at com.amazonaws.services.workdocs.ContentManager.uploadDocumentStream(ContentManager.java:180)`

## Steps to Reproduce

Small runnable example with Java and SpringBoot:

`package com.xxx.sync;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;

import javax.annotation.Resource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import com.amazonaws.services.workdocs.AmazonWorkDocs;
import com.amazonaws.services.workdocs.ContentManager;
import com.amazonaws.services.workdocs.ContentManagerBuilder;
import com.amazonaws.services.workdocs.UploadDocumentStreamRequest;
import com.xxx.sync.services.impl.SynchronizeWorkDocsToWorkDocsImpl;

@Component
public class UploadRunner implements ApplicationRunner{private static final Logger LOGGER = LoggerFactory.getLogger(SynchronizeWorkDocsToWorkDocsImpl.class);

	@Resource
	private AmazonWorkDocs workDocsClient;

	@Override
	public void run(ApplicationArguments args) throws Exception {
		Path path = Path.of(System.getProperty("java.io.tmpdir"), "xxx", "0");
		ContentManager contentManager = ContentManagerBuilder.standard().withWorkDocsClient(workDocsClient).build();

		try (InputStream inputStream = Files.newInputStream(path)) {
			UploadDocumentStreamRequest request = new UploadDocumentStreamRequest();
			request.setParentFolderId("xxx");
			request.setContentType(Files.probeContentType(path));
			request.setStream(inputStream);
			request.setDocumentName("test-1GB.txt");
			request.setDocumentSizeInBytes(Files.size(path));
			contentManager.uploadDocumentStream(request);
		} catch (IOException e) {
			LOGGER.error("error uploading file - path: ", path.toString(), e);
			throw new RuntimeException(e);
		}
	}

}
`

## Context

Trying to upload big files to Amazon WorkDocs.

## Your Environment

* AWS Java SDK version used: 1.12.57
* JDK version used: 11
* Operating System and version: Windows

**Comment by debora-ito** [comment]
@miguel-ruiz-walfen The issue is that `Files.newInputStream(path)` will open the file and load it into memory. If there's no sufficient space to allocate the big file in Java heap the application will throw `OutOfMemoryError`.

Try using FileInputStream instead:
```java
File file = new File(path);
InputStream stream = new FileInputStream(file);
```

**Comment by debora-ito** [comment]
If that doesn't help, try increasing the memory size of the JVM heap space. Using the `-Xmx` Java option sets the maximum heap size.

**Comment by miguel-ruiz-walfen** [comment]
@debora-ito Thank you for your reply.

However your solution is throwing the same error. 

Regarding increasing the JVM heap space, it's not a scalable solution. We can have multiple users and our users files don't have a size limit. I think Amazon WorkDocs doesn't specify a maximum file size.

**Comment by miguel-ruiz-walfen** [comment]
Is there any update on this issue?

**Comment by debora-ito** [comment]
Took a look at the ContentManager code, here's what I found: 
- `contentManager.uploadDocumentStream(request)` uses `IOUtils.copy(inputStream, outputStream)` underneath ([link](https://github.com/aws/aws-sdk-java/blob/1c94d1504753629995764231a311f787d42a9c8c/aws-java-sdk-core/src/main/java/com/amazonaws/util/IOUtils.java#L120))
- The copy method uses a byte buffer of 1024 * 4 bytes to read from inputstream and write to outputstream. 

This should not give a memory issue. Have you run a memory profiler? Is there a chance that the Garbage Collector is not running properly?
