### ISSUE TITLE
Uploading an object using multipart upload fails with files >~18 MB

### ISSUE THREAD

**Issue by farazoman** [aws/aws-sdk-java#2651]
# Describe the bug
on `s3Client.uploadPart` after following the template at [(sample code)](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-upload-object.html) but setting an input stream instead of a file. I get an exception: `Unable to position the currentPosition from 3775052 to 10485760` for files larger than ~18mb

# Expected behaviour

should upload the file in multiple parts regardless the size

# Current Behaviour

Throws an SdkClientException with message: `Unable to position the currentPosition from 3775052 to 10485760`

## Call Stack
```
com.amazonaws.SdkClientException: Unable to position the currentPosition from 3775052 to 10485760
	at com.amazonaws.services.s3.internal.InputSubstream.read(InputSubstream.java:80) ~[aws-java-sdk-s3-1.11.754.jar:?]
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.read(MD5DigestCalculatingInputStream.java:128) ~[aws-java-sdk-s3-1.11.754.jar:?]
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90) ~[aws-java-sdk-core-1.11.754.jar:?]
	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:140) ~[httpcore-4.4.11.jar:4.4.11]
	at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:160) ~[aws-java-sdk-core-1.11.754.jar:?]
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238) ~[httpcore-4.4.11.jar:4.4.11]
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63) ~[aws-java-sdk-core-1.11.754.jar:?]
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123) ~[httpcore-4.4.11.jar:4.4.11]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.11.jar:4.5.11]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.11.jar:4.5.11]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1323) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524) ~[aws-java-sdk-core-1.11.754.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5054) ~[aws-java-sdk-s3-1.11.754.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5000) ~[aws-java-sdk-s3-1.11.754.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:3734) ~[aws-java-sdk-s3-1.11.754.jar:?]
	at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3719) ~[aws-java-sdk-s3-1.11.754.jar:?]
```
	

# Steps to Reproduce

Follow the template in the link above with large files using AWS sdk version `1.11.754`

# Possible Solution

?

# Context

In the code I am uploading files using AWS multi-part uploading with the Java SDK and am getting a failure when uploading files larger than ~18 mb

# Your Environment

AWS sdk version: `1.11.754`
Java SDK Version: `1.8`
OS: MacOS - catalina

**Comment by aaoswal** [comment]
Hi @farazoman,
After following the instructions provided in the template for [Uploading an object using multipart upload](https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-upload-object.html). I was not able to reproduce the issue that you have been facing using a <b>20 MB file/image</b>. The steps that I used for reproduction of the issue are:

1. Create an empty Java Maven Project and add the required dependencies in the `pom.xml` file. ([Ref Link](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-project-maven.html#configuring-maven))
2. Create a java class as below under `src/test/java/`: 
    AWS SDK version: `1.11.754`
    Java SDK Version: `1.8`
<details>
<summary><b>Java Class:</b> <i>LowLevelMultipartUpload.java</i></summary>

```
import com.amazonaws.AmazonServiceException;
import com.amazonaws.SdkClientException;
import com.amazonaws.auth.profile.ProfileCredentialsProvider;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.*;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

public class LowLevelMultipartUpload {

    public static void main(String[] args) throws IOException {
        Regions clientRegion = Regions.DEFAULT_REGION;
        String bucketName = "*** Bucket name ***";
        String keyName = "*** Key name ***";
        //String filePath = "*** Path to file to upload ***";

        File file = new File("*** File path ***");
        //declaring a file input stream from the file
        InputStream inputStream = new FileInputStream(file);
        //changing the content length to input stream
        long contentLength = inputStream.available();
        long partSize = 5 * 1024 * 1024; // Set part size to 5 MB.

        try {
            AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
                                                     .withRegion(clientRegion)
                                                     .withCredentials(new ProfileCredentialsProvider())
                                                     .build();

            // Create a list of ETag objects. You retrieve ETags for each object part uploaded,
            // then, after each individual part has been uploaded, pass the list of ETags to
            // the request to complete the upload.
            List<PartETag> partETags = new ArrayList<PartETag>();


            // Initiate the multipart upload.
            InitiateMultipartUploadRequest initRequest = new InitiateMultipartUploadRequest(bucketName, keyName);
            InitiateMultipartUploadResult initResponse = s3Client.initiateMultipartUpload(initRequest);

            // Upload the file parts.
            long filePosition = 0;
            for (int i = 1; filePosition < contentLength; i++) {
                // Because the last part could be less than 5 MB, adjust the part size as needed.
                partSize = Math.min(partSize, (contentLength - filePosition));

                // Create the request to upload a part.
                UploadPartRequest uploadRequest = new UploadPartRequest()
                    .withBucketName(bucketName)
                    .withKey(keyName)
                    .withUploadId(initResponse.getUploadId())
                    .withPartNumber(i)
                    .withPartSize(partSize)
                    .withInputStream(inputStream);

                // Upload the part and add the response's ETag to our list.
                UploadPartResult uploadResult = s3Client.uploadPart(uploadRequest);
                partETags.add(uploadResult.getPartETag());

                filePosition += partSize;
            }

            // Complete the multipart upload.
            CompleteMultipartUploadRequest compRequest = new CompleteMultipartUploadRequest(bucketName, keyName,
                                                                                            initResponse.getUploadId(), partETags);
            s3Client.completeMultipartUpload(compRequest);
        } catch (AmazonServiceException e) {
            // The call was transmitted successfully, but Amazon S3 couldn't process
            // it, so it returned an error response.
            e.printStackTrace();
        } catch (SdkClientException e) {
            // Amazon S3 couldn't be contacted for a response, or the client
            // couldn't parse the response from Amazon S3.
            e.printStackTrace();
        }
    }
}
```

</details>


3. After running the above code, the object is successfully uploaded in the respective bucket.


Make sure you are using `inputStream.available()` as `contentLength` to get the size of the InputStream as the template uses file size which is invalid for an InputStream. 

If you still face the same issue, please do share your sample code which would really help me in reproducing the issue and helping you further.

Thanks,
Anish.
