### ISSUE TITLE
Ec2 metadata endpoint connection refused

### ISSUE THREAD

**Issue by Ans-hrf** [aws/aws-sdk-java#2670]
### Describe the issue

We are running an EMR cluster on a private subnet, during bootstrap phase a service called emr-record-server tries to retrieve aws credentials and fails with error : 

**_Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.reflect.InvocationTargetException
  at com.amazonaws.emr.recordserver.module.BaseModule.authProvider(BaseModule.scala:41)
  while locating com.amazonaws.emr.recordserver.auth.provider.AuthProvider
    for the 2nd parameter of com.amazonaws.emr.recordserver.service.CatalogService.<init>(CatalogService.scala:20)
  while locating com.amazonaws.emr.recordserver.service.CatalogService

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1097)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
	at com.amazonaws.emr.recordserver.server.RecordServer.<init>(RecordServerMain.scala:29)
	at com.amazonaws.emr.recordserver.server.RecordServer$.main(RecordServerMain.scala:21)
	at com.amazonaws.emr.recordserver.server.RecordServer.main(RecordServerMain.scala)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.amazonaws.emr.recordserver.util.ReflectionUtils$.createInstanceOf(ReflectionUtils.scala:9)
	at com.amazonaws.emr.recordserver.module.BaseModule.authProvider(BaseModule.scala:42)
	at com.amazonaws.emr.recordserver.module.BaseModule$$FastClassByGuice$$edf05d6b.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094)
	... 4 more
Caused by: java.lang.ExceptionInInitializerError
	at com.amazonaws.emr.recordserver.auth.provider.ranger.SparkRangerAuthProvider.<init>(SparkRangerAuthProvider.scala:36)
	... 24 more
Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@4dd94a58: profile file cannot lbe nul, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@65f00478: Failed to connect to service endpoint: ]_**

A bit before this error, we can see this WARN :

**com.amazonaws.SdkClientException: Failed to connect to service endpoint: 
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:100)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.getToken(InstanceMetadataServiceResourceFetcher.java:91)
	at com.amazonaws.internal.InstanceMetadataServiceResourceFetcher.readResource(InstanceMetadataServiceResourceFetcher.java:69)
	at com.amazonaws.internal.EC2ResourceFetcher.readResource(EC2ResourceFetcher.java:66)
	at com.amazonaws.util.EC2MetadataUtils.getItems(EC2MetadataUtils.java:403)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:372)
	at com.amazonaws.util.EC2MetadataUtils.getData(EC2MetadataUtils.java:368)
	at com.amazonaws.util.EC2MetadataUtils.getEC2InstanceRegion(EC2MetadataUtils.java:283)
	at com.amazonaws.regions.InstanceMetadataRegionProvider.tryDetectRegion(InstanceMetadataRegionProvider.java:59)
	at com.amazonaws.regions.InstanceMetadataRegionProvider.getRegion(InstanceMetadataRegionProvider.java:50)
	at com.amazonaws.regions.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:46)
	at com.amazonaws.client.builder.AwsClientBuilder.determineRegionFromRegionProvider(AwsClientBuilder.java:475)
	at com.amazonaws.client.builder.AwsClientBuilder.setRegion(AwsClientBuilder.java:458)
	at com.amazonaws.client.builder.AwsClientBuilder.configureMutableProperties(AwsClientBuilder.java:424)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at org.apache.ranger.audit.destination.AmazonCloudWatchAuditDestination.newClient(AmazonCloudWatchAuditDestination.java:208)
	at org.apache.ranger.audit.destination.AmazonCloudWatchAuditDestination.getClient(AmazonCloudWatchAuditDestination.java:197)
	at org.apache.ranger.audit.destination.AmazonCloudWatchAuditDestination.init(AmazonCloudWatchAuditDestination.java:89)
	at org.apache.ranger.audit.provider.AuditProviderFactory.init(AuditProviderFactory.java:180)
	at org.apache.ranger.plugin.service.RangerBasePlugin.init(RangerBasePlugin.java:245)
	at com.amazonaws.emr.recordserver.auth.provider.ranger.RangerSparkPluginProvider$.<init>(RangerSparkPluginProvider.scala:36)
	at com.amazonaws.emr.recordserver.auth.provider.ranger.RangerSparkPluginProvider$.<clinit>(RangerSparkPluginProvider.scala)
	at com.amazonaws.emr.recordserver.auth.provider.ranger.SparkRangerAuthProvider.<init>(SparkRangerAuthProvider.scala:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.amazonaws.emr.recordserver.util.ReflectionUtils$.createInstanceOf(ReflectionUtils.scala:9)
	at com.amazonaws.emr.recordserver.module.BaseModule.authProvider(BaseModule.scala:42)
	at com.amazonaws.emr.recordserver.module.BaseModule$$FastClassByGuice$$edf05d6b.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1094)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
	at com.amazonaws.emr.recordserver.server.RecordServer.<init>(RecordServerMain.scala:29)
	at com.amazonaws.emr.recordserver.server.RecordServer$.main(RecordServerMain.scala:21)
	at com.amazonaws.emr.recordserver.server.RecordServer.main(RecordServerMain.scala)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.amazonaws.internal.ConnectionUtils.connectToEndpoint(ConnectionUtils.java:52)
	at com.amazonaws.internal.EC2ResourceFetcher.doReadResource(EC2ResourceFetcher.java:80)
	... 46 more _**

it looks like the sdk is not able to reach the metadata endpoint of the EC2 instance to get aws credentials. When we ssh to the EC2 node we can see that there are no permission restrictions as we can run Aws CLI commands without errors, we can also run IMDSv2 and IMDSv1 without any problem.

### Steps to Reproduce

We are setting up an EMR cluster with Ranger integration within a private subnet (with no access to internet)

### Current behavior

See above

### AWS Java SDK version used

1.11.841

### JDK version used

1.8

### Operating System and version

Amazon linux

**Comment by Ans-hrf** [comment]
Not relevant anymore, the error was misleading, it had nothing to do with the SDK
