### ISSUE TITLE
java.lang.NoClassDefFoundError when creating AmazonS3Client

### ISSUE THREAD

**Issue by spachari-im** [aws/aws-sdk-java#2688]
### Describe the issue

I am working on a Vertx framework, Gradle project setup in IntelliJ IDEA IDE. When I run unit test cases in the project, I get the following error whenever the AmazonS3Client is created.

When I run any JUnit test case on the IDE OR when I run unit test cases with "gradle build" command for the project, I get the following error.
```
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.AmazonS3Client
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.defaultClient(AmazonS3ClientBuilder.java:54)
	at com.QueueManagerVerticle.start(QueueManagerVerticle.java:25)
```

### Steps to Reproduce

When I run any JUnit test case on the IntelliJ IDE OR when I run unit test cases with "gradle build" command for the project, I get the following error.
```
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.AmazonS3Client
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.defaultClient(AmazonS3ClientBuilder.java:54)
	at com.QueueManagerVerticle.start(QueueManagerVerticle.java:25)
```

### Current behavior

The project's **build.gradle** has the following dependency:
```
dependencies {
...
    compile "com.amazonaws:aws-java-sdk:1.12.131"
...
}
```
There are several Java classes that need a AmazonS3Client object. Like this:

`queueService = new QueueService(AmazonS3ClientBuilder.defaultClient(), context.config());
`

```
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.AmazonS3Client
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
	at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.services.s3.AmazonS3ClientBuilder.defaultClient(AmazonS3ClientBuilder.java:54)
	at com.QueueManagerVerticle.start(QueueManagerVerticle.java:25)
```

### AWS Java SDK version used

1.12.131

### JDK version used

jdk1.8.0_281

### Operating System and version

MacOS Big Sur 11.5.2

**Comment by kozub** [comment]
Hey @spachari-im! Thanks for raising that issue. Could you please provide sample of code that allows to reproduce this issue (e.g. empty project with that failing tests)? It's quite hard for me to reproduce it on my env.

**Comment by aaoswal** [comment]
Hi @spachari-im,
Thank you for submitting the issue. As previously mentioned by @kozub, could you please provide a sample code for reproducing the issue?
