### ISSUE TITLE
com.amazonaws.SdkClientException: Unable to store object contents to disk: Read timed out

### ISSUE THREAD

**Issue by shenhongwei33** [aws/aws-sdk-java#2700]
### Describe the issue

This error is reported when I use TransferManager to download a single file. Scenario: I use a thread pool for object storage bucket migration. Each thread will create a new AmazonS3 and TransferManager to download a single file. The exception information is as follows:

```
com.amazonaws.SdkClientException: Unable to store object contents to disk: Read timed out
        at com.amazonaws.services.s3.internal.ServiceUtils.downloadToFile(ServiceUtils.java:314)
        at com.amazonaws.services.s3.transfer.DownloadCallable.retryableDownloadS3ObjectToFile(DownloadCallable.java:282)
        at com.amazonaws.services.s3.transfer.DownloadCallable.downloadAsSingleObject(DownloadCallable.java:92)
        at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:102)
        at com.amazonaws.services.s3.transfer.internal.AbstractDownloadCallable.call(AbstractDownloadCallable.java:40)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:197)
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:107)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at com.amazonaws.services.s3.internal.ServiceUtils.downloadToFile(ServiceUtils.java:308)
        ... 8 common frames omitted
```

### Steps to Reproduce

        AmazonS3 orignS3 = null;
        AmazonS3 toS3 = null;
        TransferManager transferManager_orign = null;
        TransferManager transferManager_to = null;
        File objectFile = null;
        try {
            orignS3 = getAmazonS3(migrateTask.getOrignEndpoint(), migrateTask.getOrignRegion(), migrateTask.getOrignAccessKey(), migrateTask.getOrignSecretKey());
            toS3 = getAmazonS3(migrateTask.getTargetEndpoint(), migrateTask.getTargetRegion(), migrateTask.getTargetAccessKey(), migrateTask.getTargetSecretKey());
        if (Objects.isNull(bucket) || StringUtils.isEmpty(objectKey)) {
            throw new ObjectMigrationFailtureException("待迁移的桶或对象信息为空！", migrateTask, bucket, objectKey, orignS3, toS3);
        }
        if (Objects.isNull(orignS3) || Objects.isNull(toS3)) {
            throw new ObjectMigrationFailtureException("对象存储客户端为空！", migrateTask, bucket, objectKey, orignS3, toS3);
        }
        String migrationTaskName = migrateTask.getTaskName();
        String bucketName = bucket.getBucketName();
            ThreadFactory threadFactory = new ThreadFactory() {
                public Thread newThread(Runnable r) {
                    Thread thread = new Thread(r);
                    thread.setName("s3-transfer-manager-worker-" + objectKey);
                    return thread;
                }
            };
            transferManager_orign = TransferManagerBuilder.standard()
                    .withS3Client(orignS3).withAlwaysCalculateMultipartMd5(true).withShutDownThreadPools(true).withExecutorFactory(() -> Executors.newSingleThreadExecutor(threadFactory)).withMinimumUploadPartSize(10*1024*1024L).withMultipartUploadThreshold(10*1024*1024L)
                    .build();
            transferManager_to = TransferManagerBuilder.standard()
                    .withS3Client(toS3).withAlwaysCalculateMultipartMd5(true).withShutDownThreadPools(true).withExecutorFactory(() -> Executors.newSingleThreadExecutor(threadFactory)).withMinimumUploadPartSize(8*1024*1024L).withMultipartUploadThreshold(16*1024*1024L)
                    .build();

### Current behavior

I think this exception will continue to retry the migration, but if it continues, it will cause some objects to fail to migrate

### AWS Java SDK version used

aws-java-sdk-bom 1.12.138

### JDK version used

java version "1.8.0_172" Java(TM) SE Runtime Environment (build 1.8.0_172-b11) Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

### Operating System and version

centos 7.6

**Comment by shenhongwei33** [comment]
I haven't found the package that can realize automatic segmented download through TransferManager, but there is a specific download method to judge whether to download in parallel. Will the subsequent function be added like segmented upload?

**Comment by aaoswal** [comment]
Hi @shenhongwei33,
Could you please confirm:
- The total requests do not exceed the [3,500 requests per second](https://aws.amazon.com/premiumsupport/knowledge-center/s3-request-limit-avoid-throttling/#:~:text=You%20can%20send%203%2C500%20PUT,t%20share%20the%20same%20limit.).
- The socket timeout is not occurring due to network failures and instability. 

The stack-trace shows that the error is being caused due to `java.net.SocketTimeoutException: Read timed out` which might occur due to low timeout defaults. Hence, have you tried using custom timeout configuration for your client?
Example:
```
    ClientConfiguration config = new ClientConfiguration(); 
    config.setConnectionTimeout(connectionTimeout);
    config.setSocketTimeout(readTimeout); 
    AmazonS3 s3 = new AmazonS3Client(credentials, config);
```

Hope this helps!

**Comment by shenhongwei33** [comment]
@aaoswal 
Here is my client configuration：
```
ClientConfiguration config = new ClientConfiguration();
            config.setMaxConnections(128);
            config.setSocketTimeout(120000);
            config.setConnectionTimeout(60000);
            config.setConnectionMaxIdleMillis(130000);
            config.setResponseMetadataCacheSize(80);
            config.setMaxErrorRetry(3);
            config.setSocketBufferSizeHints(10240,10240);
```
I tried to set a smaller thread concurrency (4), and then each thread will create a new AmazonS3 and TransferManager to transfer a file. When the size of the transferred file is about 10G, if 4 threads download at the same time, the download speed will decrease after a period of time. will be 0, then an exception will be thrown.I think the network shouldn't matter, because it will automatically retry once, and each time the automatic retry will start the download, after stopping it will throw an exception.
`transferManager_orign = TransferManagerBuilder.standard().withS3Client(orignS3).withAlwaysCalculateMultipartMd5(true).withShutDownThreadPools(true).withExecutorFactory(() -> Executors.newFixedThreadPool(((2,downThreadFactory))
                    .build();
`
The overall download speed of the four threads is about 50M/s. I found nothing by checking the thread dump. I am curious why the data stream cannot be pulled. According to the SDK, the data stream of the object should have been obtained at this time.

**Comment by shenhongwei33** [comment]
The problem occurs when each thread is downloading a separate 10G sized file at the same time, no problem with small files

**Comment by shenhongwei33** [comment]
The problem occurs when each thread is downloading a separate 10G sized file at the same time, no problem with small files，I found that some JDK versions have similar data transmission problems before, but the JDK version I use should not have similar problems

**Comment by shenhongwei33** [comment]
> Hi @shenhongwei33, Could you please confirm:
> 
> * The total requests do not exceed the [3,500 requests per second](https://aws.amazon.com/premiumsupport/knowledge-center/s3-request-limit-avoid-throttling/#:~:text=You%20can%20send%203%2C500%20PUT,t%20share%20the%20same%20limit.).
> * The socket timeout is not occurring due to network failures and instability.
> 
> The stack-trace shows that the error is being caused due to `java.net.SocketTimeoutException: Read timed out` which might occur due to low timeout defaults. Hence, have you tried using custom timeout configuration for your client? Example:
> 
> ```
>     ClientConfiguration config = new ClientConfiguration(); 
>     config.setConnectionTimeout(connectionTimeout);
>     config.setSocketTimeout(readTimeout); 
>     AmazonS3 s3 = new AmazonS3Client(credentials, config);
> ```
> 
> Hope this helps!

**Comment by shenhongwei33** [comment]
I noticed that my downloads are not multi-threaded, and uploads are multi-threaded, so if I want multi-threaded downloads, how should I configure them? I want to avoid this problem by downloading with multiple threads, but I debug locally and find that the SDK is false every time it judges whether to download in parallel

**Comment by aaoswal** [comment]
Hi @shenhongwei33,
Apologies for the delay but I am unable to reproduce the issue on my end with the code snippet provided.

I would like to request you to please provide a simple java project replicating the error with necessary code for reproduction on my end. This would help me assist you better and provide you with an appropriate solution at a much faster pace.

I am actively working on finding a solution towards this issue.

Really appreciate for your patience.

**Comment by shenhongwei33** [comment]
@aaoswal 
Really appreciate for your patience.
I use the springboot framework to quickly build, the main code is as follows:
```
    @Async("migrationTaskRxecuter")
    @Override
    public void downloadAndUploadObject(MigrateTasks migrateTask, BucketList bucket, String objectKey, String pre_file_bucket_path, String toBucketName) {
        AmazonS3 orignS3 = null;
        AmazonS3 toS3 = null;
        TransferManager transferManager_orign = null;
        TransferManager transferManager_to = null;
        File objectFile = null;
        try {
            orignS3 = getAmazonS3(migrateTask.getOrignEndpoint(), migrateTask.getOrignRegion(), migrateTask.getOrignAccessKey(), migrateTask.getOrignSecretKey(),true);
            toS3 = getAmazonS3(migrateTask.getTargetEndpoint(), migrateTask.getTargetRegion(), migrateTask.getTargetAccessKey(), migrateTask.getTargetSecretKey(),false);
        if (Objects.isNull(bucket) || StringUtils.isEmpty(objectKey)) {
            throw new ObjectMigrationFailtureException("error", migrateTask, bucket, objectKey, orignS3, toS3);
        }
        if (Objects.isNull(orignS3) || Objects.isNull(toS3)) {
            throw new ObjectMigrationFailtureException("error", migrateTask, bucket, objectKey, orignS3, toS3);
        }
        String migrationTaskName = migrateTask.getTaskName();
        String bucketName = bucket.getBucketName();
            ThreadFactory downThreadFactory = new ThreadFactory() {
                public Thread newThread(Runnable r) {
                    Thread thread = new Thread(r);
                    thread.setName("s3-tm-d-" + objectKey);
                    return thread;
                }
            };
            ThreadFactory upThreadFactory = new ThreadFactory() {
                public Thread newThread(Runnable r) {
                    Thread thread = new Thread(r);
                    thread.setName("s3-tm-up-" + objectKey+"-"+new Random().nextInt(10));
                    return thread;
                }
            };
            transferManager_orign = TransferManagerBuilder.standard()
                    .withS3Client(orignS3).withAlwaysCalculateMultipartMd5(true).withShutDownThreadPools(true).withExecutorFactory(() -> Executors.newSingleThreadExecutor(downThreadFactory))
                    .build();
            transferManager_to = TransferManagerBuilder.standard()
                    .withS3Client(toS3).withAlwaysCalculateMultipartMd5(true).withShutDownThreadPools(true).withExecutorFactory(() -> Executors.newFixedThreadPool(((migration_maxPoolSize-ConstantUtil.S3_SGENT_EXIT_NUM)/ConstantUtil.S3_SGENT_EXIT_NUM)/2+1,upThreadFactory)).withMinimumUploadPartSize(8*1024*1024L).withMultipartUploadThreshold(16*1024*1024L)
                    .build();
            if (ConstantUtil.MigrateType.OBJECT_TYPE.getValue().equals(migrateTask.getTaskType())) {
                //文件迁移
                BucketObjects object = bucketObjectsService.getOne(new QueryWrapper<BucketObjects>().eq("bucket_id", bucket.getBucketId()).eq("object_key", objectKey));
                if (Objects.nonNull(object)) {
                    object.setStartTime(LocalDateTime.now());
                    ObjectMetadata orignS3ObjectMetadata = orignS3.getObjectMetadata(bucketName, objectKey);
                    if (Objects.nonNull(orignS3ObjectMetadata)) {
                        object.setObjectEtag(orignS3ObjectMetadata.getETag());
                    } else {
                        log.error("任务名称：[{}] ----桶:[{}]---------对象：[{}]迁移时未从源端获取到etag信息！", migrationTaskName, bucketName, objectKey);
                        migrationFailLogger.error("任务名称：[{}] ----桶:[{}]---------对象：[{}]迁移时未从数据库查到对象信息", migrationTaskName, bucketName, objectKey);
                    }
                    bucketObjectsService.updateById(object);
                } else {
                    log.error("任务名称：[{}] ----桶:[{}]---------对象：[{}]迁移时未从数据库查到对象信息", migrationTaskName, bucketName, objectKey);
                    migrationFailLogger.error("任务名称：[{}] ----桶:[{}]---------对象：[{}]迁移时未从数据库查到对象信息", migrationTaskName, bucketName, objectKey);
                }
            }
            if (isDir(objectKey)) {
                migrationSuccessLogger.info("任务名称：[{}] ----桶:[{}]===================出现空文件夹：[{}]", migrationTaskName, bucketName, objectKey);
                if (!toS3.doesObjectExist(toBucketName, objectKey)) {
                    //子文件夹，已经拉取下来并上传
                    migrationSuccessLogger.info("任务名称：{} ----桶:{}===================空文件夹已在目标端创建：{}", migrationTaskName, bucketName, objectKey);
                    toS3.putObject(toBucketName, objectKey, "");
                }
                bucketListService.updateBucketProgress(migrateTask, bucket, objectKey, true, "", orignS3, toS3, 0);
            } else {
                //文件,开始下载
                objectFile = new File(pre_file_bucket_path + objectKey);
                if (toS3.doesObjectExist(toBucketName, objectKey)) {
                    //文件已经存在
                    migrationFailLogger.info("任务名称：[{}] ----桶:[{}]&&&&&&&&&&&&&&&&&&文件在目标端已存在，跳过：[{}]", migrationTaskName, toBucketName, objectKey);
                    bucketListService.updateBucketProgress(migrateTask, bucket, objectKey, true, "文件已在目标端存在", orignS3, toS3, 0);
                    return;
                }
                if (!objectFile.exists()) {
                    migrationSuccessLogger.info("任务名称：[{}] ----桶:[{}]-----开始迁移文件：[{}]", migrationTaskName, bucketName, objectKey);
                    //文件key存在则跳过
                    //如果文件不存在，则拉取，若存在，则是上面文件夹已经拉取过，则跳过即可
                    Download xfer = transferManager_orign.download(bucketName, objectKey, objectFile);
                    //XferMgrProgress.showTransferProgress(xfer);
                    xfer.waitForCompletion();
                    if (Objects.nonNull(transferManager_orign)) {
                        transferManager_orign.shutdownNow(false);
                    }
                    if (xfer.isDone()) {
                        //开始上传
                        if (objectFile.exists()) {
                            Upload xfer_to = transferManager_to.upload(toBucketName, objectKey, objectFile);
                            //XferMgrProgress.showTransferProgress(xfer_to);
                            xfer_to.waitForCompletion();
                            if (Objects.nonNull(transferManager_to)) {
                                transferManager_to.shutdownNow(false);
                            }
                            //
                            if (xfer_to.isDone()) {
                                chectEtagAndLengthOnObject(orignS3, toS3, bucketName, toBucketName, objectKey);
                            }
                            migrationSuccessLogger.info("任务名称：[{}] ----桶:[{}]-----文件迁移完成-成功：[{}]", migrationTaskName, bucketName, objectKey);
                            bucketListService.updateBucketProgress(migrateTask, bucket, objectKey, true, "", orignS3, toS3, objectFile.length());
                        } else {
                            //文件不存在
                            migrationFailLogger.error("任务名称：[{}] ----桶:[{}]!!!!!!!!!!!!!!!文件下载后不存在，跳过迁移-失败：[{}]", migrationTaskName, bucketName, objectKey);
                            bucketListService.updateBucketProgress(migrateTask, bucket, objectKey, false, "文件下载后不存在", orignS3, toS3, 0);
                        }
                    } else {
                        migrationFailLogger.error("任务名称：[{}] ----桶:[{}]!!!!!!!!!!!!!!!文件下载异常，跳过迁移-失败：[{}]", migrationTaskName, bucketName, objectKey);
                        bucketListService.updateBucketProgress(migrateTask, bucket, objectKey, false, "文件下载异常,没有完全下载！", orignS3, toS3, 0);
                    }
                } else {
                    migrationFailLogger.error("任务名称：[{}] ----桶:[{}]-----文件迁移前已在本地存在，跳过迁移--：[{}]", migrationTaskName, bucketName, objectKey);
                    bucketListService.updateBucketProgress(migrateTask, bucket, objectKey, false, "文件迁移前已在本地存在", orignS3, toS3, 0);
                }
                if (objectFile.exists()) {
                    objectFile.delete();
                }
            }
        } catch (InterruptedException e) {
            throw new ObjectMigrationFailtureException(e.getMessage(), migrateTask, bucket, objectKey, e, orignS3, toS3);
        } catch (MigraionStatusUpdateFailtureException e) {
            throw new ObjectMigrationFailtureException(e.getMessage(), migrateTask, bucket, objectKey, e, orignS3, toS3);
        } catch (SdkClientException e) {
            throw new ObjectMigrationFailtureException("源端不存在该对象,桶不存在或者对象Key异常", migrateTask, bucket, objectKey, e, orignS3, toS3);
        } catch (Exception e) {
            throw new ObjectMigrationFailtureException(e.getMessage(), migrateTask, bucket, objectKey, e, orignS3, toS3);
        } finally {
            if (Objects.nonNull(transferManager_orign)) {
                transferManager_orign.shutdownNow(true);
                transferManager_orign = null;
            }
            if(Objects.nonNull(orignS3)){
                orignS3.shutdown();
                orignS3 = null;
            }
            if (Objects.nonNull(transferManager_to)) {
                transferManager_to.shutdownNow(true);
                transferManager_to = null;
            }
            if(Objects.nonNull(toS3)){
                toS3.shutdown();
                toS3 = null;
            }
            if (Objects.nonNull(objectFile) && objectFile.exists()) {
                FileUtils.deletefile(objectFile.getAbsolutePath(), true);
                objectFile = null;
            }
        }
    }

    /**
     * 
     * @param endpoint
     * @param region
     * @param accessKey
     * @param secretKey
     * @return
     * @throws AmazonS3ClientCreateFailtureException
     */
    private AmazonS3 getAmazonS3(String endpoint,String region,String accessKey,String secretKey,boolean isDownload) throws AmazonS3ClientCreateFailtureException{
        AmazonS3 orignS3 = null;
        try {
            ClientConfiguration config = new ClientConfiguration();
            config.setMaxConnections(4);
            config.setSocketTimeout(120000);
            config.setConnectionTimeout(60000);
            config.setConnectionMaxIdleMillis(10000);
            config.setResponseMetadataCacheSize(80);
            config.setUseExpectContinue(false);
            config.setMaxErrorRetry(3);
            config.setSocketBufferSizeHints(10240,10240);
            AwsClientBuilder.EndpointConfiguration endpointConfig = new AwsClientBuilder.EndpointConfiguration(endpoint, region);
            AWSCredentials awsCredentials = null;
            try {
                awsCredentials = new BasicAWSCredentials(RSAUtil.decrypt(accessKey), RSAUtil.decrypt(secretKey));
            } catch (GeneralSecurityException e) {
                e.printStackTrace();
            }
            AWSCredentialsProvider awsCredentialsProvider = new AWSStaticCredentialsProvider(awsCredentials);

            if(endpoint.toLowerCase().contains("https")){
                config.setProtocol(Protocol.HTTPS);
                HttpClientBuilder builder = HttpClientBuilder.create().useSystemProperties();
                SSLContext sslContext = null;

                sslContext = new SSLContextBuilder().loadTrustMaterial(null,
                        (TrustStrategy) (X509Certificate[] arg0, String arg1) -> true).build();
                builder.setSSLContext(sslContext);
                HostnameVerifier hostnameVerifier = new NoopHostnameVerifier();
                config.getApacheHttpClientConfig().withSslSocketFactory(new SSLConnectionSocketFactory(sslContext,hostnameVerifier));
            }

            orignS3 = AmazonS3Client.builder()
                    .withEndpointConfiguration(endpointConfig)
                    .withClientConfiguration(config)
                    .withCredentials(awsCredentialsProvider)
                    .disableChunkedEncoding()
                    .withPathStyleAccessEnabled(true)
                    .build();
        } catch (NoSuchAlgorithmException e) {
            throw new AmazonS3ClientCreateFailtureException(e.getMessage(),e);
        } catch (KeyManagementException e) {
            throw new AmazonS3ClientCreateFailtureException(e.getMessage(),e);
        } catch (KeyStoreException e) {
            throw new AmazonS3ClientCreateFailtureException(e.getMessage(),e);
        }catch (Exception e){
            throw new AmazonS3ClientCreateFailtureException(e.getMessage(),e);
        }
        return orignS3;
    }

    /**
     * 
     *
     * @param orignS3
     * @param toS3
     * @param orignBucketName
     * @param toBucketName
     * @param objectKey
     */
    private void chectEtagAndLengthOnObject(AmazonS3 orignS3, AmazonS3 toS3, String orignBucketName, String toBucketName ,String objectKey) {
            if (Objects.isNull(orignS3) || Objects.isNull(toS3)) {
                log.error("文件对比的源端或目标端S3 Client为空！");
            }
            if (StringUtils.isEmpty(orignBucketName) || StringUtils.isEmpty(objectKey) || StringUtils.isEmpty(toBucketName)) {
                log.error("文件对比的桶名或文件KEY为空！");
            }
            if (isDir(objectKey)) {
                log.info("对象 key： {}，为文件夹，不进行比对", objectKey);
                return;
            }
            boolean isSame = false;
            boolean isEtagSame = false;
            boolean isExit = false;
            ObjectMetadata orignS3ObjectMetadata = orignS3.getObjectMetadata(orignBucketName, objectKey);
            ObjectMetadata toS3ObjectMetadata = toS3.getObjectMetadata(toBucketName, objectKey);
            if (orignS3.doesObjectExist(orignBucketName, objectKey)) {
                isExit = true;
                if (orignS3ObjectMetadata.getETag().equals(toS3ObjectMetadata.getETag())) {
                    isSame = true;
                    isEtagSame = true;
                }
                if (orignS3ObjectMetadata.getContentLength() == toS3ObjectMetadata.getContentLength()) {
                    isSame = true;
                }
            }
            if (isEtagSame) {
                migrationSuccessLogger.info("[源端桶为：{} ，目标桶为：{}，对象 key： {}，是否存在：{} ，etag是否相同：{},内容长度是否相同 ： {} ，orign_etag为 ：{},to_etag为：{},orign_length：{} ，to_length:{}]", orignBucketName, toBucketName, objectKey, isExit, isEtagSame, isSame,orignS3ObjectMetadata.getETag(), toS3ObjectMetadata.getETag(), orignS3ObjectMetadata.getContentLength(), toS3ObjectMetadata.getContentLength());
            } else {
                migrationFailLogger.warn("[源端桶为：{} ，目标桶为：{}，对象 key： {}，是否存在：{} ，etag是否相同：{},内容长度是否相同 ： {},orign_etag为 ：{},to_etag为：{},orign_length：{} ，to_length:{}]", orignBucketName, toBucketName, objectKey, isExit, isEtagSame, isSame,orignS3ObjectMetadata.getETag(), toS3ObjectMetadata.getETag(), orignS3ObjectMetadata.getContentLength(), toS3ObjectMetadata.getContentLength());
            }
    }

    /**
     * 
     *
     * @param objectKey
     * @return
     */
    private boolean isDir(String objectKey) {
        if (null != objectKey) {
            return objectKey.lastIndexOf("/") == (objectKey.length() - 1);
        }
        return false;
    }
```
I deployed on the 8C16G server on centos7.6. To reproduce the problem, the following conditions must be met: each thread is downloading a separate file larger than 10G at the same time, not 4 threads are downloading a file, that is, thread A is downloading the file A. Thread B is downloading file B. Both files A and B are larger than 10G. The downloaded files are all in the same local directory. When the download starts, the speed can reach 50M/s, and the speed is basically 0 after a period of time. After a period of time, the read timoout exception will be thrown and the download will be restarted. At this time, the speed can still reach 50M/s. After a period of time, the speed will drop to 0, and the read timeout exception will continue to be thrown, and the file download will fail. 
I don't know why the download stops after a while, and at the same time I found that I can't configure the number of routes per IP of httpclient, can you help me how to use the SDK to implement chunked download to avoid this problem? Because I found that there is no problem with uploading large files

**Comment by shenhongwei33** [comment]
I found that the problem of not being able to read the data stream may be caused by the poor performance of the object storage I am requesting, the frequency of the problem can be alleviated by downloading in chunks, but it still occurs sometimes

**Comment by aaoswal** [comment]
Hi @shenhongwei33,
You are partially correct. 
The problem occurring here is due to using multiple instances of `AmazonS3Client`. The client is thread safe and manages its own connection pool resources, hence it is recommended to create a single client and reuse it wherever possible.

In your use-case, each thread is creating a new client, each client will have its own connection pool so multiple connection pools have too much resource allocation and can exhaust the environment resources causing all of the threads to fail at once and hence result in the download to fail.

Hope this helps!

**Comment by shenhongwei33** [comment]
@aaoswal  Really appreciate for your patience.
I understand what you mean, but I found in actual use that multiple thread pools reusing one AmazonS3Client will cause the download speed to be very slow, the download speed is about 2M/s, and the download speed of one client per thread can reach 50M /s, is there something wrong with my configuration? The specific client configuration is similar to what I provided above

**Comment by shenhongwei33** [comment]
At the same time, I will close the client and TransferManager in time after downloading the file, so as to ensure that only the executing thread will have a client connection. Will this also affect it?

**Comment by shenhongwei33** [comment]
Can this question be reopened please? I can't find the reopen button
