### ISSUE TITLE
java.lang.IllegalStateException: Connection pool shut down 

### ISSUE THREAD

**Issue by wowlike** [aws/aws-sdk-java#2703]
### Describe the bug

hi!, i have requst AmazonS3Client#putObject -> Connection pool shut down 

### Expected behavior

connection pool don't shut down 

### Current behavior

connection pool shut down 

### Steps to Reproduce

call AmazonS3Client#putObject

### Context

```
java.lang.IllegalStateException: Connection pool shut down
  at org.apache.http.util.Asserts.check(Asserts.java:34)
  at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
  at sun.reflect.GeneratedMethodAccessor297.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
  at com.amazonaws.http.conn.$Proxy264.requestConnection(Unknown Source)
  at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
  at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
  at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
  at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
  at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1331)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5248)
  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5195)
  at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:415)
  at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6309)
  at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1840)
  at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1800)
  ```

### AWS Java SDK version used

1.11.939

### JDK version used

jdk 8 

### Operating System and version

linux

**Comment by aaoswal** [comment]
Hi @likedeke,
Could you please provide a steps to reproduce the issue and a sample code for the same?

**Comment by likedeke** [comment]
@aaoswal  ok, it'll take a few days. I'm a bit busy at work right now，sorry!

**Comment by likedeke** [comment]
there's a message queue that accepts requests to download files, and then uploads those files with the AWS SDK, and maybe a few hours later, maybe overnight, `Connection Pool shut down` will appear.  I'm using a thread pool to listen to this queue.

**Comment by aaoswal** [comment]
Hi @likedeke,
Could you please provide a sample code in Java to reproduce the issue? 

A working code will help me understand the problem area and help assist you faster.

**Comment by likedeke** [comment]
@aaoswal hello,`git@github.com:likedeke/aws-conn-pool-down.git` is there. I haven't run this program yet，sorry，and you need a mq.

**Comment by wowlike** [comment]
i use ali sdk now.

**Comment by liuliangping** [comment]
hi .  where I can fand ali sdk? I hava same  problem when I use  AWS Java SDK 1.11.391
