### ISSUE TITLE
XML Parse Exceptions when calling S3 deleteObjects

### ISSUE THREAD

**Issue by loesak** [aws/aws-sdk-java#2705]
### Describe the bug

This issue is pretty identical to one reported, and closed unfixed, in 2017.
https://github.com/aws/aws-sdk-java/issues/1430

We are calling deleteObjects on objects that are shortly created. We often run into throttling responses from the API as the write capacity hasn't yet been allocated. The throttling responses are not an issue as the SDK is configured for retry and does attempt to retry.

However, on many occasions, we get an SAXParseException during the DeleteObjects operation (See exception below). Sometimes it's on the first call, sometimes its during a retry due to throttling. We've never seen it happen on objects that have existing for a longer period of time (has had their write capacity allocated).

We are following the AWS S3 best practices for maximizing S3 read & write throughput.

We were using AWS Java SDK version 1.11.584 and upgraded to the latest (at that time) 1.12.144 and same behavior between the two. We are also using the predefined SDKDefaultRetryCondition for our S3 client.

It may be worth knowing that we're calling DeleteObjects on a single object. We are unsure if the same behavior exists if using the DeleteObject operation.

Also to add to the symptoms, it seems that the request to delete the object that returns the invalid/incomplete XML response does end up being successful as when we retry to read the object, it no longer exists.

### Expected behavior

DeleteObjects call does not fail with SAXParseException from API response.

### Current behavior

DeleteObjects call occasionally fails with SAXParseException

```
Failed to parse XML document with handler class com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$DeleteObjectsHandler:
 com.amazonaws.SdkClientException
com.amazonaws.SdkClientException: Failed to parse XML document with handler class com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser$DeleteObjectsHandler
at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseXmlInputStream(XmlResponsesSaxParser.java:181)
at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseDeletedObjectsResult(XmlResponsesSaxParser.java:488)
at com.amazonaws.services.s3.model.transform.Unmarshallers$DeleteObjectsResultUnmarshaller.unmarshall(Unmarshallers.java:348)
at com.amazonaws.services.s3.model.transform.Unmarshallers$DeleteObjectsResultUnmarshaller.unmarshall(Unmarshallers.java:344)
at com.amazonaws.services.s3.internal.S3XmlResponseHandler.handle(S3XmlResponseHandler.java:62)
at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:44)
at com.amazonaws.services.s3.internal.ResponseHeaderHandlerChain.handle(ResponseHeaderHandlerChain.java:30)
at com.amazonaws.http.response.AwsResponseHandlerAdapter.handle(AwsResponseHandlerAdapter.java:69)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleResponse(AmazonHttpClient.java:1777)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleSuccessResponse(AmazonHttpClient.java:1474)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1381)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400)
at com.amazonaws.services.s3.AmazonS3Client.deleteObjects(AmazonS3Client.java:2332)
at com.ne.
..snip...
Caused by: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 1; Premature end of
 file.
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1473)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
at com.amazonaws.services.s3.model.transform.XmlResponsesSaxParser.parseXmlInputStream(XmlResponsesSaxParser.java:167)
... 26 more
```

### Steps to Reproduce

Attempt to delete an object in S3 that was just written to. Ensure the object path is an unseen path so that it is a candidate to be throttled as write capacity has yet to be allocated.

Our high level setup is we have a process that writes these files to S3. We have an S3 to SNS notification for ObjectCreated operations and a process that gets executed (lambda) that reads the new file and then deletes it when done.

### Context

Lamda executions are failing when trying to delete S3 objects. On retry, they fail again because the object does get deleted.

### AWS Java SDK version used

1.11.584 & 1.12.144

### JDK version used

8

### Operating System and version

Linux (Lambda)

**Comment by debora-ito** [comment]
@loesak thank you for reaching out, and apologies for taking so long to respond.

Issue https://github.com/aws/aws-sdk-java/issues/1430 was closed because, as @millems  explained, the team is prioritizing SDK v2 work and decided not fix this in v1.

I'll go ahead and mark this to autoclose soon, feel free to reach out if you have any further questions.

**Comment by sfc-gh-aramarathinam** [comment]
> @loesak thank you for reaching out, and apologies for taking so long to respond.
> 
> Issue #1430 was closed because, as @millems explained, the team is prioritizing SDK v2 work and decided not fix this in v1.
> 
> I'll go ahead and mark this to autoclose soon, feel free to reach out if you have any further questions.

Please do not close without at least a work around. We are running into this error. At least provide a workaround.
