### ISSUE TITLE
Missing JsonErrorShapeMetadata definition for ExpiredTokenException

### ISSUE THREAD

**Issue by McLuck** [aws/aws-sdk-java#2730]
### Describe the bug

Using an AWS account with a session timed, when the session times out AWS rejects requests to its APIs. We need the dynamodb client aware to have this error mapped.
The return from AWS is an ExpiredTokenException and the client should be able to handle the return.

### Expected behavior

Throws a com.amazonaws.services.securitytoken.model.ExpiredTokenException

### Current behavior

Throwing a log error com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided

### Steps to Reproduce

Use a AWS temporary credentials: https://docs.aws.amazon.com/pt_br/IAM/latest/UserGuide/id_credentials_temp_use-resources.html

### Possible Solution

Mapping for new Exception in com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient

### Context

When try any operation in dynamodb using this client, the exception is throws.

Stacktrace sample:
```java
2022-03-30 16:45:22.017 ERROR [roteirizador-veloe,690237e1a43f5488,60dfcebfda0e4955] 1 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ExpiredTokenException; Request ID: HR3O0EM30IGPU5E3288LNROMVJVV4KQNSO5AEMVJF66Q9ASUAAJG)] with root cause

com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ExpiredTokenException; Request ID: HR3O0EM30IGPU5E3288LNROMVJVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712) ~[aws-java-sdk-core-1.11.664.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367) ~[aws-java-sdk-core-1.11.664.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113) ~[aws-java-sdk-core-1.11.664.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.11.664.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744) ~[aws-java-sdk-core-1.11.664.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726) ~[aws-java-sdk-core-1.11.664.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686) ~[aws-java-sdk-core-1.11.664.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668) ~[aws-java-sdk-core-1.11.664.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532) ~[aws-java-sdk-core-1.11.664.jar!/:na]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512) ~[aws-java-sdk-core-1.11.664.jar!/:na]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:4805) ~[aws-java-sdk-dynamodb-1.11.664.jar!/:na]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4772) ~[aws-java-sdk-dynamodb-1.11.664.jar!/:na]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeScan(AmazonDynamoDBClient.java:3031) ~[aws-java-sdk-dynamodb-1.11.664.jar!/:na]
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.scan(AmazonDynamoDBClient.java:2997) ~[aws-java-sdk-dynamodb-1.11.664.jar!/:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.scan(DynamoDBMapper.java:1569) ~[aws-java-sdk-dynamodb-1.11.664.jar!/:na]
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.scan(AbstractDynamoDBMapper.java:236) ~[aws-java-sdk-dynamodb-1.11.664.jar!/:na]
	at org.socialsignin.spring.data.dynamodb.core.DynamoDBTemplate.scan(DynamoDBTemplate.java:124) ~[spring-data-dynamodb-5.2.5.jar!/:5.2.5]
	at org.socialsignin.spring.data.dynamodb.query.MultipleEntityScanExpressionQuery.getResultList(MultipleEntityScanExpressionQuery.java:37) ~[spring-data-dynamodb-5.2.5.jar!/:5.2.5]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery$CollectionExecution.execute(AbstractDynamoDBQuery.java:104) ~[spring-data-dynamodb-5.2.5.jar!/:5.2.5]
	at org.socialsignin.spring.data.dynamodb.repository.query.AbstractDynamoDBQuery.execute(AbstractDynamoDBQuery.java:311) ~[spring-data-dynamodb-5.2.5.jar!/:5.2.5]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.6.1.jar!/:2.6.1]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.6.1.jar!/:2.6.1]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:159) ~[spring-data-commons-2.6.1.jar!/:2.6.1]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138) ~[spring-data-commons-2.6.1.jar!/:2.6.1]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.15.jar!/:5.3.15]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.15.jar!/:5.3.15]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.15.jar!/:5.3.15]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.15.jar!/:5.3.15]
	at jdk.proxy2/jdk.proxy2.$Proxy155.findAllByChaveConsultaOrigemAndChaveConsultaDestino(Unknown Source) ~[na:na]
```

### AWS Java SDK version used

1.12.190

### JDK version used

17

### Operating System and version

MacOs 12.3

**Comment by debora-ito** [comment]
Hi @McLuck thank you for reaching out. It's weird you're seeing an `Unable to unmarshall` error in this case. Can you enable the verbose wirelogs and provide them with the response error? Please make sure to redact any sensitive info the wirelogs might contain, like access key ids. For info on how to enable see: https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html#sdk-net-logging-verbose
