### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by tbroadley** [aws/aws-sdk-java#2794]
### Describe the bug

The Amazon Translate SDK's `AmazonTranslate#translateText` method is throwing an AmazonServiceException when it receives a 429 from the Amazon Translate API. Based on the method's documentation, I'd expect it to throw a TooManyRequestsException.

### Expected Behavior

I expected `AmazonTranslate#translateText` to throw a TooManyRequestsException.

### Current Behavior

`AmazonTranslate#translateText` threw the following error:

```
com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonTranslate; Status Code: 429; Error Code: ThrottlingException; Request ID: 0113cb28-986c-4029-8ec4-19e777724de9; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1862)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1415)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1384)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
	at com.amazonaws.services.translate.AmazonTranslateClient.doInvoke(AmazonTranslateClient.java:1218)
	at com.amazonaws.services.translate.AmazonTranslateClient.invoke(AmazonTranslateClient.java:1185)
	at com.amazonaws.services.translate.AmazonTranslateClient.invoke(AmazonTranslateClient.java:1174)
	at com.amazonaws.services.translate.AmazonTranslateClient.executeTranslateText(AmazonTranslateClient.java:1064)
	at com.amazonaws.services.translate.AmazonTranslateClient.translateText(AmazonTranslateClient.java:1033)
        <project-specific stack frames removed>
```

### Reproduction Steps

I'm sorry, I don't think I'll be able to provide a SSCCE for this bug. It involves getting rate-limited by the Amazon Translate API. I suppose we should try to avoid that. If it'd truly be helpful, I can look into putting one together.

### Possible Solution

Add an unmarshaller for ThrottlingExceptions to the Amazon Translate SDK.

### AWS Java SDK version used

1.12.112

### JDK version used

My company is seeing this error on our cloud servers. I'd prefer not to share which JDK version they run.

### Operating System and version

My company is seeing this error on our cloud servers. I'd prefer not to share which OS they use.

**Comment by debora-ito** [comment]
@tbroadley I see that you prefer not to share the JDK version, but if you're using JDK 17 there are some reports of "Unable to unmarshall exception" due to reflective access changes in json - reported in https://github.com/aws/aws-sdk-java/issues/2754.

Are you using Java 17, would that be your case?

**Comment by tbroadley** [comment]
@debora-ito Ah thank you, I imagine that is indeed the issue.
