### ISSUE TITLE
Unable to unmarshall exception response with the unmarshallers provided

### ISSUE THREAD

**Issue by alibk0rd** [aws/aws-sdk-java#2795]
### Describe the bug

After upgrading to Java 17, Amazon Java (DynamoDB) SDK fails to unmarshall some errors:

```
com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: K7IOB4TL27I8KG12J3OJ28JGAFVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:6200)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:6167)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeUpdateItem(AmazonDynamoDBClient.java:5785)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:5749)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.doUpdateItem(DynamoDBMapper.java:871)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$2.executeLowLevelRequest(DynamoDBMapper.java:611)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.execute(DynamoDBMapper.java:750)
	at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.save(DynamoDBMapper.java:640)
	at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.save(AbstractDynamoDBMapper.java:128)
...
```

This is masking the real issue/error by failing to unmarshall the details.

### Expected Behavior

To have the real/underlying error details in the logs

### Current Behavior

Fails to unmarshall the error details, masking the real underlying issue or error

### Reproduction Steps

In at least one case the underlying error that the SDK fails to unmarshall is:

> com.amazonaws.services.dynamodbv2.model.ResourceInUseException: Cannot create preexisting table (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ResourceInUseException; Request ID: 17cbf84f-e818-499d-9cf7-5c636f420282; Proxy: null)

The underlying issue is reproduced by trying to recreate an existing DynamoDB table, but the end result is instead an exception of type `AmazonServiceException` with the error message:

> Unable to unmarshall exception response with the unmarshallers provided

Masking the root cause.

### Possible Solution

The upgrade to SDK v2 as [suggested elsewhere](https://github.com/aws/aws-sdk-java/issues/2754) is not a viable solution for us as AWS SDK v2 [is not supported by Spring AWS framework](https://github.com/awspring/spring-cloud-aws) yet.
Also, DynamoDB SDK v2 is yet to have feature parity with v1 (specifically `DynamoDBMapper`).

### AWS Java SDK version used

1.12.243

### JDK version used

17.0.3

### Operating System and version

Linux (Arch) Kernel: 5.18.7-arch1-1

**Comment by debora-ito** [comment]
Thank you for reaching out @alibk0rd.

We'll investigate the root cause of the unmarshalling error and better define the expectation of using JDK 17 with SDK v1. We'll update the README and other related docs with the results of the investigation.

**Comment by hsteidel** [comment]
Ran into this today.

JDK 17.03
Spring Boot: 2.6.9
Spring-Integration-AWS: 2.5.1
aws-java-sdk-dynamodb: 1.12.260
Jackson Databind: 2.13.3

I turned on log level debug and  the root cause seems to be
```
 Unable to make final void java.lang.Throwable.setCause(java.lang.Throwable) accessible: module java.base does not "opens java.lang" to unnamed module @4b0b0854
 ```

I might be wrong, but what I read according to the link below, is that this issue is slated to be fixed in  Jackson Databind 2.13.4/2.14.0.
https://github.com/FasterXML/jackson-databind/issues/3275

I tried downgrading a few dependencies as a workaround and no luck. I understand there are a few `illegal-access` jvm flags that can potentially be used in some Java versions, but I don't want to go there. 

Of note, this only happens to me when I set the `setTTL` option on the Table's config. Otherwise, I don't get this and my app works just fine. The offending call seems to be:
```
Sending Request: POST https://dynamodb.us-east-2.amazonaws.com / Headers: (amz-sdk-invocation-id: 0da40f4c-e922-e913-3bed-153132415507, Content-Length: 102, Content-Type: application/x-amz-json-1.0, User-Agent: aws-sdk-java/1.12.260 Mac_OS_X/12.4 OpenJDK_64-Bit_Server_VM/17.0.3+6-LTS java/17.0.3 vendor/Amazon.com_Inc. cfg/retry-mode/legacy, X-Amz-Target: DynamoDB_20120810.UpdateTimeToLive, ) 
```

**Comment by debora-ito** [comment]
Hello everyone,

after some deliberation we decided to clarify the scope of JDK support for the Java SDK v1. We added a section to the  README:
https://github.com/aws/aws-sdk-java#maintenance-and-support-for-java-versions

Essentially, the Java SDK v1 will support Java versions from 7 to 16.

If you are not able to migrate to Java SDK v2, the README section provides some workarounds based on the error you're experiencing. Please let us know of any error messages that are not on that list, we'll then provide a workaround too.

**Comment by storytime** [comment]
Same issue. 

![image](https://user-images.githubusercontent.com/2013788/188507016-0a92f838-381e-4b79-8538-cb58bc4269d3.png)

Pushing object 

![image](https://user-images.githubusercontent.com/2013788/188506992-bf40d7ce-9d7e-4bf1-af7c-acd82793332d.png)

Error: 
![image](https://user-images.githubusercontent.com/2013788/188507076-eec089e4-c417-4410-8797-bb299a0977fb.png)

![image](https://user-images.githubusercontent.com/2013788/188507127-c83dde27-df37-4cdc-b1f3-3f652af60a78.png)
