### ISSUE TITLE
Getting Error "Unable to execute HTTP request" when trying to access public s3 Bucket.

### ISSUE THREAD

**Issue by karunshivappa** [aws/aws-sdk-java#2798]

**Comment by chenja2000** [comment]
I'm wondering if we encountered the same issue on IBM Cloud Pak for Data:
at com.ibm.wdp.connect.connectors.ConnectorWrapper.createAndConnect(ConnectorWrapper.java:121)
at com.ibm.wdp.connect.connectors.ConnectorWrapper.discoverAssetsImpl(ConnectorWrapper.java:171)
at com.ibm.wdp.connect.connectors.ConnectorWrapper.discoverAssets(ConnectorWrapper.java:154)\n\t... 67 more\nCaused by: shadow.wdp.connect.library.file.amazons3.com.amazonaws.SdkClientException: Unable to execute HTTP request: com.ibm.jsse2.util.j: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target\n\t
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1207)\n\t
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1153)\n\t
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)\n\t
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)\n\t
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
shadow.wdp.connect.library.file.amazons3.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
shadow.wdp.connect.library.file.amazons3.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5445)
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5392)
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5386)
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.services.s3.AmazonS3Client.getS3AccountOwner(AmazonS3Client.java:1015)
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.services.s3.AmazonS3Client.getS3AccountOwner(AmazonS3Client.java:1005)
at com.ibm.connect.file.amazons3.AmazonS3.connect(AmazonS3.java:132)
at com.ibm.connect.file.FileConnector.connect(FileConnector.java:79)\n\t... 73 more\nCaused by: javax.net.ssl.SSLHandshakeException: com.ibm.jsse2.util.j: PKIX path building failed: com.ibm.security.cert.IBMCertPathBuilderException: unable to find valid certification path to requested target
at com.ibm.jsse2.g.a(Unknown Source)
at com.ibm.jsse2.bb.a(Unknown Source)
at com.ibm.jsse2.bb.a(Unknown Source)
at com.ibm.jsse2.bb.a(Unknown Source)
at com.ibm.jsse2.z$c.a(Unknown Source)
at com.ibm.jsse2.z$c.a(Unknown Source)\n\tat com.ibm.jsse2.z$c.consume(Unknown Source)\n\tat com.ibm.jsse2.p.consume(Unknown Source)\n\tat com.ibm.jsse2.aa.a(Unknown Source)\n\tat com.ibm.jsse2.aa.a(Unknown Source)\n\tat com.ibm.jsse2.bb.a(Unknown Source)\n\tat com.ibm.jsse2.a0.a(Unknown Source)\n\tat com.ibm.jsse2.bj.b(Unknown Source)\n\tat com.ibm.jsse2.bj.f(Unknown Source)\n\tat com.ibm.jsse2.bj.a(Unknown Source)
at com.ibm.jsse2.bj.startHandshake(Unknown Source)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
at shadow.wdp.connect.library.file.amazons3.com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:142)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by chenja2000** [comment]
@debora-ito You are right! We checked further. It seems related to proxy settings. The traffic cannot reach Amazon S3. So it fails on authentication at the first place. Thank you very much!
