### ISSUE TITLE
Unsupported cookie spec: default issue with apache http client

### ISSUE THREAD

**Issue by 24601** [aws/aws-sdk-java#281]
This error occurs when using Apache HTTP Client 4.4 with the AWS SDK, which claims compatibility with the entire 4.X series in the dep specs (can AWS predict the future or predict breaking changes in deps? this should not be that way, and seems to be the cause of the issue, and proper dep declaration methods exist to ensure precisely this does not occur). 

Seems like there's a bit of a bonehead move in packaging/specifying deps in the SDK. Reverting/including Apache HTTP Client & associated components version 4.3 avoids the issue. 

Workaround exists in the sense of going through dependency hell to accommodate this oversight. 

However, in an SDK for expensive/premium services (e.g. while this SW is free, its use is most certainly not) this seems unprofessional and quite undesirable. The fix is simple, please implement so we don't have to work around poor code quality and the AWS SDK doesn't become a thorn in dep rev management.

Java SDK on JVM 1.7.0_60 against SDK 1.9.0 using Apache HTTP Client 4.4beta1

This post elaborates on the issue/point and why this is a problem and why it's crazy and easy to fix much better than I have the time or compunction to do on an error that shouldn't even be happening.

http://tiemensfamily.com/TimOnCS/2014/09/30/amazon-sdk-broken-dependencies/

Exception in thread "main" java.lang.IllegalStateException: Unsupported cookie spec: default
	at org.apache.http.cookie.CookieSpecRegistry.getCookieSpec(CookieSpecRegistry.java:110)
	at org.apache.http.cookie.CookieSpecRegistry$1.create(CookieSpecRegistry.java:163)
	at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:157)
	at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:132)
	at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:166)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:485)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:878)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:84)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:292)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2291)
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:516)
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:1599)
	at com.voltaireapp.changeslistener.ChangesListener.runChangesListener(ChangesListener.java:47)
	at com.voltaireapp.changeslistener.ChangesListener.main(ChangesListener.java:69)

**Comment by manikandanrs** [comment]
We have fixed the range dependency on joda time in the SDK. Feel free to reopen the issue if it still exists.
