### ISSUE TITLE
DynamoDB can't handle # in the names

### ISSUE THREAD

**Issue by bgunics-talend** [aws/aws-sdk-java#2813]
### Describe the bug

One of our customers are facing the same issue that was adressed in https://github.com/aws/aws-sdk-java-v2/pull/1807/files 
They have # in the column name and our component faces an exception.

### Expected Behavior

We should be able to have # in the field names names.

### Current Behavior

tDynamoDBInput_2 ExpressionAttributeValues contains invalid key: Syntax error; key: ":filter_ServiceType#ConfigType#Drug_1" (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: JAT0F1HB8OJO7FV04OD9NKJDKNVV4....; Proxy: null)
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: ExpressionAttributeValues contains invalid key: Syntax error; key: ":filter_ServiceType#ConfigType#Drug_1" (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: JAT0F1HB8OJO7FV04OD9NKJDKNVV4.....; Proxy: null)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:5136) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:5103) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeScan(AmazonDynamoDBClient.java:3273) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.scan(AmazonDynamoDBClient.java:3239) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.services.dynamodbv2.document.internal.ScanCollection.firstPage(ScanCollection.java:53) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.services.dynamodbv2.document.internal.PageIterator.next(PageIterator.java:45) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.services.dynamodbv2.document.internal.IteratorSupport.nextResource(IteratorSupport.java:87) ~[aws-java-sdk-1.11.848.jar:?]
at com.amazonaws.services.dynamodbv2.document.internal.IteratorSupport.hasNext(IteratorSupport.java:55) ~[aws-java-sdk-1.11.848.jar:?]
at usretina.testbvconnectivity_0_1.TestBVConnectivity.tDynamoDBInput_2Process(TestBVConnectivity.java:1806) [classes/:?]

### Reproduction Steps

Try to have # in the column names, see also: https://github.com/aws/aws-sdk-java-v2/issues/1806

### AWS Java SDK version used

1.11.848

### JDK version used

Java 11

### Operating System and version

Linux / Windows

**Comment by debora-ito** [comment]
Hi @bgunics-talend the link you referenced was a report using the Java SDK v2, which it's not your case as your using 1.11.848.

Can you provide a reproducible code?

**Comment by bgunics-talend** [comment]
Hello,
I can provide you screenshots from our tool / DB setup:
![image](https://user-images.githubusercontent.com/63251373/180874947-e970b759-4620-4762-a130-efb8851e0ab8.png)
![image](https://user-images.githubusercontent.com/63251373/180875020-ed4f409c-db4c-46a5-9b4e-c2726e0dabe3.png)
Would this be sufficient?

**Comment by debora-ito** [comment]
We'd like to reproduce the error you're seeing using the Java SDK, so to be able to do this we need a sample code using the Java SDK.

Follow the instructions we put in our github issue template:

> Provide a self-contained, concise snippet of code that can be used to reproduce the issue.
> For more complex issues provide a repo with the smallest sample that reproduces the bug.
> 
> Avoid including business logic or unrelated code, it makes diagnosis more difficult.
The code sample should be an SSCCE. See http://sscce.org/ for details. In short, please provide a code sample that we can copy/paste, run and reproduce.

**Comment by wwang-talend** [comment]
Hi @debora-ito ,
this is the code we can reproduce this issue:
```
        AWSCredentials credentials = new BasicAWSCredentials(
                "xxx", "xxx");
        AWSCredentialsProvider credentialsProvider = new com.amazonaws.internal.StaticCredentialsProvider(
                credentials);

        AmazonDynamoDBClient dynamoDBClient = new AmazonDynamoDBClient(credentialsProvider);

        DynamoDB dynamoDB = new DynamoDB(
                dynamoDBClient);
        Table table = dynamoDB
                .getTable("test");

        HashMap<String, Object> valueMap = new HashMap<String, Object>();
        HashMap<String, String> nameMap = new HashMap<String, String>();

        String keyConditionExpression = null;
        String filterExpression = null;

        nameMap.put("#c", "ServiceType#ConfigType#Drug");

        valueMap.put(":keyCondition_ServiceType#ConfigType#Drug_1",
                "talend#dataextract#alldrugs");

        keyConditionExpression = "#c = :keyCondition_ServiceType#ConfigType#Drug_1 ";

        QuerySpec querySpec = new QuerySpec()
                .withKeyConditionExpression(keyConditionExpression);

        valueMap.put(":filter_ServiceType#ConfigType#Drug_1", "talend#dataextract#alldrugs");

        filterExpression = "#c = :filter_ServiceType#ConfigType#Drug_1 ";

        if (!filterExpression.isEmpty()) {
            querySpec = querySpec
                    .withFilterExpression(filterExpression);
        }

        if (valueMap.size() > 0) {
            querySpec = querySpec.withValueMap(valueMap);
        }

        if (nameMap.size() > 0) {
            querySpec = querySpec.withNameMap(nameMap);
        }

        ItemCollection<QueryOutcome> items = null;

        items = table.query(querySpec);

        Item item = null;
        Iterator<Item> iterator = null;
        iterator = items.iterator();
        while (iterator.hasNext()) {
            item = iterator.next();
        }
```

**Comment by debora-ito** [comment]
Thank you for the code snippet. With the code sample I can see now that you are using QuerySpec with keyConditionExpression and filterExpression.

I believe DynamoDB is complaining about `:filter_ServiceType#ConfigType#Drug_1` as an expression attribute value.
An expression attribute value is just a placeholder as an alternative to an actual attribute value.

According to the [DynamoDB Developer Guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ExpressionAttributeValues.html), it only accepts alphanumeric characters after the initial colon (:).

For example, if you replace ":keyCondition_ServiceType#ConfigType#Drug_1" with ":keyCondition" and replace ":filter_ServiceType#ConfigType#Drug_1" with ":filter", the code should run fine.
