### ISSUE TITLE
Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ExpiredTokenException;

### ISSUE THREAD

**Issue by shambhand** [aws/aws-sdk-java#2833]
### Describe the bug

After upgrading to `aws-java-sdk-dynamodb v1.12.267` observe following issue intermittently and cause outage to one of our most critical service

```
 com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ExpiredTokenException; Request ID: BF9K38ASVRR3PE5PMS79UQSQ9RVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
   at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:6200)
   at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:6167)
   at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeQuery(AmazonDynamoDBClient.java:3914)
   at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:3878)
   at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.query(DynamoDBMapper.java:1618)
   at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.query(AbstractDynamoDBMapper.java:285)
   at com.bcg.macoe.authorisation.clients.CacheClient.get(CacheClient.java:54)
   at com.bcg.macoe.authorisation.clients.CacheClient$$FastClassBySpringCGLIB$$428fe13b.invoke(<generated>)
   at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
   at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
   at com.bcg.macoe.authorisation.logging.TimerLoggingAspect.performMethodLogging(TimerLoggingAspect.java:25)
   at jdk.internal.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
   ```

### Expected Behavior

The AWS SDK should throw exception

### Current Behavior

```
 com.amazonaws.AmazonServiceException: Unable to unmarshall exception response with the unmarshallers provided (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ExpiredTokenException; Request ID: BF9K38ASVRR3PE5PMS79UQSQ9RVV4KQNSO5AEMVJF66Q9ASUAAJG; Proxy: null)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
   at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
   at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:6200)
   at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:6167)
   at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.executeQuery(AmazonDynamoDBClient.java:3914)
   at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:3878)
   at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.query(DynamoDBMapper.java:1618)
   at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.query(AbstractDynamoDBMapper.java:285)
   at com.bcg.macoe.authorisation.clients.CacheClient.get(CacheClient.java:54)
   at com.bcg.macoe.authorisation.clients.CacheClient$$FastClassBySpringCGLIB$$428fe13b.invoke(<generated>)
   at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
   at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
   at com.bcg.macoe.authorisation.logging.TimerLoggingAspect.performMethodLogging(TimerLoggingAspect.java:25)
   at jdk.internal.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
   ```
   

### Reproduction Steps

Observe it intermittently

### Additional Information/Context

We are running in k8s and authenticate with the kube2iam role 

### AWS Java SDK version used

1.12.267

### JDK version used

eclipse-temurin 17

### Operating System and version

Alpine

**Comment by shambhand** [comment]
I am seeing there is similar [issue](https://github.com/aws/aws-sdk-java/issues/2795) reported but in our case the error code is `ExpiredTokenException` instead of `ValidationException`

https://github.com/aws/aws-sdk-java/issues/2795

**Comment by debora-ito** [comment]
Perhaps it was working fine because you were not getting `ExpiredTokenException` before?

In any case, as we explained in https://github.com/aws/aws-sdk-java/issues/2795, Java 17 is not supported in SDK v1. We provided a workaround in the case of "Unable to unmarshall exception response":

> use JVM option --add-opens java.base/java.lang=ALL-UNNAMED at JVM startup

Please try it out and let us know if it works.
