### ISSUE TITLE
 java.lang.NoClassDefFoundError: javax/management/MalformedObjectNameException

### ISSUE THREAD

**Issue by GacaSD** [aws/aws-sdk-java#2834]
### Describe the bug

I'm working on Windows desktop application that uses AWS file service to keep files. I'm using Kotlin compose to build desktop app. Here is my dependency list: 

implementation(fileTree("lib") { include("*.jar") })
implementation(compose.desktop.currentOs)
implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.3")
val ktorVersion = "2.0.3"
implementation("io.ktor:ktor-client-core:$ktorVersion")
implementation("io.ktor:ktor-client-cio:$ktorVersion")
implementation("io.ktor:ktor-client-content-negotiation:$ktorVersion")
implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1")
implementation("org.apache.pdfbox:pdfbox:2.0.22")
implementation("com.google.zxing:javase:3.4.0")

implementation("com.amazonaws:aws-java-sdk-s3:1.12.290")
implementation("javax.xml.bind:jaxb-api:2.3.1")

Using openjdk-18.0.2 SDK to build. When I run app from project everything is working fine, no exception is shown. But when I build .exe file and install it on the same PC, exception is shown and communication with AWS server is not working.
Please help. 

### Expected Behavior

Not to show this exception

### Current Behavior

Exception in thread "DefaultDispatcher-worker-1" java.lang.NoClassDefFoundError: javax/management/MalformedObjectNameException
        at com.amazonaws.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27)
        at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:398)
        at com.amazonaws.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:359)
        at com.amazonaws.services.s3.AmazonS3Client.<clinit>(AmazonS3Client.java:440)
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
        at remote.contabo.ContaboAPIClient.<init>(ContaboAPIClient.kt:37)
        at remote.contabo.ContaboAPIClient$Companion.getInstance(ContaboAPIClient.kt:43)
        at remote.contabo.ContaboRemoteRepository.getAPIClient(ContaboRemoteRepository.kt:19)
        at remote.contabo.ContaboRemoteRepository.getFiles(ContaboRemoteRepository.kt:24)
        at Repository$1.invokeSuspend(Repository.kt:39)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@30f4129a, Dispatchers.Default]
Caused by: java.lang.ClassNotFoundException: javax.management.MalformedObjectNameException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 20 more
Exception in thread "DefaultDispatcher-worker-1" java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.services.s3.AmazonS3Client
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
        at remote.contabo.ContaboAPIClient.<init>(ContaboAPIClient.kt:37)
        at remote.contabo.ContaboAPIClient$Companion.getInstance(ContaboAPIClient.kt:43)
        at remote.contabo.ContaboRemoteRepository.getAPIClient(ContaboRemoteRepository.kt:19)
        at Repository.getAPIClient(Repository.kt:43)
        at PrinterManager$2.invokeSuspend(PrinterManager.kt:80)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@56c8be46, Dispatchers.Default]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: javax/management/MalformedObjectNameException [in thread "DefaultDispatcher-worker-1"]
        at com.amazonaws.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27)
        at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:398)
        at com.amazonaws.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:359)
        at com.amazonaws.services.s3.AmazonS3Client.<clinit>(AmazonS3Client.java:440)
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
        at remote.contabo.ContaboAPIClient.<init>(ContaboAPIClient.kt:37)
        at remote.contabo.ContaboAPIClient$Companion.getInstance(ContaboAPIClient.kt:43)
        at remote.contabo.ContaboRemoteRepository.getAPIClient(ContaboRemoteRepository.kt:19)
        at remote.contabo.ContaboRemoteRepository.getFiles(ContaboRemoteRepository.kt:24)
        at Repository$1.invokeSuspend(Repository.kt:39)
        ... 6 more

### Reproduction Steps

Not reproducible

### AWS Java SDK version used

com.amazonaws:aws-java-sdk-s3:1.12.290

### JDK version used

(build 16.0.1+9-24)

### Operating System and version

Windows 10

**Comment by GacaSD** [comment]
I have added lib javax.management.jmxri-1.2.1.jar and this is passed but now getting similar error: 

Exception in thread "DefaultDispatcher-worker-1" java.lang.NoClassDefFoundError: java/lang/management/ManagementFactory
  at com.amazonaws.jmx.MBeans.getMBeanServer(MBeans.java:114)
  at com.amazonaws.jmx.MBeans.registerMBean(MBeans.java:50)
  at com.amazonaws.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27)
  at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:398)
  at com.amazonaws.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:359)
  at com.amazonaws.services.s3.AmazonS3Client.<clinit>(AmazonS3Client.java:440)
  at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
  at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
  at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
  at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
  at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)

Not sure what I'm missing. Please help.

**Comment by debora-ito** [comment]
`ManagementFactory` is available on the JDK, so my guess is that the JDK is not configured correctly in your classpath.

This is more a "How Java works" question. If you search for "NoClassDefFoundError" in the internet you can find instructions  that are specific for the Windows environment.

**Comment by GacaSD** [comment]
I found the solution, it is not AWS problem. Here is the solution, maybe someone will need it.
Some modules should be added:
modules("java.instrument", "java.naming", "java.management",...)

**Comment by himanshumistri** [comment]
Hello @GacaSD 
Can you please share where to mention modules("java.instrument", "java.naming", "java.management",...) in Kotlin build.gradle.kts file, I am creating Compose Desktop app for the window OS.

**Comment by himanshumistri** [comment]
Thanks @GacaSD I found the configuration

nativeDistributions {
            packageName = projectName
            packageVersion = appVersion
            version = appVersion
            description = "Description"
            copyright = "The copyright"
            vendor = author
            licenseFile.set(project.file("UNLICENSE.txt"))

            windows {
                iconFile.set(project.file("icon.ico"))
                menuGroup = projectName
                upgradeUuid = "ABCDEFG-ABCD-ABCD-ABCD-ABCDABCDABCD"
                shortcut = true
            }

            targetFormats(TargetFormat.Msi)

            // run `gradle suggestRuntimeModules` to get this list
            modules("java.instrument", "java.management", "java.naming", "java.sql", "jdk.unsupported")
        }
