### ISSUE TITLE
(short issue description)Exception in thread "main" java.lang.IllegalArgumentException: Parameter 'sourceBucket' must not be null

### ISSUE THREAD

**Issue by henghengha** [aws/aws-sdk-java#2908]
### Describe the bug

Got error when running the following sample code:
https://github.com/awsdocs/aws-doc-sdk-examples/blob/c5f8486c1b569afe7828733a1afc445e44b0f0ea/javav2/example_code/s3/src/main/java/com/example/s3/CopyObject.java

But if I change copySourceIfMatch to copySource, it works well. Then it is the same with:
https://github.com/awsdocs/aws-doc-sdk-examples/blob/f0f1bacaa16350e9efeceee5ef55ee505c8bed6e/javav2/example_code/s3/src/main/java/com/example/s3/CopyObject.java

Please help check the above issue. Thanks!

### Expected Behavior

No error

### Current Behavior

Copying object kubelet.log from bucket devrepo to k8sbak
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalArgumentException: Parameter 'sourceBucket' must not be null
        at software.amazon.awssdk.utils.Validate.isTrue(Validate.java:76)
        at software.amazon.awssdk.services.s3.internal.handlers.CopySourceInterceptor.requireSet(CopySourceInterceptor.java:122)
        at software.amazon.awssdk.services.s3.internal.handlers.CopySourceInterceptor.modifyCopyObjectRequest(CopySourceInterceptor.java:66)
        at software.amazon.awssdk.services.s3.internal.handlers.CopySourceInterceptor.modifyRequest(CopySourceInterceptor.java:50)
        at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyRequest(ExecutionInterceptorChain.java:68)
        at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.runInitialInterceptors(AwsExecutionContextBuilder.java:174)
        at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:110)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsSyncClientHandler.java:69)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:78)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
        at software.amazon.awssdk.services.s3.DefaultS3Client.copyObject(DefaultS3Client.java:912)
        at com.example.s3.CopyObject.copyBucketObject(CopyObject.java:82)
        at com.example.s3.CopyObject.main(CopyObject.java:60)

### Reproduction Steps

Use the latest sample code:
https://github.com/awsdocs/aws-doc-sdk-examples/blob/c5f8486c1b569afe7828733a1afc445e44b0f0ea/javav2/example_code/s3/src/main/java/com/example/s3/CopyObject.java

        CopyObjectRequest copyReq = CopyObjectRequest.builder()
            .copySourceIfMatch(encodedUrl)
            .destinationBucket(toBucket)
            .destinationKey(objectKey)
            .build();

### AWS Java SDK version used

2.17.230

### JDK version used

18.0.1.1 2022-04-22

### Operating System and version

macOS

**Comment by debora-ito** [comment]
Hi @henghengha The latest example is incorrect, I apologize. The source bucket must always be present.

The confusion started because the `copySource` field was deprecated in favor of `sourceBucket`, `sourceKey` and `sourceVersionId`, and `copySourceIfMatch` is a completely different field - https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/CopyObjectRequest.Builder.html#copySource(java.lang.String)

Here's a working sample:
```
CopyObjectRequest request = CopyObjectRequest.builder()
                                             .sourceBucket(SOURCE_BUCKET)
                                             .sourceKey(SOURCE_KEY)
                                             .destinationBucket(DESTINATION_BUCKET)
                                             .destinationKey(DESTINATION_KEY)
                                             .build();
```

I'll work to fix the example in the awsdocs repo. Thank you for reaching out.

**Comment by henghengha** [comment]
@debora-ito Yes, it works, thanks for your help~

**Comment by debora-ito** [comment]
The example in the awsdocs repo was fixed. Closing.
