### ISSUE TITLE
Amazon Polly JDK v2 not working (software.amazon.awssdk:polly)

### ISSUE THREAD

**Issue by KostasKoyias** [aws/aws-sdk-java#2921]
### Describe the bug

Can't find any example of Amazon Polly for JDK v2 (`software.amazon.awssdk:polly`). Only examples of v1 (`com.amazonaws:aws-java-sdk-polly`) can be found in the AWS docs

I put together an example that should work given that the required fields have values set

```java
        SynthesizeSpeechRequest request = SynthesizeSpeechRequest.builder()
                .languageCode(LanguageCode.ES_US)
                .voiceId(VoiceId.JOEY)
                .outputFormat(MP3)
                .text("Hello Amazon Polly")
                .textType(TEXT)
                .build();
```

Running this leads to the following error

```
aused by: software.amazon.awssdk.thirdparty.jackson.core.JsonGenerationException: Can not write a field name, expecting a value
        at software.amazon.awssdk.thirdparty.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2657) ~[third-party-jackson-core-2.17.107.jar:?]
        at software.amazon.awssdk.thirdparty.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:220) ~[third-party-jackson-core-2.17.107.jar:?]
        at software.amazon.awssdk.protocols.json.SdkJsonGenerator.writeFieldName(SdkJsonGenerator.java:112) ~[aws-json-protocol-2.17.86.jar:?]
        at software.amazon.awssdk.protocols.json.internal.marshall.SimpleTypeJsonMarshaller$BaseJsonMarshaller.marshall(SimpleTypeJsonMarshaller.java:216) ~[aws-json-protocol-2.17.86.jar:?]
        at software.amazon.awssdk.protocols.json.internal.marshall.JsonProtocolMarshaller.marshallField(JsonProtocolMarshaller.java:267) ~[aws-json-protocol-2.17.86.jar:?]
        at software.amazon.awssdk.protocols.json.internal.marshall.JsonProtocolMarshaller.doMarshall(JsonProtocolMarshaller.java:188) ~[aws-json-protocol-2.17.86.jar:?]
        at software.amazon.awssdk.protocols.json.internal.marshall.JsonProtocolMarshaller.marshall(JsonProtocolMarshaller.java:218) ~[aws-json-protocol-2.17.86.jar:?]
        at software.amazon.awssdk.protocols.json.internal.marshall.JsonProtocolMarshaller.marshall(JsonProtocolMarshaller.java:51) ~[aws-json-protocol-2.17.86.jar:?]
        at software.amazon.awssdk.protocols.json.internal.marshall.NullAsEmptyBodyProtocolRequestMarshaller.marshall(NullAsEmptyBodyProtocolRequestMarshaller.java:37) ~[aws-json-protocol-2.17.86.jar:?]
        at software.amazon.awssdk.protocols.json.internal.marshall.NullAsEmptyBodyProtocolRequestMarshaller.marshall(NullAsEmptyBodyProtocolRequestMarshaller.java:26) ~[aws-json-protocol-2.17.86.jar:?]
        at software.amazon.awssdk.services.polly.transform.SynthesizeSpeechRequestMarshaller.marshall(SynthesizeSpeechRequestMarshaller.java:49) ~[polly-2.15.47.jar:?]
        at software.amazon.awssdk.services.polly.transform.SynthesizeSpeechRequestMarshaller.marshall(SynthesizeSpeechRequestMarshaller.java:31) ~[polly-2.15.47.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$finalizeSdkHttpFullRequest$0(BaseClientHandler.java:67) ~[sdk-core-2.17.107.jar:?]
        at software.amazon.awssdk.core.internal.util.MetricUtils.measureDuration(MetricUtils.java:51) ~[sdk-core-2.17.107.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:66) ~[sdk-core-2.17.107.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.doExecute(BaseAsyncClientHandler.java:201) ~[sdk-core-2.17.107.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.lambda$execute$3(BaseAsyncClientHandler.java:131) ~[sdk-core-2.17.107.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.measureApiCallSuccess(BaseAsyncClientHandler.java:282) ~[sdk-core-2.17.107.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.execute(BaseAsyncClientHandler.java:91) ~[sdk-core-2.17.107.jar:?]
        at software.amazon.awssdk.awscore.client.handler.AwsAsyncClientHandler.execute(AwsAsyncClientHandler.java:59) ~[aws-core-2.17.107.jar:?]
        at software.amazon.awssdk.services.polly.DefaultPollyAsyncClient.synthesizeSpeech(DefaultPollyAsyncClient.java:853) ~[polly-2.15.47.jar:?]
        at software.amazon.awssdk.services.polly.PollyAsyncClient.synthesizeSpeech(PollyAsyncClient.java:1296) ~[polly-2.15.47.jar:?]
```

### Expected Behavior

Expected a task to start, but received the error shown above

### Current Behavior

An exception was thrown

### Reproduction Steps

```java
import software.amazon.awssdk.services.polly.PollyClient;
import software.amazon.awssdk.services.polly.model.LanguageCode;
import software.amazon.awssdk.services.polly.model.SynthesizeSpeechRequest;
import software.amazon.awssdk.services.polly.model.VoiceId;

import java.nio.file.Path;

import static software.amazon.awssdk.services.polly.model.OutputFormat.MP3;
import static software.amazon.awssdk.services.polly.model.TextType.TEXT;

public class PollyService {
    public static void main(String[] args) {
        SynthesizeSpeechRequest request = SynthesizeSpeechRequest.builder()
                .languageCode(LanguageCode.ES_US)
                .voiceId(VoiceId.JOEY)
                .outputFormat(MP3)
                .text("Hello Amazon Polly")
                .textType(SSML)
                .build();

        PollyClient.create().synthesizeSpeech(request, Path.of("/tmp/audio.mp3"));
    }
}

```

### Additional Information/Context

Ran it on debug and in `software.amazon.awssdk.thirdparty.jackson.core.json.UTF8JsonGenerator#writeFieldName`
the `name` parameter has value "Engine" and in the following snippet `this._writeContext.writeFieldName(name)` at line 112 returns status 4 which causes the error

```java
    public void writeFieldName(String name) throws IOException {
        if (this._cfgPrettyPrinter != null) {
            this._writePPFieldName(name);
        } else {
            int status = this._writeContext.writeFieldName(name); // name="Engine" here if that helps
            if (status == 4) {
                this._reportError("Can not write a field name, expecting a value");
            }
....
....
```

Also the equivalent of AWS jdk v1 shown below works fine

```java
import com.amazonaws.services.polly.AmazonPollyClient;
import com.amazonaws.services.polly.model.SynthesizeSpeechRequest;
import com.amazonaws.services.polly.model.SynthesizeSpeechResult;
import com.amazonaws.services.polly.model.TextType;

import static com.amazonaws.services.polly.model.Engine.Standard;
import static com.amazonaws.services.polly.model.LanguageCode.ArAE;
import static com.amazonaws.services.polly.model.OutputFormat.Mp3;
import static com.amazonaws.services.polly.model.VoiceId.Aditi;


public class Application {
    
    public static void main(String[] args) {
        SynthesizeSpeechRequest synthesizeSpeechRequest = new SynthesizeSpeechRequest()
                .withEngine(Standard)
                .withLanguageCode(ArAE)
                .withVoiceId(Aditi)
                .withOutputFormat(Mp3)
                .withText("Hello Amazon Polly")
                .withTextType(TextType.Text);

        SynthesizeSpeechResult synthesizeSpeechResult = AmazonPollyClient.builder().build().synthesizeSpeech(synthesizeSpeechRequest);
    }
}
```

### AWS Java SDK version used

2.15.47

### JDK version used

openjdk version "11.0.17" 2022-10-18 LTS OpenJDK Runtime Environment Corretto-11.0.17.8.1 (build 11.0.17+8-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.17.8.1 (build 11.0.17+8-LTS, mixed mode)

### Operating System and version

MacOS 13.1

**Comment by KostasKoyias** [comment]
Seems like other dependencies caused this error.
If I ran this with minimal dependencies it works fine.
Sorry.
