### ISSUE TITLE
AmazonS3#getObject(String, String)#getObjectContent() sometimes returns the wrong InputStream

### ISSUE THREAD

**Issue by caarlos0** [aws/aws-sdk-java#294]
I have an A1 Certificate stored in S3 and a Java API that uses that certificate to sign things.

If I download the certificate using `s3cmd` or the S3 web interface and uses it to sign, it works gracefully.

If I get the stream using `AmazonS3#getObject(String, String)#getObjectContent()` and use this stream to sign, it breaks (the error depends on SDK version).

If I convert that stream to a `byte[]` and then to `ByteArrayInputStream` using Guava and then pass to my sign routine, it works.

I believe that there is something wrong with `S3ObjectInputStream`, but can't figure out what it is.

This code won't work:

```java
InputStream stream = getFromS3("a1.pfx");
KeyStore loadedKeyStore = KeyStore.getInstance("pkcs12");
loadedKeyStore.load( stream, "pwd".toCharArray() );
```

With SDK 1.9.3, I got the following error:

```
java.io.IOException: DerInputStream.getLength(): lengthTag=127, too big.
	at sun.security.util.DerInputStream.getLength(DerInputStream.java:561)
	at sun.security.util.DerValue.init(DerValue.java:365)
	at sun.security.util.DerValue.<init>(DerValue.java:320)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1872)
	at java.security.KeyStore.load(KeyStore.java:1433)
```

With SDK 1.8.10.2, I got this one:

```
java.io.IOException: not all indef len BER resolved
	at sun.security.util.DerIndefLenConverter.convert(DerIndefLenConverter.java:329) 
	at sun.security.util.DerValue.init(DerValue.java:376)
	at sun.security.util.DerValue.<init>(DerValue.java:320)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1872) 
	at java.security.KeyStore.load(KeyStore.java:1433)
```

If I convert the stream to `byte[]` and then to `ByteArrayInputStream`, in both versions, it works:

```java
InputStream stream = getFromS3("a1.pfx");
byte[] byteArray = ByteStreams.toByteArray( stream );
ByteArrayInputStream stream2 = new ByteArrayInputStream( byteArray );
KeyStore loadedKeyStore = KeyStore.getInstance("pkcs12");
loadedKeyStore.load( stream2, "pwd".toCharArray() );
```

I believe it might be caused by this https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/S3ObjectInputStream.java#L120 

Cheers

**Comment by caarlos0** [comment]
Any updates on this?

**Comment by caarlos0** [comment]
@hansonchar ping

**Comment by diogogallo** [comment]
I'm having the same problem, but in my case is worst, because even the workaround using ByteArrayInputStream doesn't work.

I got this error:

```
java.io.IOException: toDerInputStream rejects tag type -128
	at sun.security.util.DerValue.toDerInputStream(DerValue.java:847)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1221)
	at java.security.KeyStore.load(KeyStore.java:1214)
	at java_security_KeyStore$load$0.call(Unknown Source)
```

@hansonchar

**Comment by varunnvs92** [comment]
I noticed that this issue has been open from some time and I apologize for the lack of response. Is this still an issue for you?

**Comment by caarlos0** [comment]
@varunnvs92 yes, the workaround still in production..

**Comment by spfink** [comment]
@caarlos0, do you have an expired or example certificate that you can provide where you encounter this issue? We are unable to reproduce using pkcs12 files that we have been able to generate. 

Which version of the SDK are you now using?

**Comment by spfink** [comment]
Closing due to inactivity. Please try upgrading to the latest version of the SDK and see if this is still an issue. We are unable to reproduce using 1.11.x

**Comment by jeansossmeier** [comment]
This is related to a OpenJDK bug described here:
https://bugs.openjdk.java.net/browse/JDK-8157404

Basically, a `KeyStore` cannot load an `InputStream` which does not have all bytes available yet, like an remote input stream.
 
```This is a limitation of BER reader that it cannot resolve all indef len BER if not all bytes are available at once.```

In order to fix this you have to read the InputStream fully and then make it available again.
This is bad performance-wise because the content will be read twice, but at least you won't get stuck. 

Tomcat developers also had issues with this and dealt with it by doing exactly as described above.
https://github.com/apache/tomcat/commit/1827fcc475edca20646874636b7900d9f9ed2a15

You may end up with something like this:
```
public InputStream downloadEagerly(String file) throws IOException {
    InputStream inputStream = getFromS3(file);
    return new ByteArrayInputStream(ByteStreams.toByteArray(inputStream));
}
```
