### ISSUE TITLE
aws-java-sdk-s3 artifact in com.amazonaws group causing NoSuchFIeldError after upgrading Spring Boot to 2.6.9 from 2.3.9

### ISSUE THREAD

**Issue by amlan-rath** [aws/aws-sdk-java#2968]
### Describe the bug

Before today I was using spring boot 2.3.9, but a new task had me upgrade it to 2.6.9, but after the same was done I started to get the following error when I try to establish a S3 connection
`Caused by: java.lang.NoSuchFieldError: HAS_STREAMING_OUTPUT
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1491)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1378)
	at com.embibe.achieve.services.DataService.placeDataFromS3(DataService.java:42)
	at com.embibe.achieve.helpers.DataHelper.loadDataFromS3(DataHelper.java:162)
	at com.embibe.achieve.helpers.DataHelper.loadData(DataHelper.java:114)
	at com.embibe.achieve.helpers.DataHelper.doOnStartUp(DataHelper.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 60 common frames omitted`

My current aws-java-sdk-s3 artifact version is 1.12.429 and I also tried to add the aws-java-sdk-bom to make sure the correct aws-sdk-core version was used as below - 
`<dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <version>1.12.429</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>`

But still repeatedly getting the above error

### Expected Behavior

The S3 connection should establish normally

### Current Behavior

Currenly getting error - 
`Caused by: java.lang.NoSuchFieldError: HAS_STREAMING_OUTPUT
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1491)`

### Reproduction Steps

Using Springboot 2.6.9 and aws-java-sdk-s3 version 1.12.429 and try to establish connection to S3

### AWS Java SDK version used

1.12.429

### JDK version used

8

### Operating System and version

MacOS Monterey, version - 12.3.1

**Comment by debora-ito** [comment]
Can you share you dependency tree? You can execute the command `mvn dependency:tree`.

NoSuchFieldError indicates you have a version mismatch of SDK modules in your classpath. Ideally all versions should be the same.
