### ISSUE TITLE
java.lang.ClassNotFoundException for Custom AWSCredentialsProvider class

### ISSUE THREAD

**Issue by saravanansbv** [aws/aws-sdk-java#3005]
### Describe the bug

The MR job fails while loading the Custom AWSCredentialsProvider class with ClassNotFoundException. The job is run using hadoop jar CLI command.

Custom AWSCredentialsProvider is implemented and trying to use it using the following configuration:
job.getConfiguration().set(AWS_CREDENTIALS_PROVIDER, "com.xyz.XXXProvider");

We are using Hadoop MapReduce. The same code used to work with hadoop 3.2.1.

The ClassNotFoundException error is coming when tried to upgrade to hadoop 3.3.3

### Expected Behavior

hadoop aws libraries supposed to load the class without any issues

### Current Behavior

Following are the set of libraries used:
<hadoop.version>3.3.3</hadoop.version>
<amazon.sdk.version>1.11.1026</amazon.sdk.version>
<amazon.sdk.v2.version>2.19.33</amazon.sdk.v2.version>
<httpclient.version>4.5.13</httpclient.version>

<groupId>com.amazonaws</groupId>
<artifactId>aws-java-sdk-bundle</artifactId>
<artifactId>http</artifactId>
<version>${amazon.sdk.version}</version>

<groupId>software.amazon.awssdk</groupId>
<artifactId>sso</artifactId>
<artifactId>sts</artifactId>				
<artifactId>http-client-spi</artifactId>
<version>${amazon.sdk.v2.version}</version>

Following the exception:
java.lang.RuntimeException: java.io.IOException: From option fs.s3a.aws.credentials.provider java.lang.ClassNotFoundException: Class com.xyz.XXXProvider not found
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.setOutputPath(FileOutputFormat.java:182)
        ...
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
Caused by: java.io.IOException: From option fs.s3a.aws.credentials.provider java.lang.ClassNotFoundException: Class com.xyz.XXXProvider not found
	at org.apache.hadoop.fs.s3a.S3AUtils.loadAWSProviderClasses(S3AUtils.java:657)
	at org.apache.hadoop.fs.s3a.S3AUtils.buildAWSProviderList(S3AUtils.java:680)
	at org.apache.hadoop.fs.s3a.S3AUtils.createAWSCredentialProviderSet(S3AUtils.java:631)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.bindAWSClient(S3AFileSystem.java:877)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.initialize(S3AFileSystem.java:534)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputFormat.setOutputPath(FileOutputFormat.java:178)
	... 12 more
Caused by: java.lang.ClassNotFoundException: Class com.xyz.XXXProvider not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
	at org.apache.hadoop.conf.Configuration.getClasses(Configuration.java:2663)
	at org.apache.hadoop.fs.s3a.S3AUtils.loadAWSProviderClasses(S3AUtils.java:654)
	... 23 more 

### Reproduction Steps

hadoop jar <job-shaded.jar> <params>

### AWS Java SDK version used

1.11.1026

### JDK version used

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Operating System and version

Mac

**Comment by debora-ito** [comment]
@saravanansbv `ClassNotFoundException` indicates the class was not found in your classpath.
The class in question is not a Java SDK class, since there's no SDK class in the stacktrace. Because of this I'll go ahead and close this. You should reach out to the support channels of the library you are using.
