### ISSUE TITLE
Unable to parse clock skew offset from response: null

### ISSUE THREAD

**Issue by sdaus** [aws/aws-sdk-java#3073]
### Describe the bug

An exception is thrown when trying to parse the clock skew offset from the response of an HTTP request if it returns null. The error message is "Unable to parse clock skew offset from response: null".

Stack trace:
```java
java.lang.StringIndexOutOfBoundsException: begin 125, end 26, length 333
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at com.amazonaws.retry.ClockSkewAdjuster.getServerDateFromException(ClockSkewAdjuster.java:223)
	at com.amazonaws.retry.ClockSkewAdjuster.getServerDate(ClockSkewAdjuster.java:189)
	at com.amazonaws.retry.ClockSkewAdjuster.clientRequestWasSkewed(ClockSkewAdjuster.java:137)
	at com.amazonaws.retry.ClockSkewAdjuster.isAdjustmentRecommended(ClockSkewAdjuster.java:125)
	at com.amazonaws.retry.ClockSkewAdjuster.getAdjustment(ClockSkewAdjuster.java:102)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1423)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5456)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5403)
	at com.amazonaws.services.s3.AmazonS3Client.access$300(AmazonS3Client.java:421)
	at com.amazonaws.services.s3.AmazonS3Client$PutObjectStrategy.invokeServiceCall(AmazonS3Client.java:6531)
	at com.amazonaws.services.s3.AmazonS3Client.uploadObject(AmazonS3Client.java:1861)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1821)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:169)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:149)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:115)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:45)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Expected Behavior

I did not expect an exception to be thrown.

### Current Behavior

An exception is thrown.

### Reproduction Steps

Due to the unknown nature of the trigger, it is difficult to provide exact reproduction steps. The problem occurs randomly, seemingly for no reason.

### Possible Solution

One possible solution could be to add a fallback [here](https://github.com/aws/aws-sdk-java/blob/21d2fa1231bb6519a8cc990b2d5c8569c43d3890/aws-java-sdk-core/src/main/java/com/amazonaws/retry/ClockSkewAdjuster.java#L223) to check if `body == null`.

### Additional Information/Context

None.

### AWS Java SDK version used

1.12.261

### JDK version used

openjdk 11.0.21 2023-10-17

### Operating System and version

Ubuntu 22.04.3 LTS

**Comment by debora-ito** [comment]
> Due to the unknown nature of the trigger, it is difficult to provide exact reproduction steps. The problem occurs randomly, seemingly for no reason.

Unfortunately, without a repro code is very hard for us to root cause it.

Are you connecting to S3 directly or using a third party solution like Localstack?
