### ISSUE TITLE
ClusterNotFoundException is thrown when cluster exists in the account/region

### ISSUE THREAD

**Issue by drullar** [aws/aws-sdk-java#3093]
### Describe the bug

When executing `ECSClient.descriveServices(DescribeServicesRequest().withCluster(clusterArn).withServices(serviceArn))` 
a `ClusterNotFoundException` exception is thrown, even though the cluster is present and is visible after executing `ECSClient.listClusters()`

Note: The IAM user with which this method is executed has Full admin permissions.

### Expected Behavior

Expected behavior would be to not get the exception when the cluster exists. 

### Current Behavior

Stack Trace:
```
Exception in thread "main" com.amazonaws.services.ecs.model.ClusterNotFoundException: Cluster not found. (Service: AmazonECS; Status Code: 400; Error Code: ClusterNotFoundException; Request ID: 1edf19d4-08f0-4b24-a042-1885798c0765; Proxy: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1157)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:814)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:781)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:755)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:561)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:541)
	at com.amazonaws.services.ecs.AmazonECSClient.doInvoke(AmazonECSClient.java:4664)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:4631)
	at com.amazonaws.services.ecs.AmazonECSClient.invoke(AmazonECSClient.java:4620)
	at com.amazonaws.services.ecs.AmazonECSClient.executeListTasks(AmazonECSClient.java:2676)
	at com.amazonaws.services.ecs.AmazonECSClient.listTasks(AmazonECSClient.java:2645)```

### Reproduction Steps

Prerequisites: Have an ecs cluster and ecs service created.

Replace the clusterArn and serviceArn in the below code snippet with the actual arns of your resources.

`ECSClient.descriveServices(DescribeServicesRequest().withCluster(clusterArn).withServices(serviceArn))`

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### AWS Java SDK version used

Any 1.12.X version, including latest

### JDK version used

openjdk 17.0.9 2023-10-17 LTS

### Operating System and version

macOS 13.4

**Comment by drullar** [comment]
Hi,

I had the correct region. I suppose that there was some temporary issue with my authentication tot he account and that was causing the weird behavior. Closing my issue.
