### ISSUE TITLE
Randomly getting javax.net.ssl.SSLPeerUnverifiedException on JRE8 

### ISSUE THREAD

**Issue by caarlos0** [aws/aws-sdk-java#310]
Hi, sometimes, that look pretty much random to me, I got the following exception with JDK8:

```
2014-11-19 10:29:50,076 INFO  [com.amazonaws.http.AmazonHttpClient] (EJB default - 4) Unable to execute HTTP request: peer not authenticated: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431) [jsse.jar:1.8.0_25]
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:126) [httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572) [httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) [httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294) [httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:645) [httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:480) [httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906) [httpclient-4.2.3.jar:4.2.3]
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805) [httpclient-4.2.3.jar:4.2.3]
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:377) [aws-java-sdk-1.6.12.jar:]
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:228) [aws-java-sdk-1.6.12.jar:]
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1001) [aws-java-sdk-1.6.12.jar:]
	at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:706) [aws-java-sdk-1.6.12.jar:]
```

Java version is:

```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
``` 

BTW, I got this error both running in my local machine and in 2 EC2 instances.

I also found some further info, but I'm not sure if this makes sense to me: http://stackoverflow.com/questions/12095758/apache-httpclient-sslpeerunverifiedexception

Any thoughts?

**Comment by behrooziAWS** [comment]
Could it be related to this bug in http client?
https://issues.apache.org/jira/browse/HTTPCLIENT-1346
AWS Java SDK 1.9.1 and up upgrade to a version of http client without this issue.

**Comment by manikandanrs** [comment]
Are you seeing the issue with a latest version of the sdk ?

**Comment by manikandanrs** [comment]
Closing this as there is no reply. Feel free to reopen.
