### ISSUE TITLE
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Read timed out

### ISSUE THREAD

**Issue by houdejun214** [aws/aws-sdk-java#321]
Sometime this exception raised when call SQS client to send message:
```java
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Read timed out
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:471) ~[aws-java-sdk-core-1.9.6.jar:na]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295) ~[aws-java-sdk-core-1.9.6.jar:na]
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2291) ~[aws-java-sdk-sqs-1.9.6.jar:na]
        at com.amazonaws.services.sqs.AmazonSQSClient.sendMessageBatch(AmazonSQSClient.java:745) ~[aws-java-sdk-sqs-1.9.6.jar:na]
        at com.weardex.aws.SqsClient$1.call(SqsClient.java:106) [weardex-aws-1.0.2-SNAPSHOT.jar:na]
        at com.weardex.aws.SqsClient$1.call(SqsClient.java:101) [weardex-aws-1.0.2-SNAPSHOT.jar:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_72]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_72]
```

Our application run in ec2 instance, the exception exists in part of my instances.It will not re-produce when I relaunch a new instance with same security group setting same AMI.

I have change the networkaddress.cache.ttl=60 and the prototype is HTTP.

And the ping to endpoint is ok:
```shell
curl -i sqs.ap-southeast-1.amazonaws.com
```

**Comment by odain2** [comment]
We're seeing this as well. We have 5 hosts running. All are fine for days. Then one will start having SQS errors and it keeps having them until we restart it. Once restarted, it's fine. All good for a few days, then another host starts having the same issue.

**Comment by hanshuo-aws** [comment]
@odain2 On which SQS API did you see the timeout error? What is your current client socket timeout configuration? Can you provide us some sample code to illustrate your use case?

**Comment by odain2** [comment]
Ours always appear to be "unknown host exception" so I don't think it's a socket timeout. I just searched our logs for the last 7 days and it appears that the pattern is:

1. One host out of our 5 will start having the issue randomly. That host was initially fine.
2. Once the host has the issue it continues to have it intermittently forever, until we stop it and start a new one.
3. Pretty much all the exceptions include an UnknownHostException

It may be an issue with AWS DNS and may not have anything to do with the library.

It occurs to me that this may not be the same issue reported above. If so, I can open a separate bug for it.

Here's a stack trace:

```
Error saving in Dynamo or SQS:
jsr166e.CompletionException: com.amazonaws.AmazonClientException: Unable to execute HTTP request: sqs.us-east-1.amazonaws.com
 at jsr166e.CompletableFuture.internalComplete(CompletableFuture.java:192) [com.signifyd.jsr166e-1.0.0.jar:na]
 at jsr166e.CompletableFuture$ThenApply.run(CompletableFuture.java:665) [com.signifyd.jsr166e-1.0.0.jar:na]
 at jsr166e.CompletableFuture.postComplete(CompletableFuture.java:180) [com.signifyd.jsr166e-1.0.0.jar:na]
 at jsr166e.CompletableFuture.completeExceptionally(CompletableFuture.java:1633) [com.signifyd.jsr166e-1.0.0.jar:na]
 at com.signifyd.monads.EagerPromise.failure(EagerPromise.java:327) [com.signifyd.java-utils-4.4.0.jar:4.4.0]
 at com.signifyd.queueing.SqsDynamoKeyEnqueuer$OnMessageSent.onError(SqsDynamoKeyEnqueuer.java:66) [com.signifyd.queueing-3.0.0.jar:3.0.0]
 at com.amazonaws.services.sqs.AmazonSQSAsyncClient$20.call(AmazonSQSAsyncClient.java:1478) [com.amazonaws.aws-java-sdk-sqs-1.9.4.jar:na]
 at com.amazonaws.services.sqs.AmazonSQSAsyncClient$20.call(AmazonSQSAsyncClient.java:1472) [com.amazonaws.aws-java-sdk-sqs-1.9.4.jar:na]
 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
 at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: sqs.us-east-1.amazonaws.com
 at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467) ~[com.amazonaws.aws-java-sdk-core-1.9.4.jar:na]
 at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295) ~[com.amazonaws.aws-java-sdk-core-1.9.4.jar:na]
 at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2291) ~[com.amazonaws.aws-java-sdk-sqs-1.9.4.jar:na]
 at com.amazonaws.services.sqs.AmazonSQSClient.sendMessage(AmazonSQSClient.java:908) ~[com.amazonaws.aws-java-sdk-sqs-1.9.4.jar:na]
 at com.amazonaws.services.sqs.AmazonSQSAsyncClient$20.call(AmazonSQSAsyncClient.java:1476) [com.amazonaws.aws-java-sdk-sqs-1.9.4.jar:na]
 ... 5 common frames omitted
Caused by: java.net.UnknownHostException: sqs.us-east-1.amazonaws.com
 at java.net.InetAddress.getAllByName0(InetAddress.java:1259) ~[na:1.8.0_31]
 at java.net.InetAddress.getAllByName(InetAddress.java:1171) ~[na:1.8.0_31]
 at java.net.InetAddress.getAllByName(InetAddress.java:1105) ~[na:1.8.0_31]
 at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44) ~[org.apache.httpcomponents.httpclient-4.3.1.jar:4.3.1]
 at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:260) ~[org.apache.httpcomponents.httpclient-4.3.1.jar:4.3.1]
 at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:160) ~[org.apache.httpcomponents.httpclient-4.3.1.jar:4.3.1]
 at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304) ~[org.apache.httpcomponents.httpclient-4.3.1.jar:4.3.1]
 at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610) ~[org.apache.httpcomponents.httpclient-4.3.1.jar:4.3.1]
 at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445) ~[org.apache.httpcomponents.httpclient-4.3.1.jar:4.3.1]
 at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863) ~[org.apache.httpcomponents.httpclient-4.3.1.jar:4.3.1]
 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[org.apache.httpcomponents.httpclient-4.3.1.jar:4.3.1]
 at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57) ~[org.apache.httpcomponents.httpclient-4.3.1.jar:4.3.1]
 at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:681) ~[com.amazonaws.aws-java-sdk-core-1.9.4.jar:na]
 at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:456) ~[com.amazonaws.aws-java-sdk-core-1.9.4.jar:na]
 ... 9 common frames omitted
```

**Comment by hanshuo-aws** [comment]
@odain2 
It's possible that the IP address for the SQS service endpoint CNAME was updated, but your JVM by default still kept the cached DNS lookup with an infinite ttl.
I'd suggest you try to use the JVM's DNS ttl setting to force refreshing the DNS lookup once a while, and that will probably solve your problem.
You can find more information on this topic in this page:
http://docs.aws.amazon.com/AWSSdkDocsJava/latest//DeveloperGuide/java-dg-jvm-ttl.html

**Comment by odain2** [comment]
Thanks @hanshuo-aws. In this particular case it now appears that we actually had general network issues and weren't able to resolve **anything** via DNS. However, your correct that we should probably make the DNS fix. In any event, it appears that our issue wasn't related to the original bug here. Sorry for the false alarm.

**Comment by hanshuo-aws** [comment]
@odain2 No worry. Glad to hear you figured it out.

**Comment by dgaurav** [comment]
it will work 

ClientConfiguration configuration = new ClientConfiguration();
                configuration.setMaxErrorRetry(3);
                configuration.setConnectionTimeout(50*1000);
                configuration.setSocketTimeout(50*1000);
                configuration.setProtocol(Protocol.HTTP);

                AmazonS3 s3Client = new AmazonS3Client(new BasicAWSCredentials(AppConstant.MY_ACCESS_KEY_ID, AppConstant.MY_SECRET_KEY), configuration);

**Comment by krisnik** [comment]
@hanshuo-aws The link which you have specified doesn't work. Here is the link for Setting the JVM TTL.  http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-jvm-ttl.html

**Comment by prabha303** [comment]
This is working fine thanks.

                   int timeoutConnection = 30000;
                    ClientConfiguration clientConfiguration = new ClientConfiguration();
                    clientConfiguration.setMaxErrorRetry(2);
                    clientConfiguration.setConnectionTimeout(timeoutConnection);
                    clientConfiguration.setSocketTimeout(timeoutConnection);
                    clientConfiguration.setProtocol(Protocol.HTTP);

                    BasicAWSCredentials credentials = new BasicAWSCredentials(accessKey,secretKey);
                    AmazonS3Client s3 = new AmazonS3Client(credentials,clientConfiguration);
                    s3.setRegion(Region.getRegion(Regions.AP_SOUTH_1));

**Comment by alokipandey** [comment]
I also had this issue and I resolved it while going through multiple stackoverflow /github /aws doc pages. leaving a link to my documentation below for whomsoever may need it.
https://alokipandey.medium.com/upload-to-aws-s3-from-android-s3-in
