### ISSUE TITLE
NoClassDefFoundError when initializing AmazonS3Client

### ISSUE THREAD

**Issue by laurilehmijoki** [aws/aws-sdk-java#358]
Pushing with JDK 7 or 8 fails:

```
Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: sun/management/ExtendedPlatformComponent
    at java.lang.management.ManagementFactory.getPlatformMBeanServer(ManagementFactory.java:494)
    at com.amazonaws.jmx.MBeans.getMBeanServer(MBeans.java:112)
    at com.amazonaws.jmx.MBeans.registerMBean(MBeans.java:50)
    at com.amazonaws.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27)
    at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:330)
    at com.amazonaws.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:308)
    at com.amazonaws.services.s3.AmazonS3Client.<clinit>(AmazonS3Client.java:239)
    at s3.website.S3$.awsS3Client(S3.scala:110)
    at s3.website.S3$S3Setting$$anonfun$apply$default$1$1.apply(S3.scala:223)
    at s3.website.S3$S3Setting$$anonfun$apply$default$1$1.apply(S3.scala:223)
    at s3.website.S3$$anonfun$resolveS3Files$1.apply(S3.scala:119)
    at s3.website.S3$$anonfun$resolveS3Files$1.apply(S3.scala:114)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Tested on Mac OS X Mavericks with Oracle JDKs. There is no issue with the old Apple JDK 6.

AWS Java SDK version is 1.7.7.

Any tips on working around this problem?

**Comment by david-at-aws** [comment]
Everything I can [find](http://mail.openjdk.java.net/pipermail/core-libs-dev/2014-November/029816.html) indicates that this was [a bug](https://bugs.openjdk.java.net/browse/JDK-8065397) in some early-access builds of Java 8 update 40. I'm not able to reproduce on OS X Mavericks/Oracle JDKs 1.7.0_75 or 1.8.0_31 (latest stable releases). Which version(s) are you seeing this on?

**Comment by jponge** [comment]
I can confirm that a recent 8u40-ea build does not have the issue anymore. Thanks!

**Comment by laurilehmijoki** [comment]
This issue can be solved by upgrading to the latest JDK/JRE.

**Comment by neomatrix369** [comment]
I'm on the latest JDK i.e. 1.8.0 update 172 and still get this issue, anyone else has got this? Or know what it could be related to?

**Comment by neomatrix369** [comment]
I have fixed this issue for myself, see https://github.com/libgdx/packr/issues/94#issuecomment-444536554
