### ISSUE TITLE
Unable to execute HTTP request: Stream Closed

### ISSUE THREAD

**Issue by efic1** [aws/aws-sdk-java#361]
Hi
I'm using sdk version 1.9.13 and getting the following error from time to time, note that I've seen this error on older sdk versions too.

Unable to execute HTTP request: Stream Closed 

```
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Stream Closed
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:471)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3710)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1445)
	at com.myservice.core.service.file.S3FileSystemService.save(S3FileSystemService.java:252)
	
Caused by: java.io.IOException: Stream Closed
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:272)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
	at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:108)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
	at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.read(MD5DigestCalculatingInputStream.java:98)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at com.amazonaws.internal.SdkBufferedInputStream.read(SdkBufferedInputStream.java:76)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:151)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:138)
	at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:153)
	at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:89)
	at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
	at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:117)
	at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:265)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:203)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:236)
	at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:47)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:685)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
	... 34 more
```

**Comment by hansonchar** [comment]
Hi @efic1,

If I understand this correctly, you are trying to upload a file to S3 via a PUT object operation.  What kind of file system are you using underneath?  Seems unusual that the stream to the input file get closed in the middle of a read operation.

**Comment by efic1** [comment]
the local file system is ext3 on ec2 ephemeral ssd drive

**Comment by hansonchar** [comment]
I wonder what happened to the EC2 instance as at the time the exception was thrown.  The use of an ephemeral SSD drive suggests the file was available only during the lifetime of its associated instance, and therefore could be sensitive to the condition of the associated instance.

How often did you experience the "Stream Closed" error?  What was the state of the EC2 instance when you saw such error?
