### ISSUE TITLE
JsonMappingException on EC2MetadataUtils getInstanceInfo

### ISSUE THREAD

**Issue by cliffano** [aws/aws-sdk-java#402]
Using EC2MetadataUtils getInstanceInfo with 1.9.28.1 (and master) resulted in JsonMappingException due to incorrect billingProducts data type.

Stack trace below, and I already submitted pull request for a fix https://github.com/aws/aws-sdk-java/pull/398

```
Apr 07, 2015 12:49:04 AM com.amazonaws.util.EC2MetadataUtils getInstanceInfo
WARNING: Unable to parse dynamic EC2 instance info ({
  ...
  "billingProducts" : [ "bp-12345678" ],
  ...
}) : Unable to parse Json String.
com.amazonaws.AmazonClientException: Unable to parse Json String.
        at com.amazonaws.util.json.Jackson.fromJsonString(Jackson.java:66)
        at com.amazonaws.util.EC2MetadataUtils.getInstanceInfo(EC2MetadataUtils.java:229)
        at com.amazonaws.regions.Regions.getCurrentRegion(Regions.java:79)
        ...
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.StringReader@58651fd0; line: 2, column: 30]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
        at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:691)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:46)
        at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:331)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1071)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:268)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2993)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2098)
        at com.amazonaws.util.json.Jackson.fromJsonString(Jackson.java:64)
        ... 7 more
```

**Comment by manikandanrs** [comment]
We have fixed this in the latest SDK 1.9.32

**Comment by cliffano** [comment]
@manikandanrs I see that the fix is part of this gigantic commit affecting 460 files https://github.com/aws/aws-sdk-java/commit/67c41ad054e1ab635316adab86ebd6a380360e00 
Is that coming from an internal upstream repo at Amazon?

Is there any particular reason why the fix to this issue was not initially made publicly on GitHub? (instead of piling everything in one large commit)

**Comment by manikandanrs** [comment]
@cliffano 
 > Is that coming from an internal upstream repo at Amazon?

Yes. Our releases include feature updates to existing service clients, doc updates, bug fixes and enhancements. We would want to make Github as our master repo instead of Amazon repo and we are  working towards it. You should expect big commits like this till then. 

> Is there any particular reason why the fix to this issue was not initially made publicly on GitHub?

We encourage pull requests from customers to improve the SDK. However this issue needed some internal investigation to make sure all the fields in InstanceInfo class are mapped correctly to their data types. As you can see, not just billingProducts but devpayProductCodes had a wrong type. Hence the reason for not accepting the pull request initially.

**Comment by cliffano** [comment]
I would've been happy to help as well by improving the PR if you told me that N other fields also need to be fixed :). It's a bit discouraging to get a feedback 2 weeks after the PR, because the next time I encounter any bug, my first thinking is that it's being worked on anyway, so any time I spend on creating and testing a PR would've been a waste.

However, I understand that you're working hard on making Github as a master repo. +1 on that.
And great job with the frequent releases, kudos to Amazon.
