### ISSUE TITLE
Unable to include AWS SDK with play 2.3.8

### ISSUE THREAD

**Issue by puneetar** [aws/aws-sdk-java#422]
Hey Guys,

I tried to use the aws java sdk with play 2.3.8, but was getting the following exception on S3 BucketExists

`S3Impl.s3Client = new AmazonS3Client(AWSConfig.getAwsCredentials());
S3Impl.s3Client.doesBucketExist(S3Impl.s3Bucket)`

Dependency :
`libraryDependencies += "com.amazonaws" % "aws-java-sdk-s3" % "1.9.33"`

Exception : 
`play.api.UnexpectedException: Unexpected exception[NoSuchMethodError: org.apache.http.params.HttpConnectionParams.setSoKeepalive(Lorg/apache/http/params/HttpParams;Z)V]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:170) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:130) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.util.Success.flatMap(Try.scala:230) ~[scala-library-2.11.1.jar:na]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:128) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1.apply(ApplicationProvider.scala:120) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1361) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.1.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.1.jar:na]
Caused by: java.lang.NoSuchMethodError: org.apache.http.params.HttpConnectionParams.setSoKeepalive(Lorg/apache/http/params/HttpParams;Z)V
	at com.amazonaws.http.HttpClientFactory.createHttpClient(HttpClientFactory.java:95) ~[aws-java-sdk-core-1.9.33.jar:na]
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:193) ~[aws-java-sdk-core-1.9.33.jar:na]
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:131) ~[aws-java-sdk-core-1.9.33.jar:na]
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:115) ~[aws-java-sdk-core-1.9.33.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:379) ~[aws-java-sdk-s3-1.9.33.jar:na]
	at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:361) ~[aws-java-sdk-s3-1.9.33.jar:na]
	at service.aws.storage.S3Init.initializeS3(S3Init.java:34) ~[na:na]
	at Global.onStart(Global.java:65) ~[na:na]
	at play.core.j.JavaGlobalSettingsAdapter.onStart(JavaGlobalSettingsAdapter.scala:22) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.GlobalPlugin.onStart(GlobalSettings.scala:220) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
	at scala.collection.immutable.List.foreach(List.scala:383) ~[scala-library-2.11.1.jar:na]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:91) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.Play$.start(Play.scala:90) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.core.ReloadableApplication$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(ApplicationProvider.scala:157) ~[play_2.11-2.3.8.jar:2.3.8]
	... 14 common frames omitted`

**Comment by fulghum** [comment]
The error message sounds like a classpath issue: 
> NoSuchMethodError: org.apache.http.params.HttpConnectionParams.setSoKeepalive(Lorg/apache/http/params/HttpParams;Z)V

Make sure you have the right version of HttpClient on your classpath, and that there isn't an older version on your classpath that is being loaded first.

**Comment by puneetar** [comment]
The class path does not contain any conflicting versions of httpclient-4.3.4 or httpcore-4.3.2.

	- /home/puneet/.ivy2/cache/com.amazonaws/aws-java-sdk-s3/jars/aws-java-sdk-s3-1.9.33.jar
	- /home/puneet/.ivy2/cache/com.amazonaws/aws-java-sdk-kms/jars/aws-java-sdk-kms-1.9.33.jar
	- /home/puneet/.ivy2/cache/com.amazonaws/aws-java-sdk-core/jars/aws-java-sdk-core-1.9.33.jar
	- /home/puneet/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.3.jar
	- /home/puneet/.ivy2/cache/org.apache.httpcomponents/httpclient/jars/httpclient-4.3.4.jar
	- /home/puneet/.ivy2/cache/org.apache.httpcomponents/httpcore/jars/httpcore-4.3.2.jar
	- /home/puneet/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.7.jar

I also tried updating them to 4.4.1 (latest version), but got the same result.

**Comment by hanshuo-aws** [comment]
@puneetar Are you by any chance using Google App Engine to host your application?

**Comment by hanshuo-aws** [comment]
Also try printing out the location where HttpConnectionParams.class is loaded:
```scala
classOf[HttpConnectionParams].getResource("HttpConnectionParams.class").toString
```

**Comment by puneetar** [comment]
Thanks for pointing me in the right direction ... was able to debug the issue. 
It was due to a dependency.. 
Thanks

**Comment by tgfitz201** [comment]
What was it? I am having the same issue.

**Comment by puneetar** [comment]
I think some other library was including an older version of the same class.. I just sorted that out.
Currently I use httpclient:4.5 and httpcore:4.4.1

**Comment by Raneves** [comment]
I having the same problem

**Comment by subhaabhi** [comment]
i have the same problem no matter wat version of httpclient and httpcore version i use.The same error occurs
