### ISSUE TITLE
Could not initialize class com.amazonaws.auth.internal.AWS4SignerUtils error when initializing aws clients

### ISSUE THREAD

**Issue by ferozed** [aws/aws-sdk-java#430]
We are getting the following error when initializing aws java clients...

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.auth.internal.AWS4SignerUtils
        at com.amazonaws.auth.internal.AWS4SignerRequestParams.<init>(AWS4SignerRequestParams.java:85)
        at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:184)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:681)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2422)
        at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:541)
```

The actual root cause is the following:

```
Exception in thread "sqssweeper5-dcomp_fail_tes900" java.lang.NoSuchMethodError: org.joda.time.format.DateTimeFormatter.withZoneUTC()Lorg/joda/time/format/DateTimeFormatter;
        at com.amazonaws.auth.internal.AWS4SignerUtils.<clinit>(AWS4SignerUtils.java:26)
        at com.amazonaws.auth.internal.AWS4SignerRequestParams.<init>(AWS4SignerRequestParams.java:85)
        at com.amazonaws.auth.AWS4Signer.sign(AWS4Signer.java:184)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:681)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2422)
        at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1130)
```

This started happening because we upgraded our aws java sdk from 1.4 to 1.9.33. Looks like 1.9.33 needs a new joda-time ( > 2.0 ) whereas our project was using 1.4.

Please fix your POM file in maven so that it reflects the correct dependency versions.

**Comment by fulghum** [comment]
Hey @ferozed is it possible you're picking up that version of joda-time from another project?  The aws-java-sdk-core module has a minimum dependency on joda-time 2.2:
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/pom.xml#L37

**Comment by ferozed** [comment]
Thanks. can you point me to release notes so that I can figure out if it is safe to move from 1.4 to 1.9.latest ?

**Comment by fulghum** [comment]
You can find the release notes for the AWS SDK for Java here:
http://aws.amazon.com/releasenotes/Java?browse=1

On a related topic, we're investigating the use of a Maven BOM module to help with managing dependencies.

**Comment by ferozed** [comment]
Thanks for the link to the relnotes. It would be better if the relnotes were linked here. Who would remember to go to aws to get that link?

**Comment by manikandanrs** [comment]
Definitely. We have got requests to add support for change log in the repository itself. We have added this to our backlog. We will let you once the change log support is added.
