### ISSUE TITLE
Too many s3-transfer-manager-worker threads

### ISSUE THREAD

**Issue by gsphanikumar** [aws/aws-sdk-java#435]
Hi folks,

I am using aws sdk 1.4.7 and seeing around 1000  s3-transfer-manager-worker-1 threads in the application. I do reads and writes to S3 using the AmazonS3Client and there is only one instance of AmazonS3Client . I want to limit the no of threads transfer manager uses. 

```
    AWSCredentials awsCredentials = new BasicAWSCredentials(awsAccessKey,awsSecretKey);
    s3client = new AmazonS3Client(awsCredentials); 
  S3Object object = s3client.getObject(new GetObjectRequest(bucketName, key));

```

```
"s3-transfer-manager-worker-1" prio=10 tid=0x00007f48e4565000 nid=0x47de waiting on condition [0x00007f48a4d4e000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e9b276b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

"s3-transfer-manager-worker-1" prio=10 tid=0x00007f48e4564000 nid=0x5691 waiting on condition [0x00007f48a4e4f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e9c57768> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1068)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by hansonchar** [comment]
Hi @gsphanikumar, AWS SDK for Java [1.4.7](http://aws.amazon.com/releasenotes/7233847602537543) (released on 18Jun 2013) is close to 2 years old now. Have you considered upgrading to the latest [1.9.37](  https://aws.amazon.com/releasenotes/Java/7224797899674919) to see if the problem is still there?

**Comment by gsphanikumar** [comment]
Yes we are planning to upgrade to the latest. Will re-open this if the issue exists.

**Comment by viswanadhbysani** [comment]
Hi,

We are currently on 1.11.176, however we are experiencing the same issue as mentioned in the description. We are currently seeing **2949** instances of s3 transfer manager worker threads in the thread dump that we acquired. As a result of this, the CPU utilization is going high (almost 100%). Could you please check this again?

We are using the API as shown below.

	public TransferManager createS3TransferManager(){
		TransferManagerBuilder transferManagerBuilder = TransferManagerBuilder.standard().withS3Client(s3Client);
		transferManagerBuilder.setShutDownThreadPools(false);
		return transferManagerBuilder.build();
	}

	private void upload(final TransferManager transferManager, final PutObjectRequest uploadObjRequest, final AmazonS3FileTransferImpl transfer){
		uploadObjRequest.setGeneralProgressListener(new ProgressListener() {
			@Override
			public void progressChanged(ProgressEvent progressEvent) {
				transfer.progress(progressEvent.getBytesTransferred());
			}
		});

		transfer.start();

		final Upload upload = transferManager.upload(uploadObjRequest);
		try{
			upload.waitForCompletion();
		}catch(AmazonServiceException e){
			throw new FSRuntimeException(e);
		}catch(InterruptedException ie){
			LOG.warn("Uploading content to Amazon S3 is interuppted: " + uploadObjRequest.getBucketName() + "-->" + uploadObjRequest.getKey());
			Thread.currentThread().interrupt();
		}finally{
			transfer.end();
			transferManager.shutdownNow(false);
		}
	}

Please let me know if any more details are required for debugging this issue.

Thanks,
Kasi
