### ISSUE TITLE
AmazonHttpClient attempts to parse plain text response as JSON.

### ISSUE THREAD

**Issue by joe-spanning** [aws/aws-sdk-java#448]
SDK version: 1.9.22

I am uploading JSON documents to CloudSearch.  CloudSearch will occasionally return a very vague InternalServerError (I have verified that the JSON is perfectly valid by uploading it via the CloudSearch web console). When the AmazonHttpClient attempts to parse this Internal Server Error, it fails.

The HTTP response from CloudSearch is "text/plain" (request was sent as "application/json"):

```
HTTP/1.1 500 Server Error
Content-Type: text/plain
Date: Sun, 31 May 2015 04:04:14 GMT
x-amzn-RequestId: 198551af-074a-11e5-bdd1-2ba6d03daebd
Content-Length: 21
Connection: keep-alive

Internal Server Error
```

The stacktrace is:

```
Caused by: com.amazonaws.AmazonClientException: Unable to unmarshall error response (Unable to parse error response: 'Internal Server Error'). Response Code: 500, Response Text: Server Error
   at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1072)
   at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:726)
   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296)
   at com.amazonaws.services.cloudsearchdomain.AmazonCloudSearchDomainClient.invoke(AmazonCloudSearchDomainClient.java:527)
   at com.amazonaws.services.cloudsearchdomain.AmazonCloudSearchDomainClient.uploadDocuments(AmazonCloudSearchDomainClient.java:310)
...
...
Caused by: com.amazonaws.AmazonClientException: Unable to parse error response: 'Internal Server Error'
   at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:55)
   at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:29)
   at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1046)
   at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:726)
   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296)
   at com.amazonaws.services.cloudsearchdomain.AmazonCloudSearchDomainClient.invoke(AmazonCloudSearchDomainClient.java:527)
   at com.amazonaws.services.cloudsearchdomain.AmazonCloudSearchDomainClient.uploadDocuments(AmazonCloudSearchDomainClient.java:310)
```

So since the http client has been configured with a JsonErrorResponseHandler, it attempts to parse the plain text as JSON and fails, thus obfuscating the original error from CloudSearch.

**Comment by zhangzhx** [comment]
Are you still facing this problem when using the recent SDK version 1.10.58?

**Comment by shorea** [comment]
Closing issue, no response.

**Comment by unoexperto** [comment]
I have same problem after switching from 1.10.52 to 1.11.96. No code changes on my side. What should I do ?

I hope you guys respond fast.

Thanks!

**Comment by zhangzhx** [comment]
@unoexperto, sorry for not getting back to you soon.

Can you share more information about this issue, such as the exception trace, or error log? **Note: don't share your confidential date here.**

If you can provide a test case for us to reproduce this issue, that would be great.
