### ISSUE TITLE
Amazon S3 Client doesn't retry on java.net.UnknownHostException

### ISSUE THREAD

**Issue by jakozaur** [aws/aws-sdk-java#452]
Temporary network blip may cause DNS resolution to fail. Contrary to other network failures (IOException), AWS SDK doesn't retry by default on it.

Example failed stack trace:
```
com.amazonaws.AmazonClientException: Unable to execute HTTP request: stag-dual-custodian-store-000000000000141d.s3.amazonaws.com
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:472)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:296)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3737)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1462)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:132)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:124)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:125)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: stag-dual-custodian-store-000000000000141d.s3.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1250)
	at java.net.InetAddress.getAllByName(InetAddress.java:1162)
	at java.net.InetAddress.getAllByName(InetAddress.java:1098)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:461)
	... 11 more
```

**Comment by fulghum** [comment]
Hey Jacek, it sounds like you and David discussed this in the associated Pull Request, but since UnknownHostException does extend IOException, the SDK should be retrying this exception, too. 

I'll resolve this issue, but feel free to reopen if you think you're seeing different behavior.

**Comment by jakozaur** [comment]
Hey Jason, 

thanks for looking at it. We decided to solve that problem in more specific way. Not sure if there is something that SDK can do. Anyway thanks for pointing negative dns cache for Java. That helped a lot!
