### ISSUE TITLE
SQS getQueueAttributes is broken in 1.10.11

### ISSUE THREAD

**Issue by EugeneFeingold** [aws/aws-sdk-java#489]
This code fails in 1.10.11 (but works fine in 1.9.40):

```java
private AmazonSQS sqsClient; //Spring injected

GetQueueAttributesResult DLQAttributes = sqsClient.getQueueAttributes(
             (new GetQueueAttributesRequest(deadLetterQueueUrl))
              .withAttributeNames(new String[] {QueueAttributeName.QueueArn.name()})
  );
```

stack trace:

`java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.amazonaws.services.sqs.QueueUrlHandler.beforeRequest(QueueUrlHandler.java:39)
	at com.amazonaws.handlers.RequestHandler2Adaptor.beforeRequest(RequestHandler2Adaptor.java:37)
	at com.amazonaws.http.AmazonHttpClient.requestHandler2s(AmazonHttpClient.java:405)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:283)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:2419)
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueAttributes(AmazonSQSClient.java:694)
`

**Comment by shorea** [comment]
Looks like you are using a 1.10.x version of the client but a 1.9.x version of the core which is not something we support. You'll have to upgrade the core to a 1.10.x version as well.
