### ISSUE TITLE
sdk-core calls SSLContext.setDefault which changes entire jvm

### ISSUE THREAD

**Issue by rmuir** [aws/aws-sdk-java#552]
This failed on upgrade of elasticsearch for me with:

```
Caused by: java.security.AccessControlException: access denied ("javax.net.ssl.SSLPermission" "setDefaultSSLContext")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at javax.net.ssl.SSLContext.setDefault(SSLContext.java:119)
        at com.amazonaws.http.HttpClientFactory.createHttpClient(HttpClientFactory.java:111)
        at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:204)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:136)
        at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:450)
        at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:432)
```

Can this please be avoided? In our case the app does other things with SSL, changing this jvm-wide is a scary prospect, and obviously unnecessary.

Blame shows this introduced in AWS SDK for Java 1.10.23:

https://github.com/aws/aws-sdk-java/blob/bb9e0be441afb5658f0edbbd19bcf27e2fac4105/aws-java-sdk-core/src/main/java/com/amazonaws/http/HttpClientFactory.java#L111

**Comment by shorea** [comment]
Thanks for reporting! I agree with your assessment. We don't need to be changing the default SSL context. I'll put a patch together and update this ticket when released

**Comment by rmuir** [comment]
thanks for looking at this @shorea

**Comment by shorea** [comment]
This has been fixed and is staged for our next release tentatively scheduled for next Tuesday. Thanks again for reporting before this became a bigger problem for our customers!
