### ISSUE TITLE
Latest version (1.10.37) has introduced issue with CloudSearchDomain authentication.

### ISSUE THREAD

**Issue by tfeak** [aws/aws-sdk-java#565]
Using version 1.10.36, I have no issues accessing my CloudSearchDomain. However, when I upgraded to release 1.10.37, I get the following exception:

com.amazonaws.AmazonServiceException: Request forbidden by administrative rules (Service: AmazonCloudSearchDomain; Status Code: 403; Error Code: CloudSearchException; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1249)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:870)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:574)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
	at com.amazonaws.services.cloudsearchdomain.AmazonCloudSearchDomainClient.invoke(AmazonCloudSearchDomainClient.java:529)
	at com.amazonaws.services.cloudsearchdomain.AmazonCloudSearchDomainClient.search(AmazonCloudSearchDomainClient.java:327)

As far as I can tell, this is purely a library regression. Command line tools used from the EC2 instance have no issue making the call (aws cloudsearchdomain search ...). But a server running on the same EC2 instance with this release version gets the error every time.

**Comment by manikandanrs** [comment]
Taking a look.

**Comment by manikandanrs** [comment]
We have found the bug. We will be releasing a fix for this issue today.

**Comment by manikandanrs** [comment]
We have fixed this in 1.10.39. Thanks for reporting it.
