### ISSUE TITLE
S3 : call doesBucketExist (HEAD operation) with RequestTimeout set causes "Wrapped entity may not be null"

### ISSUE THREAD

**Issue by RaphC** [aws/aws-sdk-java#597]
Hi I'm facing an issue about requestTimeout (I'm using Java 7 with 1.10.45 sdk version).

When I set requestTimeout on my client configuration, It appears that a HEAD call (invoking doesBucketExist method) causes the following exception whereas the response is received before the timeout

<pre>
java.lang.IllegalArgumentException: Wrapped entity may not be null
	at org.apache.http.util.Args.notNull(Args.java:48)
	at org.apache.http.entity.HttpEntityWrapper.<init>(HttpEntityWrapper.java:59)
	at org.apache.http.entity.BufferedHttpEntity.<init>(BufferedHttpEntity.java:61)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:825)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3659)
	at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1087)
	at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1059)
	at com.bouygtel.ihd.siext.aws.client.AWSS3ClientImpl.<init>(AWSS3ClientImpl.java:61)
	at com.bouygtel.ihd.siext.aws.client.AWSS3ClientTest.put_with_request_timeout(AWSS3ClientTest.java:598)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.github.tomakehurst.wiremock.junit.WireMockClassRule$1.evaluate(WireMockClassRule.java:75)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
</pre>

Here is the request sent by the java client

15:02:30.855 [main] DEBUG com.amazonaws.request - Sending Request: HEAD http://bucket.test.s3.amazonaws.com / Headers: (User-Agent: aws-sdk-java/1.10.45 Windows_7/6.1 Java_HotSpot(TM)_64-Bit_Server_VM/24.0-b56/1.7.0_40, Content-Type: application/octet-stream, ) 

Am i missing something?

Regards

**Comment by RaphC** [comment]
After some investigation it seems that in case of HEAD the issue comes from AmazonHttpClient.java at line 825

<pre>
                execParams.apacheResponse.setEntity(new BufferedHttpEntity(execParams.apacheResponse.getEntity()));
</pre>

For HEAD, execParams.apacheResponse is a BasicHttpResponse with no entity so the BufferedHttpEntity instantiation failed.

**Comment by shorea** [comment]
Thanks for reporting! This looks like a straightforward fix. I'll put together a pull request for it later today.

**Comment by shorea** [comment]
This is in review, hoping to release it by the end of the week.

**Comment by RaphC** [comment]
Thanks a lot !

**Comment by shorea** [comment]
This has been pushed internally and will be available in the next SDK release which is tentatively scheduled for later today.
