### ISSUE TITLE
SQS connection can not recover from SSL exception

### ISSUE THREAD

**Issue by vinctzhang** [aws/aws-sdk-java#605]
```java 
Caused by: javax.net.ssl.SSLHandshakeException: server certificate change is restrictedduring renegotiation
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1904)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:279)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:269)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1409)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:209)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:901)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:837)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1023)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:446)
```

We are suffering from this exception. According to previous researching, this is caused by certification changed or other nodes with different certificates added into SQS server cluster, while SQS client still try to reuse old connection with old certification. 

The aws-java-sdk version we are use is : 
```
com.amazonaws:aws-java-sdk:1.8.3
````

I'd like to know is this bug (perhaps) fixed in any latter version?   Thanks guys.

**Comment by manikandanrs** [comment]
This has been fixed in the later version of the SDK. can you try testing your code against the latest version of the SDK ?

**Comment by vinctzhang** [comment]
@manikandanrs , yes, I will update our SDK. But this problem randomly happens and cannot reproduced by ourself. But thanks anyway.

**Comment by manikandanrs** [comment]
Thanks for the reply. Feel free to re open this issue if you still face this issue with the latest version of the SDK.
