### ISSUE TITLE
AWS4Signer NullPointerException due to serviceName == null

### ISSUE THREAD

**Issue by lonewasp** [aws/aws-sdk-java#614]
Version: 1.10.48

Steps:
1. Create AmazonEC2Client with access and private key
2. Issue copySnapshot request of snapshot from another region

Result:
```
com.amazonaws.AmazonClientException: Unable to calculate a request signature: null
        at com.amazonaws.auth.AbstractAWSSigner.sign(AbstractAWSSigner.java:91)
        at com.amazonaws.auth.AWS4Signer.newSigningKey(AWS4Signer.java:578)
        at com.amazonaws.auth.AWS4Signer.deriveSigningKey(AWS4Signer.java:356)
        at com.amazonaws.auth.AWS4Signer.presignRequest(AWS4Signer.java:261)
        at com.amazonaws.services.ec2.model.transform.GeneratePreSignUrlRequestHandler.beforeRequest(GeneratePreSignUrlRequestHandler.java:82)
        at com.amazonaws.http.AmazonHttpClient.requestHandler2s(AmazonHttpClient.java:507)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:13032)
        at com.amazonaws.services.ec2.AmazonEC2Client.copySnapshot(AmazonEC2Client.java:5480)
        --trimmed--
Caused by: java.lang.NullPointerException
        at com.amazonaws.auth.AbstractAWSSigner.sign(AbstractAWSSigner.java:88)
        ... 17 more
```
In debug serviceName that is passed as a value to be signed is null with non-null key.
Issue was not present on version 1.10.30

**Comment by manikandanrs** [comment]
This is a bug we identified today. I have staged a fix that is tentatively scheduled for release tomorrow.

**Comment by manikandanrs** [comment]
Closing this issue as we are scheduling this for tomorrows release.
