### ISSUE TITLE
errors run S3Sample.java

### ISSUE THREAD

**Issue by geohuz** [aws/aws-sdk-java#619]
after running: ant, I got the following errors:
```
Buildfile: /Users/geohu/Codings/Side_Projects/gskAWS/build.xml

run:
    [javac] /Users/geohu/Codings/Side_Projects/gskAWS/build.xml:12: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 131 source files to /Users/geohu/Codings/Side_Projects/gskAWS
    [javac] 
    [javac] 
    [javac] An annotation processor threw an uncaught exception.
    [javac] Consult the following stack trace for details.
    [javac] java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$VarSymbol cannot be cast to javax.lang.model.element.TypeElement
    [javac] 	at com.amazonaws.eclipse.simpleworkflow.asynchrony.annotationprocessor.AsynchronyDeciderAnnotationProcessor.processActivities(AsynchronyDeciderAnnotationProcessor.java:91)
    [javac] 	at com.amazonaws.eclipse.simpleworkflow.asynchrony.annotationprocessor.AsynchronyDeciderAnnotationProcessor.process(AsynchronyDeciderAnnotationProcessor.java:64)
    [javac] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
    [javac] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
    [javac] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
    [javac] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
    [javac] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
    [javac] 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
    [javac] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
    [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:439)
    [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:353)
    [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:342)
    [javac] 	at com.sun.tools.javac.main.Main.compile(Main.java:333)
    [javac] 	at com.sun.tools.javac.Main.compile(Main.java:76)
    [javac] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [javac] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [javac] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [javac] 	at org.apache.tools.ant.taskdefs.compilers.Javac13.execute(Javac13.java:57)
    [javac] 	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1160)
    [javac] 	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:936)
    [javac] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [javac] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [javac] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac] 	at java.lang.reflect.Method.invoke(Method.java:606)
    [javac] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac] 	at org.apache.tools.ant.Task.perform(Task.java:348)
    [javac] 	at org.apache.tools.ant.Target.execute(Target.java:435)
    [javac] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
    [javac] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    [javac] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    [javac] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    [javac] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    [javac] 	at org.apache.tools.ant.Main.runBuild(Main.java:853)
    [javac] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
    [javac] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
    [javac] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
```

**Comment by manikandanrs** [comment]
I am able to run the S3 sample successfully. From the logs I can see you are using simpleworflow and some other code ? Can you provide more context on what you are trying to do.

**Comment by geohuz** [comment]
Well I just clone the S3Sample.java from git and start it using the 'ant' command. And it failed.

**Comment by shorea** [comment]
Which version of ant and java are you using?

**Comment by manikandanrs** [comment]
Closing this issue as there is no response. Feel free to re open when you have more information.
