### ISSUE TITLE
DynamoDB - Exception in Parallel Scan causes application to hang for 60 seconds

### ISSUE THREAD

**Issue by paragvk** [aws/aws-sdk-java#623]
**Description:**
When call to DynamoDBMapper.parallelScan() fails with an Exception e.g. ProvisionedThroughputExceededException, the application hangs until the cached threads expire after 60 seconds.

**Example Stack trace:**
`com.amazonaws.services.dynamodbv2.model.ProvisionedThroughputExceededException: The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ProvisionedThroughputExceededException; Request ID: XXXXXX)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1181)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:766)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:485)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:306)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1799)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.scan(AmazonDynamoDBClient.java:1519)
	at com.amazonaws.services.dynamodbv2.datamodeling.ParallelScanTask.scanNextPageOfSegment(ParallelScanTask.java:223)
	at com.amazonaws.services.dynamodbv2.datamodeling.ParallelScanTask.access$000(ParallelScanTask.java:32)
	at com.amazonaws.services.dynamodbv2.datamodeling.ParallelScanTask$1.call(ParallelScanTask.java:157)
	at com.amazonaws.services.dynamodbv2.datamodeling.ParallelScanTask$1.call(ParallelScanTask.java:149)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Expected:**
The cached thread pool used by `com.amazonaws.services.dynamodbv2.datamodeling.ParallelScanTask` should have shutdown after the failure.

**Comment by shorea** [comment]
When you say hangs do you mean it's deadlocked or the application shutdown is delayed?

**Comment by paragvk** [comment]
@shorea Thanks for looking into this so quickly. By hang, I meant the app shutdown is delayed.

**Comment by shorea** [comment]
Duplicate issue.
