### ISSUE TITLE
Provisioning Instance with IAM name and arn returns Error

### ISSUE THREAD

**Issue by nicktylah** [aws/aws-sdk-java#647]
Using `aws-sdk-java-ec2-1.10.21`, the following error occurs when attempting to provision instance with an `IamInstanceProfileSpecification` containing both `name` and `arn`:
```
ERROR [RemoteTaskRunner-ResourceManagement--0] io.druid.indexing.overlord.autoscaling.ec2.EC2AutoScaler - Unable to provision any EC2 instances.
com.amazonaws.AmazonServiceException: The parameter 'iamInstanceProfile.name' may not be used in combination with 'iamInstanceProfile.arn' (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: 3162b924-ffed-46b9-9128-a7c87f37864a)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1182) ~[aws-java-sdk-core-1.10.21.jar:?]
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:770) ~[aws-java-sdk-core-1.10.21.jar:?]
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489) ~[aws-java-sdk-core-1.10.21.jar:?]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310) ~[aws-java-sdk-core-1.10.21.jar:?]
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:11901) ~[aws-java-sdk-ec2-1.10.21.jar:?]
        at com.amazonaws.services.ec2.AmazonEC2Client.runInstances(AmazonEC2Client.java:5724) ~[aws-java-sdk-ec2-1.10.21.jar:?]
        at io.druid.indexing.overlord.autoscaling.ec2.EC2AutoScaler.provision(EC2AutoScaler.java:162) [druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.druid.indexing.overlord.autoscaling.SimpleResourceManagementStrategy.doProvision(SimpleResourceManagementStrategy.java:138) [druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at io.druid.indexing.overlord.autoscaling.SimpleResourceManagementStrategy$4.run(SimpleResourceManagementStrategy.java:285) [druid-indexing-service-0.9.0-SNAPSHOT.jar:0.9.0-SNAPSHOT]
        at com.metamx.common.concurrent.ScheduledExecutors$3.call(ScheduledExecutors.java:140) [java-util-0.27.7.jar:?]
        at com.metamx.common.concurrent.ScheduledExecutors$3.call(ScheduledExecutors.java:136) [java-util-0.27.7.jar:?]
        at com.metamx.common.concurrent.ScheduledExecutors$4.run(ScheduledExecutors.java:173) [java-util-0.27.7.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by shorea** [comment]
Why do you need to use both? Can you try using just one of the identifiers?

**Comment by shorea** [comment]
Closing issue. Feel free to reopen if you still have the issue.
