### ISSUE TITLE
S3 connections hang up when they are created

### ISSUE THREAD

**Issue by samuelgmartinez** [aws/aws-sdk-java#657]
I have a backend service that reads files from S3 to be indexed by an external index service, the problem is that from time to time a connection hangs forever and is always when the connection is created.

Im using the SDK v1.10.38 with the default ClientConfiguration (instantiating directly the S3Connection) with JDK 1.8.0_60.

The thing is that the default config sets the connection timeout to 50s but the connection remains inactive and waiting in that socketRead0 for hours and I don't know why :cry: 

I've attached a stacktrace of the hung thread:
`"index-worker-akka.actor.default-dispatcher-4" #26 prio=5 os_prio=0 tid=0x00007fa580008800 nid=0x7ce6 runnable [0x00007fa557ffd000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:170)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
        at sun.security.ssl.InputRecord.read(InputRecord.java:532)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        - locked <0x00000000851cf828> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
        - locked <0x00000000851cf838> (a java.lang.Object)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:534)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:402)
        at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:128)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:178)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:822)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:362)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:328)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:307)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3620)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1142)
        my code here....`

**Comment by zhangzhx** [comment]
Could you upgrade Java SDK to the most recent version 1.10.60 to see if the problem still happens?

**Comment by samuelgmartinez** [comment]
Sure @zhangzhx , that is my plan for tomorrow. Change the version and rollout the new service into production.

I'll let you know how it goes. Usually it takes a few days since we notice that we have stuck connections.

**Comment by fernomac** [comment]
https://issues.apache.org/jira/browse/HTTPCLIENT-1478 is my go-to culprit for this one. Make sure you're using an appropriately recent version of the HttpClient underneath the SDK.

**Comment by samuelgmartinez** [comment]
Oh! I see... the problem is this issue is fixed for 4.3.4 while the AWS SDK, even the 1.1.38, is using the 4.3.6 version.

I took a look at the comments on the HTTPClient thread and users are telling that even in the latest version is not fully fixed. I will try the 4.5.1 version that one guy tested and [he said that with that version is properly fixed](https://issues.apache.org/jira/browse/HTTPCLIENT-1478?focusedCommentId=15152242&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15152242)

**Comment by samuelgmartinez** [comment]
As an update, I rolled up the new version of our service using AWS SDK 1.10.60 and forcing it to use the httpclient v4.5.2.

I will let you know how it goes in a few days :)

**Comment by samuelgmartinez** [comment]
1 week later it looks like it's fixed using the versions I mentioned in my previous comment. 

thanks @fernomac for the link to the httpclient issue :)
