### ISSUE TITLE
java.net.UnknownHostException: sudbucket.s3.amazonaws.com

### ISSUE THREAD

**Issue by schindh1** [aws/aws-sdk-java#659]
com.securonix.connectorframework.ConnectorException: Error connecting / communicating with the data source
	at com.securonix.connector.awscloudtrail.AWSCloudTrailConnector.initiateImport(AWSCloudTrailConnector.java:253)
	at com.securonix.application.matcher.connector.Connector.executeImport(Connector.java:285)
	at com.securonix.application.matcher.reader.AbstractResourceReader.executeImport(AbstractResourceReader.java:206)
	at com.securonix.application.matcher.process.ApplicationFeedController.importResourceData(ApplicationFeedController.java:33)
	at com.securonix.application.matcher.reader.ResourceDataReader.processImportData(ResourceDataReader.java:146)
	at com.securonix.application.scheduler.quartz.eventimport.EventImportByMode.setup(EventImportByMode.java:848)
	at com.securonix.application.scheduler.quartz.framework.QuartzJob.execute(QuartzJob.java:143)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: sudbucket.s3.amazonaws.com
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:454)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:232)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3566)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1127)
	at com.amazonaws.services.s3.AmazonS3Client$2.getS3ObjectStream(AmazonS3Client.java:1222)
	at com.amazonaws.services.s3.internal.ServiceUtils.retryableDownloadS3ObjectToFile(ServiceUtils.java:322)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1218)
	at com.securonix.connector.awscloudtrail.AWSCloudTrailConnector.initiateImport(AWSCloudTrailConnector.java:205)
	... 8 more
Caused by: java.net.UnknownHostException: sudbucket.s3.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:384)
	... 15 more

ping works fine, Tried changing networkaddress ttl, so that the cache doesnt cause this..

Any pointers as to what is goin on and how to fix this thing?

**Comment by shorea** [comment]
Is this for a newly created bucket?

Looks like you've already found the TTL settings but linking to http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-jvm-ttl.html for future developers who may see this issue.

**Comment by manikandanrs** [comment]
No response here. Closing this issue for now. Feel free to re open.
