### ISSUE TITLE
AWS IoT UpdateThing Exception

### ISSUE THREAD

**Issue by Mindbowser** [aws/aws-sdk-java#666]
We are using below method to update Thing, here is the code,

```
UpdateThingRequest updateThingRequest = new UpdateThingRequest();
updateThingRequest.setThingName("HomeIot-ABCD");
AttributePayload attributePayload = new AttributePayload();
HashMap<String, String> hashMap = new HashMap<>();
hashMap.put("\"state\"", "{\"reported\":{\"device_id\":\"ABCD\",\"motion_info\":\"STOP\"}}");
attributePayload.setAttributes(hashMap);
updateThingRequest.setAttributePayload(attributePayload);
UpdateThingResult updateThingsResult = awsIotClient.updateThing(updateThingRequest);
```

but we are getting following exception,

```
Exception in thread "main" com.amazonaws.services.iot.model.InvalidRequestException: 2 validation errors detected: Value '{"state"={"reported":{"device_id":"ABCD","motion_info":"STOP"}}}' at 'attributePayload.attributes' failed to satisfy constraint: Map keys must satisfy constraint: [Member must have length less than or equal to 128, Member must have length greater than or equal to 0, Member must satisfy regular expression pattern: [a-zA-Z0-9_.,@/:#-]+]; Value '{"state"={"reported":{"device_id":"ABCD","motion_info":"STOP"}}}' at 'attributePayload.attributes' failed to satisfy constraint: Map value must satisfy constraint: [Member must have length less than or equal to 1024, Member must have length greater than or equal to 0, Member must satisfy regular expression pattern: [a-zA-Z0-9_.,@/:#-]+] (Service: AWSIot; Status Code: 400; Error Code: InvalidRequestException; Request ID: d52c5f07-f0e5-11e5-8dd0-8d8709559cb7)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1383)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
	at com.amazonaws.services.iot.AWSIotClient.invoke(AWSIotClient.java:2773)
	at com.amazonaws.services.iot.AWSIotClient.updateThing(AWSIotClient.java:2712)
	at AWSIoTPubDemo.main(AWSIoTPubDemo.java:39)
```

BTW, we are able to list and describe things using SDK, but for update it is not working. Also if remove JSON string and put simple string value then it is returning me "{}" as response, Any idea whats the issue?

**Comment by Mindbowser** [comment]
@aws-dpt @awsdave Any idea why I am getting this error?

**Comment by shorea** [comment]
@Mindbowser I'm not sure how this operation is supposed to work. I am seeing the same behavior, JSONified strings as keys and values doesn't work but simple strings do (with empty response which the docs seem to imply is normal). I'll track down a service expert to see if we can get a better answer for you.

**Comment by Mindbowser** [comment]
Thanks a lot Andrew for quick revert. Let me know once you have update for
me. Eagerly waiting for your revert with its resolution


--
Thanks and regards,
Pravin Uttarwar
Co-Founder & CTO | Mindbowser Info Solutions Pvt Ltd
<http://t.sidekickopen50.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg2zWKbYN63Rx9WQsHZ4W7fsFDW56dxtwf51H8vn02?t=http%3A%2F%2Fwww.mindbowser.com%2F&si=6260254098063360&pi=7ba08562-c5a6-4719-b339-c0881e6c49a3>
Direct  -  +1 303 872 7868
Mobile - +91 937 128 8080
Phone - +91 20 65313444/555

Skype - pravin.mindbowser

**Comment by shorea** [comment]
I'll wait for the service team for the official response but as far as I can tell a things attributes are meant to be more static metadata about a thing hence the simple key/value map. A thing shadow is used for updating the things state and that's where you would use the JSON document containing the reported state.

I can't seem to find a example in the docs where a thing has non-empty attributes.

**Comment by Mindbowser** [comment]
Thanks. So which method correspond to updating things? I dont see any method in SDK?

**Comment by shorea** [comment]
There are two clients. The AWSIotClient is for control plane operations. The AWSIotDataClient is for data plane operations which includes APIs for updating thing shadows.

**Comment by Mindbowser** [comment]
Ok... So after trying out different ways finally I got succeeded using followign code,

```
UpdateThingShadowRequest updateThingShadowRequest = new UpdateThingShadowRequest();
		updateThingShadowRequest.setThingName("HomeIot-Rpi3-B827EB8CB946");
		String payload = "{\"state\":{\"reported\":{\"device_id\":\"B827EB8CB946\",\"motion_info\":\"START\"}}}";
		byte[] b = payload.getBytes(StandardCharsets.UTF_8);
		updateThingShadowRequest.setPayload( ByteBuffer.wrap(b));
		UpdateThingShadowResult updateThingsResult = awsIotClient.updateThingShadow(updateThingShadowRequest);
		System.out.println(updateThingsResult.toString());
```

But still I feel that documentation for updateThingRequest is misleading where in JavaDoc it has some sample json sample which seems to be wrong.

**Comment by shorea** [comment]
Passed the feedback off to the service team to improve the docs. Closing this issue.
