### ISSUE TITLE
com.amazonaws.http.AmazonHttpClient.handleInterruptedException while polling SQS

### ISSUE THREAD

**Issue by chakrapanikumar** [aws/aws-sdk-java#667]
Hi,
I am getting following exception while polling SQS for messages. I am using Java ThreadPoolExecutor to start the poller thread:com.amazonaws.AmazonClientException: 
com.amazonaws.http.timers.client.SdkInterruptedException
        at com.amazonaws.http.AmazonHttpClient.handleInterruptedException(AmazonHttpClient.java:416)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:290)
        at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1650)
        at com.amazonaws.services.sqs.AmazonSQSClient.receiveMessage(AmazonSQSClient.java:1313)
        at amazon.kcq.aws.sqs.SQSFacade.receiveMessages_aroundBody4(SQSFacade.java:67)
        at amazon.kcq.aws.sqs.SQSFacade.receiveMessages(SQSFacade.java:59)
        at amazon.kcq.aws.sqs.AbstractSQSMessageListener.doProcessLoop(AbstractSQSMessageListener.java:120)
        at amazon.kcq.aws.sqs.AbstractSQSMessageListener.run_aroundBody12(AbstractSQSMessageListener.java:107)
        at amazon.kcq.aws.sqs.AbstractSQSMessageListener.run(AbstractSQSMessageListener.java:103)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.http.timers.client.SdkInterruptedException
        at com.amazonaws.http.AmazonHttpClient.checkInterrupted(AmazonHttpClient.java:445)
        at com.amazonaws.http.AmazonHttpClient.checkInterrupted(AmazonHttpClient.java:429)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:576)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
        ... 10 more
Has anyone seen this before? Your help is very much appreciated.

**Comment by shorea** [comment]
Can you share your ClientConfiguration? Also are you interrupting the thread the client is executing on?

**Comment by chakrapanikumar** [comment]
Thanks for the response!
I am not putting ClientConfiguration in constructor. I have just created the instance of AmazonSQSClient using aws credentials. I am not interrupting the client thread. 
AmazonSQS sqsClient = new AmazonSQSClient(AWSCredentials awsCredentials)

**Comment by shorea** [comment]
Sorry for the lack of response. If you are not using the client execution timer or request timer then we will not interrupt the thread internally so something must be interrupting your thread from the outside. We don't throw checked exceptions from the SDK so we wrap it in a runtime exception and preseve the interrupt status of the thread. 

Closing this issue, if you continue to have issues feel free to reopen.
