### ISSUE TITLE
Exception using OpenJDK 1.8.0_91

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-sdk-java#694]
I get the following exception when trying to list hosted zones in Route53.

```
Exception in thread "main" com.amazonaws.AmazonServiceException: Invalid date Wed, 27 Apr 2016 08:00:18 +00:00. It must be in one of the formats specified by HTTP RFC 2616 section 3.3.1 (Service: AmazonRoute53; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 157db148-0c4e-11e6-8328-1f6b3c404b92)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1077)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:725)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
	at com.amazonaws.services.route53.AmazonRoute53Client.invoke(AmazonRoute53Client.java:2127)
	at com.amazonaws.services.route53.AmazonRoute53Client.listHostedZones(AmazonRoute53Client.java:1352)
	at com.amazonaws.services.route53.AmazonRoute53Client.listHostedZones(AmazonRoute53Client.java:2049)
```

**Comment by shorea** [comment]
This is concerning. Can you also try S3?

**Comment by shorea** [comment]
Also which version of the SDK are you using?

**Comment by fernomac** [comment]
There was a thing with an old version of JodaTime that wasn't compatible with newer JDK 8's that would do this.

**Comment by hoegertn** [comment]
Ok, using the latest version works. The SDK was an old version.
