### ISSUE TITLE
Ability to pass proxy server params to default matrices enabled by -Dcom.amazonaws.sdk.enableDefaultMetrics

### ISSUE THREAD

**Issue by gauravbrills** [aws/aws-sdk-java#701]
Hi I am using aws cloudwatch in my java app and want to publish jvm level matrics to cloudwatch .For the same I am using the jvm env var `-Dcom.amazonaws.sdk.enableDefaultMetrics` to enable the default aws matrics .

The issue now happens when I deploy my app on ec2 I am getting 

`com.amazonaws.AmazonClientException: Unable to execute HTTP request: connect timed out
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:471)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
        at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:918)
        at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.putMetricData(AmazonCloudWatchClient.java:354)
        at com.amazonaws.metrics.internal.cloudwatch.MetricUploaderThread.run(MetricUploaderThread.java:72)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:532)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409)
        at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:118)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:882)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:685)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
        ... 4 common frames omitted
`

This seems to be due to the proxy maybe restricting post to the cloudwatch url .Is there a way we can pass these params for matrices they also now work behind a proxy .I checked the `MetricUploaderThread `class and as of now there doesnt seem to be a way to inject proxy params there .

Pls help

**Comment by gauravbrills** [comment]
IS there any inputs on this or can I make a pull-request should be a simple fix in MetricUploaderThread to just be able to now pass clientconfiguration which can have proxy parameterts.This could come frome environment properties or can be customized .

**Comment by manikandanrs** [comment]
ClientConfiguration already has the capability to populate the proxy from system properties. Would it make sense to add ClientConfiguration to CloudWatchMetricConfig ?

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudwatchmetrics/src/main/java/com/amazonaws/metrics/internal/cloudwatch/CloudWatchMetricConfig.java

**Comment by gauravbrills** [comment]
@manikandanrs  yup if CloudWatchMetricConfig  has clientconfiguration the same can be used while creating the AmazonCloudWatchClient in MetricUploaderThread . will be cleaner

**Comment by gauravbrills** [comment]
Hi Looking at the example for https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudwatchmetrics/src/main/java/com/amazonaws/metrics/internal/cloudwatch/CloudWatchMetricConfig.java where is the CloudWatchRequestMetricCollector coming from cant find it anywhere in the sdk .Can some example be sighted to do this ..Thanks

**Comment by gauravbrills** [comment]
can anyone help in this issue as we are in dear need of this feature .

**Comment by manikandanrs** [comment]
Here is the file where it is created 

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-cloudwatchmetrics/src/main/java/com/amazonaws/metrics/internal/cloudwatch/DefaultMetricCollectorFactory.java#L41

**Comment by gauravbrills** [comment]
@manikandanrs  thanks that is fine but the point I have is how can I pass Client Configuration which has my proxy details to CloudWatchMetricConfig ? So that MetricUploaderThread can use the same to create the cloud watch client as so far it does not do the same .WIll this require me to change the sdk code in order to accomplish my needs.

**Comment by manikandanrs** [comment]
As per your previous comment, I thought you are sending us a PR.

https://github.com/aws/aws-sdk-java/issues/701#issuecomment-216945267

**Comment by gauravbrills** [comment]
Ohh sorry for the confusion let me do the same .. That caused the confusion

**Comment by gauravbrills** [comment]
HI @manikandanrs one small query I was making some changes .One advice so should we also include clientconfiguration to be configured via AwsSdkMetrics also so it can be customized without say overriding the collecotor ..For default impln it could be something like 
`public MetricCollector getInstance() {
        AWSCredentialsProvider provider = AwsSdkMetrics.getCredentialProvider();
        Regions region = AwsSdkMetrics.getRegion();
        Integer qSize = AwsSdkMetrics.getMetricQueueSize();
        Long timeoutMilli = AwsSdkMetrics.getQueuePollTimeoutMilli();
        CloudWatchMetricConfig config = new CloudWatchMetricConfig();
        ClientConfiguration clientConfig = new ClientConfiguration();
        if (provider != null)
            config.setCredentialsProvider(provider);
        if (region != null) {
            String endPoint = "monitoring." + region.getName() + ".amazonaws.com";
            config.setCloudWatchEndPoint(endPoint);
        }
        if (qSize != null)
            config.setMetricQueueSize(qSize.intValue());
        if (timeoutMilli != null)
            config.setQueuePollTimeoutMilli(timeoutMilli.longValue());
        config.setClientConfiguration(clientConfig);
        MetricCollectorSupport.startSingleton(config);
        return MetricCollectorSupport.getInstance();
    }`

**Comment by manikandanrs** [comment]
Ya. I like that. Go ahead and send the PR. I will take a look at it.

**Comment by gauravbrills** [comment]
sure also I guess AmazonCloudWatchClient could do with a builder implementation .

**Comment by gauravbrills** [comment]
PR merged closing the issue
