### ISSUE TITLE
S3 doesObjectExist throws Forbidden instead of returning False

### ISSUE THREAD

**Issue by sergproua** [aws/aws-sdk-java#707]
Recently got 1.10.75 and tried using doesObjectExist getting exception instead of just False when object does not exist.

com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: A8565CE6E42ECDB3), S3 Extended Request ID: L5ezGGtIa86KACyXKjNWnGHSDP+JtjRPAI7rZr1S0U9p07zY8pvKic6nsw9GgiVANVK1Ohj5BBk=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1015)
	at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:991)
	at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1050)

**Comment by varunnvs92** [comment]
@sergproua 
According to the [docs](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html), the 403 Forbidden code returned mostly for AWS account related issues like credentials not properly set, AWS account not activated, InvalidObjectState etc.

Did you try to do any other operations like creating the bucket, uploading....? Were they successful?
Can you provide information related to the object like how it was created, any restrictions on the object.
It would be helpful if you can share the code if that's okay.

Thanks!

**Comment by manikandanrs** [comment]
Do you have permissions to access the object ?

**Comment by sergproua** [comment]
Yes, I have a fully functional application uploading objects to S3 bucket on a regular basis.  I've added new feature to prevent overrides if object with a key already exists using this method which returns Exception instead of a False when object doesn't exist, it returns True when it does. I'm putting together a small test case and post here later today.

**Comment by sergproua** [comment]
My bad, just found a problem, account does not have permission to access object's metadata causing Forbidden response.
