### ISSUE TITLE
ProfileCredentialsProvider fails if credentials file has a profile with an assume role configuration

### ISSUE THREAD

**Issue by dstainer** [aws/aws-sdk-java#726]
I have a credentials file that has the following profiles:

```` 
[profile1]
aws_access_key=BLAHBLAH
aws_secret_access_key=MOREBLAH

[profile2]
role_arn=arn:aws:iam::OTHER_AWS_ACCOUNT_ID:role/FakeRole
source_profile=profile1
````

When using the command line and specifying ````profile2```` it allows me to assume a role into another AWS account to perform actions allowed by FakeRole in that other account. In this case I'm using it to sync to a particular S3 (think poor man's dropbox)

However, when I'm running my application I want to use ````profile1```` and programmatically assume a different role to write files into S3.

The issue is with the ````ProfileCredentialsProvider````, when I attempt to load a ````credentials```` file with the following setup I get an exception:

````
Caused by: com.amazonaws.AmazonClientException: Unable to load credentials into profile [profile2]: AWS Access Key ID is not specified.
	at com.amazonaws.auth.profile.internal.ProfilesConfigFileLoader.loadProfiles(ProfilesConfigFileLoader.java:92)
	at com.amazonaws.auth.profile.internal.ProfilesConfigFileLoader.loadProfiles(ProfilesConfigFileLoader.java:53)
````

Now the assume role setup described above is supported in the CLI configuration (http://docs.aws.amazon.com/cli/latest/topic/config-vars.html)

Not sure if it's a configuration you want to support in the SDK, my only thought is since the configuration values are valid, the file should parse correctly. However, the profile that assumes another role should not be selectable. 

Couple of notes:

* Version tested 1.11.5
* There are workarounds in terms of specifying the specific credential file, that excludes the assume role profile, to use for the ````ProfileCredentialsProvider````
* This is just an issue I'm running into on my development machine during feature development, we use the ````InstanceProfileCredentialsProvider```` in a deployed setting

**Comment by dstainer** [comment]
I apologize, I updated my dependencies and it didn't take. The latest version handles this correctly. Apologize for the waste of time.
