### ISSUE TITLE
Cannot upload log files that are being appended to during upload

### ISSUE THREAD

**Issue by pako-pl** [aws/aws-sdk-java#749]
It's impossible to upload files that are being appended to during upload. AWS SDK throws an exception when it detects that the file length changed during an upload. It's a safe approach, as it cannot know what parts of the file changed. 

But is there a way to work around this behaviour when I know that the files only get appended to? Otherwise I cannot use AWS SDK Java to upload log files at all. It doesn't matter if the most recently appended data gets uploaded or not, as long as the rest of the file gets safely stored in S3.

```
Exception in thread "main" com.amazonaws.AmazonClientException: More data read than expected: dataLength=48170; expectedLength=47956; includeSkipped=false; in.getClass()=class com.amazonaws.internal.ReleasableInputStream; markedSupported=false; marked=0; resetSinceLastMarked=false; markCount=0; resetCount=0
        at com.amazonaws.util.LengthCheckInputStream.checkLength(LengthCheckInputStream.java:155)
        at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:110)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:72)
        at com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream.read(MD5DigestCalculatingInputStream.java:98)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at com.amazonaws.internal.SdkBufferedInputStream.read(SdkBufferedInputStream.java:76)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:72)
        at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:151)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:72)
        at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:138)
        at com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:153)
        at org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:89)
        at org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
        at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:117)
        at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:265)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:203)
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:236)
        at com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
        at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:837)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3654)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1354)
        ...
```

**Comment by shorea** [comment]
I think you should be able to supply your own input stream and pass the content length ahead of time. For example you would calculate the content length from the current size of the file and use that in your input stream implementation to read that number of bytes (ignoring any bytes that were appended after you started the upload). Alternatively you can also copy the file to a temp location, in essence taking a snapshot of the file, and upload that.

**Comment by manikandanrs** [comment]
No response. Closing this issue. Feel free to reopen

**Comment by pako-pl** [comment]
I'll try the approach with supplying my own InputStream with fixed content length. Thanks for the suggestion.

**Comment by OndraZizka** [comment]
We see the same error - feeding an InputStream from URLConnection to the SDK leads to this error.
