### ISSUE TITLE
com.amazonaws.services.kinesis.AmazonKinesisClient.createStream: java.net.SocketException: Permission denied: connect

### ISSUE THREAD

**Issue by small-wang** [aws/aws-sdk-java#784]
Exception raised when call AmazonKinesisClient to create stream:

> java.net.SocketException: Permission denied: connect
at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:579)
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625)
at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:524)
at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
at com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:128)
at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:728)
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:489)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:310)
at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2490)
at com.amazonaws.services.kinesis.AmazonKinesisClient.createStream(AmazonKinesisClient.java:483)

exampls:
BasicAWSCredentials awsCreds = new BasicAWSCredentials(ak, sk);
AmazonKinesisClient client = new AmazonKinesisClient(awsCreds);
client.setEndpoint("kinesis.ap-northeast-2.amazonaws.com", "kinesis", "ap-northeast-2");
CreateStreamRequest createStreamRequest = new CreateStreamRequest();
createStreamRequest.setStreamName("myStreamName");
createStreamRequest.setShardCount(5);
client.createStream(createStreamRequest);

Ping to endpoint is ok:
ping kinesis.ap-northeast-2.amazonaws.com

**Comment by shorea** [comment]
Seems like the user running you're application doesn't have the appropriate system permissions.

**Comment by shorea** [comment]
Closing issue. Feel free to reopen if the problem persists.
