### ISSUE TITLE
OpsWorks: Documentation bug for CustomJson parameter on CreateDeployment action?

### ISSUE THREAD

**Issue by hopel** [aws/aws-sdk-java#791]
The [JavaDoc entries for the CustomJson parameter](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-opsworks/src/main/java/com/amazonaws/services/opsworks/model/CreateDeploymentRequest.java#L66) state that:

> [...] The string should be in the following format and must escape characters such as '"': [...]

However, applying such an escaping reliably results in a ValidationException:

```
com.amazonaws.services.cloudformation.model.AlreadyExistsException: Stack [taws-it290-41-ubot] already exists (Service: AmazonCloudFormation; Status Code: 400; Error Code: AlreadyExistsException; Request ID: e6232658-540d-11e6-8ee0-fbc06d2d1322)
		at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1379)
		at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:925)
		at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:703)
		at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:455)
		at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:417)
		at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:366)
		at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.doInvoke(AmazonCloudFormationClient.java:1637)
		at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.invoke(AmazonCloudFormationClient.java:1607)
		at com.amazonaws.services.cloudformation.AmazonCloudFormationClient.createStack(AmazonCloudFormationClient.java:518)
```

If I do _not_ escape the JSON string, the call goes through as desired.

Could this be a documentation bug?

(Note: The exact same instructions are given in the [API Reference documentation for the CustomJson parameter](http://docs.aws.amazon.com/opsworks/latest/APIReference/API_CreateDeployment.html#opsworks-CreateDeployment-request-CustomJson), as well as in the [respective entry for the AWS CLI](http://docs.aws.amazon.com/cli/latest/reference/opsworks/create-deployment.html), hence I assume this comes from code generation and is not specific to the Java SDK - just not sure where best to report this.)

**Comment by shorea** [comment]
Yeah this is unfortunate. The docs are coming from the API docs themselves, and on the wire you of course need to escape the JSON since it's embedded within JSON document. All SDK and tools actually handle this though as part of abstracting out the wire protocol so it's definitely misleading. I'll pass this feedback to the service team to see if there's a way to disambiguate the docs or add a disclaimer that this is not applicable when using an official AWS SDK.
