### ISSUE TITLE
`AmazonS3Client.getObjectMetadata` fails for bucket in other region

### ISSUE THREAD

**Issue by sebastiankirsch** [aws/aws-sdk-java#795]
We encounter this exception when fetching the metadata for an S3 bucket that resides in another region than our `AmazonS3Client` is set up with:

    com.amazonaws.services.s3.model.AmazonS3Exception: Moved Permanently (Service: Amazon S3; Status Code: 301; Error Code: 301 Moved Permanently; Request ID: 1BEA69C8759690E3)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1401)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:945)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:723)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:475)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:437)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:386)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3996)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1161)
        at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1136)

It is very inconvenient to set up an instance of `AmazonS3Client` for each and every region we deal with.

**Comment by manikandanrs** [comment]
This error is thrown by [Amazon S3](http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html). While talking with AWS services you will need to specify the correct region where the resource exists. Java SDK by default uses US-EAST-1 as the region for all services and for S3, we default to US-STANDARD. 

There are two suggestion that I could think of 

1. You can look at creating a cache that caches the s3 client for every region. This way the cache can maintain the client creation, setting up region on it and caching.
2. Java SDK introduced bucket caching logic in 1.11.x series. i.e., we make a preemptive HEAD bucket request that would return the correct bucket region. This bucket region is then cached and used later for all API calls to that bucket. You will have an additional overhead of an HEAD call every time a new bucket is encountered with this. The bucket caching logic is turned on when there is no region set on the client.

**Comment by sebastiankirsch** [comment]
Why not follow the redirect?
Using the client with region x, I can copy a file from region y to region x as well, so I can access resources outside of the configured region without interfering. Why not enable it for this use case?
If not in general, maybe by offering `GetObjectMetadataRequest.setFollowRedirects` or similar?

**Comment by shorea** [comment]
"It is very inconvenient to set up an instance of AmazonS3Client for each and every region we deal with."
We recommend this as a best practice. The current signing algorithm used by AWS services requires the region context so it's best to create a client per region you are talking to.

We follow temporary redirects but moved permanently we do not. Temporary redirects I wish we didn't follow because it appears to work for a while but once DNS entries propagate it starts failing.

**Comment by varunnvs92** [comment]
Closing due to no activity. Feel free to re-open if you have more questions.
