### ISSUE TITLE
java.net.UnknownHostException

### ISSUE THREAD

**Issue by tee33** [aws/aws-sdk-java#813]
016-08-15T10:15:42.76-0700 [APP/1]      OUT java.net.UnknownHostException:
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[na:1.8.0_71-]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[na:1.8.0_71-]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) ~[aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) ~[aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[na:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[na:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.conn.$Proxy90.connect(Unknown Source) ~[na:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.conn.$Proxy90.connect(Unknown Source) ~[na:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient-4.5.1.jar!/:4.5.1]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:787) [aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:787) [aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630) [aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:630) [aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405) [aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:405) [aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367) [aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:367) [aws-java-sdk-core-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3787) [aws-java-sdk-s3-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3787) [aws-java-sdk-s3-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1264) [aws-java-sdk-s3-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1264) [aws-java-sdk-s3-1.11.7.jar!/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.corelogic.clp.documentservice.api.S3DocumentRepositoryImpl.save(S3DocumentRepositoryImpl.java:32) [app/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.corelogic.clp.documentservice.api.S3DocumentRepositoryImpl.save(S3DocumentRepositoryImpl.java:32) [app/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.corelogic.clp.documentservice.api.DocumentsController.create(DocumentsController.java:53) [app/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.corelogic.clp.documentservice.api.DocumentsController.create(DocumentsController.java:53) [app/:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source) ~[na:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source) ~[na:na]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814) [spring-webmvc-4.2.4.RELEASE.jar!/:4.
2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814) [spring-webmvc-4.2.4.RELEASE.jar!/:4.
2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.R
ELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.R
ELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at javax.servlet.http.HttpServlet.service(HttpServlet.java:648) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845) [spring-webmvc-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.0.30.jar!/:8.0.30]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.0.30.jar!/:8.0.30]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [tomcat-embed-core-8.0.30.jar!/:8.0.30]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.corelogic.clp.logging.EnvironmentLoggingFilter.doFilter(EnvironmentLoggingFilter.java:42) [clp-logging-0.0.2.jar!/:na]  
2016-08-15T10:15:42.76-0700 [APP/1]      OUT    at com.corelogic.clp.logging.EnvironmentLoggingFilter.doFilter(EnvironmentLoggingFilter.java:42) [clp-logging-0.0.2.jar!/:na]

**Comment by spfink** [comment]
Can you please add additional details as to what your use case is here?

It looks like you are calling S3.putObject. Which version of the SDK are you using? Which region are you attempting to hit? Are you using any additional S3 options such as dualstack or accelerate?

**Comment by tee33** [comment]
Thank you.

com.amazonaws:aws-java-sdk-core:1.11.7
com.amazonaws:aws-java-sdk-s3:1.11.7

The majority are default settings.

Thanks

**Comment by spfink** [comment]
Are you using any non-default settings? If so, can you please let us know what they are. 

Which endpoint and region are you attempting to call?

**Comment by tee33** [comment]
We are using an internal hosted emc ecs s3.   We have the endpoint s3.corelogic.net, and not region.

And what strange is a test go through without any issue, and run the same test, it failed with unknownhost exception.

Thanks.

**Comment by spfink** [comment]
Are you saying that the same test both passes and succeeds or that this test always fails and others that test your S3 logic succeed?

Can you ping your internal hostname and verify it resolves correctly?

**Comment by tee33** [comment]
Correct, and the strange this is that if we scale down the instance using PcF, from 2 instances to 1, we do not run into issue.
When we scale back to 2 instances, the issue occured immediately.

Thanks,

Thyya

**Comment by spfink** [comment]
Are you able to ping the internal hostname through terminal/command line when there are two hosts behind it?

When you scale to two instances are both hosts up and accessible behind the internal hostname? Are the hosts being correctly added behind any firewalls or proxies you might have in your local network?

**Comment by tee33** [comment]
Yes, and it’s resolvable internally.

Thanks.

**Comment by spfink** [comment]
For additional clarification you said correct to the following question I had:

"Are you saying that the same test both passes and succeeds or that this test always fails and others that test your S3 logic succeed?"

Is your case related to the first or second part of that statement? Are you able to use this custom endpoint for any requests to S3? Are you using DNS or path style bucket access?

**Comment by tee33** [comment]
Using jmeter to inject 300 requests:
When, having 2 instances, it is intermittently failing posting to the s3.corelogic.net, could it be some contention, if one already writing, and another is trying to write it at the same time?

When having only one instance of the app up, it does not fail.

Thanks.

**Comment by spfink** [comment]
All the SDK is doing here is calling InetAddress.getAllByName() so there should not be any issue with contention at that level or with S3 itself as your request is failing before making the request out.

Can you run at a high rate for a single host without issue? Can you verify by adding additional logging that the hostname that is attempting to be resolved is the correct hostname?

We are unable to reproduce this issue on our side.

**Comment by tee33** [comment]
with one instance, no issue.   with two instances, will fail.  
so, i ssh into the two instances, and check that is is resolving correctly, and the ip has not changed.  okay, thanks, will let you know as we do more testing.

**Comment by dagnir** [comment]
Closing this issue due to inactivity. Please feel free to re-open if you are still experiencing further issues with this.

**Comment by caldwecr** [comment]
Recently encountered an issue that seems related to this particular GitHub issue.

Circumstance is a full redundant network in the midst of a true partition event. Access to EC2 was lost to some users within organization. (around 2018-03-02). After partition event was resolved user connectivity issues to EC2 resolved, but our existing Scala process (running the java-sdk) was unable to recover - this went on for at least 5 hours. However stopping the process and starting it again immediately restored the connectivity.

The relevant part of the stack traces:

```
Caused by: java.net.UnknownHostException: ec2.us-east-1.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280) ~[na:1.8.0_131]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[na:1.8.0_131]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[na:1.8.0_131]
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27) ~[com.amazonaws.aws-java-sdk-core-1.11.129.jar:na]
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) ~[com.amazonaws.aws-java-sdk-core-1.11.129.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111) ~[org.apache.httpcomponents.httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[org.apache.httpcomponents.httpclient-4.5.2.jar:4.5.2]
	at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[com.amazonaws.aws-java-sdk-core-1.11.129.jar:na]
	at com.amazonaws.http.conn.$Proxy25.connect(Unknown Source) ~[na:na]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[org.apache.httpcomponents.httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[org.apache.httpcomponents.httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[org.apache.httpcomponents.httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[org.apache.httpcomponents.httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[org.apache.httpcomponents.httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[org.apache.httpcomponents.httpclient-4.5.2.jar:4.5.2]
	at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[com.amazonaws.aws-java-sdk-core-1.11.129.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1190) ~[com.amazonaws.aws-java-sdk-core-1.11.129.jar:na]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030) ~[com.amazonaws.aws-java-sdk-core-1.11.129.jar:na]
	... 47 common frames omitted
2018-03-03 20:46:52,328 level=ERROR *OBFUSCATED*
com.amazonaws.SdkClientException: Unable to execute HTTP request: ec2.us-east-1.amazonaws.com
```

**Comment by Beauclair** [comment]
@spfink  @dagnir I think I have similar issue 

My sample application is host on Google cloud platform and try to get the list of objects from Amazon S3. 
Locally (Running in my laptop) it is working fine, but when I deployed it in GCP, I'm having this error : 

com.amazonaws.SdkClientException: Unable to execute HTTP request: mybucket.s3.us-east-2.amazonaws.com
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException (AmazonHttpClient.java:1175)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper (AmazonHttpClient.java:1121)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute (AmazonHttpClient.java:770)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer (AmazonHttpClient.java:744)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute (AmazonHttpClient.java:726)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500 (AmazonHttpClient.java:686)
at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute (AmazonHttpClient.java:668)
at com.amazonaws.http.AmazonHttpClient.execute (AmazonHttpClient.java:532)
at com.amazonaws.http.AmazonHttpClient.execute (AmazonHttpClient.java:512)
at com.amazonaws.services.s3.AmazonS3Client.invoke (AmazonS3Client.java:4921)
at com.amazonaws.services.s3.AmazonS3Client.invoke (AmazonS3Client.java:4867)
at com.amazonaws.services.s3.AmazonS3Client.invoke (AmazonS3Client.java:4861)
at com.amazonaws.services.s3.AmazonS3Client.listObjects (AmazonS3Client.java:880)
at com.amazonaws.services.s3.AmazonS3Client.listObjects (AmazonS3Client.java:848)
at com.mybucket.training.services.AmazonS3Services.getObjects (AmazonS3Services.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke (Method.java:498)
at com.google.api.server.spi.SystemService.invokeServiceMethod (SystemService.java:351)
at com.google.api.server.spi.handlers.EndpointsMethodHandler$RestHandler.handle (EndpointsMethodHandler.java:119)
at com.google.api.server.spi.handlers.EndpointsMethodHandler$RestHandler.handle (EndpointsMethodHandler.java:102)
at com.google.api.server.spi.dispatcher.PathDispatcher.dispatch (PathDispatcher.java:50)
at com.google.api.server.spi.EndpointsServlet.service (EndpointsServlet.java:71)
at javax.servlet.http.HttpServlet.service (HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:848)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1772)
at com.google.api.control.ControlFilter.doFilter (ControlFilter.java:225)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1759)
at com.google.api.control.ConfigFilter.doFilter (ConfigFilter.java:120)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1759)
at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter (JdbcMySqlConnectionCleanupFilter.java:60)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1759)
at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:582)
at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:524)
at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:226)
at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:134)
at com.google.apphosting.runtime.jetty9.ParseBlobUploadHandler.handle (ParseBlobUploadHandler.java:119)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1182)
at com.google.apphosting.runtime.jetty9.AppEngineWebAppContext.doHandle (AppEngineWebAppContext.java:187)
at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:512)
at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1112)
at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
at com.google.apphosting.runtime.jetty9.AppVersionHandlerMap.handle (AppVersionHandlerMap.java:293)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:134)
at org.eclipse.jetty.server.Server.handle (Server.java:539)
at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:333)
at com.google.apphosting.runtime.jetty9.RpcConnection.handle (RpcConnection.java:213)
at com.google.apphosting.runtime.jetty9.RpcConnector.serviceRequest (RpcConnector.java:81)
at com.google.apphosting.runtime.jetty9.JettyServletEngineAdapter.serviceRequest (JettyServletEngineAdapter.java:134)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchServletRequest (JavaRuntime.java:728)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest (JavaRuntime.java:691)
at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run (JavaRuntime.java:661)
at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run (JavaRuntime.java:853)
at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run (ThreadGroupPool.java:270)
at java.lang.Thread.run (Thread.java:748)
Caused by: java.net.UnknownHostException: mybucket.s3.us-east-2.amazonaws.com
at java.net.InetAddress.getAllByName0 (InetAddress.java:1282)
at java.net.InetAddress.getAllByName (InetAddress.java:1194)
at java.net.InetAddress.getAllByName (InetAddress.java:1128)
at com.amazonaws.SystemDefaultDnsResolver.resolve (SystemDefaultDnsResolver.java:27)
at com.amazonaws.http.DelegatingDnsResolver.resolve (DelegatingDnsResolver.java:38)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect (DefaultHttpClientConnectionOperator.java:112)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect (PoolingHttpClientConnectionManager.java:373)
at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke (Method.java:498)
at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke (ClientConnectionManagerFactory.java:76)
at com.amazonaws.http.conn.$Proxy26.connect (Unknown Source)
at org.apache.http.impl.execchain.MainClientExec.establishRoute (MainClientExec.java:394)
at org.apache.http.impl.execchain.MainClientExec.execute (MainClientExec.java:237)
at org.apache.http.impl.execchain.ProtocolExec.execute (ProtocolExec.java:185)
at org.apache.http.impl.client.InternalHttpClient.doExecute (InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute (CloseableHttpClient.java:56)
at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute (SdkHttpClient.java:72)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest (AmazonHttpClient.java:1297)
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper (AmazonHttpClient.java:1113)
