### ISSUE TITLE
NoSuchMethod error with HttpClient : aws-sdk-java : 1.11.27

### ISSUE THREAD

**Issue by mukteshkrmishra** [aws/aws-sdk-java#816]
Hi, 

I am getting following error while trying to use aws-java-sdk for making a call to SQS queue. Looks like http client version is not correct. I have manually corrected the http client version. Please have a look on this.

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.http.impl.conn.CPool.setValidateAfterInactivity(I)V
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:176)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:158)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:73)
	at com.amazonaws.http.apache.client.impl.ApacheConnectionManagerFactory.create(ApacheConnectionManagerFactory.java:58)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:51)
	at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:39)
	at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:282)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:164)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:153)
	at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:138)
	at com.amazonaws.services.sqs.AmazonSQSClient.<init>(AmazonSQSClient.java:231)
	at TestApp.TestApp.TestInfluxWrite.main(TestInfluxWrite.java:39)

**Comment by shorea** [comment]
What does your pom look like (before the workaround of adding the HTTP client version)?

**Comment by mukteshkrmishra** [comment]
for http client and core  I was having dependencies 4.5.2 added.

**Comment by shorea** [comment]
Do you mind sharing your pom?

**Comment by shorea** [comment]
@mukteshkrmishra would you mind sharing your pom or a snippet of it?

**Comment by shorea** [comment]
Closing this issue for now. Feel free to reopen if the problem persists.
