### ISSUE TITLE
getCurrentRegion() fails with NoSuchFieldError exception

### ISSUE THREAD

**Issue by sbanacho** [aws/aws-sdk-java#835]
I have an application running in an ECS container.  When it calls Regions.getCurrentRegion(), a NoSuchFieldError exception is thrown.

I am using 1.11.30 aws-sdk-java.

java.lang.NoSuchFieldError: ALLOW_FINAL_FIELDS_AS_MUTATORS
        at com.amazonaws.partitions.PartitionsLoader.<clinit>(PartitionsLoader.java:52) ~[aws-java-sdk-core-1.11.30.jar:na]
        at com.amazonaws.regions.RegionMetadataFactory.create(RegionMetadataFactory.java:30) ~[aws-java-sdk-core-1.11.30.jar:na]
        at com.amazonaws.regions.RegionUtils.initialize(RegionUtils.java:66) ~[aws-java-sdk-core-1.11.30.jar:na]
        at com.amazonaws.regions.RegionUtils.getRegionMetadata(RegionUtils.java:54) ~[aws-java-sdk-core-1.11.30.jar:na]
        at com.amazonaws.regions.RegionUtils.getRegion(RegionUtils.java:107) ~[aws-java-sdk-core-1.11.30.jar:na]
        at com.amazonaws.regions.Regions.getCurrentRegion(Regions.java:86) ~[aws-java-sdk-core-1.11.30.jar:na]
        at com.pepperdata.tsd.SqsConsumer.connect(SqsConsumer.java:334) ~[pdmetric-inserter-0.0.22-SNAPSHOT.jar:na]

**Comment by dagnir** [comment]
Hi @sbanacho, the stacktrace is almost exactly like the one provided at the bottom of #528. See if you can verify that a compatible version of `jackson-databind` is being loaded by your JVM; as of today, the SDK [uses version 2.6.6](https://github.com/aws/aws-sdk-java/blob/5c1ba30976a73f60dce12c0d98c07f7f4518c952/pom.xml#L117)

**Comment by sbanacho** [comment]
Yes, it appears that the jackson library is the issue.  Thanks.

**Comment by dagnir** [comment]
Cool! Glad that fixed it for you.

**Comment by rosedawson75** [comment]
@sbanacho 
I am facing the same issue in a standalone java program. What change you have done exactly? Actually I am using "com.fasterxml.jackson.databind.jar" , Do I need to take update of the jar ?

Need your help here ?

**Comment by sbanacho** [comment]
@rosedawson75 Yes, I had to update the version of jackson-databind I was using to a more recent version.  More specifically, my project had a dependency on the jackson libraries (jackson-databind, jackson core, etc.), so I just updated all of them in my maven file.

**Comment by abhilash1994** [comment]
Need some help here,

I am facing the same issue, I am using aws-java-sdk-1.11.443.
My jackson-core version is 2.6.7 and jackson-databind version is 2.6.7.1
