### ISSUE TITLE
Discrepancy between TransferManager's parallel and single-part downloads.

### ISSUE THREAD

**Issue by pbruski** [aws/aws-sdk-java#853]
For com.amazonaws.services.s3.transfer.TransferManager#download(com.amazonaws.services.s3.model.GetObjectRequest, java.io.File), when the destination directory of a file does not exist, single-part download will create one in the first lines of: com.amazonaws.services.s3.internal.ServiceUtils#downloadToFile

A multi-part parallel download will fail when attempting to lock that file when combining the parts:
```
com.amazonaws.services.s3.transfer.exception.FileLockException: java.io.FileNotFoundException: /tmp/non_existing_subdir/zero (No such file or directory)
	at com.amazonaws.services.s3.internal.FileLocks.lock(FileLocks.java:76)
	at com.amazonaws.services.s3.transfer.DownloadCallable.truncateDestinationFileIfNecessary(DownloadCallable.java:222)
	at com.amazonaws.services.s3.transfer.DownloadCallable.combineFiles(DownloadCallable.java:200)
	at com.amazonaws.services.s3.transfer.DownloadCallable.downloadInParallel(DownloadCallable.java:193)
	at com.amazonaws.services.s3.transfer.DownloadCallable.call(DownloadCallable.java:131)
	at com.amazonaws.services.s3.transfer.DownloadCallable.call(DownloadCallable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /tmp/non_existing_subdir/zero (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at com.amazonaws.services.s3.internal.FileLocks.lock(FileLocks.java:70)
	... 9 more

```
Either of these behaviours could be considered correct (with the single-part behaviour being the more user-friendly one), but they should stay consistent.
I don't think there's a choice other than implementing the dir creation in parallel download, the other option (removing parent dir creation) will certainly break user workflows.

**Comment by kiiadi** [comment]
Out of interest when did this start becoming a problem? Was it after the most recent release (1.11.37) ?

**Comment by pbruski** [comment]
It's not the latest release, we've upgraded from 1.10.50 to 1.11.29 and that's when the problem started happening.

**Comment by kiiadi** [comment]
See comments on #854 but if you upgrade to 1.11.37 you shouldn't need this.

**Comment by kiiadi** [comment]
Re-opening based on comments on #854 - sounds like we need to pull the parent directory creation up to [DownloadCallable#downloadInParallel](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/DownloadCallable.java#L172) - rather than in [DownloadCallable#combineFiles](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/DownloadCallable.java#L198)

I had (incorrectly) assumed that File.createTempFile just created the file destination rather than creating an actual file on disk - quick test showed that wasn't the case. So you're right we need to ensure the directory is created before we do anything with the FS (ie: creating temp files, downloading parts, combining etc).

Have opened PR #859
