### ISSUE TITLE
putIntegration is failing with error 

### ISSUE THREAD

**Issue by srinikandula** [aws/aws-sdk-java#860]
I'm using aws-apigateway-java-sdk 1.1.1. I'm using the below code to set up integration for a method that I created in apigateway.

```
private void createIntegration(com.amazonaws.services.apigateway.model.Method method) {
        Map<String, String> integ = new HashMap<>();
        integ.put("application/json", "{reqId:$context.requestId}");
        PutIntegrationInput input = new PutIntegrationInput()
                .withType(IntegrationType.HTTP)
                .withUri("http://localhost:8080/")
                .withCredentials("NONE")
                .withHttpMethod(method.getHttpMethod())
                .withRequestTemplates(integ)
                .withCacheNamespace(getStringValue(integ.get("cacheNamespace")));
        
        Integration integration = method.putIntegration(input);

        //createIntegrationResponses(integration, new HashMap<>());
    }
```
This piece of code fails with the below error.

```
com.amazonaws.services.apigateway.model.BadRequestException: Invalid ARN specified in the request (Service: null; Status Code: 400; Error Code: null; Request ID: a93eadb4-85e9-11e6-a108-6b65190e25f2)
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
	at com.amazonaws.hal.client.HalClient.invoke(HalClient.java:235)
	at com.amazonaws.hal.client.HalClient.putResource(HalClient.java:122)
	at com.amazonaws.hal.client.HalResourceInvocationHandler.invoke(HalResourceInvocationHandler.java:125)
	at com.sun.proxy.$Proxy37.putIntegration(Unknown Source)
```

Can somebody help me to identify what I'm doing wrong?

**Comment by shorea** [comment]
Do you mind opening an issue here https://github.com/awslabs/aws-apigateway-sdk-java. I'm not familiar with this particular client.

I wouldn't imagine the localhost integration to be valid though. I believe it would need to a remote endpoint.
