### ISSUE TITLE
s3 SDK 1.11.22 transfermanager upload resulting java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by gqian3** [aws/aws-sdk-java#862]
We are experiencing some strange AWS JAVA SDK s3 transfer manager issue where we are getting java.util.concurrent.RejectedExecutionException during s3 transfermanager upload. Basically what we are doing is to create transfermanager to transfer a list of files, however after the list has reach to certain amount, say 10 files. Uploading the any more file in the list will always fail with java.util.concurrent.RejectedExecutionException from the transfer manager. 

This happens only when we upgrade to one of latest JAVA SDK
aws-java-sdk-s3-1.11.22.jar
And the code works perfectly fine with older version:
aws-java-sdk-1.4.2.1

This is some code code snippet: 
final ThreadPoolExecutor executorService; 
(ThreadPoolExecutor) Executors.newFixedThreadPool(10, threadFactory)
tm = new TransferManager(s3Client, executorService); 
final PutObjectRequest putObjectRequest = new PutObjectRequest(bucketName, key, createFile(file.getAbsolutePath())); 
final ObjectMetadata object_metadata = new ObjectMetadata(); putObjectRequest.setMetadata(object_metadata); 
Upload upload = tm.upload(putObjectRequest);

And this is the exception we got: exception = java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@71ac5723 rejected from java.util.concurrent.ThreadPoolExecutor@2fa3be26[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@71ac5723 rejected from java.util.concurrent.ThreadPoolExecutor@2fa3be26[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0] at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047) at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823) at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369) at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) at com.amazonaws.services.s3.transfer.internal.UploadMonitor.create(UploadMonitor.java:120) at com.amazonaws.services.s3.transfer.TransferManager.doUpload(TransferManager.java:642) at com.amazonaws.services.s3.transfer.TransferManager.upload(TransferManager.java:491) 

Is there some behavior changes of AWS S3 JAVA SDK causing this regression happen.

**Comment by varunnvs92** [comment]
I was not able to reproduce the issue with v1.11.22. Can you share few more details like code for thread factory, average object sizes and if possible test code to repo the issue.

Can you create Transfermanager without your custom executor service and see if the issue exists. If the user do not provide a executorService, we create a thread pool using this code.
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/transfer/internal/TransferManagerUtils.java#L44-L56
Even this uses 10 threads, so I want to see if this will reproduce the error or not.

**Comment by hasnickl** [comment]
recently had this issue, using the default threadpool in transfer manager: ```tm = new TransferManager(s3)```

The only difference is I was doing a download instead of an upload. stacktrace:
```
"java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@36de6b5d rejected from java.util.concurrent.ThreadPoolExecutor@49a04104[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at com.amazonaws.services.s3.transfer.TransferManager.doDownload(TransferManager.java:825)
	at com.amazonaws.services.s3.transfer.TransferManager.download(TransferManager.java:691)
	at com.amazonaws.services.s3.transfer.TransferManager.download(TransferManager.java:654)
```

issue is difficult to replicate consistently. downloading about 50k files resulted in this error 4 times. i worked around this by catching the exception and trying again with a new TransferManager

aws-java-sdk version is 1.10.59. 

perhaps i was abusing the transfermanager, but I create a new one for every download, so there can't be a race on my end around a terminated pool

**Comment by varunnvs92** [comment]
@hasnickl 
RejectedExecutionException generally occurs in one of the following cases:
1) When we try to submit a new task after shutdown has been called on ExecutorService.
2) When the blocking queue is full and can't queue more tasks.
Useful link:
https://examples.javacodegeeks.com/core-java/util/concurrent/rejectedexecutionexception/java-util-concurrent-rejectedexecutionexception-how-to-solve-rejectedexecutionexception/

As you are using the default executorService provided by SDK which uses LinkedBlockingQueue to place pending tasks. LinkedBlockingQueue is unbounded and is only limited by JVM memory. Is it possible that your application is using the entire JVM memory and there is not enough space to place new tasks? Also make sure that you are not submitting new tasks after calling shutdown on TransferManager .

**Comment by varunnvs92** [comment]
@gqian3 
Please upgrade to latest version in 1.11.x and see if the error occurs. If so, provide me the details asked in my first correspondence. Thank you.

**Comment by varunnvs92** [comment]
Any updates?

**Comment by varunnvs92** [comment]
Closing due to inactivity. Feel free to reopen if the problem still exists.
