### ISSUE TITLE
JsonMappingException when a Python-implemented Lambda function returns a stack trace

### ISSUE THREAD

**Issue by ecdavis** [aws/aws-sdk-java#866]
I have a Lambda function implemented in Python and a client implemented in Java. When an exception is raised in the Lambda function, the stack trace is JSON-serialized and returned to the client.

The problem: when the stack trace is JSON-serialized in Python the line numbers are serialized as integers. For example, this output copied directly from the AWS console after executing a test on my function:

```json
 "stackTrace": [
    [
      "/var/task/lambda_function.py",
      123,
      "lambda_handler",
      "raise Exception(\"An internal error occurred.\")"
    ]
  ],
```
However, the `LambdaFunctionError` class expects the stack trace to be an instance of `List<String>`. When the client receives the stack trace above and tries to deserialize it, it fails with the following error:

```
WARNING: Error parsing exception information from response payload
com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: [B@460ebd80; line: 1, column: 17] (through reference chain: com.amazonaws.services.lambda.invoke.LambdaFunctionError["stackTrace"]->java.util.ArrayList[0])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:857)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:846)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:190)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:161)
	at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:19)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1511)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1153)
	at com.amazonaws.services.lambda.invoke.LambdaInvokerFactory$LambdaInvocationHandler.getObjectFromPayload(LambdaInvokerFactory.java:331)
	at com.amazonaws.services.lambda.invoke.LambdaInvokerFactory$LambdaInvocationHandler.getObjectFromPayload(LambdaInvokerFactory.java:320)
	at com.amazonaws.services.lambda.invoke.LambdaInvokerFactory$LambdaInvocationHandler.getExceptionFromPayload(LambdaInvokerFactory.java:238)
	at com.amazonaws.services.lambda.invoke.LambdaInvokerFactory$LambdaInvocationHandler.processInvokeResult(LambdaInvokerFactory.java:205)
	at com.amazonaws.services.lambda.invoke.LambdaInvokerFactory$LambdaInvocationHandler.invoke(LambdaInvokerFactory.java:123)
```

I don't know whether this is an issue with the SDK or Lambda itself, but it seems like it should be possible to handle exceptions from a Python lambda in a Java client.

**Comment by shorea** [comment]
I have a fix for this. Hoping to get it out today.

**Comment by shorea** [comment]
This made it in for the release today so it should be available later this afternoon. I'm preemptively closing this issue. Thanks for bringing this to our attention and if you have any other feedback about the Lambda Invoker utility or the SDK in general we'd love to hear it!

**Comment by ecdavis** [comment]
Thanks @shorea for the quick resolution, really appreciate it.

**Comment by shorea** [comment]
This has been released.
