### ISSUE TITLE
DynamoDB : Excepting when using updateitem with a map in a map

### ISSUE THREAD

**Issue by andaag** [aws/aws-sdk-java#882]
When updating an item with a map consisting of a map I get an exception. But my request seems to be converting every field to proper dynamodb syntax?

```
ADD #0 :0 SET #1 = :1
"#0" -> "version"
":0" -> "{N: 1,}"
"#1" -> "mapstructure"
":1" -> "{M: {data={M: {withdata={S: with some data in it,}},}},}"
```

```
Caused by: com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: An operand in the update expression has an incorrect data type (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 07DQO7K7OG4OEUG9E6T72D002BVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1529) ~[aws-java-sdk-core-1.11.38.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1167) ~[aws-java-sdk-core-1.11.38.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:948) ~[aws-java-sdk-core-1.11.38.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:661) ~[aws-java-sdk-core-1.11.38.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:635) ~[aws-java-sdk-core-1.11.38.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:618) ~[aws-java-sdk-core-1.11.38.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:586) ~[aws-java-sdk-core-1.11.38.jar:?]
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:573) ~[aws-java-sdk-core-1.11.38.jar:?]
```

**Comment by andaag** [comment]
(What I'm trying to do is simply take a json document and update it given a path. Which seems like quite a lot of manual work when using UpdateItem)

**Comment by kiiadi** [comment]
Can you post a code-snippet so that I can try to reproduce?

**Comment by andaag** [comment]
No unfortunately not, squished that problem as we worked around it by writing the updateexpression ourselfes.

The problem was related to using ExpressionSpecBuilder and buildForUpdate on a map containing a map. When we rewrote it to use our own expression builder it worked and the commits were squished and merged, sorry :/

**Comment by kiiadi** [comment]
So is this still an issue or is it working now? I don't suppose you have the expression builder snippet that was causing the issue so that I can help diagnose further...?

**Comment by andaag** [comment]
I've had a go at reproducing this manually, but I can't :/. If I do manage to reproduce it I will reopen. Sorry about the noise :/

**Comment by kiiadi** [comment]
No problem, please do re-open if this re-occurs.
