### ISSUE TITLE
Under MacOS Sierra SQS performance is really slow

### ISSUE THREAD

**Issue by haskovec** [aws/aws-sdk-java#885]
I upgraded my MacBookPro from El Capitian to Sierra and have noticed a massive performance drop in SQS. It seems to be hanging on the get credentials call.  Here is a snippet from a stack trace I took on 2 different apps when starting up. Our 1 app which connects to something like 8 different SQS queues used to launch in 11 seconds and now takes about 141 seconds to launch. I always find it in this place in jstack:

``` java
   at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    - locked <0x0000000773460e50> (a java.net.SocksSocketImpl)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
    - locked <0x0000000773460dc8> (a sun.net.www.http.HttpClient)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
    at sun.net.www.http.HttpClient.New(HttpClient.java:308)
    at sun.net.www.http.HttpClient.New(HttpClient.java:326)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:70)
    at com.amazonaws.auth.InstanceProfileCredentialsProvider$InstanceMetadataCredentialsEndpointProvider.getCredentialsEndpoint(InstanceProfileCredentialsProvider.java:117)
    at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:121)
    - locked <0x00000006c0ebd3c0> (a com.amazonaws.auth.EC2CredentialsFetcher)
    at com.amazonaws.auth.EC2CredentialsFetcher.getCredentials(EC2CredentialsFetcher.java:82)
    at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:104)
    at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:115)
at com.amazonaws.http.AmazonHttpClient.getCredentialsFromContext(AmazonHttpClient.java:781)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:807)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:702)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:454)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:416)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:365)
    at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1741)
    at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1711)
    at com.amazonaws.services.sqs.AmazonSQSClient.getQueueAttributes(AmazonSQSClient.java:1010)
    at com.amazonaws.services.sqs.buffered.AmazonSQSBufferedAsyncClient.getQueueAttributes(AmazonSQSBufferedAsyncClient.java:262)
    at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.queueAttributes(AbstractMessageListenerContainer.java:298)
    at org.springframework.cloud.aws.messaging.listener.AbstractMessageListenerContainer.initialize(AbstractMessageListenerContainer.java:270)
    - locked <0x000000076ee7bc18> (a java.lang.Object)
    at org.springframework.cloud.aws.messaging.listener.SimpleMessageListenerContainer.initialize(SimpleMessageListenerContainer.java:110)
```

**Comment by shorea** [comment]
Does it work once launched? Where are your credentials supposed to be loaded from?

**Comment by haskovec** [comment]
It does work once launched. Though it is slow now, I used to send messages back and forth between our 2 apps at a crazy fast speed and now there is a long wait for the messages to go between the 2 apps. My accessId and Secret key are coming from ~/.aws/credentials

**Comment by shorea** [comment]
Hmm it shouldn't be trying to hit the instance metadata service at all if your credentials are loaded from ~/.aws/credentials. https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.java

Can you share how you create clients?

**Comment by haskovec** [comment]
Oh our config in Spring boot has instance metadata enabled because in the production servers I think they use the IAM roles to connect. So we have the cloud.aws.credentials.instanceProfile=true In the Spring Boot AWS Messaging integration enabled. In the previous version of MacOS I think it would try that running locally and then just use our local credentials. Meanwhile the app in Prod picks that up and uses IAM since it doesn't have a local credentials file.

You gave me the answer there though when I set that flag to false the app now launches in 21 seconds instead of 141 so that is a huge improvement though still slower than the previous release.

**Comment by shorea** [comment]
Is your OS the only thing that changed or are have you updated your dependency on the SDK or another dependency like spring boot?

**Comment by haskovec** [comment]
The OS is the only thing that changed. We are running 1.11.18 of the SQS lib. From Spring Cloud Brixton.SR5.

**Comment by shorea** [comment]
Would it be possible to quickly try 1.11.15? There were some changes introduced in 1.11.16 in regards to instance metadata service and wanted to rule that out. If your dependent on features in 1.11.18 don't spend too much time on it though.

**Comment by haskovec** [comment]
In .15 with instanceProfile = true the startup time is 32 seconds.  With instance profile set to false I am at 11.828 seconds to back to the time I was getting under El Capitian.  I think some of the changes introduced did cause the problem. But there is still something that changed with the networking between MacOS 10.11 and 10.12. As I only after I disabled the instance checking and went back to the release 15 did I see it match the speed before.

**Comment by hawka11** [comment]
Hi, we are using 1.11.18 and we noticed that the kinesis client is taking close to 2 mins to get it's first successful lease after updating to sierra. But then it continues to loose the lease after it's timeout.

We were just starting to troubleshoot and then found this issue....i took a stack trace as well which is similar to yours...

"cw-metrics-publisher@7583" prio=5 tid=0x14 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks LeaseRenewer-1@8671
	 blocks pool-2-thread-1@8663
	  at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:-1)
	  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	  - locked <0x21e1> (a java.net.SocksSocketImpl)
	  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	  at java.net.Socket.connect(Socket.java:589)
	  at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	  at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	  at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	  - locked <0x21e2> (a sun.net.www.http.HttpClient)
	  at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	  at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	  at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	  at com.amazonaws.internal.EC2CredentialsUtils.readResource(EC2CredentialsUtils.java:70)
	  at com.amazonaws.auth.InstanceProfileCredentialsProvider$InstanceMetadataCredentialsEndpointProvider.getCredentialsEndpoint(InstanceProfileCredentialsProvider.java:117)
	  at com.amazonaws.auth.EC2CredentialsFetcher.fetchCredentials(EC2CredentialsFetcher.java:121)
	  - locked <0x1f1d> (a com.amazonaws.auth.EC2CredentialsFetcher)
	  at com.amazonaws.auth.EC2CredentialsFetcher.getCredentials(EC2CredentialsFetcher.java:82)
	  at com.amazonaws.auth.InstanceProfileCredentialsProvider.getCredentials(InstanceProfileCredentialsProvider.java:104)
	  at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:115)
	  at com.amazonaws.http.AmazonHttpClient.getCredentialsFromContext(AmazonHttpClient.java:781)
	  at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:807)
	  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:702)
	  at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:454)
	  at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:416)
	  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:365)
	  at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.doInvoke(AmazonCloudWatchClient.java:1002)
	  at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.invoke(AmazonCloudWatchClient.java:972)
	  at com.amazonaws.services.cloudwatch.AmazonCloudWatchClient.putMetricData(AmazonCloudWatchClient.java:871)
	  at com.amazonaws.services.kinesis.metrics.impl.DefaultCWMetricsPublisher.publishMetrics(DefaultCWMetricsPublisher.java:63)
	  at com.amazonaws.services.kinesis.metrics.impl.CWPublisherRunnable.runOnce(CWPublisherRunnable.java:144)
	  at com.amazonaws.services.kinesis.metrics.impl.CWPublisherRunnable.run(CWPublisherRunnable.java:90)
	  at java.lang.Thread.run(Thread.java:745)

**Comment by varunnvs92** [comment]
In 1.11.16, there were changes to do retries while fetching credentials from EC2. I guess this delay might be due that change. The change was removed in later versions (1.11.20s) as some other customers were having similar delays. Can you upgrade to the latest version of the SDK and see if the problem still exists? Thank you.

**Comment by kiiadi** [comment]
Closing aged issue, please feel free to reopen if required.
