### ISSUE TITLE
ValidationException: Type mismatch for attribute to update

### ISSUE THREAD

**Issue by swathikanury** [aws/aws-sdk-java#905]
Hi, I am trying to implement clientside encryption using aws-dynamodb-encryption-java. Saving a document works when I **do not** specify any @DynamoDBIndexHashKey's. Once I specify the IndexHashKey and IndexRangeKey, I keep getting this exception: 
Where am I going wrong? Is there a problem with encrypting globalIndex hash+range key?
Any help is greatly appreciated.

```
com.amazonaws.services.dynamodbv2.model.AmazonDynamoDBException: Type mismatch for attribute to update (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: 770b5f75-860e-4823-8095-737d515db509)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1530)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1168)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:949)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:662)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:636)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:619)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:587)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:574)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:446)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.doInvoke(AmazonDynamoDBClient.java:1723)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:1699)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.putItem(AmazonDynamoDBClient.java:1317)
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.doPutItem(DynamoDBMapper.java:882)
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$1.executeLowLevelRequest(DynamoDBMapper.java:535)
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper$SaveObjectHandler.execute(DynamoDBMapper.java:732)
    at com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper.save(DynamoDBMapper.java:622)
    at com.amazonaws.services.dynamodbv2.datamodeling.AbstractDynamoDBMapper.save(AbstractDynamoDBMapper.java:123)
    at mycode.dynamodb.DynamoDBClientSideEncryption.testEncryption(DynamoDBClientSideEncryption.java:100)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

Here is my Book Object

```
package mycode.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.encryption.DoNotEncrypt;

@DynamoDBTable(tableName = "test_Books")
public class Book {
    public String id;   
    public void setId(String id) {
        this.id = id;
    }   
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public String title;    
    public void setTitle(String title) {
        this.title = title;
    }   
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "titleIndex")
    public String getTitle() {
        return title;
    }

    public long createdAt;  
    public void setCreatedAt(long date) {
        this.createdAt = date;
    }   
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "titleIndex") 
    public long getCreatedAt() {
        return createdAt;
    }

    @Override
    public String toString() {
        return "Book [id=" + id + ", title=" + title + ", createdAt=" + createdAt + "]";
    }   

    Long version;   
    @DoNotEncrypt
    @DynamoDBVersionAttribute
    public Long getVersion() {
        return version;
    }   
    public void setVersion(Long version) {
        this.version = version;
    }

}
```

Here is my test class saving book to DB using client side encryption. 

```
package mycode.dynamodb;

import java.util.Date;
import java.util.List;
import org.apache.commons.lang3.StringUtils;
import org.junit.Before;
import org.junit.Test;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient;
import com.amazonaws.services.dynamodbv2.datamodeling.AttributeEncryptor;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig;
import com.amazonaws.services.dynamodbv2.datamodeling.encryption.DynamoDBEncryptor;
import com.amazonaws.services.dynamodbv2.datamodeling.encryption.providers.DirectKmsMaterialProvider;
import com.amazonaws.services.dynamodbv2.model.CreateTableRequest;
import com.amazonaws.services.dynamodbv2.model.GlobalSecondaryIndex;
import com.amazonaws.services.dynamodbv2.model.ProvisionedThroughput;
import com.amazonaws.services.dynamodbv2.util.TableUtils;
import com.amazonaws.services.dynamodbv2.util.TableUtils.TableNeverTransitionedToStateException;
import com.amazonaws.services.kms.AWSKMS;
import com.amazonaws.services.kms.AWSKMSClient;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class DynamoDBClientSideEncryption {
    private static final AmazonDynamoDB amazonDynamoDB;
    private static final DynamoDBMapper dynamoDBMapper;
    final static AWSKMS kms = new AWSKMSClient();
    // Set up the aws-dynamodb-encryption-java library
    final static DynamoDBEncryptor cryptor =
            DynamoDBEncryptor.getInstance(new DirectKmsMaterialProvider(kms, "alias/myalias"));

    static {
        amazonDynamoDB = new AmazonDynamoDBClient(
                new BasicAWSCredentials(System.getenv("amazon.aws.accesskey"), System.getenv("amazon.aws.secretkey")));
        final String endpoint = System.getenv("amazon.dynamodb.endpoint");
        if (StringUtils.isNotEmpty(endpoint)) {
            amazonDynamoDB.setEndpoint(endpoint);
        }
        dynamoDBMapper = new DynamoDBMapper(amazonDynamoDB, DynamoDBMapperConfig.DEFAULT, new AttributeEncryptor(cryptor));
        log.info("Connected to DynamoDB at " + endpoint);
    }

    @Before
    public void setUp() {
        Long readCapacityUnits = 10L;
        Long writeCapacityUnits = 10L;
        final ProvisionedThroughput provisionedThroughput =
                new ProvisionedThroughput(readCapacityUnits, writeCapacityUnits);
        CreateTableRequest pcTableRequest = dynamoDBMapper.generateCreateTableRequest(Book.class);
        pcTableRequest.setProvisionedThroughput(provisionedThroughput);
        List<GlobalSecondaryIndex> globalSecondaryIndexes = pcTableRequest.getGlobalSecondaryIndexes();
        if (globalSecondaryIndexes != null) {
            for (GlobalSecondaryIndex globalSecondaryIndex : globalSecondaryIndexes) {
                globalSecondaryIndex.setProvisionedThroughput(provisionedThroughput);
            }
        }
        boolean created = TableUtils.createTableIfNotExists(amazonDynamoDB, pcTableRequest);
        if (created) {
            try {
                TableUtils.waitUntilActive(amazonDynamoDB, Book.class.getSimpleName());
            }
            catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    @Test
    public void testEncryption() {
        Book book = new Book();
        book.setTitle("Title8");
        book.setCreatedAt(new Date().getTime());
        dynamoDBMapper.save(book, new DynamoDBMapperConfig(DynamoDBMapperConfig.SaveBehavior.CLOBBER));
    }
}
```

**Comment by spfink** [comment]
For DynamoDBIndexHashKey and DynamoDBIndexRangeKey you will need to specify @DoNotEncrypt to make sure that they are not encrypted.

We will look into seeing if this can be made the default behavior.

**Comment by SalusaSecondus** [comment]
Linking issues: awslabs/aws-dynamodb-encryption-java#22

**Comment by millems** [comment]
Closing to track in https://github.com/awslabs/aws-dynamodb-encryption-java/issues/22
