### ISSUE TITLE
InstanceID not found on describe instances call with no filters.

### ISSUE THREAD

**Issue by rdifalco** [aws/aws-sdk-java#911]
This is one of the odder things I've found. It doesn't recur often. If I call `descibeInstances` like this:

```
        DescribeInstancesRequest request = new DescribeInstancesRequest();
        do {
            DescribeInstancesResult result = ec2.describeInstances(request);
            request.setNextToken(result.getNextToken());
            process(result);
        } while (request.getNextToken() != null);

```
I can very rarely get an `InvalidInstanceID.NotFound` error. My guess would be that you have a race condition in your paging? Maybe the nextToken page is pre-populated and it checks on the server to see if an EC2 instance id no longer exists? But it's super odd. I'd consider it a bug because it should logically happen. 
```
com.amazonaws.services.ec2.model.AmazonEC2Exception: The instance ID 'i-6381a3fa' does not exist (Service: AmazonEC2; Status Code: 400; Error Code: InvalidInstanceID.NotFound; Request ID: 3ad835bb-58e7-4a40-9a92-b32372a3c0ab)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1529) 
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1167) 
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:948) 
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:661) 
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:635) 
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:618) 
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:586) 
  at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:573) 
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:445) 
  at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:10791) 
  at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:10767) 
  at com.amazonaws.services.ec2.AmazonEC2Client.describeInstances(AmazonEC2Client.java:5190) 
```

**Comment by shorea** [comment]
Do you mind bringing this up on the EC2 forums or through a support case? This would be a service side bug that we (SDK) don't have any control over.

**Comment by thecrux4020** [comment]
+1
