### ISSUE TITLE
java.lang.UnsupportedOperationException when using AmazonS3EncryptionClient with TransferUtility [Urgent]

### ISSUE THREAD

**Issue by hs8058** [aws/aws-sdk-java#917]
Hi,

Has anyone tried using AmazonS3EncryptionClient with TransferUtility?
Irrespective of the chosen CryptoConfiguration,  when ObjectMetadata.addUserMetadata is internally called during the building of the putobject request, an exception is raised, which is apparently the result of ObjectMetadata.usermetadata being an UnmodifiableMap, which makes it impossible to add the required custom meta data:
When using AmazonS3EncryptionClient.putObject directly (not using TransferUtility), such an error does not happen.

It won't make a difference if InstructionFile or Metadata is used. Either way, the library does try to change usermetadata which raises the exception.

V 2.3.3 has been used for this issue.

**_This is urgent._**
Here is the exception:
java.lang.UnsupportedOperationException
at java.util.Collections$UnmodifiableMap.put(Collections.java:1280)
at com.amazonaws.services.s3.model.ObjectMetadata.addUserMetadata(ObjectMetadata.java:196)
at com.amazonaws.services.s3.internal.crypto.EncryptionUtils.encryptRequestUsingInstruction(EncryptionUtils.java:362)
at com.amazonaws.services.s3.internal.crypto.S3CryptoModuleEO.putObjectUsingInstructionFile(S3CryptoModuleEO.java:354)
at com.amazonaws.services.s3.internal.crypto.S3CryptoModuleEO.putObjectSecurely(S3CryptoModuleEO.java:87)
at com.amazonaws.services.s3.internal.crypto.CryptoModuleDispatcher.putObjectSecurely(CryptoModuleDispatcher.java:85)
at com.amazonaws.services.s3.AmazonS3EncryptionClient.putObject(AmazonS3EncryptionClient.java:412)
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:203)
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:85)
at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:44)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

**Comment by dagnir** [comment]
Hi @hs8058, sorry to see you're having issues. This looks like an issue with the [Android SDK](https://github.com/aws/aws-sdk-android) though, judging from the version number and stacktrace provided. Please open an issue in that repository and they should be able to assist you.

**Comment by dagnir** [comment]
Closing this issue since it is being tracked by https://github.com/aws/aws-sdk-android/issues/214.
