### ISSUE TITLE
Unable to instantiate AmazonSQSClient due to IllegalAccessError

### ISSUE THREAD

**Issue by mattmar10** [aws/aws-sdk-java#987]
Seeing the following error when trying to instantiate an AmazonSQSClient via spring.

Note, using java version "1.8.0_60".

SEVERE: Servlet.service() for servlet [DispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.IllegalAccessError: tried to access method com.amazonaws.transform.StandardErrorUnmarshaller.<init>(Ljava/lang/Class;)V from class com.amazonaws.services.sqs.AmazonSQSClient] with root cause
```
java.lang.IllegalAccessError: tried to access method com.amazonaws.transform.StandardErrorUnmarshaller.<init>(Ljava/lang/Class;)V from class com.amazonaws.services.sqs.AmazonSQSClient
	at com.amazonaws.services.sqs.AmazonSQSClient.init(AmazonSQSClient.java:317)
	at com.amazonaws.services.sqs.AmazonSQSClient.<init>(AmazonSQSClient.java:281)
	at com.amazonaws.services.sqs.AmazonSQSClient.<init>(AmazonSQSClient.java:259)
	at com.amazon.sqs.javamessaging.SQSConnectionFactory.createConnection(SQSConnectionFactory.java:80)
	at com.amazon.sqs.javamessaging.SQSConnectionFactory.createConnection(SQSConnectionFactory.java:63)
	at com.amazon.sqs.javamessaging.SQSConnectionFactory.createConnection(SQSConnectionFactory.java:38)
	at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:180)
	at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:484)
	at org.springframework.jms.core.JmsTemplate.send(JmsTemplate.java:569)
	at org.springframework.jms.core.JmsTemplate.send(JmsTemplate.java:560)
```

**Comment by shorea** [comment]
Looks like you are using a new version of aws-java-sdk-sqs but an older version of aws-java-sdk-core. Updating to consistent versions should fix the problem.

See https://aws.amazon.com/blogs/developer/managing-dependencies-with-aws-sdk-for-java-bill-of-materials-module-bom/ for a easy way to ensure consistent versions.
