### ISSUE TITLE
HTTP 500 in AWSCostAndUsageReport

### ISSUE THREAD

**Issue by thchuong-x2011** [aws/aws-sdk-java#991]
Hello,
I am playing with the AWSCostAndUsageReport service that was introduced since 1.11.79.
So far, that does not yield any result as I always receive an HTTP 500 with PutReportDefinition or DescribeReportDefinitions method.

I use an IAM account to connect to AWS with a full-right access to the Aws Billing and Cost Management service, which I have checked by creating and viewing usage reports on the Billing dashboard.

The error I received is as follow:
```
com.amazonaws.services.costandusagereport.model.AWSCostAndUsageReportException: null (Service: AWSCostAndUsageReport; Status Code: 500; Error Code: null; Request ID: null)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.doInvoke(AWSCostAndUsageReportClient.java:436)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.invoke(AWSCostAndUsageReportClient.java:412)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.putReportDefinition(AWSCostAndUsageReportClient.java:376)
```

In the attachment, the code to reproduce the issue.
[aws-cur.java](https://github.com/aws/aws-sdk-java/files/718999/aws-cur.txt)

Regards,
Chuong

**Comment by varunnvs92** [comment]
@thchuong-x2011 
I have tested the sample code you provided with Java SDK v1.11.83 and it worked fine for me. The only changes I made are the bucket and report names.

1) What version of the SDK are you using? Can you try with 1.11.83?
2) Are you getting the same error every time?
3) Can you make sure that the bucket has correct policy?

**Comment by thchuong-x2011** [comment]
@varunnvs92,
Thank you for your reply.

I'm actually on 1.11.83 and the error happens everytime I run the test.

As for the policy,
on my IAM user, I have attached the Aws-defined "Billing" policy, plus a policy that allows "cur:PutReportDefinitions", "cur:DescribeReportDefinition", "cur:DeleteReportDefinition". I believe it would be suffice for my test.
on the bucket of interest, I have attached the policy (with the good bucket name) in the example 9. I don't know if it is correct.

Regards

**Comment by varunnvs92** [comment]
Please provide us the wire log?
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html

**Comment by thchuong-x2011** [comment]
@varunnvs92 
I have troubles setting up Log4j even by following the instructions in your link.
To summarize,
- I have put log4j-core.jar and log4j-api.jar (as instructed on http://logging.apache.org/log4j/2.x/download.html) either by declaring them as dependencies or by using Java Build Path in Eclipse.
- I have put log4j.properties in the src folder with the configuration as in the section Verbose Wire Logging.

With all these works done, I did not manage to have any logging on the console. I have tried on Eclipse and on my terminal using Maven.

Have I missed something?
Thanks

**Comment by varunnvs92** [comment]
This is my log4j.properties file. Make sure you have uncommented the http wire logging lines.

```
log4j.rootLogger=WARN, A1
log4j.appender.A1=org.apache.log4j.ConsoleAppender
log4j.appender.A1.layout=org.apache.log4j.PatternLayout

# Print the date in ISO 8601 format
log4j.appender.A1.layout.ConversionPattern=%d [%t] %-5p %c - %m%n

# HttpClient 4 Wire Logging
log4j.logger.org.apache.http.wire=DEBUG
 log4j.logger.org.apache.http=DEBUG
```

In the error stacktrace you posted, it is weird that there is no error code or error message. Are you getting the similar error every time you run it or Did you see any other error codes?

**Comment by viswanath-angajala** [comment]
Hi @varunnvs92 ,

I am also facing the same issue. Surprisingly nothing in the http response content. Below is the logs which has debug statements enabled by log4j.
Please help me on this.

2017-02-15 12:51:29,908 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> POST / HTTP/1.1
2017-02-15 12:51:29,908 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> Host: cur.us-east-1.amazonaws.com
2017-02-15 12:51:29,908 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> Authorization: AWS4-HMAC-SHA256 Credential=*******************************************, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=************************************************************
2017-02-15 12:51:29,908 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> X-Amz-Date: 20170215T072128Z
2017-02-15 12:51:29,908 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> User-Agent: aws-sdk-java/1.11.83 Windows_10/10.0 Java_HotSpot(TM)_64-Bit_Server_VM/25.60-b23/1.8.0_60
2017-02-15 12:51:29,908 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> amz-sdk-invocation-id: bb3387ed-0072-e804-0417-97cbcbe0db60
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> amz-sdk-retry: 0/0/500
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> X-Amz-Target: AWSOrigamiServiceGatewayService.PutReportDefinition
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> Content-Type: application/x-amz-json-1.1
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> Content-Length: 214
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.headers -  http-outgoing-0 >> Connection: Keep-Alive
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "POST / HTTP/1.1[\r][\n]"
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Host: cur.us-east-1.amazonaws.com[\r][\n]"
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=*******************************************************, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=***********************************************************[\r][\n]"
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "X-Amz-Date: 20170215T072128Z[\r][\n]"
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "User-Agent: aws-sdk-java/1.11.83 Windows_10/10.0 Java_HotSpot(TM)_64-Bit_Server_VM/25.60-b23/1.8.0_60[\r][\n]"
2017-02-15 12:51:29,909 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "amz-sdk-invocation-id: bb3387ed-0072-e804-0417-97cbcbe0db60[\r][\n]"
2017-02-15 12:51:29,910 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "amz-sdk-retry: 0/0/500[\r][\n]"
2017-02-15 12:51:29,910 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "X-Amz-Target: AWSOrigamiServiceGatewayService.PutReportDefinition[\r][\n]"
2017-02-15 12:51:29,910 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Content-Type: application/x-amz-json-1.1[\r][\n]"
2017-02-15 12:51:29,910 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Content-Length: 214[\r][\n]"
2017-02-15 12:51:29,910 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2017-02-15 12:51:29,910 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "[\r][\n]"
2017-02-15 12:51:29,910 [main] DEBUG org.apache.http.wire -  http-outgoing-0 >> "{"ReportDefinition":{"ReportName":"cfx-report1","TimeUnit":"DAILY","Format":"textORcsv","Compression":"ZIP","AdditionalSchemaElements":["RESOURCES"],"S3Bucket":"viswa-9582","S3Prefix":"cfx","S3Region":"us-west-1"}}"
2017-02-15 12:51:30,117 [main] DEBUG org.apache.http.wire -  http-outgoing-0 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
2017-02-15 12:51:30,117 [main] DEBUG org.apache.http.wire -  http-outgoing-0 << "Date: Wed, 15 Feb 17 07:21:29 GMT[\r][\n]"
2017-02-15 12:51:30,117 [main] DEBUG org.apache.http.wire -  http-outgoing-0 << "Connection: close[\r][\n]"
2017-02-15 12:51:30,117 [main] DEBUG org.apache.http.wire -  http-outgoing-0 << "x-amz-id-2: **********************************************************************************************[\r][\n]"
2017-02-15 12:51:30,118 [main] DEBUG org.apache.http.wire -  http-outgoing-0 << "x-amz-request-id: 26D219B23944C2F[\r][\n]"
2017-02-15 12:51:30,118 [main] DEBUG org.apache.http.wire -  http-outgoing-0 << "Content-Length: 0[\r][\n]"
2017-02-15 12:51:30,118 [main] DEBUG org.apache.http.wire -  http-outgoing-0 << "[\r][\n]"
2017-02-15 12:51:30,126 [main] DEBUG org.apache.http.headers -  http-outgoing-0 << HTTP/1.1 500 Internal Server Error
2017-02-15 12:51:30,126 [main] DEBUG org.apache.http.headers -  http-outgoing-0 << Date: Wed, 15 Feb 17 07:21:29 GMT
2017-02-15 12:51:30,126 [main] DEBUG org.apache.http.headers -  http-outgoing-0 << Connection: close
2017-02-15 12:51:30,126 [main] DEBUG org.apache.http.headers -  http-outgoing-0 << x-amz-id-2: ******************************************************************************************8
2017-02-15 12:51:30,126 [main] DEBUG org.apache.http.headers -  http-outgoing-0 << x-amz-request-id: 26D219B23944C2F
2017-02-15 12:51:30,126 [main] DEBUG org.apache.http.headers -  http-outgoing-0 << Content-Length: 0
2017-02-15 12:51:30,130 [main] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection -  http-outgoing-0: Close connection
2017-02-15 12:51:30,131 [main] DEBUG com.amazonaws.internal.SdkSSLSocket -  shutting down output of cur.us-east-1.amazonaws.com/52.94.237.91:443
2017-02-15 12:51:30,131 [main] DEBUG com.amazonaws.internal.SdkSSLSocket -  closing cur.us-east-1.amazonaws.com/52.94.237.91:443
2017-02-15 12:51:30,132 [main] DEBUG org.apache.http.impl.execchain.MainClientExec -  Connection discarded
2017-02-15 12:51:30,133 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager -  Connection released: [id: 0][route: {s}->https://cur.us-east-1.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2017-02-15 12:52:28,529 [java-sdk-http-connection-reaper] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager -  Closing connections idle longer than 60000 MILLISECONDS
2017-02-15 12:52:29,801 [main] INFO  com.amazonaws.protocol.json.JsonContent -  Unable to parse HTTP response content
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: [B@200606de; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3781)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3721)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2294)
	at com.amazonaws.protocol.json.JsonContent.parseJsonContent(JsonContent.java:72)
	at com.amazonaws.protocol.json.JsonContent.<init>(JsonContent.java:64)
	at com.amazonaws.protocol.json.JsonContent.createJsonContent(JsonContent.java:54)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:61)
	at com.amazonaws.http.JsonErrorResponseHandler.handle(JsonErrorResponseHandler.java:33)
	at com.amazonaws.http.AwsErrorResponseHandler.handleAse(AwsErrorResponseHandler.java:50)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:38)
	at com.amazonaws.http.AwsErrorResponseHandler.handle(AwsErrorResponseHandler.java:24)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1568)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.doInvoke(AWSCostAndUsageReportClient.java:436)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.invoke(AWSCostAndUsageReportClient.java:412)
	at com.amazonaws.services.costandusagereport.AWSCostAndUsageReportClient.putReportDefinition(AWSCostAndUsageReportClient.java:376)
	at com.cfx.shadow.awsec2.Test.main(Test.java:163)

**Comment by shorea** [comment]
I've engaged the service team. Will update when I hear back from them.

**Comment by shorea** [comment]
@viswanath-angajala, heard back from the service team. It appears the bucket you are using is in us-east-1 but the s3 region is us-west-1. Can you correct that parameter and try again? The service team has taken an action item to make the error for this more clear.

**Comment by kiiadi** [comment]
@viswanath-angajala based on the correspondence I'd say this isn't an SDK issue - closing this for now - please feel free to re-open if you need further assistance from the SDK team.
