### ISSUE TITLE
Amazon S3 Java MultipleFileDownload with progressbar, blocking call issue-

### ISSUE THREAD

**Issue by studioam** [aws/aws-sdk-java#994]
I'm trying to download a folder containing a large file (3GB) from S3 and use TransferManager with MultipleFileDownload. Since I'm suing java Swing for graphic side, I'm also using a progress listener to update the status of a progress bar and track download progress. I also want to remove a policy for an user once the download has finished, and also perform more final actions. The listener is made as follows:

            `          ProgressListener progressListener = new ProgressListener() {
             @Override
              public void progressChanged(ProgressEvent progressEvent) {

             if (download == null) return;
            
            
            jProgressBar1.setValue((int)download.getProgress().getPercentTransferred()); 

           if (progressEvent.getEventType()== ProgressEventType.TRANSFER_COMPLETED_EVENT) {

             if (download.isDone()){  
            tx.shutdownNow()
           AmazonIdentityManagementClient client = new AmazonIdentityManagementClient();

              DetachUserPolicyRequest cancellation = new DetachUserPolicyRequest();
               client.detachUserPolicy(cancellation.withUserName(account).withPolicyArn("blablabla"));
              }}
              if (progressEvent.getEventType() == ProgressEventType.TRANSFER_FAILED_EVENT){
              try {
                AmazonClientException e = download.waitForException();
                JOptionPane.showMessageDialog(frame,
                        "Unable to Download file from Amazon S3: " + e.getMessage(),
                        "Error Downloading File", JOptionPane.ERROR_MESSAGE);
            } catch (InterruptedException e) {}
           }
          }
       }; 
        }}

     download = tx.downloadDirectory(bucketName, keyprefix, path);

      download.addProgressListener(progressListener);

       //where tx is a transferManager and download a MultipleFileDownload. `

The problem is when both the download and parts joining end, tx.shutdown is performed and policy removed but then I have the following exception:

         `com.amazonaws.event.ProgressListenerChain          progressChanged
          AVVERTENZA: Couldn't update progress listener
             com.amazonaws.AbortedException: 
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleInterruptedException      (AmazonHttpClient.java:797)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:706)
            at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500 (AmazonHttpClient.java:672)
               at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
             at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
             at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.doInvoke(AmazonIdentityManagementClient.java:7367)
           at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.invoke(AmazonIdentityManagementClient.java:7343)
             at com.amazonaws.services.identitymanagement.AmazonIdentityManagementClient.detachUserPolicy(AmazonIdentityManagementClient.java:2946)
           at NewJFrame$7.progressChanged(NewJFrame.java:494)
                 at com.amazonaws.services.s3.model.LegacyS3ProgressListener.progressChanged(LegacyS3ProgressListener.java:47)
           at com.amazonaws.event.ProgressListenerChain.progressChanged(ProgressListenerChain.java:98)
           at com.amazonaws.services.s3.transfer.MultipleFileTransferProgressUpdatingListener.progressChanged(MultipleFileTransferProgressUpdatingListener.java:41)
             at com.amazonaws.event.ProgressListenerChain.progressChanged(ProgressListenerChain.java:98)
             at com.amazonaws.event.SDKProgressPublisher.quietlyCallListener(SDKProgressPublisher.java:86)
            at com.amazonaws.event.SDKProgressPublisher.deliverEvent(SDKProgressPublisher.java:68)
            at com.amazonaws.event.SDKProgressPublisher.publishProgress(SDKProgressPublisher.java:58)
           at com.amazonaws.services.s3.transfer.internal.AbstractTransfer.fireProgressEvent(AbstractTransfer.java:253)
           at com.amazonaws.services.s3.transfer.internal.DownloadImpl.setState(DownloadImpl.java:168)
             at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:50)
           at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:29)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: com.amazonaws.http.timers.client.SdkInterruptedException
              at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:841)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.checkInterrupted(AmazonHttpClient.java:827)
          at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1006)
          at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
           at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
      at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
         ... 22 more`

 have also tried to remove the listener and set a download.WaitforCompletion() or while (!(download.isdone())), I mean:

        `download = tx.downloadDirectory(bucketName, keyprefix, path);
         download.addProgressListener(progressListener);
           while (!(download.isDone)())){}
            /then more final actions/`

in this way the problem seems solved, but since those are blocking calls I can't have my progress bar realtime updated while downloading. 

I've been told the 1st issue occurs because JVM is exiting after calling tx.shutdownNow() which means there are no other non-daemon threads running.
Is there any way to have the progress bar updated and keep the application working smoothly untile the end (= until the last line is processed)? 

The best would have been:

      `while (!(download.isDone)())){
             jProgressBar1.setValue((int)download.getProgress().getPercentTransferred());
      }
         `
but it doesn't work  .
thanks in advance

**Comment by kiiadi** [comment]
How are you initializing `download` in order to be accessible inside the annoymous progress listener doesn't it need to be `final`?

Can you post how you're creating the S3 client / TransferManager instance? Once you've called shutdownNow on the TransferManager both the TransferManager and the underlying S3 client will be shutdown.

What happens if you remove the call to `AmazonIdentityManagementClient` for now?

**Comment by studioam** [comment]
Hi, thanks for your reply and for your help. 

Since I'm using Swing JFrame which starts download progress with the click of a START button inside it, I've declared the download as a private attribute of JFrame, this is in order to be accessible inside the anoymous progress listener. 

`private MultipleFileDownload download;`

if I set if as final, I have an error when assigning it a value:

`download = tx.downloadDirectory(bucketName, DCPname, path);`
'cannot assing a value to a final variable download'  and this is right being download a final variable.

Here it is how I created the S3 client / TransferManager instance, this is all inside the action todo in Start Button (on mouse click)

`
	ClientConfiguration config = new ClientConfiguration(); 
	config.setConnectionTimeout(connectionTimeout);
	config.setSocketTimeout(readTimeout); 
        config.setRetryPolicy(PredefinedRetryPolicies.getDefaultRetryPolicyWithCustomMaxRetries(5));
        
        
			
	
        s3 = new AmazonS3Client(credentials,config);
       Region usWest2 = Region.getRegion(Regions.EU_WEST_1);
	s3.setRegion(usWest2);
	s3.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build());
	        
	 
	tx = new TransferManager(s3); 
//here I have the definition of progress listener  and then 
download = tx.downloadDirectory(bucketName, DCPname, path);

download.addProgressListener(progressListener);`

I'm trying to remove AmazonIdentityManagementClient and report.

To help you to better unterstand how I designed the tool here there are some portions of the code; JFrame declaration with attributes and START button code:

`public class NewJFrame extends javax.swing.JFrame {
    
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private File TxtFile;
    private static NewJFrame frame;
    private  AWSCredentials credentials = null;
    private String credenziali;
    private File path = null;
    private final int connectionTimeout = 50 * 1000;
    private final int readTimeout = 55 * 1000;
    private String account ="";
    private AmazonS3 s3;
    private TransferManager tx;
    private int completedfiles =0; 
    //private int nfiles = 1;
    private String DCPname="";
    private MultipleFileDownload download;
    private int percentCompl=0;

    private String bucket_line=""; 
// then email method follow not relevant
`
and now Start Button code:

` private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
     
     String bucketName = "";
     BufferedReader br=null;
        	
			try {
				br = new BufferedReader(new FileReader(TxtFile));
			} catch (FileNotFoundException e2) {
				// TODO Auto-generated catch block
				JOptionPane.showMessageDialog(frame,
                        "File Chiave 1 Non Presente! Selezionare File Chiave 1" + e2.getMessage(),
                        "Selezionare File Chiave 1", JOptionPane.ERROR_MESSAGE);
				e2.printStackTrace();
			}
                       ///Login	
	   try {
		account= br.readLine();
	    } catch (IOException e2) {
		// TODO Auto-generated catch block
		JOptionPane.showMessageDialog(frame,
                    "Nessuna identità Selezionata" + e2.getMessage(),
                      "Inserire Identità", JOptionPane.ERROR_MESSAGE);
		e2.printStackTrace();		}
            
                try {
                  bucket_line = br.readLine();
	} catch (IOException e2) {
		// TODO Auto-generated catch block
		JOptionPane.showMessageDialog(frame,
		"File Chiave 1 Errato! Caricare un File Chiave 1 Valido" + e2.getMessage(),
                   "Caricare un File Chiave 1 Valido", JOptionPane.ERROR_MESSAGE);
				e2.printStackTrace();
	}
        
        //lettura nome DCP
        try {
            DCPname = br.readLine();
	} catch (IOException e1) {
		// TODO Auto-generated catch block
		JOptionPane.showMessageDialog(frame,
		"File Chiave 1 Errato! Caricare un File Chiave 1 Valido" + e1.getMessage(),
	              "Caricare un File Chiave 1 Valido", JOptionPane.ERROR_MESSAGE);
					
		e1.printStackTrace();
			}
                 if (DCPname.equals("")) try {
			throw new Exception();
		} catch (Exception e) {
		// TODO Auto-generated catch block
					
            JOptionPane.showMessageDialog(frame,
		"File Chiave 1 Errato! Caricare un File Chiave 1 Valido" + e.getMessage(),
	                     "Caricare un File Chiave 1 Valido", JOptionPane.ERROR_MESSAGE);
			e.printStackTrace();
	}
			
			
			
	try {
	       credentials = new ProfileCredentialsProvider(credenziali,"test-user").getCredentials();
	    } catch (Exception e) {
	        // TODO Auto-generated catch block
		JOptionPane.showMessageDialog(frame,
	                        "File Chiave 2 Errato! Caricare un File Chiave 2 Valido" + e.getMessage(),
	                        "Caricare un File Chiave 2 Valido", JOptionPane.ERROR_MESSAGE);
					e.printStackTrace();			
	        }
               ClientConfiguration config = new ClientConfiguration(); 
	config.setConnectionTimeout(connectionTimeout);
	config.setSocketTimeout(readTimeout); 
        config.setRetryPolicy(PredefinedRetryPolicies.getDefaultRetryPolicyWithCustomMaxRetries(5));
        
        
			
	
        s3 = new AmazonS3Client(credentials,config);
       Region usWest2 = Region.getRegion(Regions.EU_WEST_1);
	s3.setRegion(usWest2);
	s3.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build());
	        
	 
	tx = new TransferManager(s3); 
        try{
            	for (com.amazonaws.services.s3.model.Bucket bucket : s3.listBuckets())  if (bucket.getName().equals(bucket_line)) bucketName = bucket.getName() ;
            }catch (Exception e){
            	JOptionPane.showMessageDialog(frame,
            			"Chiavi Scadute! Per effettuare un nuovo Download richiedere nuove chiavi    " + e.getMessage(),
                        "Per effettuare un nuovo Download richiedere nuove chiavi", JOptionPane.ERROR_MESSAGE);
				e.printStackTrace();
            }
        
            
        if (bucketName.equals(""))
			try {
				
                                throw new Exception();
			     } catch (Exception e) {
					// TODO Auto-generated catch block
					
					JOptionPane.showMessageDialog(frame,
				"File Chiave 1 Errato! Caricare un File Chiave 1 Valido" + e.getMessage(),
	                        "Caricare un File Chiave 1 Valido", JOptionPane.ERROR_MESSAGE);
					e.printStackTrace();
				}        


ProgressListener progressListener = new ProgressListener() {
            @Override
            public void progressChanged(ProgressEvent progressEvent) {
                
            if (download == null) return;
            
            
            jProgressBar1.setValue((int)download.getProgress().getPercentTransferred());

if (progressEvent.getEventType()== ProgressEventType.TRANSFER_COMPLETED_EVENT) {

 if (download.isDone()){  
                
                tx.shutdownNow();

AmazonIdentityManagementClient cliente = new AmazonIdentityManagementClient();

DetachUserPolicyRequest cancellazione = new DetachUserPolicyRequest();
                cliente.detachUserPolicy(cancellazione.withUserName(account).withPolicyArn("xxxxxxxxx"));


                 String USER = "xxxxxxxxxx";
                String PASSWORD = "xxxxxxxxxx";
                String[] RECIPIENT = {"xxxxxxxxxx"};
                String oggetto = "Download avvenuto del DCP " + DCPname;
                String testo = "Il Cinema " + account + " ha scaricato il DCP "+ DCPname;
                
                try {
                    sendFromGMail(USER, PASSWORD, RECIPIENT, oggetto, testo);
                } catch (MessagingException ex) {
                    JOptionPane.showMessageDialog(frame,
                            "Impossibile Inviare Email" + ex.getMessage(),
                            " ", JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
                
                JOptionPane.showMessageDialog(frame,"Download DCP Completato. Per effettuare un nuovo Download richiedere nuove chiavi");
               
                
                }

}
            if (progressEvent.getEventType() == ProgressEventType.TRANSFER_FAILED_EVENT){
                try {
                    AmazonClientException e = download.waitForException();
                    JOptionPane.showMessageDialog(frame,
                            "Unable to Download file from Amazon S3: " + e.getMessage(),
                            "Error Downloading File", JOptionPane.ERROR_MESSAGE);
                } catch (InterruptedException e) {}
            }
            }
        }; 

download = tx.downloadDirectory(bucketName, DCPname, path);
        
        download.addProgressListener(progressListener);

}`

**Comment by studioam** [comment]
Removing  the call to AmazonIdentityManagementClient and detach policy seems working fine, I've no more exception and email gets sent end popup appears correctly.

I've therefore tried, as second try, to set the call to AmazonIdentityManagementClient and detach policy as very last instructions to execute. Now I've got exception again but the program seems working as it ends after the policy has been detached.

**Comment by studioam** [comment]
@kiiadi 

btw setting the call to AmazonIdentityManagementClient and detach policy as very last instructions causes email and final popup to be sent twice and while email and popup happen on every machine, credentials are not removed on every machine, could you figure out why? maybe because of the exception? This should look odd since the exception should eb thown after credential removal

**Comment by kiiadi** [comment]
Out of interest are you suppressing an `InterruptedException` in this code-path? It looks like the handler block for that is empty. At the very least you should re-set the interrupted flag on the thread like so: `Thread.currentThread().interrupt()` (see [here](http://stackoverflow.com/questions/3976344/handling-interruptedexception-in-java))

It's possible that this is causing your odd behaviour.

**Comment by studioam** [comment]
@kiiadi 

Hi thanks for your reply.  do you think I should place it in the cacth row of the InterruptedException  as in the linked example? I'll try to do it and report.

I also have an odd exception with the last 1.11.86 release in the upload side of the tool. Please take a look at the exception below. 

`gen 30, 2017 11:16:39 AM com.amazonaws.event.ProgressListenerChain progressChanged
AVVERTENZA: Couldn't update progress listener
java.lang.IllegalArgumentException: bytes reported must be non-negative
	at com.amazonaws.event.ProgressEvent.<init>(ProgressEvent.java:68)
	at com.amazonaws.event.ProgressEvent.<init>(ProgressEvent.java:43)
	at com.amazonaws.services.s3.model.ProgressEvent.<init>(ProgressEvent.java:30)
	at com.amazonaws.services.s3.model.LegacyS3ProgressListener.adaptToLegacyEvent(LegacyS3ProgressListener.java:53)
	at com.amazonaws.services.s3.model.LegacyS3ProgressListener.progressChanged(LegacyS3ProgressListener.java:47)
	at com.amazonaws.event.ProgressListenerChain.progressChanged(ProgressListenerChain.java:98)
	at com.amazonaws.services.s3.transfer.MultipleFileTransferProgressUpdatingListener.progressChanged(MultipleFileTransferProgressUpdatingListener.java:41)
	at com.amazonaws.event.ProgressListenerChain.progressChanged(ProgressListenerChain.java:98)
	at com.amazonaws.event.SDKProgressPublisher.quietlyCallListener(SDKProgressPublisher.java:86)
	at com.amazonaws.event.SDKProgressPublisher.deliverEvent(SDKProgressPublisher.java:68)
	at com.amazonaws.event.SDKProgressPublisher.publishResetEvent(SDKProgressPublisher.java:213)
	at com.amazonaws.event.SDKProgressPublisher.publishRequestReset(SDKProgressPublisher.java:176)
	at com.amazonaws.event.RequestProgressInputStream.onReset(RequestProgressInputStream.java:33)
	at com.amazonaws.event.ProgressInputStream.reset(ProgressInputStream.java:169)
	at com.amazonaws.internal.SdkFilterInputStream.reset(SdkFilterInputStream.java:102)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.resetRequestInputStream(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1129)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4185)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4132)
	at com.amazonaws.services.s3.AmazonS3Client.doUploadPart(AmazonS3Client.java:3172)
	at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3157)
	at com.amazonaws.services.s3.transfer.internal.UploadPartCallable.call(UploadPartCallable.java:33)
	at com.amazonaws.services.s3.transfer.internal.UploadPartCallable.call(UploadPartCallable.java:23)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

`

**Comment by studioam** [comment]
Hi, I can't find where I am supposed to insert the catch statement you mean, could you please show me? thanks,

**Comment by kiiadi** [comment]
@studioam sorry for the delay - yes that's what I meant.

**Comment by kiiadi** [comment]
@studioam were you able to resolve this in the end?

**Comment by studioam** [comment]
@kiiadi  I have tested with the latest release today and it works fine on every machine, for the 1st time it seems definitely solved.. Thanks a lot
